honojs/hono

deno_dist/utils/jwt/jws.ts
src/utils/jwt/jws.ts

This change prevents bundlers from pulling in all helpers, including the "ssg" helper which is not compatible with Cloudflare workers as it creates a "Request" in the global scope, and only imports the required (adapter) helper.

fix(jws): Only import necessary helper (not all helpers)

---

deno_dist/middleware/jsx-renderer/index.ts
src/middleware/jsx-renderer/index.test.tsx
src/middleware/jsx-renderer/index.ts

Fixes https://github.com/honojs/honox/issues/132
With this PR, you can get the context object in the component:
```ts
app.use(
jsxRenderer(
({ children }, c) => {
return (
<div>
{children} at {c.req.path}
</div>
)
},
{ docType: false }
)
)
```

feat(jsx-renderer): pass the context as 2nd arg

---

deno_dist/helper/ssg/index.ts
deno_dist/helper/ssg/middleware.ts
deno_dist/helper/ssg/ssg.ts
src/helper/ssg/index.ts
src/helper/ssg/middleware.ts
src/helper/ssg/ssg.test.tsx
src/helper/ssg/ssg.ts

Fixes #2476, https://github.com/honojs/honox/issues/58
As for #2179, using `c.env` to make the decision was a good change, but the decision in the response header should have been left as is. The response header is used again in this PR.
Since we use response headers in this PR, we can also remove the `new Response` before the request that causes an error in Cloudflare worker, but since it should not be changed in the patch version, we leave it marked as deprecated.
Also, if we can make it so that the response headers are used, the following issue will be fixed.
https://github.com/honojs/honox/issues/58

fix(ssg): use response header to mark as disabled routes for SSG

---

package.json

fix(trailing-slash): export types in `package.json` correctly

---

deno_dist/client/client.ts
deno_dist/client/utils.ts
src/client/client.test.ts
src/client/client.ts
src/client/utils.test.ts
src/client/utils.ts

This PR fixes an issue in the Hono client where WebSocket connections could not be established due to the `hc` function's `baseUrl` containing `http` or `https` schemes. Given that the WebSocket API requires URLs to use the `ws` or `wss` schemes, our existing implementation led to errors when attempting WebSocket connections with `http` or `https` URLs.
To address this, we've introduced a utility function, `replaceUrlProtocol`, which converts `http` URLs to `ws` and `https` URLs to `wss` for WebSocket connections. This ensures compatibility with the WebSocket API and resolves the protocol mismatch issue.
This change allows for seamless WebSocket communication within Hono applications by correctly handling the URL schemes required for WebSocket connections.

fix(client): fix websocket client protocol

---

deno_dist/utils/jwt/jwt.ts
src/utils/jwt/jwt.test.ts
src/utils/jwt/jwt.ts

This PR modifies the JWT header verification to make the `typ` field optional. This change is aligned with the JWT specifications as outlined in RFC 7519 Section 5.1, where the `typ` header parameter is optional. This adjustment was necessary to accommodate tokens, such as those decoded from Cloudflare Access's `CF_Authorization`, which do not include the `typ` field, thus previously preventing successful verification.
- Made the `typ` field in the `TokenHeader` interface optional.
- Updated the `isTokenHeader` function to validate headers with or without the `typ` field.
Reference to the RFC: [JWT RFC 7519 Section 5.1](https://datatracker.ietf.org/doc/html/rfc7519#section-5.1)
The necessity for this change arose during the verification of JWT tokens from Cloudflare Access, where the …

fix(jwt): Make JWT Header `typ` Field Optional to Enhance Compatibility

---

deno_dist/validator/validator.ts
src/validator/validator.test.ts
src/validator/validator.ts

This PR fixed an issue where the type was not shared properly on the Hono Client side when `json` was specified for the `validator` function.
- Default use to `OutputTypeExcludeResponseType` when `InputType` is unknown
```ts
const route = app.post(
'/foo',
validator('json', () => {
return {} as {
id: number
title: string
}
}),
(c) => {
return c.json({})
}
)
type AppType = typeof route
const client = hc<AppType>('http://localhost')
client.foo.$post({
// Previously, this would result in `unknown` instead of `{ id: number; title: string; }`
json: {
id: 1,
title: 'title'
}
})
```

fix(validator): Default use to `OutputTypeExcludeResponseType` when `InputType` is unknown

---

deno_dist/router/trie-router/node.ts
src/router/trie-router/node.ts

It appears that `parentPatterns` is updated but its content is never referenced.

refactor(trie-router): parentPatterns is updated but never queried

---

deno_dist/client/client.ts
deno_dist/helper/ssg/ssg.ts
deno_dist/middleware/serve-static/index.ts
src/adapter/cloudflare-workers/utils.ts
src/client/client.ts
src/helper/ssg/ssg.ts
src/middleware/serve-static/index.ts

refactor: Remove redundant initializer

---

src/adapter/cloudflare-workers/websocket.test.ts

As a contributor, it is annoying to see unaddressed warnings on `pnpm lint`.
```
/Users/exoego/IdeaProjects/hono/src/adapter/cloudflare-workers/websocket.test.ts
23:24  warning  'ws' is defined but never used  @typescript-eslint/no-unused-vars
✖ 1 problem (0 errors, 1 warning)
```

refactor(cloudflare-workers): Suppress eslint noise

---

deno_dist/jsx/streaming.ts
src/jsx/streaming.test.tsx
src/jsx/streaming.ts

The `.then(async function())` returns a new promise, that the above .catch() does not catch, resulting in rapid refreshing of the page to cause a fatal uncatchable error. Adding this second .catch fixes that.
If you're streaming a response, via renderToReadableStream from hono/jsx/streaming, and you rapidly refresh your page, you can trigger an error:
```sh
TypeError: Invalid state: Controller is already closed
at new NodeError (node:internal/errors:405:5)
at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1038:13)
at /Users/markwilkins/projects/wilkins-software-nx-v2/node_modules/hono/dist/cjs/jsx/streaming.js:137:24
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
which is uncatchable as far as I can tell. 
Since the [catch …

fix(jsx): Add catch to async function's promise

---

deno_dist/client/client.ts
src/client/client.test.ts
src/client/client.ts

Fixes #2509
When a hono client is instantiated in expo and then console.log(client) is called, an error is thrown:
`TypeError: Cannot determine default value of object`
This is because the hermes javascript engine expects `new String(val)` to always return a string. But the proxy object would return a ClientRequestImpl object instead.
This commit makes a string / function returned in the cases where .toString() and .valueOf() is called on the function.name or function respectively.
Also see https://github.com/facebook/hermes/issues/205

fix(client): Allow calling toString and valueOf on the proxy object

---

runtime_tests/lambda/index.test.ts
src/adapter/aws-lambda/handler.test.ts
src/adapter/aws-lambda/handler.ts

Fixes https://github.com/honojs/hono/issues/2493
Fixes https://github.com/honojs/hono/issues/2495
The current implementation assumes `headers` are always defined, which is incorrect 
`headers` can be `undefined` if `multiValueHeaders` exists,, and vice-versa, since`headers` and `multiValueHeaders` are mutually exclusive.
[`aws-lambda` type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46eab7d3077fa7939a1b11efc24358c06838df71/types/aws-lambda/trigger/alb.d.ts#L29-L39) in DefinitelyTyped also does so:
```typescript
export interface ALBEvent {
requestContext: ALBEventRequestContext;
httpMethod: string;
path: string;
queryStringParameters?: ALBEventQueryStringParameters | undefined; // URL encoded
headers?: ALBEventHeaders | undefined;
multiValueQueryStringParameters?: …
```

fix(adapter): handle multi value headers in AWS Lambda

---

deno_dist/client/utils.ts
src/client/utils.test.ts
src/client/utils.ts

`removeIndexString` should not remove a trailing slash from a top-level URL.
Fixes #2522

fix(client): shuold not remove tailing slash from top-level URL

---

src/adapter/aws-lambda/handler.ts

- Conditional logics are capsulated in the subclasses of `EventProcessor<E extends LambdaEvent>`.
- Those classes are stateless, so singleton is used to avoid allocation.
- Redundant calling `isProxyEventV2` is optimized, now only one time per event.
- Not in this PR, but this refactoring may also allow some room for optimization for particular Lambda events.

refactor(adapter/aws): Optimize multiple call of same conditions with polymorphism 

---

deno_dist/helper/streaming/sse.ts
src/helper/streaming/sse.test.ts
src/helper/streaming/sse.ts

Adds a finally block to the SSEStream class. Otherwise streamSSE will error whenever used in Cloudflare Workers.

fix(sse): close sse stream on end

---

deno_dist/client/types.ts
deno_dist/helper/websocket/index.ts
src/client/types.test.ts
src/client/types.ts
src/helper/websocket/index.ts

In client, IntelliSense always shows `(route).$ws` property.
I think client doesn't have to show `(route).$ws` property when route doesn't use WebSocket helper.

fix(client): Don't show `$ws` when not used WebSockets

---

src/adapter/cloudflare-workers/utils.ts

fix(cloudflare-workers): do not buffer content

---

deno_dist/context.ts
src/context.test.ts
src/context.ts

Potential fix for https://github.com/honojs/hono/issues/2554

fix(context): keep response cookies in newResponse instead of overwriting

---

deno_dist/request.ts
deno_dist/types.ts
src/request.ts
src/types.test.ts
src/types.ts

fix(request): infer params in a path includes one or more optional parameter

---

deno_dist/client/types.ts
deno_dist/context.ts
deno_dist/types.ts
src/client/client.test.ts
src/client/index.ts
src/client/types.ts
src/context.ts
src/helper/factory/index.test.ts
src/hono.test.ts
src/types.test.ts
src/types.ts
src/validator/validator.test.ts

This PR adds a status code to the response type and allows type filtering in RPC as below.
server.ts
```ts
const app = new Hono().get(
"/posts/:id",
zValidator(
"param",
z.object({
id: z.string(),
})
),
async (c) => {
const { id } = c.req.valid("param");
try {
const post: Post | undefined = await getPost(id);
if (post !== undefined) {
return c.json({ post }, 200);
}
return c.json({ error: "not found" }, 404);
} catch (e) {
return c.json({ error: "internal server error" }, 500);
}
}
);
export type AppType = typeof app;
```
client.ts
```ts
const client = hc<AppType>("/api");
const res = await client.posts[":id"].$get({
param: { id: "1" },
});
if (res.status === 404) {
const data: { error: string } = await res.json();
console.log(data.error);
}
if (res.ok) {
const data: { post: Post } = …
```

feat(rpc): Add status code to response type

---

deno_dist/middleware/bearer-auth/index.ts
src/middleware/bearer-auth/index.test.ts
src/middleware/bearer-auth/index.ts

Adds the possibility to use custom headers, such as `X-Auth` or `X-Access-Token` instead of `Authorization` with the `bearer-auth` middleware.

feat(bearer-auth): add `headerName` option

---

deno_dist/jsx/dom/render.ts
src/jsx/dom/index.test.tsx
src/jsx/dom/render.ts

There was a bug where the hook state was not maintained when passed as `children`.
This is not a specification change, but a fix to the original expected behaviour, so a patch version release would be acceptable, but it might cause changes in the results in existing applications, so it is better to include it in a minor version update with #2553.

fix(jsx): preserve the state of element even if it is repeatedly evaluated by children

---

deno_dist/utils/mime.ts
src/utils/mime.ts

This allows users reuse builtin MIME types while adding some custom.
```js
import { baseMimes, getMimeType } from 'hono/utils/mime';
const mimes = {
...baseMimes,
'my-own-ext': 'text/plain',
};
getMimeType('base.my-own-ext', mimes)
```

feat: expose built-in MIME types

---

deno_dist/adapter/deno/serve-static.ts
deno_dist/context.ts
deno_dist/middleware/serve-static/index.ts
package.json
src/adapter/deno/serve-static.ts
src/context.ts
src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts

This allows accessing `middleware/serve-static` from third-party
I run my own handler based on Cloudflare R2 to avoid the limitations of Cloudflare KV / Pages. And I found that most of the code I needed there was already built into hono.
So what I expect is like:
```ts
import { Hono } from 'hono';
import { serveStatic as makeServe } from 'hono/base-serve-static';
const app = new Hono<Env>();
const serveContent = makeServe<Env>({
getContent: async (path, c) => {
// retrieve
let response = await cache.match(c.req.raw);
// ...get R2 object
if (!response) {
let obj = await c.env.CONTENT.get(path);
if (obj) {
response = obj.body;
c.executionCtx.waitUntil(cache.put(c.req.raw, obj.body));
}
}
c.body(response);
},
});
app.use(serveContent);
export default app;
```

feat: expose serve-static builder

---

deno_dist/middleware/secure-headers/index.ts
src/middleware/secure-headers/index.test.ts
src/middleware/secure-headers/index.ts

https://github.com/honojs/honox/issues/157
_middleware.ts
```ts
import { createRoute } from "honox/factory";
import { secureHeaders, NONCE } from "hono/secure-headers";
export default createRoute(
secureHeaders({
contentSecurityPolicy: {
scriptSrc: [NONCE, 'https://allowed1.example.com', 'https://allowed2.example.com'],
},
})
);
```
_renderer
```ts
import { Style } from "hono/css";
import { jsxRenderer } from "hono/jsx-renderer";
import { Script } from "honox/server";
export default jsxRenderer(
({ children, title }, c) => {
return (
<html lang="en">
<head>
<meta charset="utf-8" />
<meta
name="viewport"
content="width=device-width, initial-scale=1.0"
/>
<title>{title}</title>
<Style />
</head>
<body>
{children}
<Script src="/app/client.ts" async nonce={c.get('secureHeadersNonce')} /> …
```

feat(secure-headers): enable to set nonce in CSP

---

.github/pull_request_template.md

I feel strange when I create PR.
This project recommends Bun by default, so I think PR Template should use `bun denoify` instead of `yarn denoify`.

chore(pr_template): Use Bun instead of yarn

---

deno_dist/client/types.ts
deno_dist/helper/websocket/index.ts
deno_dist/types.ts
src/client/types.ts
src/helper/factory/index.test.ts
src/helper/websocket/index.ts
src/types.test.ts
src/types.ts

A reimplement of #2562, using refactored types flow of #2581
**UPDATE:** All commits follows conventional syntax, recommended to merge without squashing.

feat: improve `ToSchema` & `WebSocket Helper` types

---

deno_dist/helper/factory/index.ts
src/helper/factory/index.test.ts
src/helper/factory/index.ts

This PR introduces `createApp()` in `hono/factory` as an experimental feature. If you use this method with `createFactory()`, you can avoid redundancy in the definition of `Env` types.
Before:
```ts
const app = new Hono<Env>()
const mw = createMiddleware<Env>(async(c, next) => {
await next()
})
```
With this PR:
```ts
const factory = createFactory<Env>()
const app = factory.createApp()
const mw = factory.createMiddleware(async (c, next) => {
await next()
})
```
Using the "Simple Factory" pattern with the Factory helper, there is no need to write type definitions in `global.d.ts` with possible type conflicts. Also, you don't have to have `Env` definitions in multiple places.
```ts
// factory-with-db.ts
type Env = {
Bindings: {
MY_DB: D1Database
}
Variables: {
db: DrizzleD1Database
}
} …
```

feat(factory): add `createApp()`

---

deno_dist/client/client.ts
deno_dist/client/types.ts
src/client/client.test.ts
src/client/client.ts
src/client/types.ts

Initally I used a function to merge the headers, but then realized it could be great if it could be used as highest priority control, added comment to tell user to be careful instead.
Resolves #2485

feat(hc): add `init` option

---

deno_dist/types.ts
src/types.ts

Resolves honojs/middleware#496
This PR make `ToSchema` compatible with older versions.
Some informations about the issue:
> Okay, so on `4.3.0` we have two types breaking on `ToSchema`:
> 
> * Update from `O` is output to `extends TypedResponse` - 8129a3a
> * Update from `I` accepting `Input['in']` to `Input` - ea4e998
> 
> Previously I thought `ToSchema` is only for internal use so I didn't think much about it, but if it is exposed for other libraries I think we should revert `ToSchema` and creates a new `ToSchemaV2` for future uses to revert the breaking changes?

fix(types): `ToSchema` compatibility

---

deno_dist/validator/validator.ts
src/validator/validator.test.ts
src/validator/validator.ts

Fixes #2625
This PR enables the validator to parse an array form value, such as the key is a `foo[]`. You should specify a key with the `[]` suffix for an array content.
Usage:
```ts
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
const schema = z.object({
'foo[]': z.array(z.string())
})
app.post('/', zValidator('form', schema), (c) => {
const data = c.req.valid('form')
const fooArray = data['foo[]']
fooArray
})
})
export default app
```

fix(validator): `form` supports multiple values with `foo[]`

---

deno_dist/validator/validator.ts
src/validator/validator.test.ts
src/validator/validator.ts

A minimal fix for #2633 using a regex. 
I liked the simplicity of the current `startsWith`-approach but it excluded subtypes.
I did:

feat(validator): check for json subtypes in validator

---

deno_dist/hono-base.ts
src/hono-base.ts

fixes #2653
Since deno checks `.length` as follows, this PR adjust `app.fetch.length` to be 1.
https://github.com/denoland/deno/blob/dac49a116e094be1a3048305dfb6b10bbddcc030/ext/http/00_serve.ts#L796-L800
We will be able to use `export default app` for `deno serve` with this PR.
This definition may seem a bit odd, but it is not overly complicated; I think the advantage of "you can write `dexport defult app` in deno just as well as in bun" is more significant.
- <del>[ ] Add tests</del>

feat(hono-base): tweaks `fetch` signature for better compatibility with `deno serve`

---

deno_dist/middleware/cache/index.ts
src/middleware/cache/index.test.ts
src/middleware/cache/index.ts
src/test-utils/setup-vitest.ts

feat(cache): improved customizability

---

.github/workflows/ci.yml
deno_dist/utils/body.ts
src/utils/body.test.ts
src/utils/body.ts

Fixes #2664 and updates the Node.js version for the `Main` CI to `v20.x`.

fix(utils/body): support multiple `File`s

---

deno_dist/helper/ssg/ssg.ts
src/helper/ssg/ssg.ts

close: https://github.com/honojs/hono/issues/2284 https://github.com/honojs/hono/issues/2244
It summarizes the history of the discussion and prescribes default values.

doc(ssg): Define the default value for Content-Type

---

runtime_tests/lambda/index.test.ts
src/adapter/aws-lambda/handler.ts

This change is made to address the issue raised in #2626. The change adds the following :
- Create a custom `albProcessor` for `ALBProxyEvent`
- Refactor code and introduced new `getHeaders` method
- Added test for certain cases of the ALB event when `multiValueHeaders` is present

feat(aws-lambda): add alb event processor

---

deno_dist/utils/cookie.ts
src/utils/cookie.ts

Added support for allowing `lax`, `strict`, and `none` values for the `SameSite` attribute in the `setCookie` function.
While the [RFC](https://datatracker.ietf.org/doc/html/draft-west-first-party-cookies-07#section-4.1) suggests that the `SameSite` attribute should `Strict`, `Lax`, `None` as values, there is no indication that the `SameSite` attribute should be case-sensitive.
Libraries like lucia (Undelying [`olso`](https://github.com/pilcrowOnPaper/oslo/blob/26f8c9dabc2dac6212c855602614d91991e87889/src/cookie/index.ts#L7)) returns cookie objects with lowercase `SameSite` attribute values, which conficts with the `SameSite` attribute values in the `setCookie` function. This needs us to convert the `SameSite` attribute values from lucia to the correct case-sensitive values which is a …

feat(utils/cookie): allow setting cookie SameSite attribute in lowercase too

---

deno_dist/middleware/method-override/index.ts
src/middleware/method-override/index.ts

this PR simply removes the `URLSearchParams` import from the node-specific package `url`.
when running hono and using the method override middleware in cloudflare workers, wrangler complains about the use of the `url` package. it prompts you to add the `node_compat` flag.
this seems a bit erroneous to me, since node has had `URLSearchParams` as a global since version 10. maybe i'm missing something specific about other runtimes, but all tests pass.
please nuke this PR if i'm flat-out wrong ;)

fix(method-override): remove un-needed import of URLSearchParams in method override middleware

---

src/validator/validator.test.ts

test(validator): compatibility with Node.js `v20.13.1`

---

deno_dist/utils/jwt/jwt.ts
deno_dist/utils/jwt/types.ts
src/utils/jwt/jwt.ts
src/utils/jwt/types.ts

refactor(utils/jwt): remove some `any`

---

deno_dist/middleware/bearer-auth/index.ts
src/middleware/bearer-auth/index.ts

This PR is to add JSDoc for Bearer Auth Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Bearer Authentication Middleware

---

deno_dist/middleware/body-limit/index.ts
src/middleware/body-limit/index.ts

This PR is to add JSDoc for Body Limit Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Body Limit Middleware

---

deno_dist/middleware/cache/index.ts
src/middleware/cache/index.ts

This PR is to add JSDoc for Cache Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Cache Middleware

---

deno_dist/middleware/compress/index.ts
src/middleware/compress/index.ts

This PR is to add JSDoc for Compress Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Compress Middleware

---

deno_dist/middleware/cors/index.ts
src/middleware/cors/index.ts

This PR is to add JSDoc for CORS Middleware.
Related:
- #1338
- #2680

docs(jsdoc): CORS Middleware

---

deno_dist/middleware/csrf/index.ts
src/middleware/csrf/index.ts

This PR is to add JSDoc for CSRF Protection Middleware.
Related:
- #1338
- #2680

docs(jsdoc): CSRF Protection Middleware

---

deno_dist/middleware/trailing-slash/index.ts
src/middleware/trailing-slash/index.ts

This PR is to add JSDoc for Trailing Slash Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Trailing Slash Middleware

---

deno_dist/middleware/timing/index.ts
src/middleware/timing/index.ts

`Partial` is convinient. However, it is easy for users to understand that it does not use `Partial`.

refactor(timing): don't use `Partial` for the options

---

deno_dist/middleware/secure-headers/index.ts
src/middleware/secure-headers/index.ts

It is the same reason as #2712 .
Sometimes `Partial` is used instead of making all option values optional, but this is not necessary in this case.

refactor(secure-headers): don't use `Partial` for the options

---

deno_dist/middleware/pretty-json/index.ts
src/middleware/pretty-json/index.ts

This PR is to add JSDoc for Pretty JSON Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Pretty JSON Middleware

---

deno_dist/middleware/method-override/index.ts
src/middleware/method-override/index.ts

This PR is to add JSDoc for Method Override Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Method Override Middleware

---

deno_dist/middleware/logger/index.ts
src/middleware/logger/index.ts

This PR is to add JSDoc for Logger Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Logger Middleware

---

deno_dist/context.ts
src/context.test.ts
src/context.ts

It seems cookie headers are not correctly appended when passing `ResponseInit` as a second parameter to `c.body(..., res)`.
Support for setting cookies was recently added to `@hono/trpc-server` in
https://github.com/honojs/middleware/pull/517, but this bug prevents multiple cookies from being set.
[Here's a reproduction](https://github.com/codeflows/hono-cookie-test/tree/main)

fix(context): Retain all cookies when passing `ResponseInit` to `c.body`

---

deno_dist/jsx/hooks/index.ts
src/jsx/hooks/dom.test.tsx
src/jsx/hooks/index.ts

My problem -  hono forward ref always need me to put ref. It's not true. It should be like "if i need to forward ref (maybe by thirdparty library like mantine, they love to put ref to your custom components)
Does hono works correct? Yes no error runtime throws, code works fine. 
What my code fixes? 
THIS:
i have to always cover with ts expect error every time i use component that i need to forward ref.

fix(hono-jsx): make ref unrequried for forward ref

---

runtime_tests/lambda/index.test.ts
src/adapter/aws-lambda/handler.ts

When working on #2626, I realized that when `multiValueHeaders` is enabled, the query string parameters are passed as an array as well. More info : https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#multi-value-headers
> If you enable multi-value headers, the load balancer uses both key values sent by the client and sends you an event that includes query string parameters using multiValueQueryStringParameters. For example:
`"multiValueQueryStringParameters": { "myKey": ["val1", "val2"] },`
This PR adds support for `multiValueQueryStringParameters` when it's available on the event

feat(aws-lambda): add support for alb multiValueQueryStringParameters

---

deno_dist/middleware/timing/index.ts
src/middleware/timing/index.ts

This PR is to add JSDoc for Server-Timing Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Server-Timing Middleware

---

deno_dist/middleware/secure-headers/index.ts
src/middleware/secure-headers/index.ts

This PR is to add JSDoc for Secure Headers Middleware.
Related:
- #1338
- #2680

docs(jsdoc): Secure Headers Middleware

---

deno_dist/http-exception.ts
src/http-exception.test.ts
src/http-exception.ts

fix(http-exception): prioritize the status code

---

deno_dist/middleware/jwt/index.ts
src/middleware/jwt/index.ts

This PR is to add JSDoc for JWT Auth Middleware.
Related:
- #1338
- #2680

docs(jsdoc): JWT Auth Middleware

---

deno_dist/adapter/deno/conninfo.ts
deno_dist/adapter/deno/index.ts
deno_dist/helper/conninfo/index.ts
package.json
src/adapter/bun/conninfo.test.ts
src/adapter/bun/conninfo.ts
src/adapter/bun/index.ts
src/adapter/cloudflare-workers/conninfo.test.ts
src/adapter/cloudflare-workers/conninfo.ts
src/adapter/deno/conninfo.test.ts
src/adapter/deno/conninfo.ts
src/adapter/deno/index.ts
src/helper/conninfo/index.ts

I created ConnInfo helper/adapter for Bun, Deno and CF Workers.
You can get client IP Address with Hono easier if we marge PR.
This provides runtime-less ConnInfo object.
For example, you can get IP Address on Bun:
```ts
import { getConnInfo } from 'hono/bun'
app.get('/', c => c.text(`Your ip address is ${getConnInfo(c).remote.address}!!`))
Bun.serve(app)
```
If you want to use Workers, replace import:
```ts
import { getConnInfo } from 'hono/cloudflare-workers'
```
In Deno:
```ts
import { getConnInfo } from 'https://deno.land/x/hono/helper.ts'
```

feat: Introduce ConnInfo helper/adapter

---

deno_dist/middleware/etag/index.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts

In this PR, I've done:
* Export `RETAINED_304_HEADERS` to make **adding** the retained header value easy.
* Add the test for retained headers.
* Refactor the tests. Removed `beforeEach` since the scope is not clear.

feat(etag): export `RETAINED_304_HEADERS`

---

deno_dist/middleware/jwt/index.ts
src/middleware/jwt/index.ts

Please see https://discord.com/channels/595317990191398933/1243024990652207115/1243024990652207115 (in the cloudflare discord)
**THIS WILL BREAK PRODUCTION**
In the docs it says
```ts
app.use(
'/auth/*',
jwt({
secret: 'it-is-very-secret',
})
)
app.get('/auth/page', (c) => {
return c.text('You are authorized')
})
```
realalitically code in production will look more like
```ts
app.use(
'/auth/*',
jwt({
secret: process.env.SECRET,
})
)
app.get('/auth/page', (c) => {
return c.text('You are authorized')
})
```
however, if this app.use is at the top level, in some instances in cloudflare process.env can be undefined. Nobody noticed this, because the code failed to check if it was actually defined.
edit: another solution would be to move this check inside the return callback, but this means that …

fix(middleware/jwt): fix incorrect assumption in jwt impl

---

deno_dist/request.ts
deno_dist/utils/body.ts
deno_dist/validator/validator.ts
src/request.test.ts
src/request.ts
src/utils/body.test.ts
src/utils/body.ts
src/validator/validator.ts

More restrictive on the type of value returned from `parseBody()`.
```ts
const value = (await parseBody(req))['key'] // => string | File
const maybeArray = (await parseBody(req, {all: true}))['key'] // => string | File | (string | File)[]
const maybeObject = (await parseBody(req, {dot: true}))['key'] // => string | File | Object
```
In v4.3.x, BodyData was defined as follows
https://github.com/honojs/hono/blob/75a7a09fc548da2a1a8f35431c456922db7d6c76/src/utils/body.ts#L3
For applications using it directly, this change results in the following (`(string | File)[]` is no longer included)
```ts
const data: BodyData = {} // means Record<string, string | File>
```
To get the same result as in v4.3.x, you need to do the following.
```ts
const data: BodyData<{all: true}> = {}
```
Although there …

feat(utils): specify detailed return type for parseBody

---

deno_dist/middleware/etag/index.ts
src/middleware/etag/index.ts

This PR is to add JSDoc for ETag Middleware.
Related:
- #1338
- #2680

docs(jsdoc): ETag Middleware

---

benchmarks/deno/hono.ts
benchmarks/routers-deno/src/hono.mts
runtime_tests/deno-jsx/deno.precompile.json
runtime_tests/deno-jsx/deno.react-jsx.json

Fix path including deno_dist.
`--unstable-sloppy-imports` flag is now required on benchmark due to jsr aliases.

chore(deno): change path including deno_dist

---

src/middleware/jwt/index.ts
src/middleware/secure-headers/index.ts
src/middleware/timing/index.ts

fix(middleware): export variables type from each `index.ts`

---

jsr.json
package.json
src/jsx/base.ts
src/jsx/dom/client.test.tsx
src/jsx/dom/client.ts
src/jsx/dom/index.test.tsx
src/jsx/dom/index.ts
src/jsx/dom/render.ts
src/jsx/index.test.tsx
src/jsx/index.ts

Fixes #2792
There seems to be a library that does conditional branching on the major version number of `React.version`.
This is like a UserAgent of a web browser (e.g. Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537. 36), which is a string for compatibility and somewhat unpleasant to use, and we do not recommend its use, but if this improves compatibility, it should be added.
Some options are not yet supported, but they can be rendered in the way recommended by React since version 18, as shown in the following diff.
https://github.com/usualoma/hono-react-compat-demo/commit/38773555179ef54f8564ca1963720ac16f720987

feat(jsx/dom): introduce react-dom/client APIs and React.version

---

src/adapter/aws-lambda/handler.ts

Updated the getQueryString function to handle the case when both queryStringParameters and multiValueQueryStringParameters properties exists.

fix(aws-lambda): Update handler.ts getQueryString

---

src/adapter/aws-lambda/handler.ts

Refer. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
> It is recommended over [Object.prototype.hasOwnProperty()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) because it works for [null-prototype objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#null-prototype_objects) and with objects that have overridden the inherited hasOwnProperty() method. While it is possible to workaround these problems by calling Object.prototype.hasOwnProperty() on an external object, Object.hasOwn() is more intuitive.
`Object.hasOwn` is supported since Node.js v16.9.0 which is [the minimum supported Node.js version in AWS …

refactor(aws-lambda): Object.hasOwn is recommended

---

src/helper/ssg/utils.test.ts
src/helper/ssg/utils.ts

fix(helper/ssg): fix bug of joinPaths

---

.github/pull_request_template.md

chore: Author should include JSDoc

---

src/hono-base.ts
src/middleware/body-limit/index.test.ts
src/middleware/body-limit/index.ts

Fixes #2627
In this case we do not need globalThis.Request anymore.

fix(middleware/body-limit): set default duplex option for readable stream

---

src/adapter/cloudflare-workers/websocket.test.ts
src/adapter/cloudflare-workers/websocket.ts
src/adapter/deno/websocket.ts

Looking at WSEvents type, we don't really need extra AND condition here, just make sure `undefined` is not invoked by specifying `?.()`
```ts
// EVENT is onOpen, onClose, onMessage, onError
(property) WSEvents.EVENT?: ((evt: CloseEvent, ws: WSContext) => void) | undefined
```
Also removes console logs in websocket test.

refactor(websocket): remove unused condition

---

src/adapter/bun/conninfo.ts
src/adapter/bun/server.test.ts
src/adapter/bun/server.ts
src/adapter/bun/websocket.ts

Resolves #2645 and #2696
In ConnInfo helper on Bun, you can give Hono env like `{ server: server }`.
However WebSocket Helper can't receive `{ server: server }`, so I created this PR. WebSocket helper on Bun can receive like it if we merged this.

feat(bun): WebSocket helper supports that env be `{ server: server }`

---

.github/workflows/ci.yml

Node.js 22 added to the test matrix.
ref : https://github.com/honojs/node-server/pull/170

ci: include node22 tests

---

src/helper/adapter/index.ts

detect runtime using `navigator.userAgent` when possible

refactor(helper/adapter): improve runtime detection

---

src/jsx/utils.test.ts
src/jsx/utils.ts

Fix #2774
Change in #2553 to add "px" when a value of type number is passed. However, it was found that some properties need to output number as is, as defined in React as follows.
https://github.com/facebook/react/blob/46339720d75337ae1d1e113fd56ac99e7fd1a0b3/packages/react-dom-bindings/src/shared/isUnitlessNumber.js#L14-L84
Keeping the entire list would increase the code, so this PR implementation was made smaller by excluding 'deprecated' and 'vendor-prefixed' items from the React list, and then grouping them into regular expressions.

fix(jsx/dom): Fixed to not add "px" for certain properties, even if numeric value is given

---

src/adapter/aws-lambda/handler.ts

`setHeadersToResult` was added in https://github.com/honojs/hono/pull/2657 but seems not used.
@yiss Please confirm it should be deleted or called.
If it should be called, I'll add tests and fix implementation.

refactor(aws-lambda): remove unused setHeadersToResult

---

src/validator/validator.test.ts
src/validator/validator.ts

The author should do the following, if applicable
specs: https://jsonapi.org/format/

fix(validator): support json api header

---

src/compose.ts

There are two `ComposeContexts` with the same type definition.
One of them is unnecessary, so it has been deleted.
https://github.com/honojs/hono/blob/1da43aee3be0ed2a991ee7199a32ed3ad4ad8fe5/src/compose.ts#L5-L23

refactor(compose): Remove type definition of ComposeContext that was defined twice

---

src/adapter/aws-lambda/handler.ts
src/context.ts
src/helper/dev/index.ts
src/helper/streaming/sse.ts
src/hono-base.ts
src/jsx/dom/render.ts

JSR was throwing an error because some functions had return types that were not set. This has been fixed.

fix: add return types of void function

---

src/adapter/deno/serve-static.ts

The ternary operator can be used.
This is smarter than before.

refactor: removed unnecessary line

---

.github/workflows/ci.yml
.vitest.config/jsx-runtime-default.ts
.vitest.config/jsx-runtime-dom.ts
codecov.yml
runtime_tests/bun/vitest.config.ts
runtime_tests/fastly/vitest.config.ts
runtime_tests/lambda-edge/vitest.config.ts
runtime_tests/lambda/vitest.config.ts
runtime_tests/node/vitest.config.ts
runtime_tests/wrangler/vitest.config.ts
vitest.config.ts

Closes #2857
Closes #1391
Closes #175
This PR configures Vitest to generate coverage in JSON format per each test suite.
Multiple coverage files are uploaded into CodeCov, then CodeCov automatically merges those uploaded coverages smartly.
https://github.com/exoego/hono/pull/3 is a working demo how CodeCov bot reports coverage changes on each PR
You can also see [the demo coverage on my CodeCov account](https://app.codecov.io/github/exoego/hono):
(this demo coverage is not "accurate" since it includes unexpected files like `benchmarks` and `runtime_tests`. Such unexpected files are excluded in this PR)
Repo administrator should set `CODECOV_TOKEN` as GitHub secret for Actions.
The token can be obtained in https://app.codecov.io/github/honojs/hono/settings
or maybe …

ci: Report coverage with CodeCov

---

runtime_tests/deno/hono.test.ts
src/adapter/deno/websocket.ts

```ts
app.get(
'/ws',
upgradeWebSocket(async (c) => {
await new Promise(resolve => setTimeout(resolve, 5e2)) // Simulate time-consuming operation
return {
onOpen: () => console.log('opened') // can't be trigger
}
})
)
```
Because `socket.onopen` was triggered before `createEvents`.
Swapping L7 and L9 can solve this problem：
https://github.com/honojs/hono/blob/3d6820b46e51622435aeb0cacc6434d722581aa2/src/adapter/deno/websocket.ts#L7-L9

fix(websocket): the onopen event cannot be triggered during delayed operations in deno

---

vitest.config.ts

These two type-only files are relatively-large uncovered files.
https://github.com/honojs/hono/blob/f634c824510f265976f4f15312e098ab37aefb21/src/jsx/intrinsic-elements.ts
https://github.com/honojs/hono/blob/f634c824510f265976f4f15312e098ab37aefb21/src/utils/http-status.ts
This change will increase coverage dramatically
```
+ Coverage   87.88%   93.06%   +5.18%     
```

chore: Exclude type-only files from coverage

---

src/utils/http-status.ts

This PR fixes typo for unofficial status code type.
Add `UnofficialStatusCode` and announce to use the type instead.
Please remove the type at an appropriate time.
The old example includes that a religious number and meaningless status message.
Use an unofficial status code that actually exists.

fix(types): fix typo for unofficial status code type

---

src/hono-base.ts
src/hono.test.ts

Resolves #2781
This PR introduces the `rewritePath` option to `app.mount()`. With the current spec, if you use `app.mount()`, the path to pass to your mounted application will be changed. The base path will be removed.
```ts
app.mount('/sub-app', subApp.handle)
```
If you access `/sub-app/hello/foo`, the subApp receives `/hello/foo`. This is good behavior for some apps, but it's bad for some apps like #2781.
With the `rewritePath` option, you can specify the path to pass to the sub-application. If you don't want to remove the base path, you can write the following:
```ts
app.mount('/sub-app', subApp.handle, {
rewritePath: (path) => path,
})
```
The logic will be a little bit complex. As for this, the application size will be slightly increased. Eitherway, I think we can reduce the size in …

feat(hono-base): add `replaceRequest` option for `app.mount`

---

src/hono-base.ts
src/hono.test.ts
src/types.ts

This change is intended to make error handling more flexible and reduce bundle size. This idea is originated from https://github.com/honojs/hono/pull/2885
- <del>Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code</del>

feat(hono-base): skip import HTTPException by using HTTPResponseError

---

src/hono-base.ts
src/hono.test.ts

This PR enables returning a 404 response if lacking returning `Response` in a single handler.
If an async handler that is not used with middleware lacks a returning `Response`, the response is 404.
But if it is not an async handler, it will not return `Response` correctly.
This PR will fix it and make it return a 404 response.

fix(hono-base): return 404 if lacking response in a single sync handler

---

src/types.ts
src/utils/types.ts

I just realized the older `Prettify` is the same as `Simplify`, but I remove the former and keep `Simplify` as it's more commonly used wording for this type.

refactor: remove `Prettify` as duplicated with `Simplify`

---

src/client/client.test.ts
src/context.ts
src/utils/types.ts

Resolves #2912
This PR introduces `SimplifyDeepArray` type to handle the case when user response with an array of interfaces.

fix(types): #2912: interfaces array's respond typed as `never`

---

src/client/client.test.ts
src/context.ts
src/types.ts

Related to #2897
This PR enables `c.redirect()` to return `TypedResponse`. So, you can handle redirect responses in the RPC mode.
```ts
const routes = app.get('/profile', (c) => {
if (!flag) {
return c.redirect('/')
}
return c.json({ name: 'abc' }, 200)
})
const client = hc<typeof routes>('/')
const res = await client.profile.$get()
if (res.status === 302) {
console.log(res.headers.get('Location'))
} else {
const data = await res.json()
//    ^ { name: string }
}
```

feat(context): `c.redirect()` supports `TypedResponse`

---

src/jsx/utils.test.ts
src/jsx/utils.ts

To enhance compatibility with React in hono/jsx, we have added support for the `htmlFor` alias. (The relevant code in React can be found at [this file](https://github.com/facebook/react/blob/3730b40e9bbacef0279f6d120b344c1544cb38ba/packages/react-dom-bindings/src/shared/getAttributeAlias.js#L12))
By supporting `htmlFor` in hono/jsx, we gain the following benefits:
Composite components utilizing HTML-only toggles, such as a `<label htmlFor="toggle">` and `<input type="checkbox" id="toggle"/>` combination, will function properly.
For instance, in daisyUI, which works purely with Tailwind, the Drawer component will operate as intended without any code modifications when used with hono/jsx.

feat(jsx): support htmlfor attribute alias

---

src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts

Refactored so that `getContent()` was called twice in the same path when 404, so it is now called once.

refactor(middleware/serve-static): call getContent only once if the file does not exist

---

src/helper/conninfo/index.ts
src/helper/conninfo/types.ts

Created `types.ts` separate from `index.ts` for type definitions to measure coverage correctly.

refactor(conninfo): create `types.ts` for type definitions

---

src/middleware/cors/index.test.ts
src/middleware/cors/index.ts

Fixes #2932 allow developers to use custom vary header value, it will helps to support many use cases with custom vary headers such as [CF Polished](https://developers.cloudflare.com/images/polish/cf-polished-statuses/).

fix(cors): allow custom vary header

---

src/jsx/base.ts
src/jsx/index.ts
src/jsx/intrinsic-elements.ts
src/jsx/types.ts

Fixes #2927
Currently, the definition for HTML tags elements and attributes are exported as a namespace named `Hono` in `jsx/intrinsic-elements.ts`. This is not bad, but the namespace `Hono` is not exported for users. So, it's impossible to extend the values such as `HTMLAttributes`.  In this PR, it will be exported from `hono/jsx`. And I renamed `Hono` to `JSX` because the name `Hono` will cause confusion. That namespace was not used in a global. So I think it will not be a breaking change.
With this PR, you can write the JSX with the HTMX attribute with the following code:
```tsx
// You may have to write `import "typed-htmx"`
declare module 'hono/jsx' {
namespace JSX {
interface HTMLAttributes extends HtmxAttributes {}
}
}
return c.render(
<div hx-get="/foo"> …
```

fix(jsx): rename `Hono` to `JSX` and export `JSX` namespace

---

src/hono-base.ts
src/hono.test.ts

The second arg of `app.route()` was optional, but the "optional" was deprecated and obsolete when releasing `v4.0.0`. So, the second arg (app) is required now. This PR corrects that forgotten handling it.

refactor(hono-base): make 2nd arg of `app.route()` required

---

src/hono-base.ts

This PR removes checking the actual value of the first argument on `app.on()`. I think it is ok not to check because the argument is typed as required. And if the coming actual value is undefined, it will be checked in the initialization phase, so it's no problem just throwing an error.

refactor(hono-base): don't check 1st argument of `app.on()`

---

src/context.test.ts
src/context.ts

This refactoring removed unnecessary initialization in `c.get()` and `c.set()`. And added tests for improving coverage.

refactor(context): remove unnecessary initialization add add tests for Context

---

src/request.ts

This refactoring shortens code inside `parseBody` and removes an unnecessary conditional check.

refactor(request): shorten `parseBody` and remove unnecessary check

---

src/jsx/base.ts
src/jsx/dom/jsx-dev-runtime.ts
src/jsx/dom/render.ts
src/jsx/utils.test.ts
src/jsx/utils.ts

Reduce the size a bit.
```bash
$ git checkout main
$ npx esbuild --bundle --minify src/jsx/dom/index.ts | wc
1     224   10594
$ git checkout feat/reduce-jsx-utils-size
$ npx esbuild --bundle --minify src/jsx/dom/index.ts | wc
1     220   10517
```
It is easier to add attributes that should be replaced.
https://github.com/honojs/hono/compare/main...usualoma:hono:feat/reduce-jsx-utils-size?expand=1#diff-7deb9d231b0c7046d4243559f6a3b475560a8f9c6e4e1445f2b98c21a73b7067R1-R4

refactor(jsx): reduce code size and improve maintainability

---

src/jsx/dom/client.test.tsx
src/jsx/dom/client.ts

Small additions to make #2925 easier to implement.

feat(jsx/dom): export createRoot and hydrateRoot from jsx/dom/client as default

---

jsr.json
package.json
src/jsx/dom/server.test.tsx
src/jsx/dom/server.ts
src/jsx/streaming.ts

Implement React compatible `renderToString` and `renderToReadableStream`.
This component is used to create an alias in #2925
As it is a component that provides stringify function, I don't think it is related to “DOM", but I chose this name because it is easier to understand if it corresponds to "react-dom/server".

feat(jsx/server): introduce `jsx/dom/server` module for compatibility with `react-dom/server`

---

src/jsx/base.ts

#2959
First of all, in the react-19-compat branch, we should bump the version number

feat(jsx): bump react compat version to 19.0.0-hono-jsx

---

runtime_tests/lambda/stream-mock.ts
runtime_tests/lambda/stream.test.ts
runtime_tests/lambda/vitest.config.ts
src/adapter/aws-lambda/handler.ts

This fix does address that cookies have to be handled
specially in lambda responses.
Fixes #2921

fix(aws-lambda): handle multiple cookies in streaming responses

---

src/jsx/context.ts
src/jsx/dom/context.test.tsx
src/jsx/dom/context.ts
src/jsx/index.test.tsx

feat(jsx/dom): implement "<Context> as a provider" for compatibility with React 19

---

src/context.test.ts
src/context.ts

I had some issues with using `c.html` with a non-promise body that had the return-type `Response | Promise<Response>`. This should use correct return-type depending on the input.

use correct return type for c.html depending on input

---

src/client/utils.test.ts

close #2980 
Adjusted the value passed as the second argument to improve coverage.

test: test uncovered return statement

---

src/request.test.ts

Possibly unintended check duplication :P

test: Update request.test.ts to remove duplicate checks

---

src/context.ts
src/types.test.ts

```ts
declare module 'hono' {
interface ContextVariableMap {
test: 'root'
}
}
const middleware = createMiddleware<{
Variables: {
test: 'override'
}
}>(async (c, next) => {
c.set('test', 'override')
await next()
})
const router = new Hono()
.get(
'/test',
middleware,
async c => {
const test = c.get('test')
//    ^? "root"
return c.text(test) // 'override', type doesn't match
},
)
.use(async (c, next) => {
c.set('test', 'root')
await next()
})
.route('/', router)
```

fix(types): env variables override ContextVariableMap

---

.github/workflows/ci.yml

ci: use `env` for codecov GitHub Actions

---

src/helper/conninfo/types.ts
src/hono-base.ts

chore: Fix typos in JSDoc

---

src/helper/accepts/accepts.ts

Hello, small perf improvements by removing spread operator.
source : https://prateeksurana.me/blog/why-using-object-spread-with-reduce-bad-idea/
I made a little repo to bench the function without spread operator, we can notice a small improvement  : https://github.com/Jayllyz/parseHeader-bench

perf: parseAccept without spread operator

---

src/utils/buffer.test.ts

close #2995
Add some tests for uncovered lines.

test: add tests for buffer.ts

---

.github/workflows/ci.yml
bunfig.toml

https://bun.sh/blog/bun-v1.1.16
Bun is now able to generate statement coverage in LCOV format, which can be uploaded to CodeCov.
This improves coverage by 0.92%!
```diff
==========================================
+ Coverage   94.76%   95.68%   +0.92%     
==========================================
Files         136      137       +1     
Lines       13361    13391      +30     
Branches     2276     2252      -24     
==========================================
+ Hits        12661    12813     +152     
+ Misses        700      578     -122     
```
> [!note]
> Currently, some types of "unexecutable" lines are marked as uncovered, but better than nothing.
> It will be improved in Bun someday.
> <img width="610" alt="image" src="https://github.com/honojs/hono/assets/127635/5ff593ba-fd1f-4858 …

chore: upload bun test coverage to CodeCov

---

src/utils/buffer.ts

Changed to use Promise.all in the `timignSafeEqual` function to improve performance.
Here we share benchmark results for `timingSafeEqual` and (using Promise.all) `timingSafeEqual2` .
https://github.com/yasuaki640/timingSafeEqual-bench/actions/runs/9646432337/job/26602824121
(Click on the Run Benchmarks section to see the benchmark results )
We observed a 1.6 ~ 2x performance improvement (except for the last case) for the test cases present in [buffer.test.ts.](https://github.com/honojs/hono/blob/main/src/utils/buffer.test.ts)
The only performance degradation was in the following case
https://github.com/honojs/hono/blob/a9d5313a5a3b23dee963b765bda0a95f7b94bec7/src/utils/buffer.test.ts#L72
(The timingSafeEqual-bench repository has the following measurements) …

perf(utils/buffer): use promise all for better performance

---

runtime_tests/deno/hono.test.ts
src/adapter/bun/conninfo.test.ts
src/adapter/bun/server.test.ts
src/adapter/cloudflare-workers/conninfo.test.ts
src/adapter/deno/conninfo.test.ts
src/compose.test.ts
src/context.test.ts
src/context.ts
src/helper/streaming/sse.test.ts
src/helper/streaming/stream.test.ts
src/helper/streaming/text.test.ts
src/hono-base.ts

This PR improves the performance for initialization of `Context`:
* Delay initialization for variables as long as possible.
* Pass `Request` object instead of `HonoRequest` and make it later if `c.req` is called.
* Some tests have been changed. But I think it is not a problem because `Context` is used in the `hono` package internally, though a type of `Context` is exported.
* It's not related to performance, but use `#` for some private properties.
With this benchmark code:
```ts
import { bench, group, run } from 'mitata'
import { Hono as HonoNext } from '../../dist/index.js'
const req = new Request('http://localhost/')
const app = new Hono().get('/', (c) => c.text('Hi'))
const appNext = new HonoNext().get('/', (c) => c.text('Hi'))
bench('noop', () => {}) …
```

perf(context): improve initializing `Context`

---

src/types.test.ts
src/types.ts

Fixes the regression bug (#2046) caused by #2412

fix(types): correct inferring env when routes channing

---

src/adapter/bun/conninfo.test.ts

test(adapter/bun): fixed `conninfo.test.ts`

---

src/jsx/dom/hooks/index.test.tsx
src/jsx/dom/index.test.tsx
src/jsx/dom/intrinsic-element/components.ts
src/jsx/dom/render.ts

Oops, the biggest point of React, the feature of not calculating the child element again if the properties are exactly the same, was not implemented. So it seems that https://github.com/orgs/honojs/discussions/3044 did not give the expected result.
If this pull request is merged, it would benefit from optimisation by React Compiler.

feat(jsx/dom): skip calculate children if props are the same

---

src/adapter/bun/conninfo.test.ts
src/adapter/cloudflare-pages/handler.test.ts
src/adapter/cloudflare-pages/handler.ts
src/adapter/cloudflare-pages/index.ts

Adds an adapter for [Cloudflare Pages middleware](https://developers.cloudflare.com/pages/functions/middleware/)
This provides a convenient way to use `Context` and helpers from `hono` within Cloudflare Pages middleware
Fixes #3015

feat(cloudflare-pages): Add Cloudflare Pages middleware handler

---

src/client/types.test.ts
src/client/types.ts

Routings without the leading slash like `app.get('foo', ...)` works well, but it seems like `hc` fails to extract its type correctly.
You can't access `hc<typeof app>('/').foo.$get`, which works on runtime though.

fix(client): set Path as the default of Original

---

src/router/linear-router/router.test.ts
src/router/reg-exp-router/router.test.ts

I was looking at the router tests and removed an async keyword that I thought was unnecessary.
I apologize if this was intended in any way.

refactor: remove unnecessary async keyword from router tests

---

src/adapter/cloudflare-pages/handler.test.ts
src/adapter/cloudflare-pages/handler.ts

This PR aims to increase the type safety of the Cloudflare Pages handlers by exposing the type parameters of the `handle` and `handleMiddleware` functions. These types are really only useful when writing tests

fix(cloudflare-pages): Expose Cloudflare Pages type parameters

---

src/validator/validator.test.ts
src/validator/validator.ts

fix(validator): don't return a FormData if formData is cached

---

src/client/client.test.ts
src/client/client.ts

This pull request adds support for query parameters to the WebSocket client in `hono/client`. The enhancement allows the WebSocket client to include query parameters in the URL, enabling more dynamic and flexible WebSocket connections.
- **Query Parameter Handling**: The WebSocket client can now accept and append query parameters to the WebSocket URL, allowing for more versatile and customized WebSocket connections.
```typescript
if (method === 'ws') {
const webSocketUrl = replaceUrlProtocol(
opts.args[0] && opts.args[0].param ? replaceUrlParam(url, opts.args[0].param) : url,
'ws'
);
const targetUrl = new URL(webSocketUrl);
for (const key in opts.args[0].query) {
targetUrl.searchParams.set(key, opts.args[0].query[key]);
}
return new WebSocket(targetUrl.toString());
}
```
This change was …

fix(client): Add Query Parameter Support to WebSocket Client in `hono/client`

---

src/types.test.ts
src/types.ts

This PR make changes based on @yusukebe's fix/workaround for the weird overload bug when using validator.
We simply move the `path, handler x*` overload down level.

refactor(types): move `HandlerInterface`'s `(path, handler)`s overloads down

---

src/helper/dev/index.test.ts

I found a typo in the test case.

test(helper/dev): fix typo of test case name

---

runtime_tests/bun/index.test.tsx
runtime_tests/deno/stream.test.ts
runtime_tests/node/index.test.ts
src/helper/streaming/sse.ts
src/helper/streaming/stream.ts
src/utils/stream.ts

#3042 fixed the problem in bun, but in deno, `onAbort()` was being called after a successful exit.
In deno, an "abort" event is fired for `req.signal` even if it exits successfully.
In this pull request, fix so that `onAbort()` is not called when stream finishes successfully.
```ts
app.get('/stream', (c) => {
return stream(c, async (stream) => {
stream.onAbort(() => {
console.log('Aborted!')
})
await stream.write('Hello')
})
})
export default app
```

fix(stream): Fixed a problem that onAbort() is called even if request is normally closed in deno

---

src/adapter/aws-lambda/handler.ts

Currently it is bugged if the cookie have comma: "," in it's value/key.  
Example: cookie with an `Expires`:  
The PR fixes this by using the newer `Header`.getSetCookie() if possible (it's still relatively new), with safe falling iterating the `Header` and extracting the set-cookie values.

fix(aws-lambda): set cookies with comma is bugged

---

src/types.test.ts
src/types.ts

fix(types): infer `path` when chaining after `use`

---

src/context.ts
src/hono-base.ts
src/http-exception.ts
src/middleware/basic-auth/index.ts
src/middleware/bearer-auth/index.ts
src/middleware/body-limit/index.ts
src/middleware/cache/index.ts
src/middleware/compress/index.ts
src/middleware/cors/index.ts
src/middleware/csrf/index.ts
src/middleware/etag/index.ts
src/middleware/jsx-renderer/index.ts
src/middleware/jwt/jwt.ts
src/middleware/logger/index.ts
src/middleware/method-override/index.ts
src/middleware/pretty-json/index.ts
src/middleware/secure-headers/secure-headers.ts
src/middleware/timing/timing.ts
src/middleware/trailing-slash/index.ts
src/request.ts

Since directory structures of `hono.dev` has changed due to https://github.com/honojs/website/pull/357, and update the links in JSDoc.

chore: update outdated links in JSDoc

---

src/jsx/base.ts
src/jsx/index.test.tsx
src/jsx/intrinsic-elements.ts

Closes: #3093
This patch changes behavior when `download` attribute is set to a boolean value.
before:
```tsx
console.log(<a download></a>) // => <a download="true"></a>
console.log(<a download={ false }></a>) // => <a download="false"></a>
```
after:
```tsx
console.log(<a download></a>) // => <a download=""></a>
console.log(<a download={ false }></a>) // => <a></a>
```

 fix(jsx): changes behavior when `download` attribute is set to a boolean value.

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

- Closes: #3091 
Changes
--- 
Firstly, it's need to create the label.

chore: add the triage label

---

src/context.ts
src/types.test.ts
src/utils/types.test.ts
src/utils/types.ts

I've improved `JSONParsed` in order to follow the spec of `JSON.stringify` as much as possible.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description
Here is major improvement:
- support tuple type
- handle undefined, symbol, and function type correctly(in array or object). For example
- convert undefined to null in an array
- drop keys whose value is undefined 
You can see some actual behaviour in [TS playground](https://www.typescriptlang.org/play/?#code/MYewdgziA2CmB00QHMAUByAZgVzMALgJbgBc6ANAAQBSAygPIBy8E+AToWMoZgJ6qoAlJQC8APkoBvAL6DhAenmVcAE1iZOsFQChQkGAiRp0EXgFsARjDJU6TFu07c+qWuavR4mEG1QAiCD85BSVVdU0dPSg4RBQMU0sYSgBrWF4AbRALACtYAgBdChoGZlYOLh5+SUp0t0TPb18AoPySSgBGWRDKPxk-XXBowzj0MI0wLUycvPxC2xKHcucqygBDNrGIyi7KRR6+gf0Yo3j3JIA3Vehs …

feat(types): improve JSONParsed

---

src/utils/http-status.ts

I think each of `UnOfficalStatusCode` and `UnofficialStatusCode` are the same types (-1).
So, I can remove this line.

refactor(http-status): remove unnecessary line of types and use common types

---

src/helper/conninfo/types.ts

This is optional, but it should allow an `undefined`.

fix(helper/conninfo): add `undefined` for `AddressType`

---

src/adapter/vercel/conninfo.test.ts
src/adapter/vercel/conninfo.ts
src/adapter/vercel/index.ts

This pr adds `getConnInfo` for vercel adapter based on https://github.com/vercel/vercel/blob/b70bfb5fbf28a4650d4042ce68ca5c636d37cf44/packages/edge/src/edge-headers.ts#L10-L12C32

feat(vercel): add `getConnInfo` for vercel adapter

---

src/adapter/vercel/conninfo.ts

In #2958, we plan to remove an unnecessary address type.
So this PR removes it from vercel adapter.

fix(vercel): remove deprecated address type

---

src/jsx/intrinsic-elements.ts

The scope attribute of the `th` element is defined as an enumerated type in the HTML spec.
[Reference](https://html.spec.whatwg.org/multipage/tables.html#attr-th-scope:~:text=The%20scope%20attribute%20is%20an%20enumerated%20attribute%20with%20the%20following%20keywords%20and%20states%3A)
So I redefined it. 
(To avoid destructive changes, the definition as a string type is retained.)

fix(jsx): redefine scope attribute as enum type

---

src/types.ts
src/validator/validator.test.ts

fix(types): allow `string[] | File[]` for RPC form value

---

src/adapter/lambda-edge/conninfo.test.ts
src/adapter/lambda-edge/conninfo.ts
src/adapter/lambda-edge/index.ts

Added `getConnInfo` for AWS Lambda@Edge.
Here is the code tested in the actual AWS environment.
https://github.com/yasuaki640/hono-lambda-edge-conninfo-20240705/blob/main/lambda/index_edge.ts

feat(lambda-edge): add `getConnInfo` helper for Lambda@Edge

---

jsr.json
package.json
src/adapter/service-worker/handler.test.ts
src/adapter/service-worker/handler.ts
src/adapter/service-worker/index.ts
src/adapter/service-worker/types.ts
tsconfig.json

I added adapter for Service Worker on browser.
I think that Hono is good for creating Service Worker.
In the PR, you can write code like that:
```ts
import { handle } from 'hono/service-worker'
app.get('/', c => c.text('Hello World'))
self.addEventListener('fetch', handle(app))
```
When app responses 404, adapter fetches the original server.

feat: Introduce Service Worker Adapter

---

jsr.json
package.json
src/middleware/request-id/index.test.ts
src/middleware/request-id/index.ts
src/middleware/request-id/request-id.ts

Request ID middleware generates a unique id for a request.
The unique request id can be used to trace a request end-to-end.
```ts
app.use(requestId())
console.log(c.get('requestId'))
return c.text('Hello World!')
})
```
It is also easily customizable with several options.
```ts
type RequesIdOptions = {
// The maximum length of request id.
// The default value is 255. 
limitLength?: number
// The header name used in request id.
// The default value is 'X-Request-Id'.
headerName?: string
// The request id generation function.
// The default value is 'crypto.randomUUID()'.
generator?: (c: Context) => string
}
```

feat(middleware): introduce Request ID middleware

---

src/middleware/combine/index.ts
src/middleware/ip-restriction/index.ts

chore: update comments in codes

---

src/jsx/intrinsic-elements.ts

The definition of the global attribute was added with reference to the [html specification](https://html.spec.whatwg.org/multipage/dom.html#global-attributes).
In my opinion, this PR will make hobo/jsx more user-friendly, though.
(It is debatable to what extent we should follow the HTML specification, so this PR will be closed if it is not necessary.)

feat(jsx): add global attributes to interface definition

---

src/middleware/jwt/jwt.ts

This PR allows the JWT-middleware secret to be a `SignatureKey`, instead of being limited to a `string`.
Since the secret is only passed to `Jwt.verify`, which already takes a `SignatureKey`, the parameter for the middleware should match.

fix(middleware/jwt): Changed the jwt-secret type to SignatureKey

---

src/middleware/bearer-auth/index.test.ts
src/middleware/bearer-auth/index.ts

feat(bearer-auth): Allow empty bearer-auth middleware prefixes

---

src/client/client.test.ts
src/client/client.ts

fix(client): support array values for `query` in `ws`

---

src/validator/validator.test.ts
src/validator/validator.ts

With this PR, the validator will ignore the mismatch between the validate type like `json` and `form` and the content type of the incoming request.
Before this PR, it will throw the error if the validator validates a request that does not have a valid content type for validate type, including `json` and `form`:
```ts
app.post(
'/post',
validator('json', (value) => value),
(c) => {
return c.json(c.req.valid('json'))
}
)
const res = await app.request('http://localhost/post', {
method: 'POST',
body: JSON.stringify({ foo: 'bar' }),
headers: {
// Does not set a content-type
},
})
// res.status will be 400!
```
This is inconvenient since it can't allow requests with no content type.
And with this spec, it does not support multiple validators for the body:
```ts
app.post( …
```

fix(validator): ignore content-type mismatches

---

src/helper/adapter/index.ts

fix(helper/adapter): don't check `navigator` is `undefined`

---

src/utils/types.test.ts
src/utils/types.ts

My apologies that `JSONParsed` didn't convert `ReadonlyArray` type correctly. Types of methods disappeared

fix(types): handle readonly array correctly

---

src/helper/adapter/index.ts

This reverts commit a285c4b3b4bc7a9c162ec24669c9890b16f91f63.
Related to #3158
I thought `navigator` would be `undefined` in the production of Cloudflare Pages. But it will not be `undefined` if we set `compatibility_date` correctly. So the commit is not necessary. We should keep the code clean.

Revert "fix(helper/adapter): don't check `navigator` is `undefined`

---

src/context.ts
src/types.test.ts
src/utils/types.ts

fix #3135 
This works in the use case of the reported issue, I'm not 100% sure why this works though

fix(type): degradation of generic type handling

---

src/middleware/csrf/index.ts

There was a section that appeared to be a naming discrepancy, which has been corrected.

fix:(csrf) fix typo of csrf middleware

---

src/middleware/secure-headers/index.test.ts
src/middleware/secure-headers/secure-headers.ts

Close https://github.com/honojs/hono/issues/3175

feat(secure-headers): remove "X-Powered-By" should be an option

---

src/validator/validator.ts

Some runtimes, like Bun (and I assume WebKit based stuff) use double quotes for the `boundary` part of `Content-Type` headers.
Here's a real value from my app: `multipart/form-data; boundary="-WebkitFormBoundary6210507107db483aa49299da6f4298bd`.
Currently, the regex does not include double quotes. This PR fixes this issue by adding double quotes. Patch tested working in my app for Hono 4.5.2.

fix(validator): Add double quotation marks to multipart checker regex

---

src/validator/validator.test.ts
src/validator/validator.ts

fix(validator): support `application/json` with a charset as JSON

---

src/jsx/dom/index.test.tsx
src/jsx/dom/render.ts

fix #3201
* First time rendering does not need to look for elements from child nodes
** Avoid unnecessary checks with `node.pP`.
* Sibling elements are always searched, so there is no need for a for loop.
** Need only `findInsertBefore(node.vC[0])`
I have not added any additional tests as there is already sufficient testing on the expected rendering results.
For performance, although it is a simple test, I have added a test to check that I am not getting as much computation as n to the nth power.

fix(jsx/dom): fix performance issue with adding many new node listings

---

src/jsx/intrinsic-elements.ts

closes #3223 
Since [the html specification defines the draggable attribute as an enum](https://html.spec.whatwg.org/multipage/dnd.html#the-draggable-attribute),
we have modified it to conform to that specification.

fix(jsx): corrects the type of 'draggable' attribute in intrinsic-elements.ts

---

src/jsx/intrinsic-elements.ts

Type declarations don't allow to merge, so [overriding type declaration](https://hono.dev/docs/guides/jsx#override-type-definitions) from docs doesn't work for CSSProperties.

feat(jsx): allow to merge CSSProperties declaration

---

src/client/client.test.ts
src/client/client.ts
src/client/types.ts

I use hono/client and wanted to reconnect websockets. However, the $ws method in hono/client internally creates a new WebSocket, so in order to use a websocket client with reconnection, it was necessary to define the url directly. This would lose the type safety of Hono RPC.
This change allows the use of clients that conform to WebSocket interfaces with reconnection, such as [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket), internally.
```ts
import ReconnectingWebSocket from 'reconnecting-websocket';
const client = hc<AppType>(url, {
webSocket(url, options) {
return new ReconnectingWebSocket(url, options)
},
})
client.index.$ws({ query })
```
- Added new test cases for WebSocket provider integration to ensure correct initialization and handling of query …

feat(client): Add WebSocket Provider Integration Tests and Enhance WebSocket Initialization

---

src/types.ts
src/validator/validator.test.ts

Fixes #3227
In the current branch, `param` will be `Record<string, string> | Record<string, string | undefined>` regardless of whether the value of path param is optional or not. With this PR, the value type will be `string` by default, but it will be `string | undefined` if it is optional.

fix(types): `param` in `ValidationTargets` supports optional param

---

runtime_tests/deno-jsx/jsx.test.tsx
src/jsx/base.ts
src/jsx/index.test.tsx

fixes #3235
The deno converts an empty `Fragment` to `null` when the value of the "jsx" entry is "precompile", but "hono/jsx" was not able to handle the function component returning `null`, which caused the problem #3235.
In the current React type definition, `FunctionComponent` returns the `ReactNode`, and since `ReactNode` also includes `boolean` and `undefined`, it would be preferable if Hono's `FC` also included these (`boolean` and `undefined`). 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1114-L1122
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L478-L489
However, the changes to add `undefined` and `boolean` have a considerable impact on existing code, so I have chosen not to do so in this pull …

fix(jsx): allow null, undefined, and boolean to be returned from function component

---

src/context.ts

I added a types for `c.header`.
I'm sure you can type headers easier.
If we merged this, we can use custom header names as before.
From: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

feat(context): Add types for `c.header`

---

src/jsx/intrinsic-elements.ts

React accepts a boolean for the draggable attribute, so I adapted the behavior.
Incidentally, other [Boolianish values](https://github.com/facebook/react/blob/ba6a9e94edf0db3ad96432804f9931ce9dc89fec/packages/react-dom-bindings/src/client/ReactDOMComponent.js#L649-L654) also render a 'true' or 'false' string when they receive a boolean, so this type definition should be less confusing to the user.
An example of the code is as follows
```tsx
it('test draggable', () => {
const template = <div draggable={true}>draggable</div>
expect(template.toString()).toBe('<div draggable="true">draggable</div>')
})
// other booleanish value
it('test spellcheck', () => {
const template = <div spellcheck={true}>spellcheck</div>
expect(template.toString()).toBe('<div spellcheck="true">spellcheck</div>')
}) …
```

fix(jsx): fix draggable type to accept boolean

---

src/jsx/index.test.tsx
src/utils/html.ts

fixes #3252
`Uncaught (in promise)` was occurring and the app was crashing under the following conditions.
* There are multiple asynchronous components.
* While waiting for the first Promise to be resolved, an error occurred in the subsequent Promise.

fix(jsx): handle async component error explicitly and throw the error in the response

---

src/validator/validator.ts

Closes [3285](https://github.com/honojs/hono/issues/3285)

fix(validator): support multipart headers without a separating space

---

src/jsx/intrinsic-elements.ts

Improve meta-tag types with well known values like `c.header` (#3221) .
Now, we can use auto-completion in JSX:

feat(jsx): improve meta-tag types with well known values

---

src/jsx/dom/intrinsic-element/components.test.tsx
src/jsx/dom/intrinsic-element/components.ts

Script elements with empty props or only src were inserted as style elements by typo.

fix(jsx/dom): Fixed a bug that caused Script elements to turn into Style elements.

---

src/jsx/dom/context.ts
src/jsx/dom/index.test.tsx
src/jsx/dom/intrinsic-element/components.test.tsx
src/jsx/dom/intrinsic-element/components.ts
src/jsx/dom/jsx-dev-runtime.ts
src/jsx/dom/render.ts
src/jsx/dom/utils.ts
src/jsx/hooks/dom.test.tsx
src/jsx/hooks/index.ts

#3264
As @ryuapp  pointed out in #3203, the implementation with recursive calls did not perform well and sometimes resulted in errors when there were a large number of elements, so it was modified so that recursive calls were not made.
* `reactElement.type`
* `reactElement.ref`
https://github.com/honojs/hono/compare/main...usualoma:hono:perf/jsx-dom?expand=1#diff-c9b14c1b74662b399c25e6dc0c870408c466e1c96e39a1d429903b2a3d0db51fL11-L20
The code to make the following properties referential is for React compatibility, but the implementation using `Object.defineProperties` was very expensive. This change is not pretty, but it is an acceptable redundancy when considered as a trade-off for improved performance.
In some cases, DOM attributes were being reassigned even when there were no changes …

perf(jsx/dom): improve performance

---

src/jsx/intrinsic-elements.ts
src/utils/types.ts

ref. #3276
* Refactor `LiteralUnion` type. It moves to utils directory and renamed to `StringLiteralUnion`.
* Improve a-tag types with well known values like meta-tag(#3276).

feat(jsx): improve a-tag types with well known values

---

src/validator/validator.test.ts
src/validator/validator.ts

fix(validator): Fixed a bug in hono/validator where URL Encoded Data could not be validated if the Content-Type included charset.

---

src/jsx/intrinsic-elements.ts

Improve `target` and `formtarget` types.
* area/target https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area#target
* base/target https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base#target
* button/formtarget https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#formtarget
* form/target https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#target
* input/formtarget https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#formtarget
Should I rename `HTMLAttributeAnchorTarget` ?

feat(jsx): improve `target` and `formtarget` attribute types

---

src/client/client.test.ts
src/client/utils.test.ts
src/client/utils.ts

fix(client): replace optional params to url correctly

---

src/jsx/intrinsic-elements.ts

improve input attribute types based on react
ref. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/865051c6befe8d67f7ac2fdcac6cdf4922c1dc83/types/react/index.d.ts#L3263-L3389
I think `autocomplete` is too complex 😅 
But I respect react types.

feat(jsx): improve input attribute types based on react

---

src/types.test.ts

Fixed a test that will fail with future TypeScript versions.
Upgrade TypeScript to `5.6.0-dev.20240819` and run `bun run test`. You'll get this error.
This is a long story, but in short, the test passes because of a bug of TypeScript. I reported the bug and it was fixed.
https://github.com/microsoft/TypeScript/issues/59450
The error was detected in https://github.com/microsoft/TypeScript/pull/59516#issuecomment-2265997355
Why does the test pass? This is because the return type of the function passed to `set('ok', ...)` is `TypedResponse<never>`. For any type `T`, `never` is subtype of `T`, so type-checking passes.
I can say `{ data: TData }` is treated as `never` here. This is just a bug of TypeScript. Because of the bug, `SimplifyDeepArray<{ data: TData }> extends JSONValue` is always …

test(types): broken test in future versions of typescript

---

src/utils/color.ts

If we run Hono with Deno in node-compat mode, permission to obtain `NO_COLOR` from env is required in logger and showRoutes.
This PR fixes that and add the Doc.
If you want to reproduce the current situation, try the following ways:
1. Make a directory and add Hono.
```sh
mkdir my-app
cd my-app
bun add hono
```
2. Run this script by Deno.
```ts
// deno run main.ts
import { getColorEnabled } from "hono/utils/color"
console.log(getColorEnabled())
```
3. Deno requests env access to "NO_COLOR".
```sh
┌ ⚠️  Deno requests env access to "NO_COLOR".
├ Run again with --allow-env to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all env permissions) >
```

fix(utils/color): Deno does not require permission for `NO_COLOR`

---

src/jsx/intrinsic-elements.ts

embed, link, object, script, source, and style elements
I did NOT add BaseMime to either source, script or style element. Should I do this?

feat(jsx): improve `type` (MIME) attribute types

---

src/middleware/pretty-json/index.test.ts
src/middleware/pretty-json/index.ts

Pretty JSON middleware changed to support custom queries, like that:
```ts
app.use('*', prettyJSON({
query: 'format'
})
```
In this case, you can see formatted JSON at `?format`.  I think it should be customizable.

feat(pretty-json): support custom query

---

src/jsx/intrinsic-elements.ts

I added attribute types for the [Popover API](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API).

feat(jsx): add popover api attributes

---

src/jsx/intrinsic-elements.ts

Improve form attribute types (`accept-charset`, `autocomplete`, `enctype` and `method`).
`button` and `input` tag attributes are also updated (`formenctype` and `formmethod`).

feat(jsx): improve form attribute types

---

src/router/common.case.test.ts

I forgot to replace the deprecated type in #3326 , so I replaced it.
[reference.](https://github.com/vitest-dev/vitest/blob/372a2c26a8e5ac2cfe6db961ed40529f09464e82/packages/vitest/src/public/index.ts#L130-L131)

chore(test): replace deprecated vitest type

---

src/middleware/logger/index.test.ts
src/middleware/logger/index.ts

fix(logger): removing spaces from logger

---

src/jsx/components.test.tsx
src/jsx/components.ts

#3333
Fixed a bug when multiple tasks were executed in parallel via event loop (setTimeout).

fix(jsx): race condition in ErrorBoundary with event loop

---

src/jsx/base.ts
src/jsx/index.test.tsx
src/jsx/intrinsic-element/components.ts

#3347
The following elements are no longer special behavior when they are already in the head element.
* title
* meta
* script
In my environment, the results were as follows
```
benchmark        time (avg)             (min … max)       p75       p99      p999
--------------------------------------------------- -----------------------------
• Real World Scenario
--------------------------------------------------- -----------------------------
KitaJS/Html     426 µs/iter     (352 µs … 1'410 µs)    384 µs    856 µs  1'015 µs
Typed Html    1'644 µs/iter   (1'477 µs … 2'078 µs)  1'751 µs  1'960 µs  2'078 µs
VHtml         2'184 µs/iter   (2'051 µs … 2'730 µs)  2'248 µs  2'655 µs  2'730 µs
React JSX     5'673 µs/iter   (5'406 µs … 6'461 µs)  5'898 µs  6'422 µs  6'461 µs
Preact          793 …
```

perf(jsx): skip the special behavior when the element is in the head.

---

src/utils/body.ts

refactor(utils/body): shorten the code

---

src/middleware/jsx-renderer/index.ts

chore: fix typo in JSDoc

---

src/middleware/basic-auth/index.ts
src/utils/basic-auth.test.ts
src/utils/basic-auth.ts

I have moved the functions used internally in the Basic Auth Middleware to the utils directory. Additionally, I have added tests.
For the background on this refactor, please refer to the following: https://github.com/honojs/middleware/pull/676#issuecomment-2323178685

refactor(utils/basic-auth):  Moved Internal function to utils 

---

runtime_tests/deno-jsx/deno.precompile.json
runtime_tests/deno-jsx/deno.react-jsx.json
runtime_tests/deno-jsx/jsx.test.tsx
runtime_tests/deno/deno.json
runtime_tests/deno/deno.lock
runtime_tests/deno/deps.ts
runtime_tests/deno/hono.test.ts
runtime_tests/deno/middleware.test.tsx
runtime_tests/deno/ssg.test.tsx
runtime_tests/deno/stream.test.ts

Update libraries for writing tests in #3367. Also, this PR removes unnecessary code.

chore(deno): use the latest jsr libraries for testing

---

src/middleware/secure-headers/index.test.ts
src/middleware/secure-headers/permissions-policy.ts
src/middleware/secure-headers/secure-headers.ts

…iddleware
Permissions-Policy was added to Secure Headers Middleware.
For more information on Permissions-Policy, please refer to the following.
EN: [Permissions-Policy | MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy)
EN: [Permissions Policy - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy)
JA: [Permissions-Policy - HTTP | MDN](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Permissions-Policy)
JA: [Permissions Policy - HTTP | MDN](https://developer.mozilla.org/ja/docs/Web/HTTP/Permissions_Policy)
Documetn Policy, which is listed as a similar Header, is not a Security requirement and does not need to be addressed.

feat(secureHeader): add Permissions-Policy header to secure headers middleware

---

src/adapter/cloudflare-pages/handler.test.ts
src/adapter/cloudflare-pages/handler.ts

Fixes #3320
This is for the Cloudflare Pages adapter. With this PR, you can access `EventContext` object in `hanldeMiddleware` via `c.env`.
```ts
// functions/_middleware.ts
import { handleMiddleware } from 'hono/cloudflare-pages'
export const onRequest = [
handleMiddleware(async (c, next) => {
c.env.eventContext.data.user = 'Joe'
await next()
}),
]
```
Then, you can access the data value in the handler:
```ts
// functions/api/[[route]].ts
import type { EventContext } from 'hono/cloudflare-pages'
import { handle } from 'hono/cloudflare-pages'
type Env = {
Bindings: {
eventContext: EventContext
}
}
const app = new Hono<Env>().basePath('/api')
const routes = app.get('/hello', (c) => {
message: `Hello, ${c.env.eventContext.data.user}!`, // 'Joe'
}) …
```

feat(cloudflare-pages): enable `c.env.eventContext` in `handleMiddleware`

---

src/adapter/bun/websocket.ts
src/adapter/cloudflare-workers/websocket.ts
src/adapter/deno/websocket.ts
src/helper/websocket/index.ts

Fix #3327 
In this pull request, you can set `ws.raw` type as `ServerWebSocket` on Bun.
So, you can now use Bun own WebSocket API, including Pub/Sub feature!
```typescript
import { createBunWebSocket } from 'hono/bun'
import type { ServerWebSocket } from 'bun'
const { upgradeWebSocket, websocket } = createBunWebSocket<ServerWebSocket>()
app.get(
'/ws',
upgradeWebSocket((c) => {
return {
onMessage(event, ws) {
ws.raw.subscribe('chat-test') // ws.raw type is unknown now, but we will be able to set ServerWebSocket.
},
}
})
)
```

feat(websocket): Add generics type to `WSContext`

---

src/middleware/jsx-renderer/index.test.tsx
src/middleware/jsx-renderer/index.ts

With this PR, if the `stream` is `true,` it will set `Content-Encoding` as `Identity`. This is needed to correct the behavior of `Suspense` when the content is encoded like `gzip.`

feat(jsx-renderer): set `Content-Encoding` when `stream` is `true`

---

jsr.json
package.json
src/middleware/context-storage/index.test.ts
src/middleware/context-storage/index.ts

Supersedes https://github.com/honojs/hono/pull/3335

feat(contextStorage): added Context Storage Middleware

---

src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts

Closes #3363 
Allows to serve all compatible pre-compressed files transparently to the client, otherwise fallback to serve the *original* file.
In case there are several files with various encodings (e.g., *.gz* and *.br*), it has priority to use brotli, then zstd and finally gzip.

feat(serveStatic): add `precompressed` option

---

src/context.ts
src/helper/streaming/sse.test.tsx
src/helper/streaming/sse.ts
src/utils/html.ts

#3319
This change allows you to use "hono/jsx" to write the following in streamSSE. I don't think there are many use cases, but the changes on the `helper/streaming/sse.ts` side are also small and could be added to the implementation.
```tsx
streamSSE(c, async (stream) => {
await stream.writeSSE({ data: <div>Hello</div> })
})
```
```tsx
streamSSE(c, async (stream) => {
await stream.writeSSE({
data: (
<ErrorBoundary fallback={<div>Error</div>}>
<AsyncComponent />
</ErrorBoundary>
),
})
})
```

feat(helper/streaming): Support Promise<string> or (async) JSX.Element in streamSSE

---

runtime_tests/node/index.test.ts
src/context.test.ts
src/context.ts

The added test fails without the PR.
Fixes:
- https://github.com/honojs/hono/issues/3316

feat(context): make fetch Response headers mutable

---

src/middleware/secure-headers/index.test.ts
src/middleware/secure-headers/secure-headers.ts

I am very sorry.
I found a bug (wrong specification) and fixed it.
- When specified with `{delective}: true`, `true` means “allowed at all origins” and should be represented as `*` in the header. However, an empty parenthesis () is printed, implying a restriction.
Please let me know if there is a problem, because I don't know if I should direct the PR to the `next` branch.

fix(secure-headers): optimize getPermissionsPolicyDirectives function

---

src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts

This PR introduces the `onFound` option for Serve Static Middleware.
If you want to add a custom header to found files, you can write the following:
```ts
app.get(
'/static/*',
serveStatic({
// ... 
onFound: (_path, c) => {
c.header('Cache-Control', `public, immutable, max-age=31536000`)
},
})
)
```
Related to #3395 https://github.com/honojs/node-server/pull/195

feat(serve-static): add `onFound` option

---

src/middleware/basic-auth/index.test.ts
src/middleware/basic-auth/index.ts

feat(basic-auth): added custom response message option

---

src/middleware/bearer-auth/index.test.ts
src/middleware/bearer-auth/index.ts

feat(bearer-auth): added custom response message options

---

build.ts

This PR improves the extension handling (in esm build) in `build.ts`.
Currently in `addExtension` esbuild plugin, we create the import path like `${args.path}/index${extension}` when the ts path of the form `path.join(args.resolveDir, args.path, "index.ts")` exists. However this has an issue when the original import path ends with `/` (like [this one](https://github.com/honojs/hono/blob/73ff6c0e82d66468e28ed439481220f56ab03882/src/helper/streaming/text.ts#L4)). In that case the resulted import path becomes something like `.//index.js`. This import path seems confusing some runtimes (ex. Deno https://github.com/denoland/deno/issues/25532 ).
This PR checks whether the original path ends with `/` or not, and creates more appropriate path.
By this change, for example, the build result of …

fix(build): improve addExtension esbuild plugin

---

src/middleware/compress/index.ts
src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts
src/utils/compress.ts

* 6a675c3e79877775c9815023a24f30acdcdeba9e : Replace with faster implementation
* 7f58d8f1aaa142b2f475d0bf0acb00bc2bcaf783 : "Content-Type" is appropriate to set only if the file is found
* 9aeb1cd2522522fc821f98c100f6a2f28ce484bb : As I wrote in https://github.com/honojs/node-server/pull/199#issuecomment-2351498366, if the file is not a compressible mime type, it is better not to find a compressed file

perf(serve-static): performance optimization for precompressed feature

---

src/middleware/serve-static/index.test.ts
src/middleware/serve-static/index.ts

Currently, if the `mimeType` could not be detected, the `Content-Type` is not set, so it falls back to “text/plain”. There may be cases where “text/plain” is acceptable, but I don't think it is appropriate for binary data to be returned as "text/plain", so I think it should be "application/octet-stream”. Even on general web servers, the default is "application/octet-stream" for files that cannot be detected from the file extension.

fix(serve-static): use application/octet-stream if the mime type is not detected

---

src/types.ts

`Instantiation` ave dropped by more than 10%（3,438,492->2,997,759)

perf(types): rm conditions to get better performance

---

src/utils/types.ts

…anches
Reduced conditional branches by using homomorphic mapped type.
The number of type instantiation has dropped a bit and the definition became simpler than before
FYI
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#mapped-types-on-tuples-and-arrays
- https://andreasimonecosta.dev/posts/what-the-heck-is-a-homomorphic-mapped-type/

perf(types): use homomorphic mapped type to reduce conditional branches

---

.github/workflows/ci.yml
perf-measures/type-check/scripts/process-results.ts

We decided not posting the result so rm the comment-outed lines and format the table to get better view in the detail page of workflow
#3438

ci: prettify type check result and rm a comment

---

src/jsx/hooks/index.ts

Align with react
note: the parameter is not used in function body

fix(types): useSyncExternalStore type

---

src/middleware/combine/index.test.ts
src/middleware/combine/index.ts

When using `every` middleware to compose middlewares that short-circuits the chain (i.e. return a `Response` object, like e.g. `zod-validator`, but I had also issues with e.g. `cors` with OPTIONS requests) and, as a result, don't call `next()`, it was throwing an error `Error: Context is not finalized. Did you forget to return a Response object or await next()?`. This fixes the issue and makes it possible to use it with (probably?) any middleware.
As a side note, I attempted to simplify the `compose`'s middleware signature (and I did) as it could easily accept an array of functions/handlers and simplify the code. But I think the signature is so complicated because of the usage in `dispatch` method of the `Hono` class and that would require mapping to an array of handlers which would …

fix(combine/every): make `every` middleware work with short-circuiting middlewares

---

src/middleware/secure-headers/index.test.ts
src/middleware/secure-headers/secure-headers.ts

feat(secureHeader): add CSP Report-Only mode support

---

jsr.json

feat(request): Make request.ts available throught JSR for frameworks that need to instantiate HonoRequest

---

runtime-tests/deno-jsx/jsx.test.tsx
src/jsx/base.ts
src/jsx/jsx-runtime.ts

fix #3427
The “precompile” process converts attribute values in the same way as the normal `renderToString` process.
https://github.com/usualoma/hono/blob/fd80df6a0f03876cf6ac2b12b4b7b812c19ca616/src/jsx/base.ts#L180-L227

feat(jsx/precompile): Normalization and stringification of attribute values as `renderToString`

---

src/client/types.test.ts
src/helper/factory/index.test.ts
src/helper/ssg/ssg.test.tsx

👇  Suppresses noisy false-positives on pull requests.
> [!note]
> Unfortunately, [there is no option to allow type-only usage and only available fix is to disable.](https://github.com/typescript-eslint/typescript-eslint/issues/9778#issuecomment-2282777895)

chore(test): suppress no-unused-vars "'x' is assigned a value but only used as type"

---

src/jsx/base.ts

make `arr.map(x => <CustomComponent key={x.id} />)` not emit type error

fix(types): add key to IntrinsicAttributes

---

src/helper/factory/index.test.ts
src/helper/factory/index.ts

If there were type mismatches regarding `Bindings` and `Variables` with nested middleware created by `createMiddleware`, it threw the error. I've fixed it does not throw the type error. 
```ts
MY_VAR_IN_BINDINGS: string
}
const app = new Hono<{ Bindings: Bindings }>()
type Variables = {
MY_VAR: string
}
const middleware = (_variable: string) =>
createMiddleware<{ Variables: Variables }>(async (c, next) => {
await next()
})
app.get(
'/',
createMiddleware<{ Bindings: Bindings }>(async (c, next) => {
const mw = middleware(c.env.MY_VAR_IN_BINDINGS)
await mw(c, next) // `c` does not throw an error
}),
(c) => {
return c.json({})
}
)
````

fix(factory): relax Bindings and Variables for `createMiddleware`

---

src/adapter/service-worker/handler.test.ts
src/adapter/service-worker/handler.ts

This PR fixes #3176 correctly. It was not working with #3200.
I added a test but it's full of mocks and probably not much useful. Feel free to remove it 😅
Ideally an e2e test is needed.

fix(service-worker): bind fetch to `globalThis`

---

src/jsx/base.ts

Avoid the error when running `test:deno`:

refactor(jsx): add `override` to `toStringToBuffer` in classes extending `JSXNode`

---

src/hono-base.ts
src/types.ts
src/utils/types.ts

**This leads a breaking change**
I found that massive amount of intersection increase type instantiation.
So, I've tried replacing intersections to union and as a result, this has decreased type instantiation drastically, that is, by about 70%.
However, union here is not intuitive and this may be a breaking change for users manipulating type of Hono somehow. I'm not certain how they do that, though
@yusukebe What's your thought on that? Do you think we should go for it this way?

perf(types): replace intersection with union to get better perf

---

.github/workflows/ci.yml

ci: use Deno `v2`

---

.github/workflows/ci.yml

Deno 2 has been released, so I changed a CI.

ci: use Deno v2 for a test running for deno

---

perf-measures/type-check/client.ts
src/client/types.ts
src/hono-base.ts
src/utils/types.ts

It's super weird, but if `ExcludeEmptyObject` is outside of `hono-base.ts`, "Type instantiation is excessively deep and possibly infinite." error occurs.
Please use this script to check
https://github.com/honojs/hono/pull/3443#issuecomment-2380551431
I don't know the cause at all, it may be a kind of cache issue, though

fix(types): rm ExcludeEmptyObject to fix massively increased type instantiations

---

src/middleware/cors/index.test.ts
src/middleware/cors/index.ts

Even if the `Origin` header of a request does not match a origin specified by `origin` option, CORS middleware always sets `Access-Control-Allow-Origin` header. I don't see this as a serious problem, but in some cases it may unintentionally expose a server setting.
- https://github.com/expressjs/cors/blob/v2.8.5/test/test.js#L251-L262 - `cors` package seems not to set the `Access-Control-Allow-Origin` if the `Origin` header of a request does not match allowed origins
- https://fetch.spec.whatwg.org/#cors-check - A CORS check returns failure if the `Access-Control-Allow-Origin` header is missing
- [Currently, CORS middleware returns a origin specified by `origin` option as the `Access-Control-Allow-Origin` if the option does not match the `Origin` header of a …

fix(cors): avoid setting `Access-Control-Allow-Origin` if there is no matching origin

---

src/middleware/powered-by/index.test.ts
src/middleware/powered-by/index.ts

feat(powered-by): optional server name

---

src/middleware/powered-by/index.ts

docs(powered-by): add JSDoc

---

.devcontainer/devcontainer.json

I ran into some issues when using the Devcontainer setup in VS Code with Podman. This PR changes the devcontainer.json to allow the use of Podman. Docker usage should not be affected. It also adds the Prettier and ESLint Extensions for VS Code explicitly to the Devcontainer.

chore: podman support for devcontainer

---

src/adapter/deno/serve-static.ts

Silences the `NotFound` warning when a file is not found using `serveStatic` for Deno.
```
NotFound: No such file or directory (os error 2)
```
Noticed that this is already the default behaviour for Bun's adapter according to #1810 but it is not with Deno due to Deno not allowing to check directly for a file's existence. Ignoring the error is the only way to avoid the warning.

fix(serve-static): silence `NotFound` warning on Deno

---

src/client/client.test.ts
src/client/client.ts
src/client/types.ts
src/client/utils.test.ts
src/client/utils.ts

Resolves #3532. I'm not sure if there's a more concise way to write the type definition, or to write a test for it, but I was able to validate that it's working as expected locally.

fix(client): return query params in $url

---

src/adapter/vercel/handler.test.ts
src/adapter/vercel/handler.ts

Fixes #3548 
The `requestContext,` which is used in the second argument of the handler, is no longer needed. Because the current version of Next.js passes only the values of `params`. But, you can get the `params` value from `c.req.param()`.
Ref: https://nextjs.org/docs/app/api-reference/file-conventions/route#context-optional
Ref: https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#typescript

fix(vercel): remove `requestContext`

---

src/router/linear-router/router.test.ts
src/router/linear-router/router.ts
src/router/pattern-router/router.ts
src/router/smart-router/router.ts
src/router/trie-router/node.ts
src/router/trie-router/router.ts

router performance improvements
Explicitly cached lengths, adjusted the order of evaluation of logical expressions, (without regexp router, for readability)
and removed debugging properties to speed up and use other unique values.  (trie-router)

perf(router):  improve performance of router

---

src/adapter/bun/websocket.ts

fix(bun/ws): fix invalid types

---

src/helper/websocket/index.test.ts
src/helper/websocket/index.ts

Changed `WSContestInit` to `WSContextInit` to correctly reflect that this is a WebSocket Context initialization type, not Contest.
This was a simple typo where 'Context' was misspelled as 'Contest' in the type name.

fix(websocket): Fix typo in WSContextInit type

---

src/helper/websocket/index.test.ts
src/helper/websocket/index.ts

When sending a `Uint8Array` through the WebSocket's `send()` method, the current implementation converts it to its underlying `ArrayBuffer` using `source.buffer`. This becomes problematic when the `Uint8Array` is a view over a larger buffer, which is common in streaming scenarios.
For example, when streaming data with Bun, it internally uses a buffer pool with 16KB buffers for efficiency. So if you have a `Uint8Array` chunk of 800 bytes, it's actually a view over a 16KB buffer. The current implementation sends the entire 16KB buffer instead of just the 800 bytes of actual data:
```typescript
// Current implementation
send(source: string | ArrayBuffer | Uint8Array) {
this.#init.send(
source instanceof Uint8Array 
? source.buffer  // Sends entire 16KB buffer! 
: source
)
}
```
This causes: …

fix(websocket): prevent sending entire buffer when streaming Uint8Array chunks

---

src/adapter/bun/websocket.test.ts
src/adapter/bun/websocket.ts

fix(bun/ws): supoort `--hot`

---

.devcontainer/devcontainer.json

fix(devcontainer): remove unknown flag on docker-compose

---

runtime-tests/deno/stream.test.ts
src/helper/cookie/index.test.ts
src/helper/ssg/ssg.ts
src/helper/ssg/utils.ts
src/hono-base.ts
src/jsx/index.test.tsx
src/middleware/ip-restriction/index.ts
src/router/trie-router/node.test.ts
src/utils/ipaddr.test.ts

refactor: fix typos

---

src/hono.test.ts
src/request.ts
src/utils/url.ts

Fixes #3550
In the current behavior, the `c.req.param()` will throw the error when decoding invalid percent encoding or invalid UTF-8 sequence.
```ts
// app
app.get('/static/:path', (c) => c.text(c.req.param('path'))
// throw `URIError: URI malformed` error:
await app.request('/static/%A4%A2') //  %A4%A2 is invalid UTF-8 sequence
// throw `URIError: URI malformed` error:
await app.request('/static/%a') // %a is invalid percent encoding
```
These behaviors are expected in the current version implementation; they are tested:
https://github.com/honojs/hono/compare/fix/request-dont-throw-error-with-percent-strings?expand=1#diff-8ac13809c9886e994d1db33943de82df4d6c5d88b73fd0270c0189804ff565c2L772-L814
However, according to #3550, throwing the error will stop the application procedure, and it …

fix(req): correct `c.req.param` decodes invalid percent strings

---

src/jsx/dom/index.test.tsx
src/jsx/dom/render.ts

The code “Fragment is continuous across components” was not updating the DOM correctly, so it was fixed.
For example, the following
https://github.com/honojs/hono/compare/main...usualoma:hono:fix-consecutive-fragment?expand=1#diff-8f050239e20450fd8425feb7efbda60df851ebbc32bec8139d6d9ad1b53a7bc0R1123-R1145

fix(jsx/dom): fix dom rendering bugs for fragment.

---

src/compose.ts

perf(compose): check if it is a instance only once

---

src/router/reg-exp-router/router.ts

perf(router): use `.concat` instead of spread syntax

---

src/hono-base.ts

`.matchRoute` is a private method that is only called from one place and does not wrap a complex process, so I think it can be removed.  
This will reduce the bundle size.

fix(hono-base): remove `.matchRoute` and reduce bundle size

---

src/utils/url.ts

In addition to the cache of length,  
we have speeded up the check for the presence of characters in the string. (indexOf is faster than regex.)
```llvm
cpu: AMD EPYC 7763 64-Core Processor
runtime: node v20.18.0 (x64-linux)
benchmark            time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------- -----------------------------
Regex              95.21 ns/iter  (86.64 ns … 219.82 ns)   93.3 ns 197.55 ns 210.05 ns
IndexOf            12.2 ns/iter    (11.1 ns … 31.96 ns)  11.41 ns  24.33 ns  24.79 ns
```
```llvm
cpu: AMD EPYC 7763 64-Core Processor
runtime: deno 2.0.4 (x86_64-unknown-linux-gnu)
benchmark            time (avg)             (min … max)       p75       p99      p995 …
```

perf(utils/url): improve performance of url utility

---

src/context.ts

Improved performance of `setHeaders` and removed unnecessary checks in `.newResponse`.
The benchmark results are as follows
```llvm
cpu: AMD EPYC 7763 64-Core Processor
runtime: node v20.18.0 (x64-linux)
benchmark             time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------- -----------------------------
using .entries      1.19 µs/iter     (1.07 µs … 1.63 ms)   1.12 µs   2.69 µs   2.89 µs
using for syntax   707.2 ns/iter (683.65 ns … 948.47 ns) 714.47 ns 948.47 ns 948.47 ns
```
```llvm
cpu: AMD EPYC 7763 64-Core Processor
runtime: deno 2.0.4 (x86_64-unknown-linux-gnu)
benchmark             time (avg)             (min … max)       p75       p99      p995
-------------------------------------------------------- …
```

perf(context): improve performance of context (setHeaders)

---

src/helper/html/index.ts

`Array.isArray` is more widely used in Hono codebase, specially in `jsx` and `css`.
Theoretical reason: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-instanceof-array.md
And it's a bit shorter 😝 
```typescript
a instanceof Array // 18 chars
Array.isArray(a)  // 16 chars
```

refactor(helper/html): Prefer Array.isArray over instanceof Array

---

src/router/reg-exp-router/trie.ts
src/utils/color.ts

It's a bit shorter and more concise (Hono repo uses it widely over `typeof`).
Performance-wise, no changes.
```typescript
import { bench, run } from 'mitata'
const v = 'str'
bench('typeof ', () => {
const s = typeof v === 'undefined'
})
bench('direct', () => {
const s = v === undefined
})
await run()
```
```
runtime: node 22.4.0 (arm64-darwin)
benchmark              avg (min … max) p75   p99    (min … top 1%)
-------------------------------------- -------------------------------
typeof                   96.02 ps/iter 101.56 ps           █           !
(71.04 ps … 52.26 ns) 111.82 ps ▁▁▁▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁
direct                   96.73 ps/iter 101.81 ps           █    ▂      !
(71.04 ps … 9.09 ns) 112.06 ps ▁▁▁▁▁▁▁▁▁▁█▁▁▁▁█▁▁▁▁▁
```
```
runtime: bun 1.1.33 (arm64-darwin)
benchmark …
```

refactor: compare with undefined directly

---

src/adapter/lambda-edge/handler.ts
src/client/client.ts
src/middleware/jsx-renderer/index.ts

refactor: remove useless spread

---

src/context.ts

I think #3592 was a very good improvement. Thanks to @EdamAme-x. In addition to it, I propose using for-of in this pull request. In the runtime environment of 2024, "for-of" will have almost the same speed as low-level "for". It's short and highly readable, so I think it should be used proactively when refactoring.
```ts
import { run, bench } from 'mitata'
const subHeaders = {
a: '1',
b: '2',
c: '3',
d: '4',
e: '5',
f: '6',
}
bench('using .entries', () => {
const headers = new Headers()
Object.entries(subHeaders).forEach(([key, value]) => headers.set(key, value))
})
bench('using for syntax', () => {
const headers = new Headers()
for (let i = 0, keys = Object.keys(subHeaders), len = keys.length; i < len; i++) {
const key = keys[i]
headers.set(key, subHeaders[key])
}
})
bench('using for-of …
```

refactor(context): use simple for-of syntax

---

src/context.test.ts
src/context.ts

feat(context): allow URL object on `c.redirect()`

---

.github/workflows/ci.yml
.github/workflows/release.yml

jsxImport bug in Bun appeared in 1.1.28, fixed in 1.1.33
- Update `oven-sh/setup-bun` to v2
- Use Bun `1.1.x`
- Update `denoland/setup-deno` to v2
- Use `jsr:@david/publish-on-tag@0.1.4`

ci: Use latest version of Bun and Deno for CI

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

Closes: https://github.com/honojs/hono/issues/3540#issuecomment-2449765586

chore(ISSUE_TEMPLATE): encourage them to add a version if possible

---

src/middleware/logger/index.test.ts
src/middleware/logger/index.ts

This PR optimizes`colorStatus` function in Logger middleware.
Performance-wise, both `if-else` version and `switch` version is the best.
I chose `switch` version which appears cleaner  to me.
I've noticed some status codes (e.g. `700`) are unreachable, so deleted.
```
// Node
> new Response("", {status:800, statusText:"aa"})
Uncaught RangeError: init["status"] must be in the range of 200 to 599, inclusive.
at initializeResponse (node:internal/deps/undici/undici:9030:15)
at new Response (node:internal/deps/undici/undici:8822:9)
```
```
// Bun
> new Response("", {status:600})
2 | new Response("", {
^
RangeError: The status provided (600) must be 101 or in the range of [200, 599]
```
```
// Deno
> new Response("", {status:800, statusText:"aa"})
Uncaught RangeError: The status provided (800) …
```

perf(middleware/logger): optimize color status

---

src/utils/mime.ts

In the previous state, we were writing the same thing twice. This PR defines it in only one place and then creates the type definition from the union of the object's values.

refactor(utils/mime): make object and type commonality

---

.github/workflows/no-response.yml

Closes: https://github.com/honojs/hono/issues/3607
The filename is from dart.  
Labels are automatically assigned after 7 days and automatically closed after two days.

chore: automatically close issues marked as “not bug” over time

---

src/utils/cookie.ts
src/utils/jwt/jwt.ts

`| 0` is faster than `Math.floor`
```llvm
cpu: AMD EPYC 7763 64-Core Processor
runtime: node 20.18.0 (x64-linux)
benchmark              avg (min … max) p75   p99    (min … top 1%)
-------------------------------------- -------------------------------
Use `| 0`                 4.47 ns/iter   4.19 ns █                    
(4.17 ns … 59.67 ns)   9.24 ns █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
Use `Math.floor`          8.45 ns/iter   6.78 ns █                    
(6.56 ns … 382.53 ns)  27.72 ns █▁▁▁▁▁▂▃▁▁▁▁▁▁▁▁▁▁▁▁▁
```
```llvm
runtime: deno 2.0.4 (x86_64-unknown-linux-gnu)
benchmark              avg (min … max) p75   p99    (min … top 1%)
-------------------------------------- -------------------------------
Use `| 0`                 1.57 ns/iter   1.40 ns ▂█                   
(1.32 ns … 138.07 ns)   3.28 ns …
```

perf(utils): use `| 0` instead of `Math.floor`

---

src/helper/cookie/index.test.ts
src/utils/cookie.test.ts
src/utils/cookie.ts

I find myself using `getCookie(c, 'name')` a lot, so I want to make it faster.
In this PR,
- `Array.reduce` is replaced with plain `for-of` loop, which is a bit faster and allows early return
- Two early returns (fast-paths) are added for the cases where `name` is specified
Overall, the optimized version is faster in all three cases
- When parse-all cookie, a bit faster (1-2%).
- When the `name` is specified and
- found in cookie, several times faster (depending on cookie length and key position, though)
- not found in cookie, a lot more faster
<details>
<summary>benchmark code</summary>
```typescript
import { bench, run } from 'mitata'
const decodeURIComponent_ = decodeURIComponent
const validCookieNameRegEx = /^[\w!#$%&'*.^`|~+-]+$/
const validCookieValueRegEx = /^[ !#-:<-[\]-~]*$/ …
```

perf(helper/cookie): fast-path for name specified

---

src/context.ts
src/hono-base.ts
src/request.ts
src/router/pattern-router/router.ts
src/router/reg-exp-router/router.ts
src/router/trie-router/node.ts

This PR reduces the bundle size using `#` for the private methods instead of the `private` keyword when the code is minified.
The result for the "Hello World" app with the `hono/tiny` preset. This is minified with `esbuild --minify` command:
```
-rw-r--r--@  1 yusuke  staff  12167 10 31 16:13 current.js
-rw-r--r--@  1 yusuke  staff  11688 10 31 16:18 next.js
```
`479 bytes` will be reduced without changing any logic and without performance degradation!
For example, you have the code:
```ts
class A {
private myPrivateMethod() {}
myPublicMethod() {
this.myPrivateMethod()
}
}
```
If you use the `private` keyword for the private method, the function name is not minifed with esbuild
```js
"use strict";class A{myPrivateMethod(){}myPublicMethod(){this.myPrivateMethod()}}
```
Instead of …

refactor: use `#` for private methods to reduce the minified file size

---

src/adapter/cloudflare-workers/websocket.test.ts
src/adapter/cloudflare-workers/websocket.ts
src/helper/websocket/index.ts

Closes: https://github.com/honojs/hono/issues/3610
Also, make the `onOpen` event, which is not available in `cloudflare-workers`, not included in the type.

fix(helper/websocket): allow custom events to be passed to generics

---

src/middleware/etag/digest.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts
src/utils/crypto.ts

Fix #3536
There are several ways to generate digests from ReadableStream, but here we have used a method that includes the previous hash value for each read, so that unique digests are generated for the same continuous data.
Even if the overall data is the same, if the number of chunks read is different, a different digest will be generated, but since it is unlikely that the same architecture (server) will have different data divisions, I think it will work effectively in practice.
It uses only the web standard `crypto.subtle`, and is characterized by its low memory load even for large-sized files.
We can write our own incremental sha1 generator in TypeScript, and using this it is possible to generate the correct sha1 for the entire data. However, I did not adopt this because an exact …

fix(middleware/etag): generate etag hash value from all chunks

---

src/utils/crypto.ts

Related: https://github.com/honojs/hono/pull/3604#discussion_r1825781670

fix(utils/crypto): fix types of crypto utility

---

.github/workflows/no-response.yml

chore: format `no-response.yml`

---

.github/workflows/ci.yml

A re-creation of #3456 in a new branch.

ci(deno): merge deno runtime coverage

---

jsr.json

Closes: https://github.com/honojs/hono/issues/3635

fix(jsr): fix missing exports

---

src/hono-base.ts

Some minifiers have smaller bundle sizes, and readability will also increase.

refactor(hono-base): use object abbreviation notation

---

runtime-tests/deno/middleware.test.tsx
src/adapter/deno/deno.d.ts
src/adapter/deno/serve-static.ts

https://github.com/honojs/hono/issues/3628
This PR addresses an issue where attempting to open an empty directory with `Deno.open` returns a `ReadableStream`, causing unexpected behavior. Specifically, it leads to a status code `200` instead of the expected 404 for directories.

fix(serveStatic): add guard to prevent reading empty folders

---

src/adapter/service-worker/index.ts

change from `Cloudflare Workers` to `Service Worker`

docs(service-worker): fix module docs for service worker adapter

---

src/hono-base.ts

1. remove unneeded process
https://github.com/honojs/hono/pull/3649/files#diff-f42b11987a9538ff250a31ba4eb66ee557f7512860fae88c5020a83b5e97c28cL136-L138
2. Inline grouping of variables that are used only once
https://github.com/honojs/hono/pull/3649/files#diff-f42b11987a9538ff250a31ba4eb66ee557f7512860fae88c5020a83b5e97c28cL492-L500

refactor(hono-base): remove unneeded processes and variables

---

src/router/trie-router/node.ts

1. The following process is not necessary and has been removed.
https://github.com/honojs/hono/pull/3647/files#diff-bf1549ba9405f87c376d2d338883f54bfeb6a91f40b28e62dd2ce5e9d4edd4e5L66-L69
2. Since it will be minified, I changed the name to be easy to understand.
Related: https://github.com/honojs/hono/pull/3596
https://github.com/honojs/hono/pull/3647/files#diff-bf1549ba9405f87c376d2d338883f54bfeb6a91f40b28e62dd2ce5e9d4edd4e5L85
3. Since only the type number is used for the key, an empty object should be created instead of `Object.create(null)`. It is faster and smaller.
Node and Bun (8x~ faster)
```llvm
runtime: node 20.18.0 (x64-linux)
benchmark              avg (min … max) p75   p99    (min … top 1%)
-------------------------------------- -------------------------------
= …
```

perf(trie-router): optimize and remove unnecessary processes

---

src/router/linear-router/router.ts
src/router/reg-exp-router/node.ts
src/router/reg-exp-router/router.ts
src/router/reg-exp-router/trie.ts
src/router/smart-router/router.ts
src/router/trie-router/node.ts
src/router/trie-router/router.ts

Related: https://github.com/honojs/hono/pull/3596
19.2kb => 18.7kb (1kb = 1024b)
0.5kb less
```llvm
gitpod@honojs-hono-3kgrjey8wtg:/workspace/hono/sandbox$ ls . -l
total 40
-rw-r--r-- 1 gitpod gitpod 18767 Nov 12 04:19 after.js
-rw-r--r-- 1 gitpod gitpod 19211 Nov 12 04:05 before.js
```

refactor(router): use `#` for private props to reduce the minified bundle size

---

src/compose.ts
src/middleware/combine/index.test.ts
src/middleware/combine/index.ts

fixes #3657
As I also refactored the relevant parts, there are a lot of changes, but the key point is that c.req.routeIndex must not be changed’ in the following line.
https://github.com/honojs/hono/compare/main...usualoma:hono:fix/conbine-every-route-index?expand=1#diff-0127ebff640ea2834e4434792875961100daac21bcdaae2d033a6a59815da3bfR98

fix(middleware/combine): prevent `c.req.routeIndex` from being changed

---

build/build.ts

Before
`Removing private fields(0/170): dist\types\types.d.ts`
After
`Removing private fields(1/170): dist\types\types.d.ts`
Progress should start at 1

chore(build): fix progress of log

---

benchmarks/query-param/package-lock.json
benchmarks/query-param/package.json
benchmarks/query-param/src/bench.mts
benchmarks/query-param/src/qs.mts

```
cpu: Apple M1 Pro
runtime: bun 1.1.33 (arm64-darwin)
benchmark            time (avg)             (min … max)       p75       p99      p995
------------------------------------------------------- -----------------------------
• {"url":"http://example.com/?page=1","key":"page"}
------------------------------------------------------- -----------------------------
hono              55.74 ns/iter   (52.33 ns … 99.93 ns)  54.98 ns  81.25 ns  84.64 ns
fastQuerystring   92.22 ns/iter  (87.42 ns … 133.98 ns)  92.13 ns 121.04 ns 133.57 ns
qs               453.64 ns/iter (427.05 ns … 534.52 ns)  489.6 ns 528.12 ns 534.52 ns
summary for {"url":"http://example.com/?page=1","key":"page"}
hono
1.65x faster than fastQuerystring
8.14x faster than qs
• …
```

chore(benchmark): add `qs` for query-param

---

.github/workflows/ci.yml
perf-measures/bundle-check/.gitignore
perf-measures/bundle-check/scripts/process-results.ts

ci: compare bundle size

---

src/hono-base.ts

With this PR, defining `errorHandler` with `private` not using `#`  in `hono-base.ts`:
```ts
private errorHandler: ErrorHandler = errorHandler
```
This will fix #3671
Since the property defined with `#` will be a completely private member that can't be accessed from outside in the JavaScript runtime phase, problem #3671 occurs. But, if you define it with `private` keyword without `#` it can be accessed from outside in the JavaScript runtime phase.

fix(base): define `errorHandler` with `private` not use `#`

---

perf-measures/bundle-check/scripts/check-bundle-size.ts

ci(perf-measures): support `KB`

---

src/router/trie-router/node.test.ts
src/router/trie-router/node.ts

Sorting was also done when number of handlers was 0 or 1, so it is no longer done.  
Also, there is no need to create a new variable.
```llvm
summary for all together
Hono RegExpRouter
1.39x faster than Memoirist
1.5x faster than koa-tree-router
1.66x faster than @medley/router
2.15x faster than rou3
2.33x faster than trek-router
2.97x faster than find-my-way
4.28x faster than Hono PatternRouter
5.43x faster than radix3
8.01x faster than koa-router
8.96x faster than Hono TrieRouter
9.13x faster than Hono BeforeTrieRouter
39.24x faster than express (WARNING: includes handling)
```
```llvm
summary for all together
Hono RegExpRouter
1.01x faster than Memoirist
1.23x faster than @medley/router
2.12x faster than koa-tree-router
2.13x faster than rou3
2.19x faster than radix3
2.33x faster than …
```

perf(router): sort handlers by score only when necessary

---

runtime-tests/deno-jsx/jsx.test.tsx
src/helper/css/common.case.test.tsx
src/helper/css/index.test.tsx
src/helper/css/index.ts
src/jsx/dom/css.test.tsx
src/jsx/dom/css.ts
src/utils/html.ts

closes #3694
This PR extends upon the work of https://github.com/honojs/hono/pull/2577 with the goal to bring the CSS nonce to the inline `style` and `script` tags created by the usage of `hono/css`. The goal is to be able to add `<Style nonce={nonce} />` in order to comply with strict CSP rules.
@usualoma could you provide me with some pointers on where to start further debugging these test failures? I see that you've implemented most code around CSP and CSS. 
```bash
FAIL  src/helper/css/index.test.tsx > CSS Helper > render css > Booleans, Null, and Undefined Are Ignored > Should render CSS styles with CSP nonce
AssertionError: expected '<script nonce="1234">document.querySe…' to be '<style id="hono-css" nonce="1234">.cs…' // Object.is equality
Expected: "<style id="hono-css" …
```

feat(css): add CSP nonce to hono/css related style and script tags

---

src/client/client.ts
src/helper/html/index.ts
src/middleware/trailing-slash/index.ts
src/router/pattern-router/router.ts
src/utils/url.ts

The size of the bundle is reduced by one ant teardrop.

refactor: use `Array.prototype.at()` to look at the end

---

src/adapter/aws-lambda/handler.test.ts
src/adapter/aws-lambda/handler.ts

---
Fix handling of multi-value query string on API Gateway v1 event.
Similar to #2782, but for API Gateway v1 event.
API Gateway v2 already handles this case because v2 event uses the raw query string directly.
https://github.com/honojs/hono/blob/190e122180dda4b51e46cbe21a301ccbec1b1f3d/src/adapter/aws-lambda/handler.ts#L285

fix(aws-lambda): Fix query string handling for v1

---

src/adapter/cloudflare-workers/serve-static.ts

Cloudflare Static Assets is now in open beta, promoted as a solution for SSR apps: https://blog.cloudflare.com/builder-day-2024-announcements/#static-asset-hosting

chore: Add Cloudflare Static Assets reference to serveStatic deprecation notice

---

src/middleware/cors/index.test.ts
src/middleware/cors/index.ts

When the `cors` middleware processes an `OPTIONS` request by default, it returns the response status text from the context, `c.res.statusText`. However, in most cases, the middleware is executed before any routes or other middlewares that could modify the response `statusText`, leading to a `Not Found` response status. To align with the explicit `204` being returned, the response should also include `No Content`, similar to how the `etag` middleware handles setting the `statusText` to `Not Modified`.

fix(middleware/cors): explicitly return No Content for the statusText when handling an OPTIONS request

---

src/middleware/ip-restriction/index.test.ts
src/utils/ipaddr.test.ts
src/utils/ipaddr.ts

fixes #3723
In all the runtimes, an IPv6-mapped IPv4 address was returned as the remote address, so I think it is appropriate to handle this by fixing `convertIPv6BinaryToString`.
```ts
import { Hono } from './src/'
import { getConnInfo } from './src/adapter/deno/conninfo' // or bun, node-server
export default new Hono().get('/', (c) => {
return c.json(getConnInfo(c))
})
```
```ts
$ deno serve --unstable-sloppy-imports --host [::] app.ts
$ bun run app.ts
```
```
% curl http://[::ffff:127.0.0.1]:8000/
{"remote":{"address":"::ffff:127.0.0.1","port":64504,"transport":"tcp"}}
% curl http://[::ffff:7f00:1]:8000/
{"remote":{"address":"::ffff:127.0.0.1","port":64519,"transport":"tcp"}}
```

fix(utils/ipaddr): support IPv6-mapped IPv4 address

---

src/router/pattern-router/router.ts

perf(pattern-router): improve performance when create null object

---

src/router/trie-router/node.ts

This optimization is based on the discussion in the following Pull Request.
Thanks to @EdamAme-x!
https://github.com/honojs/hono/pull/3732
via benchmarks/routers
```
• all together
----------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                   513 ns/iter       (490 ns … 715 ns)    524 ns    595 ns    715 ns
Hono TrieRouter(perf-trie-1208)   1'716 ns/iter   (1'652 ns … 1'895 ns)  1'723 ns  1'892 ns  1'895 ns
Hono TrieRouter(main)             2'203 ns/iter   (2'097 ns … 2'730 ns)  2'213 ns  2'709 ns  2'730 ns
summary for all together
Hono RegExpRouter
3.35x faster than Hono TrieRouter(perf-trie-1208)
4.3x faster than Hono TrieRouter(main)
```
```
• all together …
```

perf(trie-router): avoid calling spread operator for `Object.create(null)`

---

src/helper/streaming/stream.test.ts
src/helper/streaming/stream.ts

Previously, using `.pipe()` in a stream helper response would cause `console.error(undefined)` to be logged whenever the request was cancelled.
These logs did not show up in NodeJS locally, but they are visible in either Bun or in AWS CloudWatch Logs when running on AWS Lambda.
NodeJS Example:
```ts
import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { stream } from 'hono/streaming';
const originalError = console.error;
console.error = (...args) => {
originalError('ERROR', ...args);
};
export const app = new Hono()
.get('/test', c => {
return stream(
c,
s =>
s.pipe(
new ReadableStream(),
),
async (err, s) => {
console.log('error', err);
},
);
});
serve({
fetch: app.fetch,
port: 3000,
});
// Then run curl http://localhost:3000/test then press CTRL+C
```

fix(streaming) Prevent console.error(undefined) when pipe is aborted

---

jsr.json

These may have been included because they could not be linked to files on GitHub before on JSR, but now they are linked correctly like npm. Therefore, it is better to exclude them.

fix(jsr): exclude unused markdown files

---

src/context.ts
src/helper/factory/index.test.ts
src/http-exception.ts
src/middleware/bearer-auth/index.ts
src/types.test.ts
src/utils/http-status.ts
src/validator/validator.test.ts

Resolves https://github.com/honojs/hono/issues/1518
All in all, prohibits returning `c.json()` or `c.text()` or `c.html()` with 101, 204, 205, and 304 status codes.

feat(hono/context): contentful status code typing

---

src/context.ts

Fixed that my IDE threw the errors with the current code.

refactor(context): remove lint errors

---

src/context.ts
src/types.test.ts

From merging #3763, `c.json()` or `c.text()` can no longer have a contentless status code as the second argument.
In this PR, if a method such as `c.json()` has `ResponseInit` as its second argument, specifying contentless code for the status property will cause a type error.
This is the correct behavior, and I think this PR should be accepted. However, it causes minor performance degradation in TypeScript, so we need to be careful about it.

feat(context): `ResponseInit` accepts generics `StatusCode` for `status`

---

src/utils/cookie.test.ts
src/utils/cookie.ts

Hono's `setCookie` did not have `Priority` and I recently needed that option so I forked hono and added it. Nothing's serious been changed—succesfully tested locally.

feat(utils/cookie): Ability to set a priority to cookies in setCookie options

---

src/hono-base.ts
src/utils/constants.ts
src/utils/handler.ts

Fixes #3760
This PR resolves the problem described in #3760. It uses a string value for `COMPOSED_HANDLER` instead of a Symbol. We should add a test for a `fix` change, but in this PR, it's challenging to reproduce the problem in #3760, so it doesn't include a test.

fix(hono-base): don't use Symbol for `COMPOSED_HANDLER`

---

src/context.test.ts
src/context.ts
src/types.test.ts

Resolves https://github.com/honojs/hono/issues/3798

fix(context): single body overrides other returns

---

src/types.test.ts
src/types.ts

fix(types): correct `app.on(method,path[],middleware,handler)` type

---

src/helper/factory/index.ts

`createMiddleware` depends on `Hono`, so `hono/tiny` users cannot use `createMiddleware` and libraries which use `createMiddleware`. `createMiddleware` should not use `Factory`
`createMiddleware` -> `Factory` -> `Hono` (`hono/hono`)
- @hono/bun-transpiler
- @hono/cloudflare-access
- @hono/esbuild-transpiler
- @hono/oidc-auth
- @hono/prometheus
- @hono/tsyringe

fix(helper/factory): Reduce the code size of createMiddleware

---

build/build.ts
build/remove-private-fields-worker.test.ts
build/remove-private-fields-worker.ts
build/remove-private-fields.ts

`removePrivateFields` is a heavy CPU-bound process. This PR improves performance by using all CPU in WebWorker.
The following is the `removePrivateFields` time for the current build process.
Environemt:
- CPU: Intel(R) Core(TM) i7-12700F (20 Cores)
- RAM: 32GB
Current: 47750.3256ms
This PR: 10963.4007ms
The Github Actions environment is 4 CPUs, so CI may not improve performance that much. I think it will be very fast in local environment.

perf(build): Use WebWorker when removing private fields

---

src/types.ts

This PR improves the performance of type inferences by updating `types.ts`.
* Optimized `IntersectNonAnyTypes`.

perf(types): improve Utilities in `types.ts`

---

src/types.ts

`ParamKeyName` is unnecessary since it is used only in `ParamKey`. Removing it introduces decreasing in `Instantiations` for TypeScript.

perf(types): define `ParamKey` simply

---

src/helper/factory/index.test.ts
src/helper/factory/index.ts

fix(factory): correct the type of `factory.createMiddleware()`

---

src/helper/adapter/index.test.ts
src/helper/adapter/index.ts

fix(helper/adapter): `env` should set `c` type correctly

---

src/helper/streaming/sse.test.tsx
src/helper/streaming/sse.ts
src/helper/streaming/stream.test.ts
src/helper/streaming/stream.ts
src/helper/streaming/utils.ts

While investigating a memory leak, I noticed that the streams helpers in hono unconditionally attach an AbortSignal to each request. As of Bun v1.1.27, [we call `cancel` on ReadableStream](https://bun.sh/blog/bun-v1.1.27#the-cancel-method-in-readablestream) so this should be unnecessary.
I verified that on Bun v1.1.26, hardcoding the `isOldBunVersion` function to return false caused the abort-related tests to hang and that on Bun v1.2 hardcoding the `isOldBunVersion` function to return false those tests pass.
There is duplicate code but it felt less invasive to duplicate the code.

refactor(helper/streaming): Avoid attaching AbortSignal on newer versions of Bun

---

src/adapter/lambda-edge/handler.test.ts
src/adapter/lambda-edge/handler.ts

This pull request introduces support for using alternate domain names in front of a CloudFront distribution. Additionally, it enhances cookie handling by supporting the setting of multiple cookies, addressing the previous limitation where only the last cookie was set.

fix(lambda-edge-adapter): Support Alternate Domain Names and Multiple Cookies in Lambda@Edge

---

docs/CONTRIBUTING.md

`yarn.lock` has been removed by https://github.com/honojs/hono/pull/3846

docs(CONTRIBUTING): remove text about `yarn`

---

src/request.test.ts
src/request.ts

The arg of `get` in the `Headers` object is not case-insensitive. So, the `name.toLowerCase()` is unnecessary.

refactor(request): `toLowerCase()` is unnecessary for `req.header()`

---

src/helper/adapter/index.test.ts
src/helper/adapter/index.ts

Fixes https://github.com/honojs/website/pull/577

fix(helper/adapter): correct `env` type

---

src/router/common.case.test.ts
src/router/linear-router/router.test.ts
src/router/trie-router/node.ts

TrieRouter was not able to obtain parameters in the pattern of the added test, so I fixed it.
https://github.com/honojs/hono/compare/main...usualoma:fix/label-trailing-wildcard?expand=1#diff-18f50c43f41503d5cc65c9d783b57e0c683eb26957f59a11edb2d099f40114c2R502

fix(router/trie-router): fix label with trailing wildcard pattern

---

src/middleware/logger/index.test.ts
src/middleware/logger/index.ts

The default value of built-in logger is not very desirable for API servers that use query params.
e.g.) https://hono-hacker-news.deno.dev/
It's a bit disruptive for logging, so we probably won't need to add it right away.

feat(logger): include query params

---

src/helper/factory/index.test.ts
src/helper/factory/index.ts

When using factory, options such as `strict: false` cannot be specified. This Pull Request allows you to specify options when calling `createFactory` and `createApp`.
```ts
const factory = createFactory({ defaultOptions: { strict: false } });
const app = factory.createApp({ options: { strict: true } }); // Override defaultOptions
```

feat(factory): Allow HonoOptions<E> with factory

---

src/middleware/etag/digest.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts

resolve: https://github.com/honojs/hono/issues/3829
```ts
app.use(
'/etag/*',
etag({
generateDigest: (body: Uint8Array) =>
crypto.subtle.digest({
name: 'SHA-256',
},
body
),
})
)
```

feat(etag): allow for custom hashing methods to be used to etag

---

src/router/common.case.test.ts
src/router/linear-router/router.ts
src/router/reg-exp-router/router.test.ts
src/router/trie-router/node.ts
src/utils/url.test.ts
src/utils/url.ts

feat(router): support greedy matches with subsequent static components.

---

runtime-tests/deno/deno.lock

The `deno.lock` was generated if I ran `test:deno.` It's fine to add this file into the repo.

chore(runtime-tests): add `deno.lock`

---

src/helper/streaming/stream.test.ts

The problem here is that the lint results are missed due to the issues discussed in this PR.
https://github.com/honojs/hono/pull/3613

refactor(helper/streaming): remove unused variables

---

src/middleware/combine/index.test.ts
src/middleware/combine/index.ts

fix(combine): halt middleware evaluation if error in `next()`

---

src/utils/url.test.ts
src/utils/url.ts

This fixes #3909
I don't know if this is the best way of doing this, if you can find a better/faster way let me know! :)

fix(utils/url): calculate ends with slash on every iteration

---

src/utils/url.ts

I ❤️  ternary operators.
I ❤️  recursive calls.
We can pass any number of paths to `mergePath`, but in the hono core, only the pattern of passing two is used.
Looking at https://github.com/honojs/hono/issues/3909, it seems that third-party middleware sometimes uses more than three, but even so, such usage is rare.
Also, many apps do not use `mergePath`, and even when they do, they use it in the initialisation process rather than at runtime.
Therefore, the following can be considered as requirements for `mergePath` optimisation.
* The minified code should be small
* It should be particularly fast when there are two arguments
The following are the results of benchmarking using node.js, but the same trend applies to bun and deno.
<details>
<summary>bench.ts</summary>
```ts
import { run, …
```

perf(utils/url): shorten mergePath and optimize for normal use cases.

---

src/middleware/etag/digest.ts
src/middleware/etag/index.ts

This PR allows users to specify a hash generation function even in environments where there is no crypto, so the place to check for `crypto` changes.
https://github.com/honojs/hono/pull/3832

fix(etag): change where to check for `crypto`

---

src/helper/proxy/index.test.ts
src/helper/proxy/index.ts

fixes #3920
* header key is case-insensitive
* delete header if value is null or undefined

fix(proxy): fix header overwrite

---

src/helper/proxy/index.test.ts
src/helper/proxy/index.ts

This includes the original [`Request#signal`](https://developer.mozilla.org/en-US/docs/Web/API/Request/signal) in the `RequestInit` options use to create the proxy request
Currently Cloudflare doesn't expose the `abort` event to Workers, but it looks like there is work to implement it, see:
- https://github.com/cloudflare/workerd/issues/3033
- https://github.com/cloudflare/workerd/pull/3488
I'm unsure about other platforms..
fixes #3924

fix(proxy): include original request signal in proxy request

---

src/helper/proxy/index.test.ts
src/helper/proxy/index.ts

Turns out that `Request` and `Response` classes do not have enumerable properties, so using the spread operator yields an empty object 🤯 
```js
console.log({ ...new Request('http://a') }) // {}
console.log({ ...new Response(null) }) // {}
```
I haven't found where this is mentioned in the [standards documentation](https://fetch.spec.whatwg.org/) 😩 
fixes #3926

fix(helper/proxy): missing proxy response status

---

src/compose.test.ts
src/compose.ts
src/hono-base.ts
src/middleware/combine/index.ts

- ### About
Overall `compose` processing has been improved.
The biggest improvement was to minimize Context compatibility.
For some reason loose Context was allowed, but since it was a 3 year old commit and only used for testing, I decided that the current code base could be rewritten.
Although I did not actually measure it, I believe that performance increased in no small way.
- ### Others
- I improved the tests and created some additional tests.
- Rearranged the conditions of the if statement to maximize performance.
- #### Is this a breaking change?
Basically, I don't think it can be a breaking change since we can expect the complete Context to be used.
- ### The author should do the following, if applicable

refactor(compose): remove unnecessary complexity and improve testing

---

runtime-tests/deno/hono.test.ts
src/helper/websocket/index.ts
src/utils/jwt/jwt.ts

Fixes #3935
To support TypeScript 5.7, which was introduced in Deno 2.2, I've fixed some things about ArrayBuffer.

refactor: support TypeScript 5.7 for Deno 2.2

---

src/router/pattern-router/router.ts

I noticed that there is no need to declare using `let`.  
Also, one comment was incorrect and has been corrected.

refactor(pattern-router): reduce bundle size and fix comments

---

src/hono-base.ts
src/hono.test.ts

Fixes #3970
Based on #3971
As the [comment](https://github.com/honojs/hono/pull/3972#issuecomment-2698529533), the following test does not pass.
```ts
const opts = { strict: false }
const a1 = new Hono(opts)
const a2 = new Hono(opts)
a2.get('/hello', (c) => c.text('hello'))
const res = await a2.request('/hello/')
expect(res.status).toBe(200)
expect(await res.text()).toBe('hello')
```
This means `opts` passed to Hono's options will be mutated. This PR will fix it.

fix(hono-base): prevent options object mutation

---

src/utils/url.ts

Here's a small suggestion to short-circuit the `checkOptionalParameter` check without doing a regex match when we can O(1) determine it won't match.
It's a small optimization, but for the `LinearRouter` in an environment with a lot of routes it is a non-trivial improvement.
Before
```
• GET /user
LinearRouter   1'382 ns/iter     (1'208 ns … 277 µs)  1'334 ns  1'667 ns  5'333 ns
• GET /user/comments
LinearRouter   1'422 ns/iter   (1'377 ns … 1'531 ns)  1'436 ns  1'498 ns  1'531 ns
• GET /user/lookup/username/hey
LinearRouter   4'321 ns/iter   (4'205 ns … 4'551 ns)  4'381 ns  4'551 ns  4'551 ns
• GET /event/abcd1234/comments
LinearRouter   1'610 ns/iter   (1'545 ns … 1'787 ns)  1'626 ns  1'769 ns  1'787 ns
• POST /event/abcd1234/comment
LinearRouter     737 ns/iter     (692 ns … 3'858 ns) …
```

perf(utils/url): Short circuit the regex in checkOptionalParameter

---

src/adapter/bun/websocket.ts
src/middleware/secure-headers/secure-headers.ts

Updated the types that were not handled in #3939 to publish for JSR.

fix(types): fix unhandled types for Deno 2.2

---

src/adapter/bun/index.ts

fix(bun): export `BunWebSocketData` and `BunWebSocketHandler`

---

runtime-tests/lambda/index.test.ts
src/adapter/aws-lambda/handler.ts

Closes #3870
- `APIGWProxyResult` now contains `headers` or `multiValueHeaders` mutually-exclusively.
- `handle` is tweaked so the response type can be inferred from the request event type.

fix(adapter/aws-lambda): APIGWProxyResult should contain either of headers or multiValueHeaders, not both

---

src/middleware/compress/index.test.ts
src/middleware/compress/index.ts

fix #3991
As is the case when Transfer-Encoding is chunked, I think it is better not to re-encode in other cases as well, so I have made it so that if Transfer-Encoding is present, compressing is skipped.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Transfer-Encoding

fix(compress): avoid compressing if transfer-encoding is set

---

docs/CONTRIBUTING.md
runtime-tests/deno/middleware.test.tsx
runtime-tests/lambda-edge/index.test.ts
src/adapter/cloudflare-pages/handler.test.ts
src/adapter/service-worker/handler.test.ts
src/context.ts
src/helper/css/common.case.test.tsx
src/helper/css/common.ts
src/helper/html/index.test.ts
src/jsx/dom/css.ts
src/middleware/basic-auth/index.ts
src/middleware/bearer-auth/index.ts
src/middleware/body-limit/index.test.ts
src/middleware/context-storage/index.test.ts
src/middleware/context-storage/index.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts
src/middleware/request-id/index.test.ts
src/middleware/secure-headers/index.test.ts
src/utils/accept.test.ts

chore(april-fool): change `hono is cool` to `hono is hot`

---

src/middleware/trailing-slash/index.test.ts
src/middleware/trailing-slash/index.ts

closes #4048 
> [!CAUTION]
> Review should be done on a per-commit basis as test cases were refactored in 808e520b2e5e379be860295f110ea01d2bdfdc6a
> Hiding whitespace is also recommended.

fix(trailing-slash): handle HEAD request in trailing slash middleware 

---

src/helper/proxy/index.test.ts
src/helper/proxy/index.ts

fix #4021
Also mentioned here: https://github.com/honojs/hono/pull/3928#issuecomment-2662572089
The following writing method should be supported, but it was not working correctly because I overlooked the fact that `…aRawRequest` does not return a property.
```ts
proxy(aUrl, aRawRequest)
```

fix(proxy): accept a Request object as proxyInit

---

runtime-tests/deno/stream.test.ts

After updating to the latest Deno `2.2.9`, the CI stopped in the runtime test for Deno:
https://github.com/honojs/hono/actions/runs/14440296335/job/40488744441
Previously, the test was flaky because the delay before aborting the request (10ms) was too short. This change ensures we wait until the stream has actually started before sending the abort signal.
This PR should fix the CI problems.

test(deno): wait for stream to start before aborting request

---

.github/workflows/ci.yml
codecov.yml

Hey there! I work over at Sentry on the Codecov team and we've set a goal for adding some of our new features to open source repos already using Codecov. I'm a big fan of Hono, so when I saw this repo using Codecov, it seemed like a good fit :)
What is the new features?
[Bundle Analysis](https://docs.codecov.com/docs/javascript-bundle-analysis) will track your bundle size over time. This can be helpful for finding optimizations or being notified of large changes in bundle size.
Looking forward to your feedback!

ci: Add Bundle Analysis

---

src/context.test.ts
src/context.ts

Fixes #4055
This is based on https://github.com/honojs/hono/issues/4055#issuecomment-2798854609 by @usualoma. It is a "slightly overhead but simple" pattern. I think it's rare that it should catch the error with `try/catch,` so this simple implementation is better.

fix(context): don't throw the error with `c.header()` when it's finalized

---

bun.lock
package.json
runtime-tests/workerd/index.test.ts

Updated `wrangler` in `devDependencies` to `4.12.0` from `3.58.0` for the `workerd` runtime test.

chore(deps): bump wrangler to `4.12.0`

---

package.json
src/helper/websocket/index.test.ts
src/helper/websocket/index.ts

Closes #3005, and related to #3202 and #3845.
By the pull request, you would use upgradeWebSocket after `return` in handler like that:
```ts
return upgradeWebSocket(c, {
onOpen: (_e, ws) => {
ws.send('Hello World!')
}
})
})
```
A thing what I will be glad is `c.req.param` will be type-safe.
Also bindings and variables are supported.
```ts
const app = new Hono<{
Bindings: {
DB: {
insert: (v: string | Blob | ArrayBuffer) => void
}
}
}>()
app.get('/:room', (c) => {
return upgradeWebSocket(c, {
onMessage(e) {
c.env.DB.insert(e.data)
}
})
})
```

feat(ws): allow to use upgradeWebSocket in handler

---

src/helper/ssg/ssg.test.tsx
src/helper/ssg/ssg.ts

Pass the extension map through the generation methods.

fix(ssg): Fix SSG Extension Map

---

src/helper/cookie/index.test.ts
src/helper/cookie/index.ts

Deleting a cookie with `{ prefix: CookiePrefixOptions }` doesn't return the cookie value as the `prefix` isn't passed to `getCookie()`

fix(cookie): get deleted value with prefix

---

src/hono-base.ts
src/hono.test.ts
src/utils/body.test.ts

Fixes  #4138
With the current implementation, the `errorHandler` and `#notFoundHandler` are not copied in the `#clone()`. So the issue #4138 occurs. In this PR, it copies them.

fix(hono-base): copy notfound and error handlers in `#clone()`

---

benchmarks/query-param/src/bench.mts

Added the benchmark written in [the comment](https://github.com/honojs/hono/pull/3565#issuecomment-2442884990).

chore(benchmark): add `URLSearchParams` to the query-params benchmark

---

src/middleware/etag/index.test.ts
src/middleware/etag/index.ts

close: https://github.com/honojs/hono/issues/4170

fix(middleware/etag): should return 304 when weak etag is passed in  'If-None-Match'

---

src/hono-base.ts
src/hono.test.ts

fix(base): use `c.newResponse()` for the response of `err.getResponse()`

---

src/middleware/etag/digest.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts

This PR handles the environment that does not support it. I'm not sure the Lambda does not support `res.clone()`, but if so, this PR will fix #4031.

fix(etag): fallback if `res.clone()` is not supported

---

src/middleware/etag/digest.ts
src/middleware/etag/index.test.ts
src/middleware/etag/index.ts

This reverts commit 548d73f06139cb50ee974e8e7d82ef511b6fef29.

Revert "fix(etag): fallback if `res.clone()` is not supported (#4198)"

---

.devcontainer/docker-compose.yml

This pull request removes obsolete `version` field from docker-compose.yml 
Fixes #4207

chore(devcontainer): remove obsolete version field from docker-compose.yml

---

src/middleware/secure-headers/index.test.ts

chore(secure-headers): format

---

src/middleware/cache/index.test.ts
src/middleware/cache/index.ts

This pull request updates the cache middleware to avoid caching when it is defined as uncacheable in RFC 7231.
Caching will no longer occur under the following conditions.
> Responses with status codes that are defined as cacheable by default
(e.g., 200, 203, 204, 206, 300, 301, 404, 405, 410, 414, and 501 in this specification)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.1
Additionally, It introducing an optional argument to allow caching of arbitrary status codes.
```ts
// In this case, only 412 will be cached.
app.use(
'/*',
cache({
cacheName: 'foo',
wait: true,
cacheControl: 'max-age=10',
cacheableStatusCodes: [412],
})
)
```
Only GET, HEAD, POST, and PATCH will be cached, otherwise it is no longer cached.
> this specification defines GET, HEAD, and POST as
cacheable …

feat(middleware/cache): add `cacheableStatusCodes` option

---

src/middleware/jwk/index.test.ts
src/middleware/jwk/jwk.ts
src/utils/jwt/jwt.ts

Adding two main useful features people have been asking for in the [original PR](https://github.com/honojs/hono/pull/3826) + some slight changes.
- **Allow anonymous requests** by setting the new **`allow_anon`** option to `true`
- https://github.com/honojs/hono/pull/3826#issuecomment-2656576941
- **Optional callback for the `jwks_uri`** instead of only a hard-coded string
- **`Context`** is now **included in all callbacks**, so you can **e.g** pull information from `c.env` such as auth server
- https://github.com/honojs/hono/pull/3826#issuecomment-2687416251
- Callbacks now can be either **async or sync**
**Example:**
```ts
app.use(
'/auth/*',
jwk({
jwks_uri: (c) => `https://${c.env.authServer}/.well-known/jwks.json`,
allow_anon: true
})
)
```
**Note 1**: This PR allows having a single …

feat(hono/jwk): Extended with `allow_anon` option & passing `Context` to callbacks

---

src/helper/testing/index.test.ts
src/helper/testing/index.ts

This PR makes it possible to pass hc options to testClient. This excludes the `fetch` option, which is always passed by the testClient; removing it obviates the need for testClient entirely.
I needed this because I wanted my testClient to always pass certain headers for authentication in dev mode.

feat(hono/testing): Allow passing hc options to testClient

---

src/middleware/cors/index.test.ts
src/middleware/cors/index.ts

In my usecase, it is needed to set different `Access-Control-Allow-Methods` by origins.
Then, I modified `hono/cors` for 'allowedMethods' to accept `function` like `origins`.
How do you think?
`GET` or `HEAD` can be performed from any origins, but others only from specific origin.
```typescript
app.use(
'/api7/*',
cors({
origin: (origin) => (origin === 'http://example.com' ? origin : '*'),
allowMethods: (origin) =>
origin === 'http://example.com'
? ['GET', 'HEAD', 'POST', 'PATCH', 'DELETE']
: ['GET', 'HEAD'],
})
)
```

feat(cors): allowedMethods by function

---

src/utils/body.test.ts
src/utils/body.ts

fix(utils/body): normalize key names in parseBody (#4108)

---

src/utils/url.test.ts
src/utils/url.ts

https://github.com/orgs/honojs/discussions/4145
`http+unix` is often used on the client side (e.g., curl), but it is very rarely used on the server side. However, in Deno, when you specify `path` in `Deno.serve`, a string like `http+unix://%2Ftmp%2Fsocket%2Esock/your/path` is passed to the URL of the Request object.
In Deno, it is set with the following code.
https://github.com/denoland/deno/blob/94683caba1d7247ba914107b521efa54b61580b1/runtime/ops/http.rs#L100
`bun` and `node-server` do not use it.
I compared using the following benchmark script, and `url.charCodeAt(9) === 58 ? 13 : 8` seems to offer the best performance. Compared to the current situation, the performance is reduced by only a few tens of ps. However, since this is not a frequently used feature, it seems wasteful to incur …

feat: support http+unix scheme

---

src/middleware/jwt/index.test.ts
src/middleware/jwt/jwt.ts

Add a custom header location to the JWT middleware. 
Follows from https://github.com/honojs/hono/issues/3572.
---
I wasn't sure how much would be too much, so I stuck to the current changes for now.
But we could also explore other alternatives:
```typescript
export const jwt = (options: {
secret: SignatureKey
cookie?:
| string
| { key: string; secret?: string | BufferSource; prefixOptions?: CookiePrefixOptions }
alg?: SignatureAlgorithm
header?: string | (() => string | Promise<string>)  // allows more flexibility
```
We can take a function to let the user decide how to get the token. That might play well with the `bearerAuth` middleware as well.
```typescript
export const jwt = (options: {
secret: SignatureKey
cookie?:
| string
| { key: string; secret?: string | BufferSource; …
```

feat(jwt): Add custom header location

---

src/utils/url.test.ts
src/utils/url.ts

Fixes #3952
The code is based on https://github.com/honojs/hono/issues/3952#issuecomment-2745203982

fix(req): don't throw if the query param is invalid

---

src/router/trie-router/node.ts

I and AI improved TrieRouter's performance. The file size is reduced, and performance is not changed or is improved slightly.
Bundle Size:
- Before: 19,059 characters
- After: 18,989 characters
- Improvement: -70 characters (-0.37%)
TrieRouter Performance (average time):
| Test Case              | Before   | After    | Improvement |
|------------------------|----------|----------|-------------|
| short static           | 237 ns   | 240 ns   | -1.3%       |
| static with same radix | 284 ns   | 282 ns   | +0.7%       |
| dynamic route          | 789 ns   | 792 ns   | -0.4%       |
| mixed static dynamic   | 774 ns   | 783 ns   | -1.2%       |
| post                   | 745 ns   | 751 ns   | -0.8%       |
| long static            | 832 ns   | 860 ns   | -3.4%       |
| wildcard …

perf(trie-router): improve performance and reduce file size

---

src/middleware/bearer-auth/index.ts

docs(bearer-auth): fix typo

---

src/utils/color.test.ts
src/utils/color.ts

fixes #4232, #4233
Popular bundlers(`esbuild`, `webpack`) check packages and provide optimizations, but `cloudflare:workers` is often not supported by default. In this PR, to avoid these optimization checks, change a package name to a variable name.
This PR adds a test to check whether these issues can be avoided in `esbuild`. We should also add `webpack` tests, but I didn't have a smart way. `webpack` has been checked to work with at least [this repository](https://github.com/ryuapp/check-color-next).

fix(utils/color): avoid unhandled scheme errors

---

package.json
runtime-tests/bun/color.test.ts
src/utils/color.ts

follow up https://github.com/honojs/hono/issues/4233#issuecomment-2990039940
[Bun.build](https://bun.sh/docs/bundler) is smarter than other bundlers and when minifying it will try to resolve a package name, which will result in an error.
~~This PR will switch `cloudflare:workers` variable name declaration from `const` to `let` declaration to prevent the problem.~~
This PR use `async/await` to work around a bug in opennext temporary: https://github.com/honojs/hono/issues/4233#issuecomment-2992430971 Proper opennext support will be prepared later.

fix(utils/color): avoid resolving pacakages via Bun.build

---

src/jsx/base.ts
src/jsx/index.test.tsx

fixes #4235
We should throw an `Error` instance instead of a string.

fix(jsx): throw new Error instead of string

---

src/jsx/base.ts
src/jsx/index.test.tsx

According to the [React document](https://react.dev/reference/react-dom/components/common#ref-callback), `ref` should accept the function and it properly implemented. However, the validation in `toStringBuffer()` is not reflect that and causes false positive error. This PR fixes that.
1. I don't have time to implement tests for now, Feel free to add or just close my PR and create the independent fix.
2. Also, I don't checked other validations issues, maybe there is more

fix(jsx): Fix the JSXNode validation. Allow the function type for props.ref

---

src/jsx/base.test.tsx
src/jsx/base.ts

When I use Hono JSX with [html-react-parser](https://github.com/remarkablemark/html-react-parser/blob/a71f4dc78b8a0aed88bb692704d480a46ac83cde/src/dom-to-react.ts#L53), I realized `cloneElement` didn't copy children.
I wrote fix and tests.
I only changed `jsx` (server side) implementation and  haven't checked `jsx/dom`. That might also have the issue.

fix(jsx): cloneElement didn't copy children

---

src/client/client.test.ts
src/client/client.ts

fix(client): remove `index` string when calling `$url()`

---

src/utils/url.test.ts
src/utils/url.ts

Fixes https://github.com/honojs/hono/pull/4297#issuecomment-3117351523

fix(utils/url): prevent double encoding in `safeEncodeURI`

---

src/adapter/service-worker/types.ts

This PR updates the `FetchEvent.handled` type in `adapter/service-worker`  to be in line with [typescript's webworker types](https://github.com/microsoft/TypeScript/blob/be8678315541e814da14316848a9468e8f90ab11/src/lib/webworker.generated.d.ts#L4119).

refactor(types): bring adapter/service-worker types up to date

---

src/utils/cookie.test.ts
src/utils/cookie.ts

---
This PR adds support for lowercase priority values in cookies, similar to how sameSite is handled, to improve compatibility with other libraries.
Currently, a conflict occurs when used alongside libraries that depend on [jshttp/cookie](https://github.com/jshttp/cookie).
For example, using Hono with `next` or `@supabase/ssr` may result in type errors due to differing expectations for the casing of priority values.
---

fix(cookie): support lowercase priority for compatibility with other libraries

---

src/context.ts

fix(types): should populate `output` type for `c.body()`

---

src/adapter/service-worker/handler.test.ts
src/adapter/service-worker/handler.ts

fix(service-worker): pass `FetchEvent` as second argument to `app.fetch`

---

.github/workflows/ci.yml

The version of bun currently used in CI (v1.1.39) isn't compatible with the `lockfileVersion` in `bun.lock`
https://github.com/honojs/hono/blob/bd454fe8a6c494050fc48f7a3eb61af3d49f91b4/bun.lock#L2
This causes an error in CI, but `bun install` continues anyway by ignoring the lock file and generating a new one. This defeats the purpose of a lock file 🙈 
https://github.com/honojs/hono/actions/runs/16609360703/job/46988990584#step:4:6
I've updated to use the current version of bun

chore(ci): upgrade bun version to 1.2.19

---

src/router/common.case.test.ts
src/router/linear-router/router.test.ts
src/router/reg-exp-router/node.ts
src/router/reg-exp-router/router.test.ts
src/router/trie-router/node.ts

I investigated to fix #4325, and I found bugs in the routers.
If the registered path is `/files/:name{.*}`, the behaviors of some routers are incorrect.
Fixes #4325

fix(router): support `/files/:name{.*}`

---

src/adapter/aws-lambda/handler.test.ts
src/adapter/aws-lambda/handler.ts
src/adapter/aws-lambda/index.ts

- add `contentTypesAsBinary` to spefify which content-type should be treated as binary (will be base64 encoded)
```typescript
// content-type: application/vnd.mapbox-vector-tile will be base64-encoded and response as binary.
handle(app, { contentTypesAsBinary: ['application/vnd.mapbox-vector-tile'] })
```
Current implementation treats some pre-defined content-types as "should be base64-encoded".
However, sometimes we need to treat some types other than them as binary (e.g. `'application/vnd.mapbox-vector-tile` https://github.com/mapbox/vector-tile-spec ).
What do yo think?

feat(aws-lambda): specify content-type as binary

---

src/helper/cookie/index.test.ts
src/helper/cookie/index.ts

Closes https://github.com/honojs/hono/issues/4281
I will write docs if this idea gets accepted.

feat(cookie): generateCookie and generateSignedCookie helpers

---

src/client/fetch-result-please.ts
src/client/utils.test.ts

This PR simply set the `.name` for the `DetailedError` class, which is a good pratice, so user is able to do a fast equality check in code / search for the error in log.
I forgot to add it previously and just hit a case where I need it because I have `DetailedError` classes coming from multiple source and `instanceof` is a bit wonky.
I also added tests for cases where error is thrown.
Theoretically "breaking", but should be safe to include in next patch.

feat(parseResponse): set `DetailedError.name` (+ error tests)

---

src/client/types.ts
src/client/utils.test.ts
src/client/utils.ts

Continuing from #4346, because I did a lot of updates and I can't push to the existing PR so I created a new one, I added more test cases and use another approach that is cleaner and fixes all problems.
In summary: 
* The PR adds a new type util: `FilterClientResponseByStatusCode`, which is used by `parseResponse` to exclude error responses.  
* More test cases are also added to make sure `parseResponse` is correct in use cases where a route will also return error responses.
* Some minor adjustments are also done in this PR, like:
* Use `c.text` instead of `c.notFound` for correct `TypedResponse` infer and test
* Add `.buffer` chain for `/rawBuffer` return, this fixes a minor type issue in newest node version.
---

fix(parseResponse): should not include error responses in result

---

src/client/client.test.ts
src/client/utils.test.ts
src/client/utils.ts

Fixes https://github.com/honojs/hono/pull/4267#issuecomment-3182884803

fix(client): handle query parameters in `removeIndexString`

---

src/helper/proxy/index.test.ts
src/helper/proxy/index.ts

Resolves #4351
This PR will add the option parameter `customFetch` to allow the user to override the global `fetch` in Proxy helper.
Usage:
```ts
app.get('/', () =>
proxy(`https://example.com/`, {
customFetch,
})
)
```

feat(proxy): add `customFetch` option to allow custom fetch function

---

src/adapter/aws-lambda/handler.test.ts
src/adapter/aws-lambda/handler.ts

Fixes #4358
API Gateway provides decoded query parameters to Lambda, but `c.req.url` should preserve the original percent-encoded format. This change ensures query parameters are properly re-encoded when constructing the URL.
Also refactored the test code.

fix(aws-lambda): preserve percent-encoded values in query strings

---

src/middleware/cors/index.test.ts
src/middleware/cors/index.ts

This PR updates the CORS middleware to support asynchronous functions for the `origin` and `allowMethods` options.
This allows for dynamic, asynchronous logic (e.g., database lookups) when determining CORS headers.
```ts
app.use(
'/api/*',
cors({
origin: async (origin) => {
// e.g. check an allow-list in a database
const isAllowed = await db.isOriginAllowed(origin)
return isAllowed ? origin : 'https://fallback.example.com'
},
})
)
```
This change is backward-compatible.

feat(cors): Allow async functions for `origin` and `allowMethods`

---

src/middleware/cors/index.ts

Forgot about that in [this PR](https://github.com/honojs/hono/pull/4373)
Updates the `origin` function's return type. The `Promise` can now resolve to `undefined` or `null`, aligning it with the synchronous return type.

feat(cors): Correct origin function return type asynchronously returning null or undefined for origin

---

src/middleware/language/index.test.ts
src/middleware/language/language.ts

Use the source URL from the request to detect language from path. Because `c.req.path` will be updated by the `getPath` method.
```javascript
const languages = ['en', 'es', 'ru']
const app = new Hono({
getPath: (req) => {
const url = new URL(req.url)
let pathname = url.pathname
for (let idx = 0; idx < languages.length; idx++) {
if (pathname.startsWith('/' + languages[idx] + '/')) {
pathname = pathname.replaceAll('/' + languages[idx] + '/', '/')
break
}
}
return pathname
}
})
```
Detect language from the path:
```javascript
app.use(languageDetector({
debug: true,
order: ['querystring', 'path', 'cookie', 'header'],
lookupFromPathIndex: 0, // /en/profile → index 0 = 'en'
convertDetectedLanguage: (lang) => lang.split('-')[0],
supportedLanguages: languages, // Must include fallback …
```

fix(language-detector): Detect language from path after getPath changed

---

src/adapter/service-worker/index.ts

This PR adds generic parameters to `fire()` in `hono/service-worker` to accept generic variants.
```typescript
import { Hono } from 'hono/quick'
import { fire } from 'hono/service-worker'
type Env = {
Variables: {
// ...
},
}
const app = new Hono<Env>()
// ...
fire(app)
```
Without this fix, the above code gives this TypeScript error:
```
% npx tsc --noEmit
src/index.ts:69:6 - error TS2345: Argument of type 'Hono<Env, BlankSchema, "/">' is not assignable to parameter of type 'Hono<BlankEnv, BlankSchema, "/">'.
The types of 'get(...).get' are incompatible between these types.
Type 'HandlerInterface<Env, "get", { [x: string]: { $get: { input: any; output: {}; outputFormat: string; status: StatusCode; }; }; }, "/">' is not assignable to type 'HandlerInterface<{}, "get", { [x: string]: { …
```

fix(service-worker): Update service-worker fire() to accept generic variants of Hono app instance

---

src/adapter/aws-lambda/handler.test.ts
src/adapter/aws-lambda/handler.ts

fix(aws-lambda): sanitize non-ASCII header values to prevent ByteString errors

---

src/utils/types.test.ts
src/utils/types.ts

After 4.9.8, the error checking in the `JSONParsed` utility function, short circuits any checking for the `toJSON` function. The error checking was moved to the unknown case. This fixes cases where an invalid type like `bigint` has a global override to `toJSON`.
e.g.
```typescript
declare global {
interface BigInt {
toJSON(): string;
}
}
// expected
type should_be_string = JSONParsed<bigint>;
```

fix(types): fix 4.9.8 regression
