honojs/hono

src/hono.ts, test/hono.test.ts
fixed #25
You can write `app.get('/foo', ()=>{}).post(() => {})`
=> Chained route without route method

example/basic/index.js, src/hono.ts, src/middleware.ts, src/middleware/body-parse/body-parse.test.ts, src/middleware/body-parse/body-parse.ts
Hi @yusukebe , not sure it's good idea or not if *Hono* provides a built-in `body-parse` middleware to handle the `json`, `xml` and `form` payload for `POST` method.  
This is just a simple PR to explain what it maybe like,  which is not ready for review, just for a better discussion.
=> feat(body-parse): a body parse middleware

README.md, example/basic/index.js, example/blog/src/controller.ts, example/compute-at-edge/index.js, example/jsx-ssr/src/index.js, src/context.ts, src/hono.ts, src/middleware/default.ts, src/middleware/logger/logger.test.ts, test/context.test.ts, test/hono.test.ts
Add new shortcuts for Requests:
```js
c.req.header('Header-Name')
c.req.param('q') // instead of c.req.params
```
Add new shortcuts for Response:
```js
c.header('Header-Name', 'Header-Value')
c.status(201)
c.statusText('This status text')
return c.text('This is Body text')
/*
new Response('This is Body text', {
status: 201,
statusText: 'This status text',
headers: { 'Header-Name': 'Header-Value', 'Content-Type': 'plain/text' },
})
*/
```
=> feat: Add new shortcuts for request/response

src/compose.ts, src/middleware/basic-auth/basic-auth.ts, src/middleware/mustache/README.md, src/middleware/mustache/mustache.ts
Installing `buffer` and `crypto` packages enables basic auth, if `buffer` of `crypto` is not in pollyfills such as webpack 5 environment.
Close #82
=> fix: basic auth

examples/compute-at-edge/index.js, examples/compute-at-edge/package.json, examples/compute-at-edge/webpack.config.js, package.json, src/middleware/basic-auth/basic-auth.ts, src/utils/buffer.test.ts, src/utils/buffer.ts
Basic auth support Fastly Compute@Edge with polyfills.
Webpack example:
```js
const path = require('path')
module.exports = {
entry: './index.js',
target: ['webworker'],
output: {
filename: 'index.js',
path: path.resolve(__dirname, 'bin'),
libraryTarget: 'this',
},
resolve: {
fallback: {
buffer: require.resolve('buffer/'),
crypto: require.resolve('crypto-browserify'),
stream: require.resolve('stream-browserify'),
process: require.resolve('process/browser'),
},
}
}
```
=> feat: Basic-auth with polyfill

src/context.ts, src/hono.ts
Hi,
Thank you for publishing such a good product.
This PR adds the ability to complete the type of `c.req.param`.
I think this is a nice feature, but it also makes type definitions more complex, so I think it is reasonable to decide not to adopt it.
We can get support from the editor for the type of c.req.param. Also, if there is no possibility of a value being returned from c.req.param, the parameter type will be set to `never` and cannot be specified.
https://user-images.githubusercontent.com/30598/153787066-92e7f97b-32e9-4387-add5-166b2cf302c9.mov
The simplicity of the type display will be lost.
The following image is before the PR was applied. For those who are not used to reading conditional type specifications, this may be easier to read.
=> Added type to c.req.param key.

README.md, examples/basic/index.js, src/hono.ts, src/utils/url.test.ts, src/utils/url.ts, test/hono.test.ts
`app.route` is changed:
**Chained route** is obsolete:
```
app.route('/')
.get((c) => c.text('get /'))
// ^^^ Not working now!!
```
Now, `app.route` enables **nested route**:
```
const book = app.route('/book')
book.get('/', (c) => c.text('List books')) // => GET /book
book.get('/:id', (c) => {
return c.text('Get Book: ' + c.req.param('id'))) // => GET /book/:id
})
```
=> feat: nested route

benchmarks/handle-event/index.js, src/hono.ts, src/node.ts, src/router.ts, src/router/reg-exp-router/index.ts, src/router/reg-exp-router/node.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts, src/router/reg-exp-router/trie.ts, test/router.test.ts
Hi,
I tried to improve the performance of the router using a different strategy.
All the routes into one RegExp object.
* /help
* /:user_id/followees
* /:user_id/followers
* /:user_id/posts
* /:user_id/posts/:post_id
* /:user_id/posts/:post_id/likes
into `^/(?:help$()|([^/]+)/(?:followe(?:es$()|rs$())|posts(?:/([^/]+)(?:/likes$()|$())|$())))`
It will be a large regular expression, but since common prefixes can be grouped together by trie, I think it will grow slowly in the general case.
Also, the return value of `match` will be larger in proportion to the number of routes, but it will be an array where most of the elements are `undefined`, so I think it is still an acceptable size in the general case.
The following Perl modules use large regular expression objects for high performance.
* …
=> Introduce RegExpRouter

src/router/reg-exp-router/node.ts, src/router/reg-exp-router/router.ts, src/router/reg-exp-router/trie.ts
In this PR, I will add a very small optimization to RegExpRouter.
It turns out that iterating through the results of Object.keys is little bit expensive, so I change ParamMap to a list of keys and values (a.k.a Association List).
https://gist.github.com/usualoma/6d22fdb1b64e7ae8f4d6fe2d204b9208
I don't think this optimization will make any visible difference to the router benchmarks.
I also tried optimize by using lastIndexOf() instead of indexOf(), but failed. Because lastIndexOf() is slow.
https://blog.taaas.jp/tips/v8lastindexof/
=> Make ParamMap Array<[key, value]>.

README.md, examples/basic/index.js, src/compose.ts, src/hono.test.ts, src/hono.ts
`app.notFound` and `app.onError` are changed:
```js
// Custom Not Found Response
app.notFound((c) => c.text('404', 404))
// Handle Error and return custom Error Response
app.onError((err, c) => {
console.error(`${err}`)
return c.text('500', 500)
})
```
=> feat: `app.notFound()` and `app.onError()`

README.md, docs/README.ja.md, src/context.test.ts, src/context.ts, src/hono.test.ts, src/hono.ts
Add `request` method. It's useful for testing.
```js
test('GET /hello is ok', async () => {
const res = await app.request('http://localhost/hello')
expect(res.status).toBe(200)
})
```
=> feat: add `request` method

src/router/reg-exp-router/node.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts
Hi,
I tried to optimize RegExpRouter.
I think most middleware is applied to paths like '\*' or '/path/to/\*' that take no parameters.
In that case, parameter handling is not needed, so `match` can be optimized as follows.
https://github.com/yusukebe/hono/compare/master...usualoma:optimize-reg-exp-router?expand=1#diff-06f981941f95eecd6e249629fd9d5d4badaf8dfbe96ade6219e67691359df679R35-R38
And by optimizing the '\*' commonly used in middleware separately as described above, we can make it simpler for normal routing as well.
https://github.com/yusukebe/hono/compare/master...usualoma:optimize-reg-exp-router?expand=1#diff-06f981941f95eecd6e249629fd9d5d4badaf8dfbe96ade6219e67691359df679R43
Since TrieRouter and RegExpRouter are already fast enough, the ranking may not be stable due to minute …
=> Optimize RegExpRouter

src/utils/crypto.test.ts, src/utils/crypto.ts
=> fix: `encodeBase64/decodeBase64` throw Error if the argument is null

src/context.test.ts, src/context.ts, src/middleware/logger/index.test.ts, src/middleware/logger/index.ts, src/middleware/serve-static/index.test.ts
Calculating Content-Length makes returning a response slowly. But Wrangler, Miniflare, or Cloudflare calculate Content-Length and add to a header automatically. So, we do not have to do it by ourselves.
Close #179
=> feat: [BREAKING] `Content-Length` is not added automatically

src/context.test.ts, src/context.ts, src/hono.test.ts, src/hono.ts, src/utils/encode.test.ts
Enable adding types for Env variables using generics in Module Worker mode.
```ts
interface Env {
API_KEY: string
API_SECRET: string
MY_KV: KVNamespace
}
const app = new Hono<Env>()
const key = c.env.API_KEY
const secret = c.env.API_SECRET
const message = getMessage({ key, secret })
return c.text(`Hono! ${message}`)
})
export default app
```
=> feat: enable adding types for Env variables

src/compose.test.ts, src/compose.ts
This PR is to make compose function to do composition for both ordinary middlewares and response middlewares, then we can make #189 a little more easier.
=> feat(compose): compose both the ordinary middlewares and response middlewares

src/hono.test.ts, src/hono.ts, src/index.ts, src/router.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts, src/router/trie-router/node.ts, src/utils/body.ts
I have made middleware as `Handler`. So, **every handler is a `Handler`**. We can use middleware with app.**HTTP_METHOD**.
```ts
app.all('*', logger())
app.post('/posts', bodyParse(), basicAuth(), (c) => {
const body = c.req.parsedBody
const post = createPost(body)
return c.text(`${post.id} is created!`, 201)
})
```
Also chained routes are available.
```ts
app.get('/posts', (c) => {
return c.text('POST LIST')
}).post(bodyParse(), basicAuth(), (c) => {
//...
})
```
=> feat: make everything(including Middleware) as `Handler`

src/hono.test.ts, src/hono.ts, src/index.ts
Using `Route` object with `app.route` method, we can make the large structured applications more easily.
For example:
```ts
// route.ts
import { Route } from 'hono'
import { cors } from 'hono/cors'
import { poweredBy } from 'hono/powered-by'
export const route = new Route()
route
.get('/', (c) => c.text('List posts'))
.post(cors(), poweredBy(), (c) => {
return c.text('Create post')
})
.get('/:id{[0-9]+}', (c) => {
const id = c.req.param('id')
return c.text(`Your id is ${id}`)
})
```
```ts
// index.ts
import { route } from './route'
app.route('/v1', route)
app.fire()
```
Related #200 
Close #201
=> feat: `app.route(path, Route)`

src/hono.test.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts
There were bugs in `trie-router`. I got the error with this code. Fixed it in this PR.
```ts
app.get('/:id/:action', async (c, next) => {
const id = c.req.param('id')
console.log(`Middleware  A: id is ${id}`)
await next()
})
app.get('/posts/:id', (c) => {
const id = c.req.param('id')
return c.text(`Route B: id is ${id}`)
})
```
=> fix(router): fix `trie-router` bugs

README.md
Wrangler 2 is no longer in beta (https://github.com/cloudflare/wrangler2/releases/tag/wrangler%402.0.0) and can now be used directly as just `npx wrangler`.
=> docs: update readme wrangler2 no longer in beta

src/context.ts, src/hono.test.ts, src/hono.ts, src/middleware/cookie/index.test.ts, src/middleware/cookie/index.ts
If no arguments are specified, returns an object containing all parameters.
This is just an idea, but what about being able to write the following.
```typescript
app.get('/posts/:id', (c) => {
const { id } = c.req.param()
const { q, lang } = c.req.query()
const {
'Content-Type': contentType,
'X-Custom': custom,
} = c.req.header()
}))
```
=> Tweaks return values of functions for request parameters.

src/hono.test.ts, src/hono.ts, src/index.ts
`Route` will be ***obsolete***! in this PR.
For grouping routes, use `Hono` instead.
```ts
// const api = new Route() <--- obsolete
const api = new Hono()
api.get('/posts', (c) => c.text('list'))
api.post('/posts', (c) => c.text('create'))
app.route('/v1', api)
```
Close #236
=> feat: [BREAKING] deprecate `Route`, use `Hono` instead

src/context.test.ts, src/context.ts
=> fix(Context): `c.body()` accept null for 204 response

src/middleware/jwt/index.ts
The current JWT middleware checks the token only after the request has run (because `await next()` is run first). I think this means that whatever code is in your handler is called, _even if_ the JWT token is invalid or expired. 
This PR changes the behaviour to bail out of the request if the token validation fails.
=> fix(jwt): ensure the request does not continue if the jwt token is invalid or expired

src/utils/url.test.ts, src/utils/url.ts
Made it faster!
```
hono - org x 708,830 ops/sec ±3.48% (83 runs sampled)
hono - trie-router(default) x 800,532 ops/sec ±4.11% (65 runs sampled)
```
=> perf(util): cache regex result for URL path(s)

benchmarks/handle-event/index.js, benchmarks/handle-event/package.json, benchmarks/handle-event/yarn.lock, src/hono.ts
In this #282 , I've brought up the issue about the benchmark. Both benchmark scores seem to be not correct. So, I tried to *polyfill* `Request` and `Response` objects by `node-fetch`. Then, scores are changed. *minimal handler* has become faster and *hono - regexp-router* is a second faster than *sunder*.
```
minimal handler x 790,920 ops/sec ±4.97% (78 runs sampled)
hono - trie-router(default) x 332,451 ops/sec ±2.66% (88 runs sampled)
hono - regexp-router x 370,257 ops/sec ±2.94% (83 runs sampled)
itty-router x 206,874 ops/sec ±3.60% (86 runs sampled)
sunder x 290,147 ops/sec ±4.99% (84 runs sampled)
worktop x 165,212 ops/sec ±4.87% (77 runs sampled)
Fastest is minimal handler
✨  Done in 45.34s.
```
It's good news for Hono. Sure Sunder is fast, but I inspected it by performance tools, …
=> chore(benchmark): polyfill `Request` and `Response`

.github/workflows/ci.yml, package.json, yarn.lock
This PR is to close https://github.com/honojs/hono/issues/214 by upgrading to latest release of miniflare https://github.com/cloudflare/miniflare/releases/tag/v2.5.0
=> fix(test): upgrade the miniflare to consume the fix on node18

src/middleware/jwt/index.test.ts, src/middleware/jwt/index.ts
This PR is correct the status code for no or invalid authorization data provided,   thanks @sdarnell 's reminder.
=> fix(status): make the status 401 for the invalid authorization info

src/utils/crypto.test.ts, src/utils/crypto.ts
Export an additional `md5` function in the crypto utility.
Useful when working with R2 and providing a MD5 hash for verification.
```
import { md5 } from "hono/utils/crypto";
...
const md5Digest = md5(body);
const object = await bucket.put(key, body, {md5: md5Digest});
```
It is worth noting, however, that "MD5 is not part of the WebCrypto standard but is supported in Cloudflare Workers for interacting with legacy systems that require MD5." <sup>[1]</sup>
[1]: https://developers.cloudflare.com/workers/runtime-apis/web-crypto/
=> Export `md5` function in src/utils/crypto.ts

src/utils/html.ts
* Replace all in one `replace()` call.
* We do not need to escape "'".
=> perf(utils/html): Improve performance `escape()`

src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts
This PR provide a memo that can be used in much the same way as React.memo.
I think the React.memo is "do not recalculate the Virtual DOM unless there are changes in the props".
There is no Virtual DOM in hono's jsx engine, but I think we can give a meaning to memo that says "return a calculated EscapedString if there are no changes in props".
This can be used to avoid recalculating the following JSX on every render
https://github.com/yusukebe/iekei/blob/nano-jsx/src/components/footer.tsx
=> feat(middleware/jsx): Introduce memo.

README.md, package.json, src/context.ts, src/middleware/jsx/README.md, src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts, src/middleware/mustache/Context.ts, src/middleware/mustache/mustache.ts, src/utils/html.test.ts, src/utils/html.ts, tsconfig.json
=> feat: jsx middleware

src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts, tsconfig.json
I think we also need Fragment.
Although `key` is not used in hono, it would be useful to be able to bring the template with React as is, so this was added for compatibility.
> key is the only attribute that can be passed to Fragment. 
https://reactjs.org/docs/fragments.html#keyed-fragments
=> feat(middleware/jsx): We need Fragment.

src/middleware/jsx/index.ts, src/utils/html.test.ts, src/utils/html.ts
This PR is a small addition but one that I believe has great potential.
What we will be able to do is explained below.
There is a precedent for a library that handles HTML template literals with a tag named "html", and I refer to this as an idea.
* https://github.com/lit/lit/tree/main/packages/lit-html
* https://github.com/developit/htm
Thanks to these libraries, VisualStudioCode and vim also interprets template literals as HTML, allowing syntax highlighting and formatting to be applied.
* https://marketplace.visualstudio.com/items?itemName=bierner.lit-html
* https://github.com/MaxMEllon/vim-jsx-pretty
```typescript
app.get('/:username', (c) => {
const { username } = c.req.param()
return c.html(
html`<!DOCTYPE html>
<h1>Hello! ${username}!</h1>`
)
})
```
```typescript
const snippet = …
```
=> feat: Introduce html template literals tag.

src/utils/html.test.ts, src/utils/html.ts
Fixes #314
Although `raw` could be used in the following locations, I did not apply it to these locations to avoid the overhead of function calls, since they are very frequently executed.
https://github.com/honojs/hono/blob/master/src/middleware/jsx/index.ts#L75-L76
=> feat(utils/html): Introduce a function `raw`.

src/middleware/jsx/README.md, src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts, tsconfig.json
This PR includes BREAKING CHANGES.
* `h` is obsolete, removed. Use `jsx` instead.
* Don't write `app.use('*', jsx())`. It's not needed.
* If you want to return HTML, use `c.html()`
You can write as a below:
```tsx
import { jsx } from 'hono/jsx'
return c.html(
'<!doctype html>' +
(
<html>
<body>
<p>Hono!</p>
</body>
</html>
)
)
})
app.fire()
```
Close #313
=> [BREAKING] refactor(jsx): `h` to `jsx`, remove `h`

src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts
=> refactor(reg-exp-router): Routes are returned in the registration order.

src/router/trie-router/node.test.ts, src/router/trie-router/node.ts
=> refactor(trie-router): routes are returned in the registration order

README.md, src/context.ts, src/hono.ts
When using Module syntax, there is no FetchEvent, only ExecutionContext (FetchEvent implements ExecutionContext's functions as well, `waitUntil` and `passThroughUntilException`).
This PR adds `c.executionCtx`, which is set on both Service Worker syntax and Module syntax. `c.event` is only used on Service Worker syntax.
=> feat(context): add executionCtx to Context

src/compose.test.ts, src/context.ts, src/hono.ts, src/middleware/body-parse/index.test.ts, src/middleware/body-parse/index.ts, src/middleware/cookie/index.ts, src/request.ts
Instead of extending `Request`, I created `HonoRequest`. APIs such as `c.req.param()` are not changed.
Close #213
=> refactor: make `HonoRequest`

README.md, deno_dist/README.md, deno_dist/hono.ts, src/hono.ts
On Deno, you can write like below:
```ts
import { serve } from 'https://deno.land/std/http/server.ts'
import { Hono } from 'https://deno.land/x/hono/mod.ts'
// ...
serve(app.fetch) // <---
```
=> refactor: use arrow func for `app.fetch`

package.json, src/middleware/compress/index.test.ts, src/middleware/compress/index.ts, yarn.lock
`compress` middleware solves the performance related to the transferring speed on the internet.
This pull request depends on the `CompressStream` [^1]. It might not work on the Bun because Safari cannot use no such a class. However, we can run it on Node and Deno. Please consider to employ this middleware in your project. Cheers.
[^1]: https://developer.mozilla.org/en-US/docs/Web/API/CompressionStream/CompressionStream
=> Add compress middleware

bun_test/index.test.ts, src/middleware/jwt/index.ts, src/utils/jwt/jwt.ts
`jwt` middleware is not supported on Bun, yet.
Close #381
=> refactor(bun): throw error when using `jwt` middleware

deno_dist/utils/jwt/jwt.ts, deno_dist/utils/jwt/types.ts, src/utils/jwt/jwt.test.ts, src/utils/jwt/jwt.ts, src/utils/jwt/types.ts
Noticed a small typo in error class name.
Exported original name for backward-compat.
Let me know what you think.
I'll update usages of the class everywhere else in the code if you are accepting this PR.
=> chore: fix typo in error class name

src/middleware/serve-static/module.mts
I had a problem using the `{path: "..."}` option with the serve-static middleware when using cloudflare module workers. This should hopefully fix it.
=> Pass path to serve-static middleware when using cloudflare module workers

deno_dist/router/trie-router/node.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts, src/router/trie-router/router.test.ts
It should work:
```ts
app.get('/book/a', (c) => {
return c.text(c.req.param('slug') || 'no-slug')
})
app.get('/book/:slug', (c) => {
return c.text(c.req.param('slug') || 'no-slug-at-slug-endpoint')
})
```
```
$ curl http://localhost:8787/book/a
no-slug
$ curl http://localhost:8787/book/foo
foo
```
Close #418
=> fix(trie-router): fix the rule for capturing named parameters

bun_test/index.test.tsx, deno_dist/middleware/jsx/index.test.tsx, deno_dist/middleware/jsx/index.ts, deno_dist/middleware/jsx/jsx-dev-runtime.ts, deno_dist/middleware/jsx/jsx-runtime.ts, package.json, src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts, src/middleware/jsx/jsx-dev-runtime.ts, src/middleware/jsx/jsx-runtime.ts
Support `jsxImportSource`.
You can use this option on Bun and Deno (Wrangler does not support it).
if you write tsconfig as below, JSX middleware will be enabled without `import { jsx } from 'hono/jsx'`.
```json
{
"compilerOptions": {
"jsx": "react-jsx",
"jsxFragmentFactory": "Fragment",
"jsxImportSource": "hono/jsx"
}
}
```
=> feat(jsx): support `jsxImportSource`

bun_test/index.test.tsx, deno_dist/middleware/jsx/jsx-dev-runtime.ts, src/middleware/jsx/jsx-dev-runtime.ts
For JSX middleware on Bun.
Fix bug that JSX `children` will force escaped.
=> fix(jsx/bun): do not escape children

src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts
Fixes #427:
- `checked` and `selected` will not be rendered when set to false
- `checked="checked"` and `selected="selected"` will be rendered when no value set or set to `true`
=> fix(jsx): Fix for JSX checked and selected props

src/context.ts, src/hono.ts
Allows the user to type the value of `ctx.set('variable', var)` or `ctx.get('variable')`.
This is one of the ideas to solve the #414 problem, but even if this were not used to solve #414, I think this would still be a useful feature.
=> feat(context): Introduce ContextVariableMap.

src/utils/body.test.ts, src/utils/body.ts
If incomming request content-header is `application/json`, but the body is nothing, it was throwing 500 internal server error. It's better to return bank object `{}` if this situation.
Fix #428
=> fix(`parseBody`): return blank object when JSON body is nothing

benchmarks/jsx/index.tsx, src/middleware/html/index.ts, src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts, src/middleware/jsx/jsx-dev-runtime.ts, src/utils/html.test.ts, src/utils/html.ts
This PR fixes #439.
There are no changes to the external specification in this PR, and we can continue to stringify templates with `(<p>text</p>).toString()`. However, there are some changes in the internal structure.
Previously, upon calling `jsx`, basic stringification was completed and an `HtmlEscapedString` object was returned, but with this PR, a data-wrapped `JSXNode` is returned upon calling `jsx`. The stringification is done at `toString()` call.
With this PR, `escape` defined in utils/html is no longer used inside the hono repository. (Only `escapeToBuffer` is used.)
The `escape` function is fast enough and convenient for hono users to use in their applications, but depending on policy, it could be removed as unnecessary.
```
Hono x 173,197 ops/sec ±2.16% (93 runs sampled)
React …
```
=> perf(jsx): JSX performance improvement

src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts
I think it is better to support all boolean attirbutes listed in the table below.
https://html.spec.whatwg.org/#attributes-3
And, supporting all of them will not affect performance.
=> refactor(jsx): Support all the boolean attributes.

deno_dist/middleware/html/index.ts, deno_dist/middleware/jsx/index.test.tsx, deno_dist/middleware/jsx/index.ts, deno_dist/middleware/jsx/jsx-dev-runtime.ts, deno_dist/middleware/jwt/index.ts, deno_dist/request.ts, deno_dist/utils/body.ts, deno_dist/utils/html.ts, src/middleware/html/index.ts, src/middleware/jsx/index.ts, src/utils/html.test.ts, src/utils/html.ts
Ranamed `Buffer` to `StringBuffer` in `utils/html`.
Fixed namespace conflicts. denoify force polyfill the type named `Buffer` for [Buffer](https://nodejs.org/api/buffer.html) module.
=> refactor(`utils/html`): rename `Buffer` to `StringBuffer`

deno_dist/utils/crypto.ts, src/middleware/etag/index.test.ts, src/utils/crypto.test.ts, src/utils/crypto.ts
If an object type was passed as a parameter, the values would all be the same.
I've fixed it by making the object a different value by JSON.stringiy.
If the output values from the "object" and the "string" value are the same, the hash value will be the same. This is a specification.
Fix #451
=> fix(`utils/crypto`): stringify the parameter which is object in `createHash`

deno_dist/utils/body.ts, deno_dist/utils/crypto.ts, src/middleware/etag/index.test.ts, src/utils/body.ts, src/utils/crypto.test.ts, src/utils/crypto.ts
JSON object and Binary such ArrayBuffer or Uint8Array are not cryptos correctly.
In this PR, make a crypto hash according to the type of parameters.
Fix #451
=> fix(utils/crypto): make Binary and JSON object crypto correct

deno_dist/context.ts, src/context.test.ts, src/context.ts, src/hono.test.ts
Header values in Context may sometimes be "shifting" This PR does:
* Handle header values as lowercase.
* Fix the order of setting headers.
=> fix(context): fix header values shifting

deno_dist/context.ts, src/context.ts
`ContextVariableMap` was not available on the built code for the npm library. We have to write the lines in this PR.
=> fix(context): fixed `ContextVariableMap` is not enabled in built code

README.md, deno_dist/README.md, deno_dist/router/trie-router/node.ts, src/router/trie-router/node.ts
I did some minor tweaking of the TrieRouter and made it 9-10% faster.
```
hono - trie-router(default) x 434,571 ops/sec ±4.82% (81 runs sampled)
hono - [Optimized] trie-router(default) x 465,051 ops/sec ±3.45% (87 runs sampled)
hono - regexp-router x 528,354 ops/sec ±4.34% (84 runs sampled)
itty-router x 201,821 ops/sec ±4.02% (88 runs sampled)
sunder x 320,189 ops/sec ±2.17% (88 runs sampled)
worktop x 191,326 ops/sec ±2.88% (83 runs sampled)
Fastest is hono - regexp-router
✨  Done in 44.36s.
```
=> perf(trie-router): fine tuning, 9~10% faster

deno_dist/mod.ts, src/index.ts, src/mod.ts
`ContextVariableMap` is not working in the npm package because it's not exported from 'dist/hono/index`. In this PR, I've made that export correctly.
=> fix(context): export `ContextVariableMap` correctly

deno_dist/context.ts, deno_dist/hono.ts, src/context.ts, src/hono.ts
This PR is for enabling adding Types for variables used in `c.set` and `c.get`. Related to #472 
`c.set()` and `c.get()` are useful to store variables for middleware and handlers. For example, you can set the "client" object in middleware and use it later in a handler. But, these key-value do not have Types.
In this PR, Types will be available for `c.set` and `c.get` by passing the Types as generics into Hono class.
Before this PR, the generics is used for "bindings" on Cloudflare Workers.
```ts
KV: KVNamespace
Storage: R2Bucket
}
const app = new Hono<Bindings>()
```
After this PR, the generics will be used for "bindings" and "variables":
```ts
KV: KVNamespace
Storage: R2Bucket
}
type WebClient = {
user: string
pass: string
}
type Variables = {
client: …
```
=> feat(types): enable adding Types for variables used in `c.set`/`c.get`

deno_dist/request.ts, deno_dist/utils/body.ts, src/hono.test.ts, src/request.ts, src/utils/body.ts
Fix #479 #341 
In this PR, we can pass the Generics to `c.req.parseBody()`. If we do not it, type will be `any`.
```ts
const body = await c.req.parseBody() // body is any
type Post = { message: string }
const postBody = await c.req.parseBody<Post>() // postBody is Post
```
=> fix: enable passing Generics to c.req.parseBody, default is any

deno_dist/request.ts, deno_dist/utils/body.ts, src/hono.test.ts, src/request.ts, src/utils/body.test.ts, src/utils/body.ts
Make that `c.req.parseBody` parses only FormData and does not parse JSON, text, and arrayBuffer. This fix includes breaking changes.
Before this PR, this function returns the parsed body according to Content-Type, despite the type of body. And, it will be `any`:
```ts
parseBody<T = any>(r: Request | Response): Promise<T>
```
Even though the user was expecting a `Record<string, string>`, this may return `Object`. This behavior could potentially cause a security vulnerability. See #484 
In this PR, `c.req.parseBody` only parse `FormData`. If the user wants to parse others than FormData, then the user should explicitly use `json()`, `text()`, and `arrayBuffer()`.
```ts
const data = c.req.json()
```
`parseBody` will only return `Record<string, string | File>`.
```ts
parseBody(r: Request | …
```
=> [BREAKING] fix: make that `c.req.parseBody` parses only `FormData`

src/hono.ts
Hi, Thank you for publishing such a good product!
This PR improve type of app.HTTP_METHOD.
If the return type of the handler function is wrong, as in the example below, an error is reported for "path".
This is not ideal. Because it should be the handler function that should report the error like below.
=> fix app.HTTP_METHOD type

deno_dist/context.ts, deno_dist/deno/serve-static.ts, deno_dist/hono.ts, deno_dist/middleware/serve-static/serve-static.ts, src/context.ts, src/deno/serve-static.ts, src/hono.test.ts, src/hono.ts, src/middleware/serve-static/serve-static.ts
By this PR #493 , the logger is called twice if it's not found. And the first log shows "200". The following case:
```ts
app.use('*', logger())
app.get('/', (c) => c.text('Hono!!'))
```
```
GET /not-found
```
This problem is caused by two reasons.
1. It did not return 404 response immediately If the response is undefined. 
2. Default `c.res` is 200 response. It should be 404 response.
This PR fixed this problem.
This is the issue pointed out in the comments of this PR.
https://github.com/honojs/hono/pull/493#issuecomment-1234769263
=> fix: fixed the issue logger called twice

deno_dist/compose.ts, deno_dist/hono.ts, src/compose.test.ts, src/compose.ts, src/hono.ts
* Reduced use of `await`
* Reduced use of `context instanceof HonoContext`
* I think this code did not limit the type of `context` for abstraction, but since it will always be `HonoContext` in production environment, we have limited the type of `context` so that we do not have to compare.
There are many changes to the test code, but no changes to Hono's API.
These are the results in my environment.
#493 reflects the results of optimization.
```
hono - trie-router(default) x 220,343 ops/sec ±5.68% (83 runs sampled)
hono - regexp-router x 261,953 ops/sec ±5.37% (82 runs sampled)
itty-router x 82,331 ops/sec ±3.38% (85 runs sampled)
sunder x 114,834 ops/sec ±2.25% (83 runs sampled)
worktop x 66,525 ops/sec ±3.41% (87 runs sampled)
Fastest is hono - regexp-router
```
Apply the following …
=> perf(compose): Remove `await composed()` from hono.ts.

deno_dist/compose.ts, src/compose.ts
This PR will improve the poor performance noted in the following comment.
https://github.com/honojs/hono/pull/495#issuecomment-1236125012
This branch is the fastest in my environment.
```
% bombardier -c 200 -d 20s http://127.0.0.1:3000/with-middleware
Bombarding http://127.0.0.1:3000/with-middleware for 20s using 200 connection(s)
[==========================================================================================] 20s
Done!
Statistics        Avg      Stdev        Max
Reqs/sec     28673.49    2688.43   35743.89
Latency        6.97ms   306.34us    24.17ms
HTTP codes:
1xx - 0, 2xx - 573631, 3xx - 0, 4xx - 0, 5xx - 0
others - 0
Throughput:     4.87MB/s
```
```
% bombardier -c 200 -d 20s http://127.0.0.1:3000/with-middleware
Bombarding http://127.0.0.1:3000/with-middleware for 20s …
```
=> perf(compose): Always return a Promise without async.

deno_dist/request.ts, deno_dist/utils/url.ts, src/request.ts, src/utils/url.test.ts, src/utils/url.ts
I've improved `c.req.query` performance. Currently, `c.req.query` uses `new URL` for parsing query parameters strings. It is inefficient. In this PR, `c.req.query` uses just `URLSearchParams`, it becomes to be faster.
Scripts:
```ts
import { run, bench } from 'mitata'
import { getQueryStringFromURL } from '../../src/utils/url'
const urlString = 'http://localhost?foo=bar&foo2=bar2&foo3=bar3'
{
bench('URL', () => {
const url = new URL(urlString)
url.searchParams.get('foo')
})
}
{
bench('getQueryStringFromURL + URLSearchParams', () => {
const queryStirng = getQueryStringFromURL(urlString)
const searchParams = new URLSearchParams(queryStirng)
searchParams.get('foo')
})
}
await run()
```
Results:
```plain
MacBook@yusuke $ bun run ./url-params.ts
cpu: Apple M1 Pro
runtime: bun 0.1.11 …
```
=> perf(req): improve `c.req.query` performance

deno_dist/hono.ts, deno_dist/router.ts, deno_dist/router/reg-exp-router/router.ts, deno_dist/router/smart-router/index.ts, deno_dist/router/smart-router/router.ts, deno_dist/router/static-router/index.ts, deno_dist/router/static-router/router.ts, src/hono.test.ts, src/hono.ts, src/router.ts, src/router/reg-exp-router/router.ts, src/router/smart-router/index.ts, src/router/smart-router/router.test.ts, src/router/smart-router/router.ts, src/router/static-router/index.ts, src/router/static-router/router.test.ts, src/router/static-router/router.ts
I think it would be difficult for users to take advantage of the "hono has two routers and the optional RegExpRouter is faster."
This PR changes this to "By default, the best router is selected based on the routing of the application."
StaticRouter is a new alternative. Works fast when there is no path to receive parameters.
I think that this is not a router for benchmarking purposes, and that it could be used in the real world as follows
```ts
app.use('*', logger(), cors())
app.use(
'/graphql',
graphqlServer({
schema,
rootResolver,
})
)
```
However, when benchmarked, there did not appear to be a significant difference with RegExpRouter in nodejs.
If it is a bun, there may be a little difference, but there may not be.
I think this StaticRouter is a good example of the use of SmartRouter, …
=> Introduce StaticRouter and SmartRouter

README.md
The Discord invite url in the readme.md is invalid.
valid invite url: https://discord.gg/KMh2eNSdxV
invalid invite url in the readme.md: https://discord.gg/KVYKWmfD
I found the valid url from the comment [here](https://github.com/honojs/hono/issues/483#issuecomment-1227848565).
https://github.com/honojs/hono/issues/483#issuecomment-1227848565
=> docs(readme): update discord invite url

package.json, tsconfig.build.cjs.json, tsconfig.build.json, tsconfig.json
Currently, only CommonJS has been distributed, but this PR will also support ES Modules.
This will reduce the bundle size when using Hono with the `import` keyword. The following is the result of bundling using Wrangler.
Before:
```
MacBook@yusuke $ wrangler dev src/worker.ts
⛅️ wrangler 2.1.3
-------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
⬣ Listening at http://0.0.0.0:8787
Total Upload: 43.88 KiB / gzip: 9.06 KiB
```
This PR:
```
MacBook@yusuke $ wrangler dev src/worker.ts
⛅️ wrangler 2.1.3
-------------------
Retrieving cached values for userId from node_modules/.cache/wrangler
⬣ Listening at http://0.0.0.0:8787
Total Upload: 30.23 KiB / gzip: 7.44 KiB
```
=> feat: support ES modules!!

deno_dist/README.md, deno_dist/middleware/cors/index.ts, deno_dist/middleware/validator/validator.ts, deno_dist/utils/url.ts, src/middleware/cors/index.test.ts, src/middleware/cors/index.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts, src/utils/url.test.ts, src/utils/url.ts
In this RP, it allows multiple origins on CORS middleware.
```ts
app.use(
'*',
cors({
origin: ['https://example.com', 'https://example.org'],
//...
})
)
```
This middleware responds with the correct origin based on the `Referer` header. Falling back to origin[0] if it is empty or none.
Close #503
=> feat(cors): allow multiple origins

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/middleware/validator/index.ts, deno_dist/middleware/validator/middleware.ts, deno_dist/middleware/validator/rule.ts, deno_dist/middleware/validator/sanitizer.ts, deno_dist/middleware/validator/validator.ts, deno_dist/request.ts, deno_dist/utils/encode.ts, deno_dist/utils/json.ts, src/context.ts, src/hono.ts, src/middleware/validator/index.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/middleware/validator/rule.test.ts, src/middleware/validator/rule.ts, src/middleware/validator/sanitizer.test.ts, src/middleware/validator/sanitizer.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts, src/request.ts, src/utils/json.test.ts, src/utils/json.ts
I like the current validator middleware API:
```ts
app.post(
'/json',
validation((v) => ({
json: {
'post.author.name': v.isAlpha,
},
})),
(c) => {
return c.text('Valid')
}
)
```
But there are times when I want "Types":
```ts
async (c) => {
const data = await c.req.json()
// How can I access `post.author.name` ?
return c.text('Valid')
}
```
So I implemented the new idea of Validator Middleware that support "Types". This is the approach of "declaring the keys of properties first".
```ts
app.post(
'/posts',
validator((v) => ({
id: v.json('post.id').asNumber().isRequired(),
title: v.json('post.title').isRequired().isLength(400),
body: v.json('post.body').isOptional(),
})),
(c) => {
const data = c.req.valid()
return c.text(`ID is ${data.id}, Title is ${data.title}`)
}
)
```
Wow, we got …
=> feat: another idea of Validator Middleware

deno_dist/context.ts, deno_dist/utils/encode.ts, src/context.test.ts, src/context.ts, src/hono.test.ts
This PR enables appending values into the header with `c.header` function and makes it easier to set multiple values.
```ts
c.header('x-custom', 'foo')
c.header('x-custom', 'bar', { append: true })
```
And this PR proposes setting multiple cookies.
```ts
c.cookie('delicious_cookie', 'macha')
c.cookie('delicious_cookie', 'choco')
```
Close #534 #536
=> feat: support appending values with `c.header`

deno_dist/context.ts, deno_dist/hono.ts, src/context.ts, src/hono.ts
This PR fixes the problem when installing Hono on Bun.
Fix #548
=> fix: don't use `defaultNotFoundMessage` variable

deno_dist/hono.ts, deno_dist/utils/encode.ts, src/hono.ts
Remove `async` from `dispatch` function in `hono.ts`. A single handler that does not use `async` will be about 16% faster on Bun:
v2.2.1:
```
Reqs/sec    158951.18   43864.54  202188.36
Latency        1.26ms     1.39ms    41.26ms
HTTP codes:
1xx - 0, 2xx - 1589211, 3xx - 0, 4xx - 0, 5xx - 0
others - 0
Throughput:    21.67MB/s
```
This PR:
```
Reqs/sec    188225.08   24307.40  218436.45
Latency        1.06ms   109.58us    12.83ms
HTTP codes:
1xx - 0, 2xx - 1880915, 3xx - 0, 4xx - 0, 5xx - 0
others - 0
Throughput:    25.65MB/s
```
This benchmark using: https://github.com/SaltyAom/bun-http-framework-benchmark
=> perf: remove `async` from dispatch; will be 16% faster

.vscode/settings.json, deno_dist/middleware/validator/middleware.ts, deno_dist/middleware/validator/validator.ts, deno_dist/utils/encode.ts, deno_dist/utils/json.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts, src/utils/json.test.ts, src/utils/json.ts
This PR adds support for JSON array paths in the JSONPath util, and also support for validating JSON array paths from a validator context.
The update doesn't break backwards compatibility with the current API (besides the previous less standard `.i` syntax, eg. `posts.4` instead of `posts[4]`) and provides the ability to validate arbitrary array paths, including complex paths of nested arrays and objects.
For example this:
```ts
const jsonBody = {
posts: [
{
title: 'New Post 1',
tags: ['new-ish', false],
},
{
title: 'New Post 2',
tags: ['newest', true],
},
],
}
```
Can have arbitrary validations like this:
```ts
validator((v) => ({
title: v.json('posts[*].title').isRequired(),
secondTag: v.json('posts[*].tags[1]').asBoolean().isRequired(),
}))
```
One thing I would like to do in the …
=> feat(validator): add support for JSON array path validation

src/middleware/serve-static/bun.ts
It does not check `c.res` so that `c.res` would not be initialized.
This PR related to #510
=> refactor(bun/serve-static): don't check `c.res`

deno_dist/middleware.ts, src/middleware.ts, src/utils/jwt/jwt.test.ts
We should export the Cache middleware for the Deno distribution so that we can use it in Deno 1.26+ now that it is available.
=> fix(cache): export cache middleware for Deno

deno_dist/compose.ts, deno_dist/context.ts, deno_dist/hono.ts, src/compose.test.ts, src/compose.ts, src/context.ts, src/hono.test.ts, src/hono.ts
**This PR has a small breaking change**
Currently, if an error occurred in the Handler, it would immediately throw an Error. Therefore, the Middleware process after `await next()` will not be executed. When handling errors in Middleware, it was necessary to wrap them in try-catch.
```ts
app.use('*', async (c, next) => {
try {
await next()
} catch (_) {
//...
}
})
```
This works well for Sentry Middleware, but has a bad effect on Logger Middleware and CORS. This is mentioned #575 
This way of error handling was introduced in #491.
However, referring above, it is not so good, so in this PR, reverting back to the way and makinging it possible to handle Error objects in the Middleware.
If the Handler throws an error, there is no need to try-catch in the Middleware, and the error resopnse is …
=> fix(compose): don't throw Error; set error response into `c.res`

deno_dist/middleware/validator/middleware.ts, deno_dist/middleware/validator/validator.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts
This PR should close #562. The Validator middleware will now return a HTTP 400 Bad Request response whenever JSON in the request body fails to parse, or if the body is empty.
=> fix(validator): return HTTP 400 on malformed JSON request

deno_dist/compose.ts, src/compose.ts, src/hono.test.ts
The following PR did not support `async`.
https://github.com/honojs/hono/pull/576
This PR will support `async`. Will fix https://github.com/honojs/hono/issues/575
=> fix(compose): fix for error handling with `async`

src/middleware/compress/index.ts
Response constructor's 2nd argument does not require a cloned response as all it does is read these fields and does not modify anything:
- status
- statusText
- headers
> https://fetch.spec.whatwg.org/#initialize-a-response
=> perf: remove unrequired cloning of ctx.res

src/utils/object.ts
This seems to fix the issue with missing fields on objects in the CI runner. Also immutable merges are probably safer.
=> fix(object): make merge immutable to fix issues with missing fields

deno_dist/middleware/validator/middleware.ts, deno_dist/middleware/validator/validator.ts, deno_dist/utils/encode.ts, deno_dist/utils/json.ts, deno_dist/utils/object.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts, src/utils/json.test.ts, src/utils/json.ts, src/utils/object.test.ts, src/utils/object.ts
This PR introduces "nested validation" for Validator Middleware.
In this PR, we can validate nested JSON structured data using `v.array()` and `v.object()` functions. After much thought and consideration, the result is this API.
For example, there is a nested object like below:
```ts
const data = {
posts: [
{
id: 123,
title: 'JavaScript',
tags: ['Workers', 'Deno', 'Bun'],
},
],
pager: {
prev: true,
next: false,
},
}
```
It will be validated with `v.array()` and `v.object()`:
```ts
app.post(
'/posts',
validator((v) => ({
posts: v.array('posts', (v) => ({
id: v.json('id').asNumber().isRequired(),
title: v.json('title'),
tags: v.json('tags').asArray(),
})),
pager: v.object('pager', (v) => ({
prev: v.json('prev').asBoolean(),
next: v.json('next').asBoolean(),
})),
})),
(c) => {
return …
```
=> feat(validator): introduce nested validation

deno_dist/middleware/validator/middleware.ts, deno_dist/middleware/validator/validator.ts, deno_dist/utils/json.ts, deno_dist/utils/object.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/middleware/validator/validator.test.ts, src/middleware/validator/validator.ts, src/utils/json.ts
In this PR, the validator will have multiple result objects, so it will have an error message per rule.
For example, one error message will become more friendly.
```
'Invalid Value: the request body "title" is invalid - abcdefg'
```
will be:
```
'Invalid Value [abcdef]: the request body "title" is invalid - isLength'
```
Internally, it has error objects as follows:
```json
[
{
"isValid": true,
"target": "body",
"key": "title",
"value": "abcdefg",
"ruleName": "should be \"string\"",
"ruleType": "type"
},
{
"isValid": false,
"message": "Invalid Value [abcdefg]: the request body \"title\" is invalid - isLength",
"target": "body",
"key": "title",
"value": "abcdefg",
"ruleName": "isLength",
"ruleType": "value"
}
]
```
If you want to do more complex error handling, you can refer to this result …
=> feat(validator): has the error message per rule

src/middleware/basic-auth/index.test.ts, src/middleware/basic-auth/index.ts, src/middleware/bearer-auth/index.test.ts, src/middleware/bearer-auth/index.ts
This is a huge security concern. Imagine securing a nuclear launch handler with it :scream: 
I would suggest yanking all previous versions with this middleware
=> fix(bearer-auth, basic-auth): handler should not be executed when unauthorized

deno_dist/middleware/validator/middleware.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts
Fixed the bug returning an empty body if the results don't have "value" errors.
=> fix(validator): show "type" error messages if does not have "value" errors

deno_dist/mod.ts, src/index.ts, src/mod.ts
You can write your schema definition outside the middleware handler as follows:
```ts
import type { Validator } from 'hono'
import { validator } from 'hono/validator
const schema = (v: Validator) => ({
query: v.query('query').isRequired(),
page: v.query('page').isNumeric().isOptional(),
})
app.get('/search', validator(schema), (c) => {
const { query, page } = c.req.valid()
//...
return c.text('Result!!')
})
```
`Validator` and `validator` are similar and confusing, but if you don't like it, just use an alias.
This will fix #624
=> feat(validator): export `Validator` from 'hono'

package.cjs.json
The "type" in package.cjs.json was set to "target".
The bug did not occur because the default "type" in package.json is "commonjs".
I have not checked another property but it may have been overridden by default.
This package.cjs.json also worked
```
{}
```
=> fix(typo) package.cjs.json target to type

deno_dist/middleware/validator/middleware.ts, deno_dist/validator/validator.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/validator/validator.ts
Currently, with Validator middleware, if the JSON body is empty, it will return "Malformed JSON in request body" response error immediately. This behavior is good but it's not possible to handle in the validator middleware `done` method. This is mentioned in #561.
To handle "Malformed JSON in request body" error we have to write another middleware to get an error object. It's very verbose. So, in this PR, I made it we can handle "Malformed JSON in request body" in validator middleware.
If we have handler like below:
```ts
app.post(
'/posts',
validator(
(v) => ({
title: v.json('title'),
}),
{
done: (results, c) => {
return c.json(results, 400)
},
}
),
(c) => {
message: 'Valid!',
})
}
)
```
Then, post the empty body to the endpoint, the result response will be this:
```json …
```
=> fix(validator): enable handling "Bad Request" in validator

deno_dist/middleware/jsx/jsx-dev-runtime.ts, deno_dist/middleware/jsx/jsx-runtime.ts, src/middleware/jsx/jsx-dev-runtime.ts, src/middleware/jsx/jsx-runtime.ts
`Fragment` is not exported from `jsx-runtime`. Fixed it.
=> fix(jsx): export fragment

bun_test/index.test.tsx, deno_dist/context.ts, deno_test/hono.test.ts, src/context.test.ts, src/context.ts
As mentioned in #413, it might be useful to have way to know on which platform the code is running. This PR introduces `c.runtime`, which is getter of `Context` interface.
```ts
const global = globalThis as any
if (global?.process?.title === 'node') {
return 'node'
}
if (global?.Deno !== undefined) {
return 'deno'
}
if (global?.Bun !== undefined) {
return 'bun' 
}
```
This is straightforward. 
For `Deno`, `global?.process?.title === 'deno'` is possible,  but I just used shorter one.
```ts
if (typeof global?.WebSocketPair === 'function') {
return 'cloudflare'
}
return 'fastly'
```
[WebSocketPair](https://developers.cloudflare.com/workers/runtime-apis/websockets/) is Cloudflare Worker's runtime API. I picked this because this is only available in CF. (For example, …
=> feat(context): Introducing c.runtime

bun_test/index.test.tsx, deno_dist/compose.ts, deno_dist/context.ts, deno_dist/hono.ts, deno_dist/types.ts, deno_test/hono.test.ts, src/compose.test.ts, src/compose.ts, src/context.test.ts, src/context.ts, src/hono.ts, src/types.ts, src/validator/validator.test.ts
This PR is about refactoring. Remove `HonoContext`; use instead of `Context` as a class. Polish `ErrorHandler` and `NotFoundHandler` types.
=> refactor(types): reduce type definitions

deno_dist/context.ts, src/context.test.ts, src/context.ts
In my environment the test in `context.test.ts` fails:
I don't know why it is be passed on the CI, but I think we have to fix the test and `contex.ts`.
Actually, the test environment with `miniflare` is not only "node" but also "cloudflare". There are both `global.process.title` and `global.WebSocketPair` in my environment.
In this case, we have to check first whether it is `cloudflare` or not and check it later for `node`.
=> fix(context): check cloudflare before checking node in `c.runtime`

deno_dist/hono.ts, deno_dist/utils/encode.ts, src/hono.test.ts, src/hono.ts
=> fix(error): make `notFound()` enables to catch errors correctly

deno_dist/hono.ts, src/hono.test.ts, src/hono.ts
This PR includes a new feature `app.showRoutes()`.
Sometimes it is difficult to see what routes are registered. I've created this feature to prevent us from losing time on that. Using `app.showRoutes`, will show the routes that are registered:
=> feat(app): introduce `app.showRoutes()`

deno_dist/router/reg-exp-router/router.ts, deno_dist/router/static-router/router.ts, src/router/reg-exp-router/router.ts, src/router/static-router/router.ts
* Since the first argument of `Router<T>#add` is expected to be uppercase, and existing code will not work correctly if lowercase is passed, I thought `toUpperCase` was unnecessary.
* In StaticRouter, when adding a new method, the middleware in METHOD_ALL must be copied.
=> Refactoring of feat/on branche

deno_dist/hono.ts, deno_dist/router/reg-exp-router/router.ts, deno_dist/router/static-router/router.ts, src/hono.test.ts, src/hono.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts, src/router/smart-router/router.test.ts, src/router/static-router/router.test.ts, src/router/static-router/router.ts, src/router/trie-router/router.test.ts
This PR introduces `app.on()`.
Currently, the HTTP methods we can use are specified in the code:
https://github.com/honojs/hono/blob/fadce526736a610248ec5175ca66ddcc5a84c883/src/router.ts#L3
The `app.on()` function will enable we set the custom HTTP method as we like:
```ts
app.on('PURGE', '/foo', async (c) => {
await purgeCache('foo')
return c.redirect('/')
})
```
=> feat(app): introduce `app.on(method, path, handler)`

jest.config.js, package.json
hono did not work with ESM project.
Added type field to package.json.
```
import { Hono } from "hono";
^^^^
SyntaxError: Named export 'Hono' not found. The requested module 'hono' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'hono';
const { Hono } = pkg;
```
=> fix(package.json): add "type": "module"

src/validator/validator.test.ts, src/validator/validator.ts
fix the bug of `v.json()` calls made after a `v.array()` to be mistakenly considered as still being inside the array
fixes one of the issues mentioned in #677
____
This is the result of the test I've added before applying the change:
(the rest of the checks passed already, but I've included them for completeness and to cover all cases for `v.json()` :slightly_smiling_face: )
=> fix(validator): fix jsons validation after arrays

deno_dist/validator/validator.ts, src/validator/validator.test.ts, src/validator/validator.ts
fix the bug of having subsequent objects inside a nested structure causing the validator to forget the previous keys in the scheme's path
fixes point 1 of #677
=> fix(validator): fix subsequent nested objects names

deno_dist/router/reg-exp-router/router.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts
Hi @yusukebe !
I don't think #684 is the cause of this problem, as #688 reproduces in v2.5.6 as well.
However, the cause is in a similar area and it is my fault for not noticing this problem when fixing #684.
In the current RegExpRouter architecture, handlers added with METHOD_NAME_ALL are copied to each method, so I believe that copying all existing handlers the first time they (new method) are added will correct the problem, including #681.
=> fix(reg-exp-router): Copy from METHOD_NAME_ALL for new methods

deno_dist/middleware/cors/index.ts, src/middleware/cors/index.ts
Do not call `next` for OPTIONS pre-flight requests to avoid side effects and more sensible defaults.
=> Updated CORS

jest.config.js
- This PR removes unnecessary jest config `testPathIgnorePatterns: ['./examples']`.
The config was introduced when `examples` directory was created.
https://github.com/honojs/hono/commit/511c0ebd7e63706d748a2950e016c1e542c8103c
I guess we can remove it since `examples` directory has been removed.
https://github.com/honojs/hono/commit/13373f0836cf4976e28e1ed7afab26b452da8de7
=> chore: remove unnecessary config testPathIgnorePatterns

deno_dist/router/trie-router/node.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts, src/router/trie-router/router.test.ts
Fixed the bug, we could not capture the named path parameter following the pattern. When accessing `GET /hello/world`, the `console.log()` may show `undefined`:
```ts
app.get('/hello/:foo', async (c, next) => {
const foo = c.req.param('foo')
console.log(foo)
await next()
})
app.get('/hello/world', (c) => {
const foo = c.req.param('foo')
return c.text('res')
})
```
This is a bug of TrieRouter. Already been fixed in this PR.  This bug is reported by this tweet: https://twitter.com/_ayame113_/status/1600467184853319680 Thanks!
=> fix(trie-router): bug for routing orders with named param

deno_dist/request.ts, src/hono.test.ts, src/request.ts
if a cookie with a name isn't present, `cookie` function returns undefined although this isn't reflected at the type level.
=> `cookie` should return `string | undefined`

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/middleware/html/index.ts, deno_dist/middleware/validator/middleware.ts, deno_dist/request.ts, deno_dist/types.ts, src/context.ts, src/hono.ts, src/middleware/html/index.ts, src/middleware/validator/middleware.test.ts, src/middleware/validator/middleware.ts, src/request.ts, src/types.test.ts, src/types.ts
This PR allows normal types, instead of only allowing `Schema` in the Handler.
```ts
type User = {
id: string
name: string
age: number
}
const handler: Handler<User> = (c) => {
const user = c.req.valid() // <--- user is User
// ...
}
```
This change also makes it possible to use the 3rd party library such as "[Zod](https://zod.dev)" for validation.
```ts
import { z } from 'zod'
import type { ZodType } from 'zod'
import { Hono } from '../../../src/hono'
import type { Handler } from '../../../src/index'
const schema = z.object({
id: z.string(),
name: z.string(),
age: z.number(),
})
// You can write a custom validator with Zod:
const zValidtor = <T extends ZodType>(schema: T): Handler<z.infer<T>> => {
return async (c, next) => {
const parsed = schema.safeParse(await …
```
=> feat(handler): "schema" allow normal types

deno_dist/validator/schema.ts, src/validator/schema.test.ts, src/validator/schema.ts
This PR will make`SchemaToProps` return types correctly. We can get "normal types" from `c.req.valid()`. I think this is a good change.
Before:
After:
=> fix(type): infer types correctly

deno_dist/request.ts, src/hono.test.ts, src/request.ts
`c.req.param('missing-parameter')` was returning "undefined". It was a string!! not `undefined`.  Of course, it should not return a string, should return `undefined`.
This was taught to me by noil on Discord. Thanks.
=> fix(request): `c.req.param()` should return `undefined` not "undefined"

deno_dist/context.ts, src/context.test.ts, src/context.ts
`c.text()` returns `Response` immediately if headers are empty.
It does not set `Content-Type` intentionally, but `text/plain` is added automatically, so it is not a breaking change. This is mainly for benchmarking, but benchmarking is important.
`GET /` will become 13% faster on Bun!
=> perf(context): `c.text()` returns a response immediately if header is empty

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/middleware/basic-auth/index.ts, deno_dist/middleware/cache/index.ts, deno_dist/request.ts, deno_dist/utils/encode.ts, deno_dist/validator/validator.ts, src/compose.test.ts, src/context.test.ts, src/context.ts, src/hono.test.ts, src/hono.ts, src/middleware/basic-auth/index.ts, src/middleware/cache/index.ts, src/request.ts, src/validator/validator.test.ts, src/validator/validator.ts
This PR introduces "HonoRequest" class to handle a request object with a "wrapper pattern". This is told in #712 . For the same purpose @stefanmaric is implementing "HonoRequest" with "proxy pattern". #727 .
The wrapper pattern has two features.
1. There are no "big" breaking changes, but access to environment-specific properties such as `c.req.cf` must be changed to `c.req.original.cf`.
2. There is no performance degradation with this change. It may even improve it.
Detail. First, HonoRequest will no longer be compatible with `Request`. So, if we want to use the raw `Request` object, we should write like this:
```ts
const cacheKey = c.req.original
```
But, all standard methods and properties of `Request` are ported. We can use `c.req` the same way we have always used it.
```ts
const …
```
=> feat: introduce HonoRequest with "wrapper pattern"

package.json, tsconfig.build.json
To support "moduleResolution" : "NodeNext", output .d.ts to the dist/types directory and add dist/types/package.json { "type": "commonjs" }.
#679 
#668
=> fix: Support tsconfig.json "moduleResolution" : "NodeNext"

package.json
There was a mistake in #747 , sorry.
I was able to find it in publint.
``npx publint`` or https://publint.dev/hono
=> fix(package.json): typo exports static-router

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/middleware/logger/index.ts, deno_dist/request.ts, deno_dist/utils/encode.ts, deno_dist/utils/url.ts, src/context.ts, src/hono.ts, src/request.ts, src/utils/url.test.ts, src/utils/url.ts
This PR includes many changes for optimization.
* Avoid using `URLSearchParams`.
* Created original function to parse query params.
* Optimize handling headers.
* Reduced the number of headers passed to `Response`.
* Decode URL based on whether it contains `%` or not.
* Pass static value to `split` instead of regexp.
* Use `indexOf` instead of `slice`.
The result, 19% faster than 2.7.1!
=> perf: optimize parsing queries and headers / 19% faster than 2.7.1

src/utils/url.test.ts, src/utils/url.ts
I noticed that `@` is not part of the path, but is available as part of the parameter name.
I don't expect many people to use @ in parameter names, but I would like to make @ available because fewer restrictions due to internal implementation methods is better.
I don't think it is quintessential to use `\` as a parameter name, so I don't think there is any conflict if it is `@\\{i}`.
To simplify future discussions, it may be possible to decide in some version that "only `[a-zA-Z_][a-zA-Z0-9_]+` can be used for parameter names".
=> refactor(utils): splitRoutingPath, allow `@` to be safely used in parameter names.

deno_dist/router/trie-router/node.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts, src/utils/url.test.ts, src/utils/url.ts
"TrieRouter" did not support regexp routing with slash `/`. This means that it will match paths in the same depth but cannot match paths in a dynamic depth. 
```ts
// GET `/js/chunk/abc.js` is not matched
app.get('/:filename{.+.js$}', async (c, next) => {
console.log(`You access ${c.req.param('filename')}`)
await next()
})
```
In this PR, make it supports slash.
Will match `/js/chunk/abc.js` not only `/abc.js`.
P.S.
Currently, "RegExpRouter" also does **not** support regexp routing with slashes. It would be good to support it.
=> feat(trie-router): `regexp` support path including slashes

deno_dist/hono.ts, deno_dist/middleware/basic-auth/index.ts, deno_dist/middleware/bearer-auth/index.ts, deno_dist/middleware/jwt/index.ts, deno_dist/utils/http-exception.ts, src/hono.test.ts, src/hono.ts, src/middleware/basic-auth/index.ts, src/middleware/bearer-auth/index.ts, src/middleware/jwt/index.ts, src/utils/http-exceoption.test.ts, src/utils/http-exception.ts, test_lagon/index.ts
In this PR, I will introduce `HTTPException`.
Until now, we have not dared to create an `Exception` class that extends `Error`. Because we can handle it with the middleware looking up status codes.
```ts
app.post('/validator', async (c, next) => {
await next()
if (c.res.status === 400) {
return c.text('Validation error!', 400)
}
})
```
But, if 401 error occurs in Basic Auth or Bearer Auth middleware, another middleware cannot handle it because Basic Auth and Bearer Auth middleware immediately returns the Response. We must not fire the next middleware handler for a security issue.
So, when a fatal error occurs, such as an authentication error, we can throw this `HTTPException` and handle it with `app.onError`.
```ts
app.onError((e, c) => {
if (e instanceof HTTPException && e.status === …
```
=> feat: introduce `HTTPException`

tsconfig.json
The [TypeScript documentation](https://www.typescriptlang.org/tsconfig#strict) said:
> The `strict` flag enables a wide range of type checking behavior that results in stronger guarantees of program correctness. **Turning this on is equivalent to enabling all of the strict mode family options**, which are outlined below. You can then turn off individual strict mode family checks as needed.
Because there is already a `strict` flag, so `strictPropertyInitialization` and `strictNullChecks` are redundant.
=> remove unnecessary individual strict mode family options

src/adapter/cloudflare-pages/index.ts
In v3 RC, `hono/cloudflare-pages` is currently unusable due to discordance between the `exports` field and actual build asset:
https://github.com/honojs/hono/blob/2cb250faf9b8520719102b2a4e522307323ba803/package.json#L145-L149
and
```console
$ cd repro && cd $_
$ npm init -y && npm install hono@next
$ ls node_modules/hono/dist/adapter/cloudflare-pages
handler.js
```
This PR aims to fix the problem.
=> fix: correctly export pages adapter

deno_dist/hono.ts, deno_dist/middleware/validator/middleware.ts, deno_dist/request.ts, deno_dist/types.ts, deno_dist/utils/types.ts, src/hono.test.ts, src/hono.ts, src/middleware/validator/middleware.ts, src/request.ts, src/types.ts, src/utils/types.ts
This PR fix #821 
In the current version, if `/api/animal/:type?` is defined as a route, `type` will be `string` though it is "optional". It's the wrong type. In this PR, it will be `string | undefined`.
I've made PR #825  which makes it a blank string `''` not `string | undefined`. But, after getting advice from @pmbanugo, I rethought it should be `string | undefined`.
=> fix(request): make optional param type correct

deno_dist/hono.ts, deno_dist/middleware/validator/index.ts, deno_dist/types.ts, src/hono.ts, src/middleware/validator/index.test.ts, src/middleware/validator/index.ts, src/types.test.ts, src/types.ts
This PR enable we can register multiple validator/handlers with complex patterns.
See: <https://github.com/honojs/hono/issues/823>
Thanks to everyone, it comes true. We can write like this:
Note:
* We can't register over ten handlers with validators. Have to write it down in the document when releasing the "v3".
* There may be some things to fix, but I'll merge them in, to be fixed later.
=> feat(validator): support multiple handlers w/ complex patterns.

deno_dist/middleware/validator/index.ts, deno_dist/request.ts, deno_dist/types.ts, src/middleware/validator/index.test.ts, src/middleware/validator/index.ts, src/request.test.ts, src/request.ts, src/types.test.ts, src/types.ts
In this PR, we can specify which type of data we want to get by `c.req.valid()` such as `c.req.valid('query')`.
```ts
api.get(
'/',
zValidator(
'query',
z.object({
page: z.number(),
})
),
(c) => {
const { page } = c.req.valid('query')
return c.text(`Current page is ${page}`)
}
)
```
We can call `c.req.valid()` with no arguments as always to get all the data.
=> feat(req): support `c.req.valid('query')`

deno_dist/context.ts, src/context.test.ts, src/context.ts, src/hono.test.ts
=> fix(context): fixed bug raw `Response` content-type is overwritten

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/middleware/validator/index.ts, deno_dist/mod.ts, deno_dist/request.ts, deno_dist/types.ts, src/context.ts, src/hono.test.ts, src/hono.ts, src/middleware/validator/index.test.ts, src/middleware/validator/index.ts, src/mod.ts, src/request.ts, src/types.test.ts, src/types.ts
This PR renews output types emitted from "app".
Before this PR, it will output types with `app.build()` and the client such as `hc` use it. But in this PR, we don't have to use `app.build()`, and emitted types are changed:
For example, write the endpoint with the validator middleware:
```ts
const route = app.post(
'/api/v2/posts',
validator(
'json',
validatorFunc(
z.object({
id: z.number(),
title: z.string(),
})
)
),
(c) => {
success: true,
})
}
)
```
And we can get the type:
```ts
export type AppType = typeof route
type Schema = ExtractSchema<typeof route>
```
The extracted types are the followings. `Schema` will be:
```ts
type Schema = {
'/api/v2/posts': {
$post: {
input: {
json: {
id: number
title: string
}
}
output: {
success: boolean
}
}
}
}
```
I think this format …
=> feat: rewnew output types

src/deno/serve-static.ts
There will be a 404 error when non-standard characters appear in URL. Add `decodeURI()` to fix it.
=> Fix 404 error on Serve Static Middleware

deno_dist/router/reg-exp-router/router.ts, src/router/reg-exp-router/router.ts
I would like to change it to cache the constructed `Result<T>` for static paths.
I could not see a clear change in the benchmark, but I believe there is a slight performance benefit, which can reduce object creation at request time.
=> perf(reg-exp-router): Cache Result<T> instead of T[] if there is no parameter.

deno_dist/client/client.ts, deno_dist/client/index.ts, deno_dist/client/types.ts, deno_dist/client/utils.ts, package.json, src/client/client.test.ts, src/client/client.ts, src/client/index.ts, src/client/types.ts, src/client/utils.test.ts, src/client/utils.ts, src/middleware/validator/index.test.ts, yarn.lock
This PR introduces a new feature, "Hono Client". "hc" for the same purpose was built as `@hono/hc`, but making it obsolete, includes it in the core package.
First, create the API server. Write the endpoint and export the type of route:
```ts
// server.ts
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
const route = app.post(
'/api/v2/posts',
zValidator(
'json',
z.object({
id: z.number(),
title: z.string(),
})
),
(c) => {
const { id, title } = c.req.valid('json')
// Use `c.jsonT()` to emit types
message: `${id} is ${title}`,
success: true,
})
}
)
export type AppType = typeof route // export the type
```
Second, start writing the `client.ts`, import the type from `server.ts` and pass it to the `hc` …
=> feat: `hc` - Hono Client

src/adapter/cloudflare-pages/handler.test.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.test.ts, src/adapter/nextjs/handler.ts
This PR is for the adapter of Cloudflare Pages and Next.js. It allows passing the mount path as an argument to `handle`.
For example, if you struct the Next.js project like this:
`pages/api/[route].ts` could be follows:
```ts
import { handle } from 'hono/nextjs'
app.get('/hello', (c) => {
message: 'Hello',
})
})
app.get('/morning', (c) => {
message: 'Morning',
})
})
export default handle('/api', app)
```
It is simpler because you don't have to write `/api` in the argument of `app.get` every time.
=> feat(adapter): `handle(path, app)` for CF Pages & Next.js

src/adapter/cloudflare-pages/handler.test.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.test.ts, src/adapter/nextjs/handler.ts
***This PR breaks compatibility with rc.12 but is still compatible with rc.11.*** Since rc.12 is only 9 hours old and adapters aren't in the stable releases yet, I hope this breaking change doesn't have any significant impact.
With this PR, type definitions for `handle` in Cloudflare Pages and Next.js become simpler and parameter names are more descriptive. It also saves the bundle size; minified ESM for Cloudflare Pages adapter is reduced from 825B to 503B and Next.js adapter from 561B to 406B.
Here are the pros/cons I can think of:
<dl>
<dt>Pros</dt>
<dd>
- Bundle size is smaller.
- Interface is simpler.
</dd>
<dt>Cons</dt>
<dd>
- Parameter order is different from `Hono.prototype.route`. Some people might feel awkward.
- A new Hono app is always instantiated and this has a slight …
=> feat(adapter)!: simplify HandleInterface and reduce bundle size

deno_dist/README.md, deno_dist/hono.ts, deno_dist/types.ts, src/hono.test.ts, src/hono.ts, src/types.ts
This PR enables handling multiple methods with `app.on()` method.
```ts
app.on(['PUT', 'DELETE'], '/posts/:id', (c) => {
//...
return c.text(`Your method is ${c.req.method}`)
})
```
=> feat(`app`): support multiple methods with `app.on()`

deno_dist/client/types.ts, src/client/client.test.ts, src/client/types.ts
```ts
const req = client.index
type Actual = InferResponseType<typeof req>
```
will be:
```ts
const req = client.index.$get
type Actual = InferResponseType<typeof req>
```
=> feat: change the arg `InferResponseType` receives

deno_dist/client/types.ts, src/client/client.test.ts, src/client/types.ts
We can write like below:
```ts
const client = hc<AppType>('/')
const $get = client.index.$get
type ReqType = InferRequestType<typeof $get>
type T = ReqType['query']
```
=> feat(hc): add `InferRequestType`

deno_dist/client/index.ts, deno_dist/client/types.ts, src/client/index.ts, src/client/types.ts
With `Fetch`, you can write `fetcher` for [SWR](https://swr.vercel.app/ja) type-safety.
```ts
import useSWR from 'swr'
import { hc, InferRequestType, Fetch } from 'hono/client'
import { AppType } from '../functions/api/[[route]]'
const App = () => {
const client = hc<AppType>('/api')
const $get = client.hello.$get
const fetcher = (method: Fetch<typeof $get>) => (arg: InferRequestType<typeof $get>) => {
return async () => {
const res = await method(arg)
return await res.json()
}
}
const { data, error, isLoading } = useSWR(
'api-hello',
fetcher($get)({
query: {
name: 'SWR',
},
})
)
if (error) return <div>failed to load</div>
if (isLoading) return <div>loading...</div>
return <h1>{data.message}</h1>
}
```
=> feat(client): introduce `Fetch` type

deno_dist/client/client.ts, deno_dist/client/types.ts, deno_dist/client/utils.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts, src/client/utils.test.ts, src/client/utils.ts
Enabled passing the commonly used site header as an argument during HonoClient instance generation.
=> feat(client): Inject common headers

deno_dist/client/client.ts, deno_dist/client/types.ts, deno_dist/hono.ts, deno_dist/types.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts, src/hono.ts, src/types.test.ts, src/types.ts
This PR will fix the matter of #907 .
When using `app.route()`, the schema information is missing but made it so that it is kept.
=> feat(types): keep schema info with `app.route()`

deno_dist/client/client.ts, deno_dist/client/types.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts
As described in my issue https://github.com/honojs/hono/issues/917 it would be great to be able to pass a custom fetch method to Hono Client to be able to call Service Bindings through Hono Client.
I have just added an optional `fetch` method to the `RequestOptions` so that the `fetch` method of a Service Binding can be used instead of the default `fetch` API when it's set in the options.
See this example on how it would be used:
```
services = [
{ binding = "AUTH", service = "auth-service" },
]
```
```typescript
const client = hc<CreateProfileType>('/', { fetch: c.env. AUTH.fetch });
...
// use client normally
```
=> Custom fetch method for Hono Client options

deno_dist/hono.ts, src/hono.test.ts, src/hono.ts
In order to avoid having to write the full URL every time when writing tests, 
we implemented a feature to implicitly format the URL and generate the request object when the pathname argument is entered.
=> feat: allow pathname argument

deno_dist/hono.ts, deno_dist/types.ts, src/client/client.test.ts, src/hono.ts, src/types.ts
As pointed out in #915, the type was incorrectly inferred when mounting an app with multiple `jsonT()` endpoints using `app.route()`.
This PR will fix #915
=> fix(types): `app.route` with multiple endpoints returns types correctly

src/index.ts
Congrats on the v3, launch. Really liking Hono as a clean and fast framework. 
In my apps, I sometimes build utility functions that are used by multiple handlers and they interact with the Request. Since the request has changed to `HonoRequest`, I think it is valuable to also expose its type, so ppl can write functions and define `HonoRequest` as a parameter.
=> Expose HonoRequest Type

deno_dist/utils/encode.ts, src/utils/encode.ts
We don't need it anymore. Fix #924
=> refactor(util): remove using `Buffer` from `encode.ts`

deno_dist/validator/validator.ts, src/validator/validator.test.ts, src/validator/validator.ts
It throws the error if we do `c.req.json()` or `c.req.parseBody()` after validating `json` or `form` with `hono/validator`, 
```ts
app.post(
'/',
validator('json', () => {
return {
foo: 'bar',
}
}),
async (c) => {
await c.req.json() // throw error!
return c.text('foo')
}
)
```
This bug is caused by the Request object being used though the body has been used. So, we should clone it before validation.
Fix #818
=> fix(validator): clone Request object if `json` or `form`

deno_dist/client/client.ts, deno_dist/client/types.ts, deno_dist/hono.ts, deno_dist/types.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts, src/hono.test.ts, src/hono.ts, src/types.ts
This PR implements the following.
* Reduce side-effects of `route()` calls on the parent app
* https://github.com/honojs/hono/compare/main...usualoma:hono:feat/basepath-2?expand=1#diff-8ac13809c9886e994d1db33943de82df4d6c5d88b73fd0270c0189804ff565c2R182
* Support nested `route()` calls
* https://github.com/honojs/hono/compare/main...usualoma:hono:feat/basepath-2?expand=1#diff-8ac13809c9886e994d1db33943de82df4d6c5d88b73fd0270c0189804ff565c2R179-R180
`route()` can be used to specify the base path.
```typescript
const hono = new Hono().route('/api')
const api = hono.get('/search', (c) => c.jsonT({ ok: true }))
type AppType = typeof api
```
I also wrote the following code to try to be able to specify it in the constructor, but I just could not get it to infer correctly. …
=> feat: Improve route()

deno_dist/hono.ts, src/hono.ts
This pr is to extend `app.request` usage range.
We test app by fetching directly via `app.request` without a setup of an app server, but the request parameters can only accept string or request, while fetch's can accept string, request or URL for the first parameter.
Moreover, when the input is request, then the second paramter `RequestInit` dose not worked as fetch dose.
=> fix: let the app.request behave the same as fetch

deno_dist/context.ts, deno_dist/utils/types.ts, src/client/client.test.ts, src/context.ts, src/utils/types.ts
`jsonT()` returns a JSON object composed of primitive types. For example, a `Date` object is converted to a string. But currently, `jsonT()` allows the `Date` type.
```ts
app.get('/hello', (c) => {
messge: 'Hello',
datetime: new Date(), // does not show the error
})
})
```
And the Client will get the `Date` type even though the actual value is a string.
Allowing the types of objects other than primitives to be loose can be confusing.
In this PR, I've made it provides a JSON type and limits the object that `jsonT()` would receive, and if they are not JSON type, it throws an error.
On the client side, the return type of `res.json()` is `never`.
This feature was inspired by the following article.
<https://zenn.dev/kosei28/articles/f4bac1ed2b64a7#date%E5%9E%8B%E3%81%AF%E6%96%8 …
=> feat(`jsonT`): check JSON type

deno_dist/client/types.ts, deno_dist/hono.ts, deno_dist/types.ts, deno_dist/utils/types.ts, src/client/client.test.ts, src/client/types.ts, src/hono.ts, src/types.ts, src/utils/types.ts
Made it throws the type error if `client.path.$method()` needs arguments:
This fix will make the Client more type-safety.
=> fix(client): show type error if `$get()` needs args

src/adapter/cloudflare-pages/handler.test.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.test.ts, src/adapter/nextjs/handler.ts
If we use `handle` in the Cloudflare Pages adapter with no second argument:
```ts
export const onRequest = handle(app)
```
With the current implementation,  `app` will be passed to `route()`
https://github.com/honojs/hono/blob/b1c50597088c2e4e1d3666f53f3f9de171cbd506/src/adapter/cloudflare-pages/handler.ts#L17-L22
If we do so, the error thrown from `app` can't be re-thrown:
```ts
const app = new Hono().route('/api')
app.get('/hello', (c) => {
throw new Error('Capture this error in Sentry!')
})
app.onError((e) => {
throw e // <--- This will not be a real "error", will return 500 response.
})
export const onRequest = handle(app)
```
This PR fixes this issue.
This will resolve #938
=> fix(pages/nextjs): don't use `route()` if path is not passed

src/client/client.test.ts, src/client/types.ts, src/context.ts, src/types.test.ts, src/utils/types.ts, src/validator/validator.test.ts
Do not use `PrettyJSON<T>` because it causes unnecessary distributions. As a side effect, `boolean` is inferred to `true | false`. But I think there is no problem in practical use.
This will fix #950
=> fix(type): remove unnecessary distribution

README.md, deno_dist/README.md
I have wanted to write this for a while; this is important.
One of the features of Hono is the RegExpRouter, but I must not take credit for that.
=> docs(readme): add creator name of RegExpRouter and SmartRouter

.github/workflows/ci.yml, deno_dist/adapter.ts, deno_dist/client/types.ts, deno_dist/middleware/cache/index.ts, jest.wrangler.config.js, package.json, src/adapter.ts, src/client/types.ts, src/context.test.ts, src/hono.test.ts, src/middleware/cache/index.ts, test_bun/index.test.tsx, test_deno/hono.test.ts, test_fastly/index.test.ts, test_lagon/.env.lagon, test_lagon/index.test.ts, test_lagon/index.ts, test_node/index.test.ts, test_wrangler/index.test.ts, test_wrangler/index.ts, yarn.lock
This PR introduces `env` function to get environment variables for any runtimes, not only variables of Cloudflare Workers' Bindings.
We can write the code with the same syntax at any runtime:
```ts
import { env } from 'hono/adapter'
app.get('/env', (c) => {
const { NAME } = env<{ NAME: string }>(c)
return c.text(NAME)
})
```
Supported runtimes:
* Cloudflare Workers
* Deno
* Bun
* Lagon ( It works on dev but can't resolve the path of `.env` on CI )
* Node.js
* Vercel ( No CI )
* Fastly ( Users may not define the values... )
Already we are using `c.env` for Cloudflare Workers' Bindings, so we can use it for other runtimes. But, if we do so, we have to write the code to `context.ts`. It's bad to write that things depend on each environment on the common component. Separating `env` as `import …
=> feat: `env` support enviroment variables for multi runtimes

deno_dist/hono.ts, src/adapter/cloudflare-pages/handler.test.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.test.ts, src/adapter/nextjs/handler.ts, src/client/client.test.ts, src/hono.test.ts, src/hono.ts
#948 basePath() version
One difference from https://github.com/honojs/hono/pull/948#issuecomment-1455115090 is that we replaced `private _basePath` with `#basePath`. This should make it more straightforward that it is a local member.
To reduce confusion caused by compatibility issues, it would be possible to allow `route(path)` to be used in 3.x and then remove it in 4.x.
```diff
diff --git a/src/hono.ts b/src/hono.ts
index 72380c8..3238c35 100644
--- a/src/hono.ts
+++ b/src/hono.ts
@@ -137,9 +137,23 @@ export class Hono<
route<SubPath extends string, SubEnv extends Env, SubSchema>(
path: SubPath,
app: Hono<SubEnv, SubSchema>
+  ): Hono<E, RemoveBlankRecord<MergeSchemaPath<SubSchema, SubPath> | S>, BasePath>
+  /** @deprecated
+   * Use `basePath` instead of `route` with one argument.
+ …
```
=> feat: `route()` with one argument is renamed `basePath()`.

deno_dist/context.ts, src/context.test.ts, src/context.ts
This PR proposes allowing us to pass `InitResponse` as the second argument to `c.text()` or `c.json()`. It will overload these methods.
```ts
interface TextRespond {
(text: string, status?: StatusCode, headers?: HeaderRecord): Response
(text: string, init?: ResponseInit): Response
}
```
This is inspired by Issue #952. Now, it is very tedious to customize Basic Auth errors.
```ts
app.onError((e, c) => {
if (e instanceof HTTPException) {
const res = e.getResponse()
res.headers.set('content-type', 'application/json')
return new Response(
JSON.stringify({
message: 'Unauthorized!',
}),
res
)
// ...
```
So I thought it would be easier if we can pass `ResponseInit`, i.e. meta information such as headers, to `c.json()`.
```ts
app.onError((e, c) => {
if (e instanceof HTTPException) {
return …
```
=> feat(context): allow passing `RequestInit` to `c.json()` etc.

deno_dist/context.ts, deno_dist/request.ts, deno_dist/types.ts, deno_dist/validator/index.ts, deno_dist/validator/validator.ts, src/context.ts, src/request.ts, src/types.test.ts, src/types.ts, src/validator/index.ts, src/validator/validator.test.ts, src/validator/validator.ts
This PR provides supporting "type transformation" for the validator.
For example, Zod has a "transform" feature.
```ts
z.string()
.regex(/^[0-9]+$/)
.transform(Number)
```
This means that the input type(`string`) and output type(`number`) are different. But, Hono does not support different input and output types. If we use "transform" in Zod Validator Middleware, the value from `c.req.valid()` will be "input type" not "output type":
```ts
const app = new Hono().post(
'/foo',
zValidator(
'json',
z.object({
id: z
.string()
.regex(/^[0-9]+$/)
.transform(Number),
})
),
(c) => {
c.req.valid('json').id // expected to be `number`
```
This is mentioned at #946 
With this PR, the validator treats input and output types as different, so it will suport Zod's transform.
Without this feature, …
=> feat(validator): support type transformation

deno_dist/middleware/etag/index.ts, src/middleware/etag/index.test.ts, src/middleware/etag/index.ts
In this PR, I've made the Etag Middleware returns the `Etag` header if the response is `304`.
This will fix #972
=> fix(etag): returns correct headers

src/context.ts, src/hono.test.ts
This PR enables completely overwriting the response from middleware after `next()`. This matter is mentioned at #960 .
We can do it by putting `undefined`:
```ts
app.use('*', async (c, next) => {
await next()
c.res = undefined
c.res = new Response('New Response')
})
```
Good PR, as this is done with very few codes.
Fix #960
=> feat(middleware): support overwriting response after `next()`

deno_dist/types.ts, src/client/types.ts, src/types.test.ts, src/types.ts
This PR fixes the `MergePath` type definition.
Before this PR if you write the following:
```ts
type path = MergePath<'/api', '/'>
```
`path` will be `/api/`. But this is not correct because the actual value with `mergePath()` is the different. The trailing slash is removed:
https://github.com/honojs/hono/blob/fea78f29bd681350ce61dd71b33042aa6ec7db5c/src/utils/url.test.ts#L113
So, I've fixed it:
```ts
type path = MergePath<'/api', '/'>
// path will be /api
```
Whit this PR, the matters mentioned at #962 may be resolved.
=> fix(types): make `MergePath<'/api', '/'>` work well

deno_dist/client/utils.ts, src/client/utils.test.ts, src/client/utils.ts
`removeIndexString`  was supporting only `/`, so if we have a case like below, it will request to `/foo/index`.
```ts
const res = await client.foo.index.$get()
```
But,  if the endpoint path is `/foo/`, of course, it will return Not Found.
This PR makes `removeIndexString` support `/sub/index` and will fix the issue.
Fix #962
=> fix(client): `removeIndexString` supports `/sub/index`

src/adapter/cloudflare-pages/handler.test.ts, src/adapter/cloudflare-pages/handler.ts, src/adapter/cloudflare-pages/index.ts
This PR is for an adapter of Cloudflare Pages. Now we can get "EventContext" from `env`. It's useful for adding Basic Auth to your page's site with the middleware.
```ts
// functions/_middleware.ts
import { basicAuth } from 'hono/basic-auth'
import { handle } from 'hono/cloudflare-pages'
import type { EventContext } from 'hono/cloudflare-pages'
eventContext: EventContext
}
const app = new Hono<{ Bindings: Bindings }>()
app.get(
'*',
basicAuth({
username: 'hoge',
password: 'bar',
}),
async (c) => {
return c.env.eventContext.next()
}
)
export const onRequest = handle(app)
```
=> feat(pages): enable getting `eventContext`

src/adapter/cloudflare-pages/handler.ts, src/adapter/nextjs/handler.ts
This PR is for the Cloudflare Pages adapter and the Next.js adapter. Now, we recommend using `app.basePath()` to set the base path instead of passing a second argument to `handle()`. With this PR showing the "deprecated" message:
=> feat(page/nextjs): show "deprecated" for 2nd arg of `handle()`

deno_dist/context.ts, deno_dist/hono.ts, deno_dist/request.ts, deno_dist/utils/url.ts, src/context.ts, src/hono.test.ts, src/hono.ts, src/request.ts, src/utils/url.test.ts, src/utils/url.ts
This PR introduces the property `path` for HonoRequest.
This simple feature allows you to get the URL's path by accessing `c.req.path`.
```ts
app.get('/search', (c) => c.text(c.req.path)) // "search"
```
This feature is what many users wanted. This is good because there is no performance degradation, only a slight increase in file size. There are some API changes, but they are used internally, so there are no problems.
=> feat(req): introduce `c.req.path`

deno_dist/context.ts, src/context.test.ts, src/context.ts
This PR fixes the issue for `c.header()` with `append` option.
When using `c.header()` with the `append` option as in the following code, the `Content-Type` was not set correctly.
```ts
c.header('foo', 'bar', { append: true })
return c.html('<h1>This rendered fine</h1>') // <== text/plain...
})
```
This PR will resolve it.
Fix #995
=> fix(context): fixed a bug for `c.header()` with a `append` option

deno_dist/utils/url.ts, src/utils/url.test.ts, src/utils/url.ts
Do not remove slashes when the strict option is `false` and the path is `/`.
Fix https://github.com/honojs/hono/issues/1000
=> fix(app): don't remove slash form `/` if strict is false

src/request.test.ts, src/utils/url.ts
This PR enables `c.req.query` and `c.req.queries` to decode special characters in URL parameters.
This will fix #1006
=> fix(req): decode special chars in URL params

deno_dist/utils/url.ts, src/utils/url.test.ts, src/utils/url.ts
This PR fixes #1022
There is almost no performance degradation (In particular, there is no degradation for `_getQueryParam(url, key)`.)
=> fix(utils/url): Fix behavior when parameters with no value specified are mixed.

benchmarks/query-param/package-lock.json, benchmarks/query-param/package.json, benchmarks/query-param/src/bench.mts, benchmarks/query-param/src/fast-querystring.mts, benchmarks/query-param/src/hono.mts, deno_dist/adapter.ts, deno_dist/middleware/jwt/index.ts, deno_dist/mod.ts, deno_dist/request.ts, deno_dist/utils/jwt/jwt.ts, deno_dist/utils/url.ts, package.json, src/adapter.ts, src/index.ts, src/middleware/jwt/index.test.ts, src/middleware/jwt/index.ts, src/mod.ts, src/request.ts, src/utils/jwt/jwt.test.ts, src/utils/jwt/jwt.ts, src/utils/url.test.ts, src/utils/url.ts
This PR will add support for getting the decoded payload from `c.get('jwtPaload')` for JWT Auth Middleware.
```ts
app.post(
'/auth/abc',
jwt({
secret: 'a-secret',
}),
(c) => {
const payload = c.get('jwtPayload')
//...
}
)
```
This will resolve #810 #1005 
The `verify()` API in `utils/jwt/jwt.ts` has been changed. It will return `any` instead of `boolean`. This seems to be  a breaking change, but this function is mainly "utility" used in the Hono internal. We should release the fix, including breaking changes as major version up, but this change will not affect end users. EDIT ~~I'd like to release it as a minor version up "3.2.0".~~
EDIT:
We can release this with a patch release.
* Utilities such as `utils/url.ts` are broken and changed without notice. utilities are intended to be used …
=> feat(jwt): support for getting payload from `c.get('jwtPayload')`

benchmarks/routers/package.json, benchmarks/routers/src/bench-includes-init.mts, deno_dist/router/linear-router/index.ts, deno_dist/router/linear-router/router.ts, src/router/linear-router/index.ts, src/router/linear-router/router.test.ts, src/router/linear-router/router.ts
It is slightly slower than #1041, but the bugs have been fixed, and it covers most use cases.
```
% npm run bench-includes-init:node
> bench-includes-init:node
> tsx ./src/bench-includes-init.mts
cpu: Apple M2 Pro
runtime: node v18.14.0 (arm64-darwin)
benchmark          time (avg)             (min … max)       p75       p99      p995
----------------------------------------------------- -----------------------------
• GET /user
----------------------------------------------------- -----------------------------
RegExpRouter    30.71 µs/iter    (24.88 µs … 1.84 ms)  28.54 µs  86.63 µs 335.17 µs
TrieRouter       8.16 µs/iter    (7.5 µs … 155.54 µs)   7.88 µs   12.5 µs  16.83 µs
LinearRouter   946.25 ns/iter (932.29 ns … 985.59 ns) 950.19 ns 985.59 ns 985.59 ns
MedleyRouter      2.8 µs/iter …
```
=> feat: Introduce LinearRouter.

deno_dist/request.ts, src/request.test.ts, src/request.ts
As mentioned in [this PR](https://github.com/honojs/hono/pull/884#issuecomment-1426925215), empty strings are valid header values.
=> empty string is a valid header value

deno_dist/adapter.ts, deno_dist/context.ts, src/adapter.ts, src/context.ts, test_fastly/index.test.ts
This PR fixes the method for detecting whether the code is running on Fastly Compute@Edge or not.
Previously, it used `require('fastly:env')` and checked whether it could access the variables. With this PR, it checks for `global.fastly` instead. Additionally, in `adapter.ts`, the `env` function used dynamic require, but this caused errors in environments like `webpack`, so it has been removed. We can use `ConfigStore` to manage user-defined data on Fastly.
Resolve #1052
=> fix: check `global.fastly` instead of `require('fastly:env')`

src/context.test.ts, src/context.ts
This PR allows the Context to clear a header using `c.header(key, undefined)` because previously, we didn't have a way to clear headers.
=> feat(context): clear the header with `c.header(key, undefined)`

deno_dist/context.ts, deno_dist/middleware.ts, deno_dist/middleware/cookie/index.ts, deno_dist/request.ts, package.json, src/context.ts, src/middleware.ts, src/middleware/cookie/index.test.ts, src/middleware/cookie/index.ts, src/request.ts
This PR introduces the Cookie Middleware, which includes `getCookie()` and `setCookie()` methods. As a result, `c.req.cookie()` and `c.cookie()` will be deprecated.
```ts
import { getCookie, setCookie } from 'hono/cookie'
// ...
app.get('/cookie', (c) => {
const yummyCookie = getCookie(c, 'yummy_cookie')
// ...
setCookie(c, 'delicious_cookie', 'macha')
//
}
```
`c.req.cookie()` and `c.header()` will be obsolete in v4.
Related to #965
=> feat: Cookie Middleware and deprecate `c.req.cookie()` / `c.cookie()`

package.json, src/adapter/nextjs/handler.ts, src/adapter/vercel/handler.test.ts, src/adapter/vercel/handler.ts, src/adapter/vercel/index.ts
I realized that Hono works on Vercel, not only with Next.js. Therefore, I create `hono/vercel` and deprecate `hono/nextjs`. `hono/nextjs` will become obsolete in v4.
=> feat(adapter): add `hono/vercel` / deprecate `hono/nextjs`

package.json, src/preset/quick.ts, src/preset/tiny.ts
This PR introduces `hono/quick` and a `preset` directory to manage `hono/tiny` and `hono/quick`.
`hono/quick` uses only the **LinearRouter**. It has the fastest boot time, making it suitable for Fastly Compute@Edge.
You can use `hono/quick` just like `hono`:
```ts
import { Hono } from 'hono/quick'
```
=> feat(preset): add `hono/quick`

runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/handler.ts
Lambda Function URLs are endpoints that allow for simple requests to be passed to Lambda without an API Gateway. 
https://aws.amazon.com/jp/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/
Most of the event is compatible with API Gateway, but the location of the method is different, which is why, as mentioned in https://github.com/honojs/hono/issues/1075, we specified the behavior of GET during a POST request. This patch attempts to fix that issue.
=> feat(adapter): AWS Lambda Adapter supports requests via Lambda Function URLs.

runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/handler.test.ts, src/adapter/aws-lambda/handler.ts
This PR concerns the AWS Lambda adapter.
From PR #1009, it encodes any content as Base64.
This works fine on Function URLs, but it does not perform well on Lambda with API Gateway. We don't need to encode text-based content, only binary. In this PR, it determines whether the content is text or not and decides whether encoding is necessary.
=> fix(lambda): don't encode text

src/adapter/cloudflare-workers/server-static-module.ts
This PR enables the `rewriteRequestPath` option for `serveStatic`.
=> fix(cloudflare-workers): serveStatic `rewriteRequestPath` option

deno_dist/compose.ts, deno_dist/types.ts, src/compose.ts, src/hono.test.ts, src/types.ts
As mentioned by @AliKaanT in #1088, `app.onError()` can be an asynchronous function.
```ts
app.onError(async (e, c) => {
//...
})
```
This PR enables support for an asynchronous function in `app.onError()`. It is based on #1088, I added tests and a small fix. If this is merged, I will need to add @AliKaanT as a co-author.
=> feat(app): `onError()` supports async

deno_dist/context.ts, deno_dist/hono-base.ts, deno_dist/router.ts, deno_dist/router/linear-router/router.ts, deno_dist/router/pattern-router/router.ts, deno_dist/router/reg-exp-router/router.ts, deno_dist/router/smart-router/router.ts, deno_dist/router/trie-router/router.ts, src/context.ts, src/hono-base.ts, src/hono.test.ts, src/router.ts, src/router/linear-router/router.ts, src/router/pattern-router/router.ts, src/router/reg-exp-router/router.ts, src/router/smart-router/router.test.ts, src/router/smart-router/router.ts, src/router/trie-router/router.ts
This PR introduces a `c.routerName()` function in `context.ts`. With this function, we can determine the name of the currently active router. This can be useful for debugging purposes.
```ts
//...
return c.text(c.routerName ?? 'N/A') // "SmartRouter + RegExpRouter"
})
```
=> feat(app): `app.routerName()`

deno_dist/middleware/basic-auth/index.ts, runtime_tests/deno/middleware.test.tsx, src/middleware/basic-auth/index.ts
This PR will fix #1121.
If an invalid value like `G9ubzphY29vbHByb2plY3Q=` is passed to `atob()`, it should throw a `DOMException`. However, the existing Basic Auth middleware cannot handle this, resulting in a "500 Internal Error" when an invalid string is sent.
The `jest-environment-miniflare` testing environment does not throw an exception from `atob()`. Therefore, this PR includes a test for this in `runtime_tests/deno/middleware.test.tsx`. The implementation in Deno is correct according to the spec.
Regarding the implementation, it uses `try`, even though we can check if the string is valid or invalid for Base64. This is because testing is difficult due to the above reasons, so I believe we need to keep the implementation as simple as possible.
=> fix(basic-auth): handle passing invalid value to `atob()`

deno_dist/middleware/cache/index.ts, deno_dist/middleware/cors/index.ts, deno_dist/middleware/etag/index.ts, deno_dist/middleware/powered-by/index.ts, src/middleware/cache/index.test.ts, src/middleware/cache/index.ts, src/middleware/cors/index.test.ts, src/middleware/cors/index.ts, src/middleware/etag/index.test.ts, src/middleware/etag/index.ts, src/middleware/powered-by/index.test.ts, src/middleware/powered-by/index.ts
Some middleware are using `response.headers.append()` when setting header values. With this method, it's possible to set duplicate values if the middleware is called twice.
```ts
app.use(
'/api/*',
cors({
origin: 'http://example.com',
})
)
app.use(
'/api/*',
cors({
origin: 'http://example.com',
})
)
```
In this PR, `response.headers.set()` is used to fix this issue.
=> fix(middleware): don't use `headers.append()`, use `headers.set()`

deno_dist/client/client.ts, deno_dist/client/index.ts, deno_dist/client/types.ts, src/client/client.ts, src/client/index.ts, src/client/types.ts, src/index.ts
Hi @yusukebe we have an issue with `hc` – we'd like to publish typed hono client from our Hono app as a library with zero dependencies, but since hono package.json has `"types": "dist/types/index.d.ts",` and this file doesn't contain client types we can't make it standalone – without `import from 'hono/dist...'` (see screenshots now/after change).
We have such entry point (client.ts) that we build separately from Hono app worker itself:
```
import { hc } from 'hono/client';
import { AppType } from '.';
export type { InferRequestType, InferResponseType } from 'hono/client';
export const client = hc<AppType>;
```
This is what we have now after build:
This is what we want to have with this changes:
So i exported few hono client types that we 
need for that. Changed RequestOptions => …
=> fix: Add missing client types and TypedResponse type

deno_dist/router/reg-exp-router/router.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts
=> fix(reg-exp-router): Register static paths first for duplicate checking.

deno_dist/hono-base.ts, deno_dist/router.ts, runtime_tests/lagon/index.ts, src/hono-base.ts, src/hono.test.ts, src/router.ts
This PR allows `app.get()` to handle the HEAD method, resolving issue #1130.
Currently, we have to define the process in `app.head()` if a HEAD method request comes in. However, the HEAD method is essentially "the response of GET without the body". Therefore, `HEAD /foo` will be handled by `app.get('/foo')` and return the response without the body. Users will not be able to define `app.head()`.
While this is a feature change, on the other hand, it simply corrects the handling of HEAD. Therefore, I believe it's acceptable to release it as a patch.
=> feat: handle HEAD method

deno_dist/router/pattern-router/router.ts, deno_dist/router/trie-router/node.ts, src/router/pattern-router/router.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts, src/router/trie-router/router.test.ts
This PR will fix the issue of capturing named parameters in TrieRouter and PatternRouter.
If we have the following routes:
```ts
app.get('/webhooks/github', async (c, next) => {
await next()
})
app.get('/webhooks/:service', (c) => {
return c.text(`service: ${c.req.param('service')}`)
})
```
Then, when accessing `GET /webhooks/github`, it currently can't handle the named parameter as `github`:
```
GET /webhooks/github => service: undefined
```
With this fix, it can capture `github`:
```
GET /webhooks/github => service: github
```
Resolves #1141
=> fix(tire-router/pattern-router): fixed the named capture issue

deno_dist/context.ts, deno_dist/hono-base.ts, deno_dist/router/reg-exp-router/router.ts, deno_dist/utils/url.ts, src/context.ts, src/hono-base.ts
It would reduce the number of conditional branches in `result?.handlers` and `result?.params` and shorten the code by a few lines.
Since this is not a particularly big improvement, it is safe to decide not to merge.
=> refactor: Tweaks variable names to reduce code.

deno_dist/utils/encode.ts, src/utils/encode.ts
In Node.js, spread operator for large-sized array occurs Range Error:
https://stackoverflow.com/questions/51249561/aws-lambda-rangeerror-maximum-call-stack-size-exceeded
https://github.com/nodejs/node/issues/16870
When I use somewhat large image this problem happens. To avoid this I re-wrote some codes. This doesn't make no change on behaiviors.
=> fix: avoid range-error

deno_dist/middleware/jsx/index.test.tsx, deno_dist/middleware/jsx/index.ts, src/middleware/jsx/index.test.tsx, src/middleware/jsx/index.ts
This PR introduces a React-like `style` attribute conversion in the JSX middleware. This could be referred to as "CSS in JS", but since the definition isn't clear, I'll call it "React-like" for now.
You can now write `style` attributes using an object:
```ts
const Tag = () => (
<h1
style={{
color: 'red',
fontSize: 'small',
}}
>
Hello
</h1>
)
```
This will be converted to:
```html
<h1 style="color:red;font-size:small">Hello</h1>
```
I believe this feature will be useful for creating styled web pages.
=> feat(jsx): React-like `style` conversion

deno_dist/utils/body.ts, src/utils/body.ts
The current logic for decoding application/x-www-form-urlencoded is overly restrictive and misses `Content-Type` headers with a character encoding set, i.e., `application/x-www-form-urlencoded; charset=UTF-8`.
This fix harmonizes the logic for handling `multipart/form-data` and `application/x-www-form-urlencoded` in the `parseBody` method of request objects.
=> fix: application/x-www-form-urlencoded decoding

deno_dist/utils/cookie.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
With #1194 fix, it doe's not allow `0` for the maxAge option. `0` can be set.
=> fix(utils/cookie): allow 0 to maxAge

deno_dist/middleware/etag/index.ts, src/middleware/etag/index.test.ts, src/middleware/etag/index.ts
* chore(etag): reduce global state in tests
* perf(etag): don't override ETags from upstream
* perf(etag): 304s include only necessary headers
* fix(etag): Support multi-value If-None-Match
* perf(etag): prefer Header.prototype.get
I recommend reviewing commit-by-commit as each commit has detailed rationale, including references to the relevant specs.
=> fix(etag): support multi-value If-None-Match

deno_dist/request.ts, src/request.ts
`Request.prototype.header` has two overloads:
1. with a string name, it returns that header value if present
2. with no argument, it returns all the headers as an object
Previously, the implementation built the whole object for (2) even when returning a single header. This was wasteful. This commit changes it to return the header by name if specified and only iterate over all the headers when the caller asks for the whole object.
=> perf(Request) optimize Request.prototype.header

deno_dist/client/types.ts, deno_dist/context.ts, deno_dist/hono-base.ts, deno_dist/mod.ts, deno_dist/request.ts, deno_dist/types.ts, src/client/types.ts, src/context.ts, src/hono-base.ts, src/mod.ts, src/request.ts, src/types.ts
Currently, if a user doesn't set `skipLibCheck` to `true` in `tsconfig.json`, it throws the error as shown below:
To fix it, in this PR, I've done the following:
1. Removed unnecessary properties that are not in `@cloudflare/workers-types` and `DOM` from `Request`.
2. Created `FetchEventLike` to ensure compatibility between environments where there is `FetchEvent` and where there isn't.
3. Added the properties in `Response` to `ClientResponse`.
This change allows it to pass `tsc` and simplifies `tsconfig.json`:
```ts
{
"compilerOptions": {
"target": "ESNext",
"module": "ESNext",
"moduleResolution": "node",
"strict": true,
"lib": [
"esnext"
],
"types": [
"@cloudflare/workers-types",
],
},
}
```
And if you don't want to use `@cloudflare/workers-types`:
```ts
{
"compilerOptions": {
"target": …
```
=> fix(types): allow not to set `skipLibCheck`

deno_dist/context.ts, src/client/client.test.ts, src/context.ts, src/types.test.ts, src/validator/validator.test.ts
The code below should not throw an error, but currently, it throws a "Type" error:
```ts
const route = app.get('/message', (c) => {
const ok = Math.random() > 0.5
if (ok) {
success: true,
message: 'Error!',
})
}
success: false,
message: 'Success!',
})
})
```
This is because 'success' is "`true`", not "`boolean`".
PR #1162 fixed this bug or something similar, but to maintain backward compatibility, the old pattern remains via overloading.
However, I think it's unnecessary to keep the old code and it's better to change the test code just for that. This is because, it's a bug if 'success' is not considered as "`boolean`", rather than maintaining the test code unchanged.
With this PR, the code works as expected.
=> fix(`jsonT`): remove overloads from `JSONTRespond`

package.json, runtime_tests/lagon/index.test.ts
This PR fixes the env test of Lagon by using the `-e` (or `--env`) flag of `lagon dev` to load the `.env.lagon` file.
=> fix(tests): Lagon env test

deno_dist/client/utils.ts, src/client/utils.test.ts, src/client/utils.ts
This PR fixes #1213. 
Fix Regex pattern in replaceUrlParam to replace regex path correctly.
=> Fix replaceUrlParam to ignore regexp in path

.github/workflows/ci.yml
While fixing this CI https://github.com/honojs/hono/pull/1210, I noticed that the latest Actions were not being used.
- actions/checkout@v2 ->actions/checkout@v3
- https://github.com/actions/checkout
- actions/setup-node@v2 ->actions/setup-node@v3
- https://github.com/actions/setup-node
=> chore(ci): Update Action

runtime_tests/lambda-edge/index.test.ts, src/adapter/lambda-edge/handler.ts, src/adapter/lambda-edge/index.ts
This PR allows the Lambda@Edge Adapter to pass the `callback` method, `context`, and `request` object to handlers as `env` variables. This means it can continue request processing if basic authentication has been verified.
```ts
import { Callback, CloudFrontRequest, handle } from 'hono/lambda-edge'
callback: Callback
request: CloudFrontRequest
}
const app = new Hono<{ Bindings: Bindings }>()
app.get(
'*',
basicAuth({
username: 'a',
password: 'b'
})
)
app.get('/index.html', async (c, next) => {
await next()
c.env.callback(null, c.env.request)
})
export const handler = handle(app)
```
There's a limitation issue where you cannot add headers such as a specific header value to an origin response. You can only pass through.
Fix #1225
=> feat(lambda-edge): pass the `context` and `callback` as env

runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/handler.ts
So far, the AWS Lambda adapter has used `atob` to convert a Base64-encoded request body to a binary. However, `atob` returns a string, and passing that to the `Request` constructor (at least on Node.js, which Lambda runs on) results in the binary string being encoded as UTF-8. This means that if the request body contains bytes which are not in the ASCII range, they are replaced with UTF-8 multi-byte encodings, which leads to `c.req.blob()`, `c.req.formData()`, etc. returning the wrong binary data!
This commit fixes the issue by replacing `atob(body)` with `Buffer.from(body, 'base64')`, which does not have that problem. The `Buffer` can be directly passed as body for `new Request()` because it implements the `Uint8Array` interface. While this makes the AWS Lambda adapter depend directly on …
=> fix(lambda): avoid UTF-8-encoding binary data

runtime_tests/lambda-edge/index.test.ts, runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/handler.ts, src/adapter/lambda-edge/handler.ts
This modification replaces the use of atob() and new Buffer() with Buffer.from(). As mentioned in [this article](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_class_buffer), I believe that new Buffer() should not be used.
=> fix: Safe modification of Buffer

deno_dist/preset/quick.ts, src/preset/quick.ts
As discussed in #1243, the LinearRouter can't handle all route patterns. Therefore, the `hono/quick` preset must use SmartRouter with LinearRouter and TrieRouter.
```ts
this.router = new SmartRouter({
routers: [new LinearRouter(), new TrieRouter()],
})
```
As a result of this PR, the bundle size will increase slightly:
```
// `hono/quick` before this PR
Total Upload: 13.14 KiB / gzip: 4.89 KiB
// `hono/quick` with this PR
Total Upload: 16.85 KiB / gzip: 6.36 KiB
```
=> fix(hono/quick): use SmartRouter

runtime_tests/lambda-edge/index.test.ts, src/adapter/lambda-edge/handler.ts
adding
1. Cloudflont response can now be handled.
```ts
callback: Callback
request: CloudFrontRequest
response: CloudFrontResponse
}
app.get('/callback/response', async (c, next) => {
await next()
c.env.callback(null, c.env.response)
})
```
2. Headers can now be added in OriginResponse. (I have a feeling we can do this in a much cooler way)
```ts
app.get('/header/add', async (c, next) => {
c.env.response.headers['Strict-Transport-Security'.toLowerCase()] = [{
key: 'Strict-Transport-Security',
value: 'max-age=63072000; includeSubdomains; preload'
}];
c.env.response.headers['X-Custom'.toLowerCase()] = [{
key: 'X-Custom',
value: 'Foo'
}];
await next()
c.env.callback(null, c.env.response)
})
```
3. refactoring. I cut out a lot of the internal header manipulation process.
=> feat(adaptor): Lambda@Edge supports response callbacks

deno_dist/utils/html.ts, src/utils/html.ts
Escape single quote (0x27) to limit execution capabilities under certain conditions.
Example, using JSX:
```tsx
const value = "alert('works')"
server.get("/*", c => c.html(<script>{value}</script>))
```
```tsx
const value = "alert('bar!')"
server.get("/*", c => {
return c.html(<Html><div onmouseover={value}>foo</div></Html>)
})
```
The condition under which it works are limited and should be avoided, but in reality its never as straightforward as in this simple example. Adjusted behavior mimics that of react-dom escaping single quotes.
Here without jsx. More dangerous, you can escape properties and inject script, because single quotes are valid attribute value delimiters and in this example are not enforced like they are in jsx:
```ts
const value = "' onmouseover='alert(`bar!`)' data-x='" …
```
=> fix escapeToBuffer vulnerability

deno_dist/adapter/deno/serve-static.ts, deno_dist/utils/filepath.ts, src/adapter/bun/serve-static.ts, src/adapter/cloudflare-workers/serve-static.ts, src/adapter/deno/serve-static.ts, src/utils/filepath.test.ts, src/utils/filepath.ts
Security fix for ServeStatic of Bun. Bun's Request object doesn't remove dot segments `..` in URL path. So, we have to remove it in our framework.
=> fix(utils/filepath): don't allow dot segments

deno_dist/utils/filepath.ts, src/utils/filepath.test.ts, src/utils/filepath.ts
It can allow `foo/bar....buzz.jpg` and `foo../bar.jpg` as filepath.
=> fix(utils/filepath): allow `..` in filename

deno_dist/types.ts, src/types.ts
Added a missing handler type: `app.get(path, handler)`.
Will be:
=> fix(types): add a missing handler type

deno_dist/middleware/cookie/index.ts, deno_dist/utils/cookie.ts, src/middleware/cookie/index.test.ts, src/middleware/cookie/index.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
Relates issue: https://github.com/honojs/hono/issues/1164
Related PR for website/docs: https://github.com/honojs/website/pull/77
Tried to be backwards compatible with the current `setCookie`/`getCookie` API, so decided to introduce new functions for this instead (similar to how express cookie-parser would do that).
Some things I wasn't sure about:
* If a cookie signature is not valid, what should happen with the cookie. At the moment it would return `undefined` in the `getSignedCookie` method. This might be misleading and hiding errors though, but throwing an error here instead might be too invasive. How would you handle this and at notify that the cookie was tampered with?
* Thinking about this a bit more, `getSignedCookie` should probably just work exactly like `getCookie` for multiple …
=> feat(middleware): Simple cookie signing functionality

deno_dist/request.ts, deno_dist/utils/body.ts, src/request.ts, src/utils/body.ts
This allows to write like the following:
```ts
app.post('/', async (c) => {
const { foo } = await c.req.parseBody<{ foo: string }>()
// foo is string
})
```
=> feat(parseBody): allow passing generics to `parseBody()`

deno_dist/adapter/netlify/handler.ts, deno_dist/adapter/netlify/mod.ts, src/adapter/netlify/handler.ts, src/adapter/netlify/mod.ts
This PR introduces Netfliy adapter. Hono runs on Netlify Edge Functions. Fix #1281
[Netlify Edge Functions](https://www.netlify.com/products/#netlify-edge-functions) is a Deno-based platform. So, you can use the Hono's Deno module on `deno.land/x`.
Usage:
```ts
// netlify/edge-functions/index.ts
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { prettyJSON } from 'https://deno.land/x/hono/middleware.ts'
import { handle } from 'https://deno.land/x/hono/adapter/netlify/mod.ts'
import type { Env } from 'https://deno.land/x/hono/adapter/netlify/mod.ts'
const app = new Hono<Env>()
app.get('/country', prettyJSON(), (c) =>
c.json({
'You are in': c.env.context.geo.country?.name
})
)
export default handle(app)
```
```toml
[[edge_functions]]
function = "index"
path = "/*"
```
You can …
=> feat(adapter): add Netlify adapter

src/context.test.ts, src/context.ts, src/middleware/pretty-json/index.ts
This PR refactors the Pretty JSON Middleware. It previously used the `c.pretty()` function, but this PR no longer relies on it. The middleware retrieves the JSON object with `c.res.json()` from the `Response`, stringifies it, and creates a new Response object.
Though this may seem to increase performance overhead, I've measured the benchmark, and the results are the same.
Additionally, this PR removes the `c.pretty()` method from the Context. This might seem like a breaking change, but since `c.pretty()` is not officially documented, and the users are very few, we can remove it right now.
=> refactor(json-pretty): don't use `c.pretty()`

deno_dist/hono-base.ts, src/hono-base.ts
To detect the class name of the instance, `res.contructor.name === 'Response'` is faster than `res instanceof Response` on Bun.
=> perf(hono-base): use `constructor.name` instead of `instanceof`

runtime_tests/deno/.vscode/settings.json, runtime_tests/lambda-edge/index.test.ts, runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/custom-context.ts, src/adapter/aws-lambda/handler.ts, src/adapter/aws-lambda/index.ts
fixed: https://github.com/honojs/hono/issues/1197
We have revised the approach by opting to retrieve it as c.env, rather than the method of the function we were discussing.
usage:
```typescript
import { handle, getLambdaContext } from 'hono/aws-lambda'
import type { ApiGatewayRequestContext } from 'hono/aws-lambda'
requestContext: ApiGatewayRequestContext 
}
app.get('/custom-context/apigw', (c) => {
const lambdaContext = c.env.requestContext
return c.json(lambdaContext)
})
```
=> fix(adaptor): Access to custom request context on AWS Lambda Adaptor 

deno_dist/utils/html.ts, src/utils/html.ts
Hello!
Sorry for the very minor changes.
On Sep 29, 2022, 
https://github.com/facebook/react/commit/97d75c9c8bcddb0daed1ed062101c7f5e9b825f4
It appears that the implementation detail portion of  React-DOM implementation details has been moved from `. /packages/react-dom` to `. /packages/react-dom-bindings`.
The link was thereby broken and has been corrected to the correct link.
=> docs: support change of escapeTextForBrowser path in react

deno_dist/client/client.ts, deno_dist/middleware/compress/index.ts, deno_dist/middleware/etag/index.ts, src/middleware/compress/index.ts
Hello. Please merge it if you like!
I could not remove ts-ignore because Nodejs globalThis does not have a CompressionStream type...
=> refactor(compress-middleware): resolve type assertion using const assertion

deno_dist/client/client.ts, deno_dist/middleware/etag/index.ts, src/client/client.ts
- Opened this PR after I was confused why conditional code was being ran in my API when using the RPC client. Realized that I had a query string that contained `&filter=undefined` that was then parsed into `{ filter: 'undefined'}`
- Added check for undefined value in query to prevent API receiving values of `undefined`.
=> Web query undefined check

package.json
This PR enables to export `hono/context`. With this feature, you can set the variables types for `c.get()`/`c.set()` using `ContextVariableMap`.
```ts
declare module 'hono/context' {
interface ContextVariableMap {
message: string
}
}
```
Fix #1319
=> feat(`package.json`): export `hono/context`

deno_dist/client/client.ts, deno_dist/middleware/etag/index.ts, deno_dist/utils/cookie.ts, src/middleware/cookie/index.test.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
Related issue: https://github.com/honojs/hono/issues/1337
Done the following:
=> fix(middleware): signed cookie misinterpretation of cookie values with dot

deno_dist/context.ts, deno_dist/types.ts, src/context.ts
Each method is typed by Interface and doesn't affect the type of function arguments as seen by the caller, but wouldn't it be healthier to modify it?
=> fix(types): corrected argument types for `Context` methods

deno_dist/middleware/compress/index.ts, src/middleware/compress/index.test.ts, src/middleware/compress/index.ts
It should be deleted. Fix https://github.com/honojs/node-server/issues/79
=> fix(compress): delete `content-length` header

deno_dist/client/types.ts, deno_dist/hono-base.ts, deno_dist/hono.ts, deno_dist/preset/quick.ts, deno_dist/preset/tiny.ts, deno_dist/types.ts, src/adapter/aws-lambda/handler.ts, src/client/types.ts, src/hono-base.ts, src/hono.ts, src/preset/quick.ts, src/preset/tiny.ts, src/types.test.ts, src/types.ts
This PR prevents infinite loops in type inference for routes. With this update, you can use many routes in RPC mode.
Current:
With this PR:
May fix #1360
=> fix(types): remove type-errors for routes

deno_dist/client/types.ts, deno_dist/types.ts, src/client/client.test.ts, src/client/types.ts, src/types.test.ts, src/types.ts
With this PR, `c.jsonT()` can now handle two or more distinct types:
```ts
const routes = app.get('/all', (c) => {
const data: Data = { success: true, data: {} }
if (!data.success) {
success: false,
message: 'Could not fetch data',
})
}
success: true,
data: data.data,
})
})
```
The returned types are as follows:
```ts
{
success: boolean;
message: string;
} & {
success: boolean;
data: any;
}
```
Fix #1377.
=> fix(context): different types using `jsonT()`

deno_dist/types.ts, src/types.test.ts, src/types.ts
Degraded by the PR #1379
Fixes #1383
=> fix(types): infer a response type for async handler

deno_dist/client/client.ts, deno_dist/client/types.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts
Hello,
This change is a proof of concept of a simple feature request. In our project, we are using Hono RPC and need to extract the URL of a Hono router endpoint for mocking in tests.
```
let fetchMock = getMiniflareFetchMock()
const { pathname, hostname } = hono.client.api.bar.$url()
fetchMock
.get(hostname)
.intercept({
method: "POST",
path: pathname,
})
.reply(200, {}, { headers: { "content-type": "application/json" } }),
```
This will mock the request to `http://localhost:8777/api/bar` by using the proposed `$url` method of the Hono client.
The `$url` method returns a URL representing the full url of the configured client request.
Do you think this is good to add to the client? If so, can you guide me in improving the type definitions to include `$url`?
And also to let me know if I …
=> Add $url method to hono client to extract an endpoint's url

.gitignore, deno_dist/middleware/secure-headers/index.ts, src/middleware/secure-headers/index.test.ts, src/middleware/secure-headers/index.ts
- fix CSP directive names (e.g. `defaultSrc ` should be `default-src`)
- add more CSP directives (e.g. `child-src`, `connect-src`, `form-action`, etc...)
- add new `Report-To` and `Reporting-Endpoints` headers in support of the `report-to` CSP directive
- pre-calculate CSP header once at setup instead of per request
- allow overriding header values (e.g. `xFrameOptions: true` or `xFrameOptions: 'DENY'`)
I'd be happy to update the [docs](https://hono.dev/middleware/builtin/secure-headers) as well once this PR is accepted.
=> improvements to secure headers middleware

deno_dist/request.ts, deno_dist/utils/body.ts, deno_dist/utils/buffer.ts, deno_dist/validator/validator.ts, src/request.ts, src/utils/body.test.ts, src/utils/body.ts, src/utils/buffer.test.ts, src/utils/buffer.ts, src/validator/validator.test.ts, src/validator/validator.ts
This PR enhances the handling of request bodies post-validation. After validating a JSON with the validator, you can now invoke `c.req.text()` to access the request body. Additionally, `c.req.text()` is now available `body` validation. We achieve this by caching the `arrayBuffer` in `c.req.bodyCache` and reusing it when calling `c.req.text()`.
Note, if you attempt to use `c.req.raw.text()` after validating the `json` or `body`, you will encounter an error. Instead, always use `c.req.text()` in this context.
Fix #1387
=> fix(validator): cache `arrayBuffer` to use after validation

deno_dist/hono-base.ts, src/client/client.test.ts, src/hono-base.ts
This PR will make the RPC-mode infers the path type correctly, with `app.basePath()` and `app.route()`:
```ts
const book = new Hono().post('/create', (c) => c.jsonT('test root'))
const api = new Hono().basePath('/v1').route('/book', book)
```
Will be handled as:
```ts
const res = await client.v1.book.create.$post()
// ...
```
=> fix(rpc): infer path with `route()` and `basePath()`

.github/workflows/ci.yml
For now, we'll attempt to mitigate the issue using a GitHub Token.
close #1398
=> chore(ci): Avoid denoify API rate limit

deno_dist/context.ts, deno_dist/types.ts, src/context.test.ts, src/context.ts, src/types.ts
Very simple, just adds a `status` prop to `TypedResponse` like mentioned in the issue.
Closes #1323.
=> feat(context): add `status` to `TypedResponse`

deno_dist/context.ts, deno_dist/mod.ts, src/context.test.ts, src/context.ts, src/hono.test.ts, src/index.ts, src/mod.ts
This PR introduces `c.render()` and `c.setRenderer()` functions. These functions enhance Hono's response handling, allowing for more flexible and modular response structures, especially useful for defining common parts of responses, like HTML layouts.
You can set a layout using `c.setRenderer()` within a custom middleware, as shown below:
```tsx
app.use('*', async (c, next) => {
c.setRenderer((content) => {
return c.html(
<html>
<body>
<p>{content}</p>
</body>
</html>
)
})
await next()
})
```
Subsequently, you can utilize `c.render()` to create responses within this layout:
```tsx
return c.render('Hello!')
})
```
The output of which will be:
```html
<html><body><p>Hello!</p></body></html>
```
Additionally, this feature offers the flexibility to customize arguments. …
=> feat(context): introduce `c.render()`

deno_dist/middleware/bearer-auth/index.ts, deno_dist/middleware/cors/index.ts, deno_dist/middleware/etag/index.ts, deno_dist/request.ts, src/compose.test.ts, src/hono.test.ts, src/middleware/bearer-auth/index.ts, src/middleware/cors/index.ts, src/middleware/etag/index.ts, src/request.ts
This PR makes these properties in `HonoRequest` deprecated:
```ts
get headers() {
return this.raw.headers
}
get body() {
return this.raw.body
}
get bodyUsed() {
return this.raw.bodyUsed
}
get integrity() {
return this.raw.integrity
}
get keepalive() {
return this.raw.keepalive
}
get referrer() {
return this.raw.referrer
}
get signal() {
return this.raw.signal
}
```
These will be obsolete in v4.
Close #1399
=> feat(req): deprecate `c.req.headers` (not `c.req.header`) and others

src/adapter/vercel/handler.test.ts, src/adapter/vercel/handler.ts
PR with implementation added to #1416.
=> feat(vercel): pass `RequestContext`

vitest.config.ts
I always create a directory called `sandbox` for my experiments.
=> test: ignore `sandbox` dir

package.json
After replacing Jest with Vitest, I noticed that types are not being checked. So, adding `tsc` before running `vitest`.
=> test: `tsc` before `vitest`

deno_dist/helper/cookie/index.ts, deno_dist/utils/cookie.ts, src/helper/cookie/index.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
- validate cookie names and values during parsing per rfc6265 to mitigate various security threats
- protect signed cookies against timing attacks (i.e. utilize `crypto.subtle.verify` instead of comparing strings)
- fix bug where unsigned cookie values that match the shape of signed values are not returned
- remove constraints on signed cookie values (e.g. signed values can contain period now)
- allow use of binary secret for signed cookies
- improved efficiency (e.g. remove duplicated logic / cache secret key when verifying multiple signed values)
=> cookie parsing improvements

deno_dist/context.ts, deno_dist/types.ts, src/context.ts, src/hono.test.ts, src/types.ts
This PR introduces two new features: the ability to set variables using `Middleware` generics and accessing them via `c.var`.
Currently, you can globally define variable types using generics for `Hono`.
```ts
type Client = 'foo client'
const app = new Hono<{
Variables: {
client: Client
}
}>()
```
Alternatively, you can specify them for a specific middleware using `ContextVariableMap`:
```ts
// JWT middleare
declare module '../../context' { // Or you can write `declare module 'hono'`
interface ContextVariableMap {
jwtPayload: any
}
}
```
The challenge here is that using `ContextVariableMap` makes it globally available. For instance, after importing the JWT middleware, you can access `jwtPayload` in any handler.
With this PR, you can confine middleware-defined variables to specific handlers …
=> feat(context): introduce `c.var`

deno_dist/jsx/index.test.tsx, deno_dist/jsx/index.ts, src/jsx/index.test.tsx, src/jsx/index.ts
This PR makes JSX supports exporting `FC`. You can use it for specifying types to the function component.
```tsx
import { FC } from 'hono/jsx'
const Layout: FC<{ title: string }> = (props) => {
return (
<html>
<head>
<title>{props.title}</title>
</head>
<body>{props.children}</body>
</html>
)
}
const Top = (
<Layout title='Home page'>
<h1>Hono</h1>
<p>Hono is great</p>
</Layout>
)
```
Fix #1419
=> feat(jsx): export `FC`

deno_dist/helper/factory/index.ts, package.json, src/helper/factory/index.test.ts, src/helper/factory/index.ts
This PR introduces `factory` helper. Now, this provides a `middleware` factory method to create a middleware handler.
```ts
const mw = (message: string) =>
middleware(async (c, next) => {
await next()
c.header('X-Message', message)
})
```
If define your middleware with `middleware`, the appropriate types will be added.
=> feat(helper): introduce `factory` helper

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts
Added optional Env?: E['Bindings'] | {} and executionCtx?: ExecutionContext parameters to the app.request method signature.
Modified app.request to pass these new parameters to the app.fetch method.
=> feat: extend app.request paramters

deno_dist/client/types.ts, deno_dist/hono-base.ts, src/client/client.test.ts, src/client/types.ts, src/hono-base.ts
- Defined HonoRequest using type Hono.prototype['request'].
- Updated ClientRequestOptions to optionally accept either the native fetch method or the HonoRequest method.
By specifying app.request as a custom fetch, users can now write tests through app.request more efficiently while still adhering to type safety.
=> feat: allow the type of app.request

deno_dist/helper/adapter/index.ts, src/context.test.ts, src/helper/adapter/index.ts
I've removed the logic that depends on c.runtime. I've also refactored the code to map behavior for each runtime to an object. If this is overkill, I can revert it back to the original code.
fixed: https://github.com/honojs/hono/issues/1452
=> refactor(helper):  Use getRuntimeKey() in env function

src/hono.test.ts, src/types.test.ts
before we used custom type to test types but now we choose to use ExpectTypeOf from vitest to test types
=> fix(types): Use ExpectTypeOf from vitest to test types

deno_dist/types.ts, src/hono.test.ts, src/types.ts
=> fix(types): support infering path types for multiple handlers

deno_dist/context.ts, deno_dist/utils/stream.ts, src/context.test.ts, src/context.ts, src/utils/stream.test.ts, src/utils/stream.ts
Hi, @yusukebe, @ geelen
I implemented `c.stream()` according to #914. I'd like to see @geelen added as a co-author as well, since I'm pretty much quoting the code from the issue.
This is the first time I've use a StreamAPI, so feel free to point out any mistakes.
@yusukebe asked me to give some examples of using `c.stream()`.
Below are some examples.
Enable rate limiting to protect or hide external APIs
<details>
<summary>Code</summary>
```ts
import OpenAI from 'openai'
const app = new Hono<{
Bindings: {
OPENAI_API_KEY: string
}
}>()
const PROMPT = (message: string) => [
{
role: 'system' as const,
content:
'You are an Web developer. If you receive a question about Web-related technologies, you can answer it.',
},
{
role: 'user' as const,
content: message,
},
] …
```
=> feat: Add `c.stream()`

deno_dist/client/types.ts, src/client/client.test.ts, src/client/types.ts
The changes are aimed at improving the type safety when dealing with client requests that include headers. 
By enforcing the validation at the type level, we can catch potential issues earlier in the development process, reducing the risk of runtime errors.
=> feat: Refactor ClientRequest Type for header validation

deno_dist/middleware/jwt/index.ts, src/middleware/jwt/index.ts
Expose the `sign`, `verify` and `decode` functions under `hono/jwt`
Usage: 
```js
import { decode, sign, verify } from 'hono/jwt'
```
Closes #1443
=> feat: expose the Jwt fucntions under the 'hono/jwt' path

deno_dist/helper/testing/index.ts, package.json, src/helper/testing/index.test.ts, src/helper/testing/index.ts
By using the hc test client, we can easily write tests. This utility enables efficient integration and unit testing by allowing manipulation of the Hono application object rather than making actual HTTP requests.
```ts
it('test', async() => {
const app = new Hono().get('/search', (c) => c.jsonT({ hello: 'world' }))
const res = await hc(app).search.$get()
expect(await res.json()).toEqual({ hello: 'world' })
})
```
=> feat: add Hono test client (RPC)

deno_dist/helper/cookie/index.ts, src/helper/cookie/index.test.ts, src/helper/cookie/index.ts
TypeError: Cannot read properties of undefined (reading 'split')
=> fix: error to retrieve cookie

deno_dist/context.ts, deno_dist/utils/stream.ts, src/context.test.ts, src/context.ts, src/utils/stream.test.ts, src/utils/stream.ts
This PR includes these fixes:
* Make the response headers of `c.streamText()` correct.
* Make `text/plain; charset=UTF-8` as the variable to reduce bundle size.
* Handling errors and ignoring them. If there is an error throw, the process may stop. And also, tracing an error may get in the way. So, I decided to do nothing in the catch.
Errors are as follows. Occurs when accessing while it is streaming.
=> fix(context): fix `c.stream()` and `c.streamText()` matters

deno_dist/utils/jwt/types.ts, src/utils/jwt/types.ts
The error message is a duplicate of line 14 `JwtTokenInvalid` and is no descriptive to the actual cause of the issue.
Updated the error message to align with the name of the error
- N/A: Add test
=> fix(jwt): incorrect error message

deno_dist/types.ts, src/hono.test.ts, src/types.ts
Fix the issue in this comment: https://github.com/honojs/hono/issues/1513#issuecomment-1738890316
=> fix(types): fix inferring path strings for an optional parameter with regexp

deno_dist/jsx/index.test.tsx, deno_dist/jsx/index.ts, src/jsx/index.test.tsx, src/jsx/index.ts
=> fix(jsx): render a child or odd children with `Fragment` correctly

deno_dist/request.ts, deno_dist/utils/body.ts, src/request.ts, src/utils/body.test.ts, src/utils/body.ts
Hi @yusukebe 
This is an implemention of the suggesion in #1018
As you mention, this changes have backward compatible.
=> feat: `parseBody()` for multi values' field

deno_dist/context.ts, deno_dist/types.ts, src/adapter/vercel/handler.ts, src/context.ts, src/types.ts, tsconfig.json
=> fix(types): don't use webworker types

deno_dist/router/reg-exp-router/node.ts, src/router/reg-exp-router/node.ts, src/router/reg-exp-router/router.test.ts
* `(a|b)` => Automatically converted to non-capturing group and no longer an error in RegExpRouter. 🆕 
* `(?:a|b)` => If you already explicitly use non-capturing groups, it works without error. (Backward compatible)
* `prefix(a|b)` => Throw `UnsupportedPathError`. 🆕
=> feat(reg-exp-router): Improve capture group support.

deno_dist/validator/validator.ts, src/validator/validator.test.ts, src/validator/validator.ts
When using `validator('form', ...)` hono is returning a 500 status when receiving a POST request with a JSON in request body, instead of a bad request 400, .
This is happenning due to a unhandled error in an
underlying library (@miniflare).
https://github.com/cloudflare/miniflare/pull/711
The code changes in this PR are responsible to prepare the code to handle possible TypeError that can be thrown in the future, by the lib doing the FormData parsing, as per, https://fetch.spec.whatwg.org/#dom-body-formdata.
This PR should wait for bugfix on @miniflare.
=> fix: return status 500 when using validator 'form'

deno_dist/hono-base.ts, src/hono-base.ts
Since #1311, it uses `res.constructor.name === 'Response'` instead of `res instanceof Response`. However, on Node.js, this change results in a significant performance decrease. Therefore, it should be rolled back.
=> perf(hono-base): use `instanceOf`

src/helper/streaming/index.test.ts
=> test: fix the sleep time for SSE

deno_dist/hono-base.ts, deno_dist/hono.ts, deno_dist/preset/quick.ts, deno_dist/preset/tiny.ts, src/hono-base.ts, src/hono.test.ts, src/hono.ts, src/preset/quick.ts, src/preset/tiny.ts
* Create `basePath` option for the constructor of `Hono`.
* Deprecate `app.basePath()`.
You can specify the base-path like the following:
```ts
const app = new Hono({ basePath: '/api' })
```
Resolves #1531
=> feat(app): `basePath` option for the constructor, deprecate `app.basePath()`

deno_dist/hono-base.ts, deno_dist/hono.ts, deno_dist/preset/quick.ts, deno_dist/preset/tiny.ts, src/hono-base.ts, src/hono.test.ts, src/hono.ts, src/preset/quick.ts, src/preset/tiny.ts
Fixes #1584 
This reverts commit 8b6bd46e6699d6ad80eced222b8cd52c9a878692.
=> Revert "feat(app): `basePath` option for the constructor, deprecate `app.basePath()` (#1560)"

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts
Fixes #1590
It may look like a dirty hack at first glance, but if you look closely, you will see it is not a problem.
I have also considered the following approaches.
* https://github.com/usualoma/hono/tree/fix-nested-onerror-params-by-getParams
* https://github.com/usualoma/hono/tree/fix-nested-onerror-params-by-undefined
However, they all increase the code and complexity of types, so this PR approach is better.
=> fix: `c.req.params()` in nested app with custom error handler.

deno_dist/context.ts, deno_dist/types.ts, src/adapter/vercel/handler.ts, src/context.ts, src/types.ts
To detect whether it is a `FetchEvent` or not, I've used this method in this PR instead of `instanceof`:
```ts
this._exCtx && 'respondWith' in this._exCtx
```
Fixes #1423
=> fix(context): change `FetchEvent` detection way

.github/workflows/ci.yml
Starting from October 24, NodeJS V20 will become the LTS version. I believe we should also support this in our CI. For now, I've only added Node, but if there is a need to include other runtimes, I am more than happy to accommodate that as well.
=> chore(ci): update node v20

package.json
**How to reproduce**
```ts
import { Hono } from 'hono';
const group = new Hono().get('/', (c) => c.text('ok'));
const app = new Hono().use().route('/group', group);
export default app;
```
The issue only appears if `app` is exported (or `group` is imported).
**Error observed**
```
The inferred type of 'app' cannot be named without a reference to '../../../node_modules/hono/dist/types/hono-base'. This is likely not portable. A type annotation is necessary.ts(2742)
```
**Solution**
Upgrading to `v3.8.2` partially addressed the issue (https://github.com/honojs/hono/pull/1604/files), but I found it necessary to make `hono/types` publicly accessible also.
=> Fix: combine fluent interface with route grouping

runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/handler.ts
The `getCookie`  and `setCookie` helpers don't work properly when handling multiple cookies with aws-lambda adapter because of different versions of request and response payload in `API Gateway Proxy Event`.
I created two functions `getCookies` and `setCookies` in src/adapter/aws-lambda/handler.ts file to get and set cookies payload/header corresponding to the version of the `API Gateway Proxy Event`. Additionally, two tests for this implementation are added in the lambda runtime test file.
=> Aws lambda cookies fix

deno_dist/jsx/index.ts, deno_dist/jsx/intrinsic-elements.ts, src/jsx/index.ts, src/jsx/intrinsic-elements.ts
This PR introduces type definitions for JSX elements to enhance the developer experience.
There are several ways to add types to JSX elements. With this PR, the approach taken is as follows:
* Define types manually, without referring to the DOM lib.
* Main tags are ported from React's definitions: https://www.npmjs.com/package/@types/react?activeTab=code
* Removed some elements and attributes such as ARIA's to keep it minimum.
* Renamed some properties for HTML compatibility, e.g., `readOnly` to `readonly`.
* For compatibility with unknown elements and attributes, it allows any elements and attributes.
In this PR, any elements and any attributes are allowed. This is defined as follows:
Attributes:
```ts
type AnyAttributes = { [attributeName: string]: any }
//...
interface HTMLAttributes …
```
=> feat: types for JSX elements

deno_dist/middleware/jsx-renderer/index.ts, src/middleware/jsx-renderer/index.test.tsx, src/middleware/jsx-renderer/index.ts
Currently, when using JSX Renderer, we can't easily add a `DOCTYPE`. This PR introduces a `docType` option for the JSX Renderer to add a `DOCTYPE`.
```tsx
app.use(
'*',
jsxRenderer(
({ children }) => {
return (
<html>
<body>{children}</body>
</html>
)
},
{ docType: true }
)
)
```
If you want to customize the `DOCTYPE`, you can pass the string:
```tsx
app.use(
'*',
jsxRenderer(
({ children }) => {
return (
<html>
<body>{children}</body>
</html>
)
},
{
docType:
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">',
}
)
)
```
=> feat(jsx-renderer): `docType` option

package.json
=> fix(`package.json`): export types correctly

.github/workflows/ci.yml
made the following changes to the CI:
- Updated to the latest version as Action's version v4 is now available.
https://github.com/actions/setup-node/releases/tag/v4.0.0
- Fixed the issue where multiple versions of Node.js could not be selected. Apologies!
=> chore(ci): maintenance Node.js

deno_dist/utils/filepath.ts, src/utils/filepath.test.ts, src/utils/filepath.ts
This PR makes `filepath` util supports Windows and prevents the path traversal on Windows.
=> fix(utils/filepath): filepath supports Windows

deno_dist/jsx/streaming.ts, src/jsx/streaming.test.tsx, src/jsx/streaming.ts
=> fix(jsx/streaming): Fixed a bug that caused async components to be evaluated multiple times inside Suspense.

deno_dist/helper/streaming/index.ts, runtime_tests/lambda/index.test.ts, src/helper/streaming/index.ts
I fixed a bug where the Stream SSE Helper would not close, preventing the session from ending. Additionally, I've implemented error handling for the pipe.
Actually, it was known that the AWS Lambda Adaptor did not terminate during testing, so I've added tests to cover that :)
=> fix(helper): Stream SSE Helper Non-Closure

.github/workflows/ci.yml, deno_dist/jsx/jsx-dev-runtime.ts, deno_dist/jsx/jsx-runtime.ts, deno_dist/jsx/streaming.ts, package.json, runtime_tests/deno-jsx/deno.precompile.json, runtime_tests/deno-jsx/deno.react-jsx.json, runtime_tests/deno-jsx/jsx.test.tsx, src/jsx/jsx-dev-runtime.ts, src/jsx/jsx-runtime.ts, src/jsx/streaming.test.tsx, src/jsx/streaming.ts
Merging this PR will support the JSX transforms included in Deno's 1.38
https://deno.com/blog/v1.38#fastest-jsx-transform
The async component and `renderToReadableStream()` are also working.
The following benchmarks were used for comparison
```ts
import { bench, run } from 'https://esm.sh/mitata'
const title = '<Hello>'
const name = '<Deno>'
const Component = (props: { name: string }) => (
<>
Hello <b>{props.name}!</b>
</>
)
const getHtml = () => (
<div>
<a title={title}>
<Component name={name} />
</a>
</div>
)
if (getHtml().toString() !== '<div><a title="&lt;Hello&gt;">Hello <b>&lt;Deno&gt;!</b></a></div>') {
throw new Error('failed')
}
bench('toString()', () => {
for (let i = 0; i < 10000; i++) {
getHtml().toString()
}
})
await run()
```
deno.json
```json
{
"compilerOptions": {
"jsx": …
```
=> feat(jsx): Define jsxTemplate/jsxAttr/jsxEscape for "@jsx precompile" of Deno 1.38

runtime_tests/lambda/index.test.ts, src/adapter/aws-lambda/awslambda.d.ts, src/adapter/aws-lambda/handler.ts
fixed: https://github.com/honojs/hono/issues/1672
I'd like to share that we have completed actual device verification with AWS Lambda for the magic method awslambda.HttpResponseStream.from, which adds metadata (statusCode, Headers) to the responseStream.
=> fix(Adaptor): Lambda Response Streaming With Content Type 

deno_dist/helper/adapter/index.ts, src/helper/adapter/index.ts
Right now it is only possible to set a string as environment value. But in my case I'm using [Cloudflare Pages Functions](https://developers.cloudflare.com/pages/platform/functions/) which allows me to [bind](https://developers.cloudflare.com/pages/platform/functions/bindings/) different kinds of Cloudflare resources.
For example I want to bind my Pages Function (which is a [Cloudflare Worker](https://developers.cloudflare.com/workers/) in the end) to [R2](https://developers.cloudflare.com/r2/). Therefore I have to use `R2Bucket` as type:
```ts
import { env } from "hono/adapter";
type Environment = {
readonly MY_BUCKET: R2Bucket;
}
const { MY_BUCKET } = env<Environment>(context, "workerd");
```
With the current implementation I'm just able to assign `string` to `MY_BUCKET` (compiler error …
=> fix(types): allow arbitrary values as environment values

deno_dist/hono-base.ts, src/hono-base.ts
Using `console.error(err)` is better than `console.trace(err)` to understand what is happening.
=> feat(app): use `console.error()` for default `errorHandler`

deno_dist/compose.ts, deno_dist/hono-base.ts, src/compose.ts, src/hono-base.ts
With this PR, I've refactored `compose.ts` to simplify it and improve performance.
We might consider adding changes to enhance performance as mentioned in [this comment](https://github.com/honojs/hono/pull/1685#issuecomment-1809240099).
However, let's first focus on merging this refactoring. Although it's a `perf` change, it could be related to a new feature, so we should merge it into the `next` branch.
=> perf(compose): simplify

src/adapter/aws-lambda/handler.ts, src/adapter/aws-lambda/index.ts
Adds an export for `APIGatewayProxyResult` so that it can be referenced from a handler:
```ts
export const handler: APIGatewayProxyResult = handle(app);
```
Without it exposed, TS complains:
```
Exported variable 'handler' has or is using name 'APIGatewayProxyResult' from external module "node_modules/.pnpm/hono@3.10.1/node_modules/hono/dist/types/adapter/aws-lambda/handler" but cannot be named.
```
=> Export APIGatewayProxyResult from aws-lambda

deno_dist/compose.ts, src/compose.test.ts, src/compose.ts
=> fix(compose): allow `onError()` handler to be async

jest.config.js
Now that we are going to use Vitest, we can remove it.
=> chore: remove `jest.config.js`

deno_dist/jsx/index.ts, src/jsx/index.test.tsx, src/jsx/index.ts
Fix a double escaping problem when an escaped string is passed as an HTML attribute value.
=> fix(jsx): Write the raw value if the value is a HtmlEscaped string

deno_dist/types.ts, src/hono.test.ts, src/types.test.ts, src/types.ts
Handle until 10 handlers on `app.method([path], ...handlers)` by simple adding more overloads.
This is not optimal by far. I'm compromised to find a better and beautiful solution, but until then I think this will cover more use cases, like I'm personally facing now.
=> feat(types): Support types until 10 handlers

deno_dist/helper/factory/index.ts, deno_dist/types.ts, src/helper/factory/index.test.ts, src/helper/factory/index.ts, src/types.ts
I made #1722 a draft and create this new PR instead it.
This PR introduce `Factory` class, `createFactory()`, and `createHandlers()` in `Factory` exported from `hono/factory`.
```ts
import { createFactory } from 'hono/factory'
import { logger } from 'hono/logger'
const factory = createFactory<Env>()
const middleware = factory.createMiddleware(async (c, next) => {
c.set('foo', 'bar')
await next()
})
const handlers = factory.createHandlers(logger(), middleware, (c) => {
return c.json(c.var.foo)
})
app.get('/api', ...handlers)
```
This is useful for defining handlers outside of `app.get('/api', ...)`. Using this approach, you can structure your application in a Ruby on Rails-like Controller pattern, as discussed in #1072.
A key feature is its ability to correctly infer types.
Ideally, you …
=> feat: introduce `createFactory()` and `createHandlers()`

deno_dist/compose.ts, deno_dist/context.ts, deno_dist/hono-base.ts, deno_dist/types.ts, src/client/client.test.ts, src/compose.ts, src/context.test.ts, src/context.ts, src/helper/testing/index.test.ts, src/hono-base.ts, src/hono.test.ts, src/types.test.ts, src/types.ts, src/validator/validator.test.ts
I am unfamiliar with PRC mode, so I apologize if I am off base.
The idea of the RPC mode is a great one, but having to call jsonT() instead of json() is expensive to learn. Also, hono-base.ts and context.ts have additional processing for this purpose, so if you could eliminate that, that would be great.
It is an evil hack that is declared to return a TypedResponse but only returns a Response, but if this works well, it is better this way.
In my small demo, I had no problems with this change.
=> Ensure that calls to `c.json()` have a type equivalent to `c.jsonT()`

deno_dist/jsx/components.ts, src/jsx/components.ts
Make `ErrorBoundary` as `experimental` as same as `Suspense`.
=> feat(jsx): mark `ErrorBoundary` as `experimental`

deno_dist/helper/dev/index.ts, deno_dist/hono-base.ts, src/helper/dev/index.ts, src/hono-base.ts
- Updated `showRoutes` deprecated doc comments to provide the correct import path (`/dev` instead of `/helper`)
- Added `TEnv` type argument to both `showRoutes` & `inspectRoutes` helpers & passed to the first (`hono: Hono`) parameter. 
- This fixes a type error where if you pass in a Hono instance with a custom environment type these 2 functions will complain as it does not match the default / base `Hono` type(s).
=> fix(types): Added `E` env type argument to `showRoutes` & `inspectRoutes` `hono` parameter

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts
Fixes https://github.com/honojs/middleware/issues/290
To maintain compatibility with Zod OpenAPI Hono, change the `basePath` property to `private _basePath` instead of using `#basePath`. Using `#basePath` causes issues in Zod OpenAPI Hono, as seen in https://github.com/honojs/middleware/issues/290.
=> fix(base): name `private _basePath` instead of `#basePath`

src/adapter/aws-lambda/handler.test.ts, src/adapter/aws-lambda/handler.ts, src/adapter/lambda-edge/handler.test.ts, src/adapter/lambda-edge/handler.ts
=> fix: add missing tail to svg regex

deno_dist/context.ts, src/context.test.ts, src/context.ts
In `context.ts`, I fixed a bug where header values were not set correctly if `#this.headers` was set and the `arg` was of type `ResponseInit`.
Related to #1807
=> fix(context): set headers values correctly

README.md, deno_dist/README.md
Hono have grown.
I checked the size of `hono/tiny` with following the command.
```sh
npx esbuild --outdir=dist --bundle --minify ./src/preset/tiny.ts
```
```sh
npx esbuild --outdir=dist --bundle --minify ./src/preset/tiny.ts
dist\tiny.js  13.9kb
⚡ Done in 12ms
```
Based on the above result, I update the size in readme.
Minimal app may exceed 14kb.
=> docs(readme): update `hono/tiny` size

deno_dist/context.ts, deno_dist/utils/types.ts, src/client/client.test.ts, src/context.ts, src/utils/types.ts
=> fix(context): `c.json()` allows object and returns JSONParsed<T>

deno_dist/helper/html/index.ts, deno_dist/utils/html.ts, src/helper/html/index.test.ts, src/helper/html/index.ts, src/utils/html.ts
This PR allows `Promise<string | HtmlEscapedString>` to be passed to the `html` tagFunction variables as well.
Fixes: #1812
=> feat(helper/html): Support Promise<string | HtmlEscapedString> in html tagged template literals

package.json, src/router/trie-router/node.test.ts, tsconfig.json, yarn.lock
Sorry, I broke the reviewed working branch. Here are the fixes.
- vitest to v1.0.4
- @vitest/coverage-v8 to v1.0.4
- Commented.
- ref: https://github.com/honojs/hono/pull/1817
=> chore: upgrading vitest to v1.0

package.json, tsconfig.build.json, vitest.config.ts, yarn.lock
I have made these settings. 
~~1. Handling Vitest's type checking. This makes tsc --no-emit unnecessary.
https://vitest.dev/config/#typecheck~~
2. I don't think the Vitest configuration file is needed in tsconfig.build. I have listed similar items that I think are unnecessary, but please point out if I am mistaken.
3.  Update from Vitest 1.04 to 1.10.
=> Refactor(test): update vitest settings

deno_dist/middleware.ts, deno_dist/middleware/csrf/index.ts, package.json, src/middleware.ts, src/middleware/csrf/index.test.ts, src/middleware/csrf/index.ts
This middleware prevents CSRF attacks by checking request headers.
When you need to protect against CSRF attacks (i.e. submitting with a form element) all you have to do is add the following one line
```ts
app.use('*', csrf())
```
This works well enough in most cases.
For "old browsers that do not send Origin headers" or "environments that use reverse proxies and drop Origin headers," it may not be possible to submit with false positives. If you want to support such environments, this middleware is not sufficient, and it is better to use CSRF tokens.
By default, the Origin header is compared to the requested URL. Generally, this works well enough, but sometimes an explicit specification is necessary for a variety of reasons. It is advisable to refer to the OWASP cheat sheet for the …
=> feat(middleware/csrf): Introduce CSRF middleware

deno_dist/helper/dev/index.ts, deno_dist/hono-base.ts, src/helper/dev/index.test.ts, src/helper/dev/index.ts, src/hono-base.ts
This PR introduces `getRouterName()` function in `hono/dev` helper and deprecates `app.routerName()`.
I think `app.routerName()` is not used by many users, and if users use it, the purpose is debugging in most cases. So, we can place it in `hono/dev` is better.
Usage:
```ts
import { getRouterName } from 'hono/dev'
//...
console.log(getRouterName(app))
```
=> feat(dev): add `getRouterName()`

deno_dist/adapter/deno/serve-static.ts, runtime_tests/bun/index.test.tsx, runtime_tests/deno/deps.ts, runtime_tests/deno/middleware.test.tsx, src/adapter/bun/serve-static.ts, src/adapter/cloudflare-workers/serve-static.test.ts, src/adapter/cloudflare-workers/serve-static.ts, src/adapter/deno/serve-static.ts
=> feat: Add `onNotFound` handler in adapters' `serveStatic`

deno_dist/helper/dev/index.ts, deno_dist/hono-base.ts, src/helper/dev/index.test.ts, src/helper/dev/index.ts, src/hono-base.ts
Fixes #1868
How about this solution?
I suppose we could add the information "added from sub pp" in inspectRoutes. But I didn't go that far at this point, because I think it's enough to fix the problem in #1868.
=> fix(dev): preserve original handler in [composedHandler].

deno_dist/utils/types.ts, src/utils/types.test.ts, src/utils/types.ts
=> fix(types): `JSONParsed` supports interface and `Date` etc.

deno_dist/hono-base.ts, src/hono-base.ts
This is deprecated since the PR #1841.
=> feat(hono-base): add deprecated flag to `app.routerName`

deno_dist/adapter/deno/serve-static.ts, runtime_tests/bun/index.test.tsx, runtime_tests/deno/middleware.test.tsx, src/adapter/bun/serve-static.ts, src/adapter/cloudflare-workers/serve-static.test.ts, src/adapter/cloudflare-workers/serve-static.ts, src/adapter/cloudflare-workers/server-static-module.ts, src/adapter/deno/serve-static.ts
=> feat: pass context to onNotFound callback in serveStatic

deno_dist/helper/dev/index.ts, src/helper/dev/index.test.ts, src/helper/dev/index.ts
This PR introduces the `colorize` option for `showRoutes()` in `hono/dev`.
You can disable colorizing the output if you set the option as `false`:
```ts
showRoutes(app, {
colorize: false,
})
```
Resolves #1881, related to #1883.
=> feat(dev): add `colorize` option for `showRoutes()`

deno_dist/context.ts, deno_dist/helper/streaming/sse.ts, deno_dist/helper/streaming/stream.ts, deno_dist/utils/stream.ts, src/context.test.ts, src/context.ts, src/helper/streaming/sse.ts, src/helper/streaming/stream.ts, src/utils/stream.test.ts, src/utils/stream.ts
=> feat: implement stream.onAbort

deno_dist/client/client.ts, deno_dist/client/types.ts, src/client/client.test.ts, src/client/client.ts, src/client/types.ts
This PR introduces an option to the `$url()` function in Hono's client.
You can write the param values as an option of `$url()` like the following:
```ts
const route = app.get('/api/:id/bar', (c) => c.json({ foo: 'bar' }))
const client = hc<typeof route>('http://localhost:8787/')
const url = client.api[':id'].bar.$url({
param: {
id: '123',
},
})
```
Inferring types are available:
https://github.com/honojs/hono/assets/10682/eaff7c97-6429-41ae-b2ca-8813387a85af
Resolves #1870
=> feat(client): add `param` option to `$url()`

deno_dist/validator/validator.ts, src/validator/validator.test.ts, src/validator/validator.ts
=> fix(validator): exclude Response type for returned values from `c.req.valid()`

deno_dist/client/client.ts, src/client/client.test.ts, src/client/client.ts
Right now if you await the RPC client, it produces undefined behavior and can hang the application. This also occurs if the client is returned from an async function that is then awaited. This adds a quick fix to detect that edge case, and handle it properly.
=> fix(client): Fix issue awaiting RPC client

deno_dist/hono-base.ts, deno_dist/types.ts, src/hono-base.ts, src/hono.test.ts, src/types.ts
Fixes #1901
This PR enables `app.on` to handle multiple paths.
Usage:
```ts
app.on('GET', ['/hello', '/ja/hello', '/en/hello'], (c) => {
return c.text('Hello!')
})
```
It does not support multiple paths with `app.get()`, etc.
=> feat(hono-base): `app.on` supports multiple paths

deno_dist/helper/css/index.ts, src/helper/css/index.test.tsx, src/helper/css/index.ts
If you wrap the whole thing (not just part of it) in a pseudo-selector called `:-hono-global`. The output of the  `css` is not wrapped in the generated class name, but is interpreted as a top-level specification.
```ts
css`
:-hono-global {
body {
font-size: 10px;
}
}
`
```
You can extend it by embedding the class name by writing it in the following syntax `${baseClass} {`
```ts
const baseClass = css`display: flex`
const extendedByContent = css`
${baseClass}
flex-direction: column;
` // This is already possible
const extendedByClassName = css`
${baseClass} {
flex-direction: column;
p {
color: red;
}
}
` // This is made possible by this PR
```
The following can be written to place the media query at the top level so that it can be interpreted by older browsers that do not support nesting. …
=> feat(css): Introduce pseudo global selector and class name based extend syntax

deno_dist/middleware/cache/index.ts, src/middleware/cache/index.test.ts, src/middleware/cache/index.ts
Fix https://github.com/honojs/hono/issues/1915
1. Allow nested cache middlewares to compose a final Cache-Control header
2. Allow handlers to also add cache control directives
This slightly changes the implementation from raw string handling to acknowledge the existance of individual directives, this way we can avoid duplicating directives that were overriden in inner middleware/handlers.
=> fix(cache): Allow composing cache control directives

deno_dist/adapter/netlify/handler.ts, src/adapter/netlify/handler.ts
There is an issue when using the Netlify Adapter via `deno.land/x`. https://github.com/honojs/hono/blob/8de60599aafca908b6214f047571415c6e17f8ea/deno_dist/adapter/netlify/handler.ts#L4 This line references `../../index.ts` but that doesn't exist in the root of `deno_dist/` so we much use `../../hono.ts` or `../../mod.ts`. Please let me know what you prefer. Thank you!
Photo of error:
=> fix(netlify): change path in `deno_dist/adapter/netlify`

deno_dist/router/linear-router/router.ts, deno_dist/router/reg-exp-router/router.ts, src/router/linear-router/router.test.ts, src/router/linear-router/router.ts, src/router/pattern-router/router.test.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts, src/router/trie-router/router.test.ts
=> fix(routers): RegExpRouter and LinearRouter support multiple optional params

runtime_tests/lambda-edge/index.test.ts, src/adapter/lambda-edge/handler.ts
In the current implementation, when lambda@Edge is launched with a CloudFront origin request, CloudFront returns an error when processing binary data.
Probably because the body is base64 but there is no bodyEncoding property.
When returning a base64 body, the bodyEncoding property should now include base64.
=> Fix/response for lambda@edge adapter

deno_dist/adapter/deno/ssg.ts, deno_dist/helper/ssg/index.ts, src/adapter/bun/ssg.ts, src/adapter/deno/ssg.ts, src/helper/ssg/index.ts
fixes: https://github.com/honojs/hono/issues/1961
All exported APIs have been described. Please let me know if this standard is excessive.
=> chore(helper): Add experimental flag the SSG features

deno_dist/helper/ssg/index.ts, deno_dist/helper/ssg/utils.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts, src/helper/ssg/utils.test.ts, src/helper/ssg/utils.ts
You can close #1964 If you merge this PR.
=> refactor(ssg): SSG works without `node:path`

deno_dist/helper/factory/index.ts, src/helper/factory/index.ts
=> feat(factory): remove `deprecated` from `Factory` and `createHandlers`

deno_dist/helper/ssg/utils.ts, src/helper/ssg/utils.test.ts, src/helper/ssg/utils.ts
=> fix(ssg): fix path parser bug & refactor code

src/adapter/lambda-edge/handler.ts
The origin field in the request object in the Lambda@Edge adapter is assumed to be only a custom origin.
Referring to 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html ,
I have defined a TypeScript type that is also compatible with S3 origins.
=> feat: Add Type to request for Lambda@Edge adapter to support S3 origin

src/adapter/cloudflare-workers/serve-static-module.ts, src/adapter/cloudflare-workers/serve-static.test.ts, src/adapter/cloudflare-workers/serve-static.ts
Fixes #1127 #1093
This is the same as #1804 by @Code-Hex .
With this PR, if you use the Cloudflare Workers adapter's `serve-static`, you should specify the `manifest` option.
```ts
import manifest from '__STATIC_CONTENT_MANIFEST'
// ...
app.use('/static/*', serveStatic({ root: './assets', manifest }))
```
This avoids a compile error if there is an import of "`__STATIC_CONTENT_MANIFEST`" in Hono core's code.
This is a BREAKING CHANGE, so we need to write the migration instructions in the migration guide.
=> feat!(cloudflare-workers): make `manifest` required

deno_dist/types.ts, deno_dist/utils/types.ts, src/types.test.ts, src/types.ts, src/utils/types.ts
=> fix(types): correct `c.get()` inference

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.ts
When introducing `ssgParams()`, tests fail. I've fixed the matter.
=> fix(ssg): fixed `isDynamicRoute` and `ssgParams` matter

deno_dist/jsx/context.ts, deno_dist/jsx/dom/context.ts, deno_dist/jsx/dom/index.ts, deno_dist/jsx/index.ts, src/jsx/context.ts, src/jsx/dom/context.test.tsx, src/jsx/dom/context.ts, src/jsx/dom/index.ts, src/jsx/index.ts
```ts
import { createContext, useContext } from 'hono/jsx'
// or dom specific version
// import { createContext, useContext } from 'hono/jsx/dom'
const Context = createContext(0)
const Content = () => {
const num = useContext(Context)
return <p>{num}</p>
}
const Component = () => {
return (
<>
<Context.Provider value={1}>
<Content />
<Context.Provider value={3}>
<Content />
</Context.Provider>
<Content />
</Context.Provider>
</>
)
}
```
=> feat(jsx/dom): support createContext and useContext in jsx/dom

deno_dist/jsx/hooks/index.ts, src/jsx/hooks/index.ts
After relearning about TaskQueue and Microtask in JavaScript, I understood that execution by `setTimeout()` does not overtake the first `update()`. There is no need to use `promise` here.
Also, I don't think a 10ms wait is necessary.
=> refactor(jsx/dom): make `useTransition()` handling more simple

deno_dist/jsx/dom/render.ts, src/jsx/dom/index.test.tsx, src/jsx/dom/render.ts
=> fix(jsx/dom): find "insertBefore" node from next node list if not found

deno_dist/hono-base.ts, deno_dist/types.ts, src/hono-base.ts, src/types.test.ts, src/types.ts
Hello!
First off, thank you for creating Hono. I'm using it in my personal projects and it's been a great experience!
This pull request aims to improve type inference when extending context variables in middlewares.
Currently, When using handlers like `app.get` to register middlewares that extends context variables, the context type is correctly inferred.
```typescript
const mw = createMiddleware<{ Variables: { foo: string } }>(async () => {});
app.get(mw, async (c) => {
// this is correctly typed.
const foo: string = c.var.foo
})
```
However, when using `app.use`, the types aren't as well defined.
```typescript
app.use(mw).get(async (c) => {
// this isn't correctly typed before merging this PR.
const foo: string = c.var.foo
})
```
While `app.use` can accept path …
=> fix(types): use middlewares with different env types

deno_dist/jsx/dom/render.ts, deno_dist/jsx/hooks/index.ts, src/jsx/dom/components.test.tsx, src/jsx/dom/index.test.tsx, src/jsx/dom/render.ts, src/jsx/hooks/dom.test.tsx, src/jsx/hooks/index.ts
This PR contains two refactorings, and fixes. This is the last PR regarding "jsx/dom" for v4 and is intended to be a feature freeze. (Continue to fix bugs and support CSS helpers.)
This improves the following two issues
* Multiple updates of stete in a single callback will now invoke `update()` only once.
* https://github.com/honojs/hono/compare/v4...usualoma:hono:feat/jsx-dom-render-in-microtask?expand=1#diff-8f050239e20450fd8425feb7efbda60df851ebbc32bec8139d6d9ad1b53a7bc0R189-R217
* `useTransition` and `startViewTransition` can be used at the same time.
```ts
/** @jsxRuntime automatic @jsxImportSource ./src/jsx/dom */
import { render } from './src/jsx/dom'
import { useState, useTransition, startViewTransition } from './src/jsx/hooks'
const HeavyContent = ({ count }) => {
const startTime …
```
=> refactor(jsx/dom): invoke update() in microtask

deno_dist/helper/accept/accept.ts, deno_dist/helper/accept/index.ts, package.json, src/helper/accept/accept.test.ts, src/helper/accept/accept.ts, src/helper/accept/index.ts
=> feat: introduce Accepts Helper

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts
Context Env generics support for `ssgParams` middleware.
use a simple array for `ssgParams` middleware's argument.
=> feat: improve `ssgParams` flexibility

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts
- before:  `/api/` -> `./static/api/.html`
- after:  `/api/` -> `./static/api/index.html`
@yusukebe 
Currently, the implementation uniformly converts paths like `/css/` to `/css/index.css`. Considering this, there are two possible approaches to the implementation, and I have chosen the first one:
1. Treat all paths ending with a slash uniformly as `index.ext`, even for non-HTML files. Those who dislike this approach can use paths like `/css` without the trailing slash.
2. For non-HTML files ending with a slash, complete them as `/css.css`. I did not adopt this approach as it seems counterintuitive
=> fix(ssg): Uniformly Convert Paths Ending with Slash to 'index.ext' Format

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts
Following @yusukebe  advice, I have created the beforeRequestHook and AfterRequestHook. Users can now prevent unexpected outputs with these hooks.
=> feat(ssg): support Improve Hook Handling

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.ts
ref https://github.com/honojs/hono/pull/2054
The test appears to be failing accidentally. This is probably due to something not awaiting generatehook
=> fix: await generate hook

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts
Fixes #2061
Fix problem where notFound was not handled correctly when the result returned from the router was a single middleware.
=> fix(hono-base): fix not found handler calling timing when one middleware

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts
This PR fixes regression in the https://github.com/honojs/hono/pull/2080.
At first glance, it appears to be a significant change from the following code, but the conditions are the same.
```ts
if (res instanceof Response) return res
return (async () => {
let awaited: Response | void
try {
awaited = await res
if (!awaited) {
return this.notFoundHandler(c)
}
} catch (err) {
return this.handleError(err, c)
}
return awaited
})()
```
If `res instanceof Response` is `false`, whether it is a `Promise<Response>` or a Response-like object, it is resolved in the subsequent `await res`. Therefore, it is sufficient to check the type of res with `res instanceof Promise` and switch its behavior.
=> fix: enable to return Response like object 

deno_dist/hono-base.ts, src/hono-base.ts
=> refactor: "if" on one line and deletion of unneeded variables

package.json
=> fix: add typesVersions of accepts helper

deno_dist/adapter/deno/serve-static.ts, deno_dist/utils/mime.ts, src/adapter/bun/serve-static.ts, src/adapter/cloudflare-workers/serve-static.test.ts, src/adapter/cloudflare-workers/serve-static.ts, src/adapter/deno/serve-static.ts, src/utils/mime.test.ts, src/utils/mime.ts
close #2067 
This option enables you to set your own mime to serveStatic().
This `mimes` overwrites default mime in Hono.
```ts
// e.g. HLS
const mimes = {
m3u8: 'application/x-mpegURL',
ts: 'video/mp2t'
}
app.use('/video/*', serveStatic({mimes}))
```
=> feat(serve-static): `mimes` option for serve-static

deno_dist/context.ts, deno_dist/utils/types.ts, src/context.ts, src/utils/types.ts
I noticed `ContextVariableMap` is pretty much useless for `c.var` if `Env` in `Context` is `any` (the default), so I decided to make it respect it without breaking much code.
```ts
declare module 'hono' {
export interface ContextVariableMap {
x: string;
}
}
const c = new Context(...);
c.var.x; // any
c.var.y; // any
```
```ts
declare module 'hono' {
export interface ContextVariableMap {
x: string;
}
}
const c = new Context(...);
c.var.x; // string
c.var.y; // still any, as to not break any code
```
=> feat(types): better `c.var` type

deno_dist/middleware/jsx-renderer/index.ts, src/middleware/jsx-renderer/index.test.tsx, src/middleware/jsx-renderer/index.ts
Fixed not working correctly when there are more than 2 nested layouts.
=> fix(jsx-renderer): correct nested layouts

deno_dist/helper/css/index.ts, deno_dist/jsx/components.ts, deno_dist/jsx/constants.ts, deno_dist/jsx/context.ts, deno_dist/jsx/dom/components.ts, deno_dist/jsx/dom/context.ts, deno_dist/jsx/dom/index.ts, deno_dist/jsx/dom/render.ts, deno_dist/jsx/hooks/index.ts, deno_dist/jsx/index.ts, deno_dist/jsx/streaming.ts, src/helper/css/index.ts, src/jsx/components.ts, src/jsx/constants.ts, src/jsx/context.ts, src/jsx/dom/components.test.tsx, src/jsx/dom/components.ts, src/jsx/dom/context.test.tsx, src/jsx/dom/context.ts, src/jsx/dom/css.test.tsx, src/jsx/dom/index.test.tsx, src/jsx/dom/index.ts, src/jsx/dom/render.ts, src/jsx/hooks/dom.test.tsx, src/jsx/hooks/index.ts, src/jsx/index.test.tsx, src/jsx/index.ts, src/jsx/streaming.ts
Merging this PR will accomplish the purpose of #2131.
`useMemo`, `useLeyoutEffect`, `isValidElement`, `cloneElement`
Fixed the same problem with dom version as #2124
As in the original React, useEffect is now executed asynchronously after the DOM is rendered, rather than synchronously.
You can use dom-specific version of hooks and utils by importing from 'hono/jsx/dom' by 09da043
=> feat(jsx/dom): more react staff

deno_dist/helper/html/index.ts, deno_dist/utils/html.ts, src/helper/html/index.ts, src/utils/html.ts
There is a circular dependency between `src/helper/html/index.ts` and `src/utils/html.ts`. This PR removes this circular dependency by removing imports to helper files in utility files.
I found this circular dependency while running Hono in [Expo API Routes](https://blog.expo.dev/rfc-api-routes-cce5a3b9f25d). Displaying warnings for node_modules dependencies is [a bug](https://github.com/expo/expo/issues/26613) in Expo but I believe it's good to remove circular dependencies in the first place. 
Move the `raw` function to `src/utils/html.ts` and re-export `raw` in `src/helper/html/index.ts`
- Run the following command to find circular dependencies warnings disappear after the change.
```
npx dpdm --transform --no-tree ./src/helper/html/index.ts
```
- Tests for the `raw` remain in the …
=> fix(html): Remove circular dependencies in `hono/html`

deno_dist/helper/html/index.ts, deno_dist/router/trie-router/node.ts, deno_dist/types.ts, deno_dist/utils/html.ts, src/adapter/bun/serve-static.ts, src/helper/html/index.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts, src/types.test.ts, src/types.ts, src/utils/html.ts
=> Merge main into v4

deno_dist/jsx/dom/jsx-dev-runtime.ts, deno_dist/jsx/index.ts, deno_dist/jsx/utils.ts, src/jsx/dom/index.test.tsx, src/jsx/dom/jsx-dev-runtime.ts, src/jsx/index.test.tsx, src/jsx/index.ts, src/jsx/utils.ts
=> feat(jsx): "className" is now an alias for "class"

deno_dist/types.ts, src/types.test.ts, src/types.ts
=> fix(types): `MergeSchemePath` infers param types correctly

deno_dist/jsx/dom/jsx-dev-runtime.ts, deno_dist/jsx/jsx-dev-runtime.ts, src/jsx/dom/jsx-dev-runtime.ts, src/jsx/jsx-dev-runtime.ts
As shown in the following example, if key is unspecified, the third argument is not passed, so it is correct that it is optional.
https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
=> fix(jsx): The third argument of jsx(), key, is optional

deno_dist/utils/mime.ts, src/utils/mime.ts
`find` method is generally slower than for loop.
This PR replace it with for loop. More than 10x faster.
<details>
<summary>Source code</summary>
```ts
// Run `deno bench`
export const getExtension1 = (mimeType: string): string | undefined => {
return Object.keys(baseMimes).find((ext) => baseMimes[ext] === mimeType);
};
export const getExtension2 = (mimeType: string): string | undefined => {
for (const ext in baseMimes) {
if (baseMimes[ext] === mimeType) {
return ext;
}
}
};
const baseMimes: Record<string, string> = {
aac: "audio/aac",
avi: "video/x-msvideo",
avif: "image/avif",
av1: "video/av1",
bin: "application/octet-stream",
bmp: "image/bmp",
css: "text/css",
csv: "text/csv",
eot: "application/vnd.ms-fontobject",
epub: "application/epub+zip",
gif: "image/gif",
gz: "application/gzip", …
```
=> perf(mime): make `getExtension()` fast

deno_dist/context.ts, src/context.ts
The `render` method was defined twice in the `Context` class. This duplicate definition was causing a TypeScript error below if `tsc` is used to compile the project:
```
node_modules/hono/dist/types/context.d.ts(134,5): error TS2300: Duplicate identifier 'render'.
```
=> fix(context): remove duplicate definition of render method

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts
=> refactor(ssg): create request from saved requestInit in order to avoid memory leak warnings

deno_dist/jsx/dom/render.ts, src/jsx/dom/index.test.tsx, src/jsx/dom/render.ts
Fixed the same problem as #2016 when one child is updated in an element having multiple children.
=> fix(jsx/dom): Do not call insertBefore if the element position does not change

deno_dist/helper/dev/index.ts, deno_dist/helper/ssg/index.ts, deno_dist/helper/ssg/utils.ts, deno_dist/utils/handler.ts, src/helper/dev/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts, src/helper/ssg/utils.ts, src/utils/handler.ts
Note: This overlaps with some aspects of the issue discussed here: https://github.com/honojs/hono/pull/2179.
We have ceased relying on inspectRoute and instead are filtering using a custom method for the following reasons.
1. Unnecessary information: Information such as Middleware and HandlerName is not needed. 
2. Avoiding bloat in fetchContentRoutes: If we are to apply filters for isMiddleware as well as for GET and ALL methods, it is more efficient to filter right from the start.
=> refactor(ssg): filter SSG Route

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.test.tsx, src/helper/ssg/index.ts
Fixes #2176
Only GET and METHOD_NAME_ALL will be output. I don't think this will be disputed.
Added a utility function to check that the context is an SSG context.
```
app.get('/', (c) => c.html(<h1>{isSSGContext(c) ? 'SSG' : 'noSSG'}</h1>))
```
The header-based approach is not a bad one, but should not be used because visitors may insert headers, or the headers may reveal more information than necessary. Instead, environment variables and objects can be used to determine whether they are enabled or disabled.
The following is excluded from this PR, as they appear to be issues currently handled by `afterResponseHook`.
<del>
If the status code is not 200, it should be an error. There may be cases where it is better to continue without exiting, but I think it would be better to add that …
=> refactor(ssg): check `c.env` variables to disable/enable SSG

deno_dist/client/utils.ts, src/client/utils.test.ts, src/client/utils.ts
There seems to be an issue with the function `replaceUrlParam` that replaces regular expressions in the path within the Client. Specifically, the problem arises when there's a length specification (`{}`) within the regular expression, and it appears at the end of the regex section.
```
/year/:year{[0-9]{4}}/month/:month{[0-9]{1,2}}
```
In this case, when the Client is given the params:
```
param: {
year: "2024",
month: "2",
}
```
it parses them as:
```
/year/2024}/month/2}
```
The regular expression that "detects the regex section" within the path was only matching a single `}`. I propose to modify this to match one or more times (`+`), ensuring correct detection even when the length specification (`{}`) is at the end of the section.
=> Fix regex pattern with length limit at replaceUrlParam

deno_dist/router/linear-router/router.ts, deno_dist/router/pattern-router/router.ts, src/router/linear-router/router.test.ts, src/router/linear-router/router.ts, src/router/pattern-router/router.test.ts, src/router/pattern-router/router.ts
=> fix(router): LinearRouter and PatternRouter support regexp quantifiers

deno_dist/hono-base.ts, src/hono-base.ts, src/hono.test.ts, src/middleware/compress/index.test.ts
Fixed Custom NotFound not working with middleware that creates a new Response object after `next()` such as Compress Middleware. And added proper tests.
This was fixed by #2080, but it may not be merged to the main branch well. And there is no test to handle it, so we can't notice it has the bug.
=> fix(hono-base): custom not found with middleware like compress

deno_dist/jsx/components.ts, deno_dist/jsx/streaming.ts, runtime_tests/deno-jsx/jsx.test.tsx, src/helper/css/index.test.tsx, src/jsx/components.test.tsx, src/jsx/components.ts, src/jsx/index.test.tsx, src/jsx/streaming.test.tsx, src/jsx/streaming.ts, src/middleware/jsx-renderer/index.test.tsx
There is no change in behavior, but it is not a useful refactoring for existing applications, so it is a question of whether to include it in a patch version. A minor version might be fine.
* 867f85722b33038606a8f3d7b826742d490a0134 : Depending on the content, it may look like the following, and in this case a JS error occurs.
* `<template id="E:0"></template><! -E:0->`
* 71c8ec52bbcedf1149420a81bb9fd0b53ce791ec : When handling https://github.com/honojs/honox/issues/47, it is useful to be able to retrieve the resolved value later, so the data attribute was added. The data will be slightly larger, but I don't think it will be a problem.
=> refactor: jsx streaming

deno_dist/jsx/hooks/index.ts, src/jsx/hooks/index.ts
This is a very small refactoring and changes nothing in the specifications.
When processing the result of an "if/else" type of promise, it is shorter and clearer to pass two functions to `.then()` than to use `.catch()`.
=> refactor(jsx): shorten use hook a bit

deno_dist/context.ts, deno_dist/middleware/jsx-renderer/index.ts, src/context.ts, src/middleware/jsx-renderer/index.ts
Maybe fixes #2190
Importing "hono/client" is causing problems because hono's JSX types are being read.
```ts
import { hc } from "hono/client";
```
This is because "context.ts" imports "hono/jsx" and "hono/middleware/jsx-renderer". This PR eliminates this.
However, even after resolving this, if I try to use `React.ElementType` and "hono/jsx" at the same time (I am not aware if there is such a case or not), we still have problems. 
The following part cannot avoid conflict with the `React.ElementType` definition in any way.
https://github.com/usualoma/hono/blob/33f2d484f651ea55913ebe7022ed028e8ac7743f/src/jsx/base.ts#L20-L22
If a workaround is needed, I think the only way is to remove `[tagName: string]: Props`.
=> refactor(context): skip jsx type import

deno_dist/jsx/dom/render.ts, src/jsx/dom/index.test.tsx, src/jsx/dom/render.ts
fixes https://github.com/honojs/honox/issues/71
In the case of SVG and MathML elements, it is necessary to use createElementNS instead of createElement to support them.
In React, it is necessary to specify in lower camel case, and I think the output will be converted to kebab case. This PR does not do that conversion, but I think it is OK to have hono specify kebab case from the beginning. If there are many requests, we will consider adding a conversion process.
```tsx
// in React 
<circle
cx="40"
cy="40"
r="35"
stroke="black"
strokeWidth="4"
fill="lightgrey"
/> // => <circle cx="40" cy="40" r="35" stroke="black" stroke-width="4" fill="lightgrey" />
```
=> feat(jsx/dom): support namespace for svg and mathml elements

.devcontainer/Dockerfile
Deno installer support ARM64 builds from [v1.40.4](https://github.com/denoland/deno/releases/tag/v1.40.4).
The third party installer we are currently using has officially come to an end.
https://github.com/LukeChannings/deno-arm64
We can use the official installer.
=> chore: use official deno installer

deno_dist/router/reg-exp-router/router.ts, src/router/reg-exp-router/router.test.ts, src/router/reg-exp-router/router.ts
fixes #2254
Fixed an error when accessed by an unknown method. I don't think there is a compatibility issue.
I will think about #1953 later.
=> fix(reg-exp-router): use matchers[METHOD_NAME_ALL] as fallback for unknown method

deno_dist/adapter/deno/serve-static.ts, deno_dist/middleware/serve-static/index.ts, deno_dist/utils/filepath.ts, runtime_tests/bun/index.test.tsx, runtime_tests/bun/static/download, runtime_tests/deno/middleware.test.tsx, runtime_tests/deno/static/download, src/adapter/bun/serve-static.ts, src/adapter/cloudflare-workers/serve-static.test.ts, src/adapter/cloudflare-workers/serve-static.ts, src/adapter/deno/serve-static.ts, src/middleware/serve-static/index.ts, src/utils/filepath.test.ts, src/utils/filepath.ts
Fixes #2251 and refactored.
Refactoring methods:
* Created `middleware/serve-static`, which is not used by users directly.
* Wrap the middleware by the environment, such as Deno, Bun, and Cloudflare Workers.
=> fix(serve-static): support extensionless files and refactor

deno_dist/http-exception.ts, src/http-exception.test.ts, src/http-exception.ts, tsconfig.json
Add a "cause" option to HTTPException for easier debugging.
close #2170 
```ts
app.get('/users', (c) => {
try {
const result = await db.select().from(users);
return c.json(result);
} catch (error) {
throw new HTTPException(500, {
message: 'Internal Server Error',
cause: error,
})
}
})
```
=> feat: Add a "cause" option to HTTPException

deno_dist/helper/dev/index.ts, deno_dist/middleware/logger/index.ts, deno_dist/utils/color.ts, src/helper/dev/index.ts, src/middleware/logger/index.test.ts, src/middleware/logger/index.ts, src/utils/color.test.ts, src/utils/color.ts
Related: https://github.com/honojs/hono/pull/2007
This PR adds `utils/colors.ts`.
We have to support `NO_COLOR`.
=> feat(logger): support `NO_COLOR`

deno_dist/types.ts, src/types.test.ts, src/types.ts
=> fix(types): `MergeSchemaPath` supports regexp path params

deno_dist/helper/cookie/index.ts, deno_dist/utils/cookie.ts, src/helper/cookie/index.test.ts, src/helper/cookie/index.ts, src/utils/cookie.ts
Hello @yusukebe!
I have added support for secure and host prefixes. This PR resolves https://github.com/honojs/hono/issues/1203
cc: @Code-Hex
=> feat(cookie): add secure and host prefix support

deno_dist/helper/ssg/index.ts, src/helper/ssg/index.ts
Fixing the type error. The type here is never used, so it can be loose.
=> fix(ssg): allow `app: Hono<any, any, any>` for `toSSG`

deno_dist/types.ts, src/types.ts
`c.jsonT` is removed now, but there is a reference to it in the comment.
I found it when I was reading the code, it may cause confusion for contributors, so I fixed it.
=> fix: fix comment

deno_dist/utils/stream.ts, src/utils/stream.ts
Fixes: #2068
In the current version of Hono, the `stream.writeSSE` method was getting blocked indefinitely when the user disconnects from the SSE stream prematurely. Consider this example (taken from #2068):
```typescript
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { streamSSE } from "hono/streaming";
const app = new Hono();
let testId = 0;
app.get("/sse", (c) =>
streamSSE(c, async (stream) => {
try {
const currentTestId = ++testId;
let aborted = false;
stream.onAbort(() => {
aborted = true;
});
for (let i = 0; i < 10; i++) {
console.log(currentTestId, "Iteration", i, aborted ? "(aborted)" : "");
// If I await the writeSSE like this, it sometimes never returns when the stream is aborted
await stream.writeSSE({ data: JSON.stringify({ iteration: i }) }); …
```
=> Handler stuck when awaiting aborted SSE stream

deno_dist/types.ts, src/types.ts
If it uses `Partial`, the type will include `undefined`. It causes unexpected behavior in validators like Zod Validator.
=> fix(types): use `{}` instead of Partial

deno_dist/jsx/hooks/index.ts, src/jsx/dom/index.test.tsx, src/jsx/hooks/index.ts
fixes #2303
We have had simple examples that worked, but the actual implementation was almost what we would call a mock😢  This PR will make sure that the values are properly stored within the lifecycle.
=> fix (jsx/dom): keep ref.current value during lifecycle.

deno_dist/middleware/body-limit/index.ts, package.json, src/middleware/body-limit/index.test.ts, src/middleware/body-limit/index.ts
This is an implementation of the feature proposed in #2077 using stream.
Simply specify the maximum size.
```ts
app.post(
'/hello',
bodyLimit({
maxSize: 15 * Unit.b, // byte,
onError: (c) => {
return c.text('oveflow :(', 413)
},
}),
(c) => {
return c.text('pass :)')
}
)
```
The problem discussed in #2077 that a body must be read at a time is solved by using stream.
It uses `c.req.bodyCache` used by the Validator implementation. By setting the loaded ArrayBuffer to `c.req.bodyCache.arrayBuffer`, such as `c.req.json()` will use that cached body from then on.
=> feat: introduce Body Limit Middleware using stream

deno_dist/utils/cookie.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
New Cookie RFC (a.k.a cookie-bis) and CHIPS includes some best practices for Cookie settings which developers should follow.
This PR adding some condition check for Cookie handling especially.
- [RFC6265bis-13](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-13)
- `Max-Age`/`Expires` limitation
- `--Host-`/`--Secure_` prefix limitation 
- [CHIPS-01](https://www.ietf.org/archive/id/draft-cutler-httpbis-partitioned-cookies-01.html)
- `Partitioned` limitation
Note: I'm adding link to latest draft in each comment, but should be updated to RFC link.
=> feat(cookie): Add Cookie bis condition check

deno_dist/mod.ts, src/index.ts, src/mod.ts
With this change, you can re-define `ExecutionContext` types in your app:
```ts
declare module 'hono' {
interface ExecutionContext {
waitUntil(promise: Promise<any>): void
passThroughOnException(): void
abort(reason?: any): void
}
}
```
Fixes #2341
=> fix(context): export `ExecutionContext` from `hono`

deno_dist/client/utils.ts, src/client/utils.test.ts, src/client/utils.ts
This PR addresses an issue where the `removeIndexString` function was leaving a trailing slash when removing `/index` from URLs, which conflicted with Hono's exact matching behavior for route definitions. This behavior was observed in Hono v4.1.0 running on Cloudflare Workers, where the presence of a trailing slash would cause an otherwise valid endpoint to return a 404 error.
- Updated `removeIndexString` function within the Hono Client to ensure the trailing slash is removed along with `/index`, aligning URL formats with the expected endpoint paths for exact matching.
Below is an example highlighting the issue and demonstrating how the current implementation may lead to unexpected behavior:
```ts
const app = new Hono().basePath("/api/v1");
export const getMe = new Hono().get("", async …
```
=> fix(client): Remove trailing slash from /index for precise path matching

deno_dist/utils/cookie.ts, src/utils/cookie.test.ts, src/utils/cookie.ts
add Types for settings cookie options and make below operations typesafe
- `--Secure_` prefix
- `--Host_` prefix
- `Partitoned` option
as discussed in https://github.com/honojs/hono/pull/2314#issuecomment-1980809011
- [N/A] Add tests
=> feat(utils/cookie): Typesafe cookie options

benchmarks/utils/.gitignore, benchmarks/utils/package.json, benchmarks/utils/src/get-path.ts, deno_dist/utils/url.ts, src/utils/url.ts
For `getPath()`, the `slice` + `indexOf` is faster than RegExp.
Node.js:
```txt
cpu: Apple M1 Pro
runtime: node v20.10.0 (arm64-darwin)
benchmark            time (avg)             (min … max)       p75       p99      p999
------------------------------------------------------- -----------------------------
noop                 61 ps/iter        (20 ps … 257 ns)     61 ps     81 ps    143 ps !
• getPath
------------------------------------------------------- -----------------------------
slice + indexOf   35.85 ns/iter     (21.28 ns … 162 ns)  36.11 ns  38.84 ns  47.32 ns
regexp            57.76 ns/iter     (45.29 ns … 215 ns)  55.81 ns    134 ns    185 ns
summary for getPath
slice + indexOf
1.61x faster than regexp
```
Bun:
```
cpu: Apple M1 Pro
runtime: bun 1.0.31 (arm64-darwin) …
```
=> perf(utils/url): use `slice` + `indexOf` for `getPath()`

deno_dist/router/linear-router/router.ts, deno_dist/router/pattern-router/router.ts, deno_dist/router/reg-exp-router/node.ts, deno_dist/router/reg-exp-router/router.ts, deno_dist/router/trie-router/node.ts, src/router/common.case.test.ts, src/router/linear-router/router.ts, src/router/pattern-router/router.ts, src/router/reg-exp-router/node.ts, src/router/reg-exp-router/router.ts, src/router/trie-router/node.test.ts, src/router/trie-router/node.ts
=> fix(router): wildcard paths when using js reserved words (like constructor and __proto__)

deno_dist/validator/validator.ts, src/validator/validator.test.ts, src/validator/validator.ts
=> fix(validator): use cached body for `json` and `form` validation

deno_dist/jsx/base.ts, deno_dist/jsx/components.ts, deno_dist/jsx/streaming.ts, src/jsx/base.ts, src/jsx/components.test.tsx, src/jsx/components.ts, src/jsx/streaming.test.tsx, src/jsx/streaming.ts
fixes #2391
`null` and `undefined` should also be allowed for JSX child elements, and even hono was implemented with this assumption in the following places, but it was omitted from the type definition. This will be fixed in c16c6c0e839188742f24eec6f86266ead02ec707
https://github.com/usualoma/hono/blob/b5ad5f4418a6ed50ac61bdb07b8f016693bfd533/src/jsx/base.ts#L76-L77
There were some child elements of `Suspense` and `ErrorBoundary` that had insufficient handling of `null` and `undefined`, which were fixed with e151c792cf40751cacd988fc2745ef5e08ae56e9.
=> fix(jsx): allow null, undefined, and boolean as children

deno_dist/router/reg-exp-router/router.ts, src/router/common.case.test.ts, src/router/reg-exp-router/router.ts
=> fix(reg-exp-router): escape meta characters for find middleware

deno_dist/helper/testing/index.ts, deno_dist/jsx/hooks/index.ts, deno_dist/types.ts, deno_dist/utils/types.ts, src/helper/testing/index.ts, src/hono.test.ts, src/jsx/hooks/index.ts, src/types.test.ts, src/types.ts, src/utils/types.ts
I've refactored the code for some types of matters.
* Fixed the handlers' overload order. This improves performance when inferring handler return types.
* Fixed some bugs for types.
* Apply `Prettify`.
* Fixed `tsc` errors.
Related to #2399
Getting faster inferring handler return types. Below are the results if it's a simple case that it has one handler.
Before:
This PR:
This improves RPC-mode performance but does not change much because the implementation of the `hc` function is not so good.
```ts
// create.ts
import { writeFileSync } from 'fs'
let code = `
const routes = app
`
for (let i = 1; i < 300; i++) {
code += `.get('/route${i}', (c) => {
ok: true
})
})`
}
code += `
export type AppType = typeof routes
export …
```
=> refactor(types): optimize inferring handler types

deno_dist/hono-base.ts, src/hono-base.ts
I replaced some `Arrap.prototype.map` to `Arrap.prototype.forEach` to up performance a little.
`forEach` doesn't make result value, so It's faster than `map` a little.
[perf.link](https://perf.link/#eyJpZCI6InM1MHQwMWhhODZmIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGFyciA9IG5ldyBBcnJheSgxMDAwKS5maWxsKE1hdGgucmFuZG9tKCkpIiwidGVzdHMiOlt7Im5hbWUiOiJVc2luZyBgbWFwYCIsImNvZGUiOiJjb25zdCBuZXdBcnIgPSBbXVxuYXJyLm1hcCgoZSkgPT4ge1xuXHRuZXdBcnIucHVzaChlKVxufSkiLCJydW5zIjpbODMzMywzMzMzLDIwMDAwLDEwNjY2LDEwNjY2LDEwNjY2LDIzMzMzLDExNjY2LDc2NjYsMTA2NjYsMzMzMywyMzMzMywxMDY2NiwxMDY2NiwxMDY2NiwxMDY2NiwxMDMzMywxMDY2NiwxMDY2NiwxMTAwMCw5MzMzLDI2NjYsMjMzMzMsOTY2NiwxNDAwMCw2MDAwLDI0NjY2LDIwMzMzLDE1MzMzLDEwNjY2LDIzMzMzLDEwNjY2LDI5MDAwLDEzMDAwLDkzMzMsMTA2NjYsNzMzMywxMDY2NiwxM …
=> perf: Don't use `Arrap.prototype.map` if it is not needed return value

deno_dist/middleware/jwt/index.ts, src/middleware/jwt/index.ts
Improves error handling in the JWT middleware by passing error descriptions to `message` prop in `HTTPExceptionOptions`.
=> feat(middleware/jwt): improve error handling

deno_dist/request.ts, deno_dist/validator/validator.ts, src/request.test.ts, src/request.ts, src/validator/validator.ts
Closes #1499 
As mentioned in #1499,`c.req.json()` throws an error if `c.req.text()` is called before it. With this PR, the body content created by `c.req.text()`, `c.req.arrayBuffer()`, and others will be cached correctly and reused so the error will not be thrown.
A concern is that there will be more code in `request.ts`, but this change is important for DX, so we will introduce it
=> feat(request): cache body for reusing

src/adapter/aws-lambda/handler.ts
In case of a streaming lambda, the response should still contain metadata
like status and content type, even if no body is given.
This could be for example a redirect response.
=> fix(aws-lambda): handle response without body (#2401)

deno_dist/middleware/cors/index.ts, src/middleware/cors/index.ts
Hello!
I opened this PR because I wanted to use a context in the options.origin function as follows:
```
app.use(
'/api/*',
cors({
origin: (origin, c) => {
return c.env.MY_ALLOW_ORIGIN
},
})
)
```
=> feat(middleware/cors): pass context to options.origin function

deno_dist/middleware/cache/index.ts, src/middleware/cache/index.test.ts, src/middleware/cache/index.ts
This PR adds support for the `Vary` header in cache middleware, allowing developers to specify headers that should trigger separate cache entries. This feature is essential for applications serving content that varies based on client headers, such as Accept or Accept-Language, enhancing content negotiation and caching efficiency.
closed: https://github.com/honojs/hono/issues/2395
```ts
app.use('/example/*', cache({ cacheName: 'my-app-cache', vary: 'Accept, Accept-Encoding' }));
app.get('/example/', (c) => {
return c.text('This content is cached with Vary header.');
});
```
This simple addition enables the server to cache different versions of a resource based on the specified header(s), ensuring that clients receive content that's tailored to their needs, such as different image formats …
=> feat: support for `vary` header in cache middleware

src/test-utils/setup-vitest.ts
Stub only when there is no `crypto` in global.
=> test: stub `crypto` if not exist

deno_dist/middleware/bearer-auth/index.ts, src/middleware/bearer-auth/index.test.ts, src/middleware/bearer-auth/index.ts
This PR will fix #2316 and #2410.
With this PR, it enables passing the function to verify the token in Bearer Middleware.
```ts
app.use(
'/auth-verify-token/*',
bearerAuth({
verifyToken: async (token) => {
return token === 'dynamic-token'
},
})
)
```
=> feat(bearer-auth): add `verifyToken` option
