honojs/hono

- .github/workflows/ci.yml
- jest.config.js
- package.json
- src/middleware/basic-auth/basic-auth.test.ts
- src/middleware/body-parse/body-parse.test.ts
- src/middleware/logger/logger.test.ts
- src/middleware/powered-by/powered-by.test.ts
- test/context.test.ts
- test/hono.test.ts
- test/middleware.test.ts
- yarn.lock
Close https://github.com/yusukebe/hono/issues/40
> feat(miniflare): repalce service-worker-mock with miniflare

- src/middleware/logger/logger.test.ts
- src/middleware/logger/logger.ts
Close https://github.com/yusukebe/hono/issues/56
> feat(content-length): add Content-Length in log output

- src/middleware/basic-auth/basic-auth.test.ts
- src/middleware/basic-auth/basic-auth.ts
https://github.com/yusukebe/hono/pull/84#pullrequestreview-870144435
Thank you @danielweck
> fix: Unicode problem about atob/btoa

- README.md
- src/context.ts
- src/utils/http-status.test.ts
- src/utils/http-status.ts
- test/context.test.ts
- test/hono.test.ts
`c.statusText()` is obsoleted. Status text is set automatically.
> feat: auto set `statusText`

- README.md
- src/hono.ts
- src/utils/url.test.ts
- src/utils/url.ts
- test/hono.test.ts
> feat: add option for `no` strict routing

- package.json
> feat: exports `RegExpRouter`

- examples/blog/src/controller.ts
- src/hono.ts
> fix(types): add `Handler<string>`

- src/context.test.ts
- src/context.ts
You can set a JSON pretty option with `c.pretty(true)`.
> feat: add JSON pretty option

- src/middleware/jwt/index.ts
- src/utils/jwt/jwt.test.ts
- src/utils/jwt/types.test.ts
This PR is to,
* fix the algorithm not used in Jwt middleware when it's defined.
* add more unit tests.
> fix(jwt): the alg option should be same as the one in options

- src/hono.test.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
apply the patch by @usualoma  https://github.com/honojs/hono/issues/189#issuecomment-1121773536
> feat(trie-router): error handling for duplicate param name

- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
Removed unnecessary features from #223.
> feat(reg-exp-router): error handling for duplicate param name

- src/context.test.ts
- src/context.ts
Resolve https://github.com/honojs/hono/issues/205
> feat(ctx): enable set and get in ctx, to hold values

- README.md
- src/context.ts
- src/hono.test.ts
- src/hono.ts
- src/index.ts
- src/middleware/cookie/index.test.ts
- src/middleware/cookie/index.ts
> for v1.3.0

- src/middleware/serve-static/index.test.ts
- src/middleware/serve-static/index.ts
> fix(serve-static): enable with other middleware

- src/middleware/mustache/mustache.ts
- src/utils/crypto.ts
- src/utils/encode.ts
Fix throwing errors in Wrangler **2.0.6**. Don't use `dynamic import`.
Close #248
> fix: throwing errors in Wrangler 2.0.6

- src/compose.ts
- src/hono.test.ts
> fix(compose): fix a bug for colliding async routes

- README.md
- src/context.ts
- src/hono.test.ts
- src/hono.ts
> feat: multiple query values `c.req.queries`

- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
Implementation of the following specifications.
* https://github.com/honojs/hono/issues/262#issuecomment-1134747110
* https://github.com/honojs/hono/issues/262#issuecomment-1135232294
> feat: adoption of a new sort order for routing in RegExpRouter

- src/middleware/jwt/index.test.ts
- src/middleware/jwt/index.ts
This PR is to fix https://github.com/honojs/hono/issues/291
FYI: https://www.rfc-editor.org/rfc/rfc2617#page-8
> fix(token): correct 'WWW-Authenticate' header in response

- src/index.ts
> fix: Import "declare global" for the Request interface explicitly.

- package.json
- src/middleware/bearer-auth/README.md
- src/middleware/bearer-auth/index.test.ts
- src/middleware/bearer-auth/index.ts
> feat(middleware): add bearer auth middleware

- src/compose.test.ts
- src/hono.test.ts
- src/hono.ts
> feat: throw error if context is not finalized

- src/compose.ts
- src/context.ts
- src/hono.ts
> feat: `notFound` support asyc/await

- README.md
- package.json
- src/middleware/html/README.md
- src/middleware/html/index.test.ts
- src/middleware/html/index.ts
- src/middleware/jsx/README.md
- src/utils/html.test.ts
- src/utils/html.ts
> refactor(html): make `html` as middleware

- src/middleware/jsx/README.md
> fix(typo) JSX README

- src/middleware/serve-static/README.md
- src/middleware/serve-static/serve-static.test.ts
- src/middleware/serve-static/serve-static.ts
- src/utils/cloudflare.ts
> feat(serve-static): add `path` option

- README.md
- deno_dist/README.md
- deno_dist/mod.ts
- src/mod.ts
Obsolete `app.fire()` for Deno. Instead of that, write this:
```ts
serve((req) => app.fetch(req))
```
> refactor(deno): [BREAKING] obsolete `app.fire()`

- .github/workflows/ci.yml
- package.json
> ci: setup CI for Deno

- .github/workflows/ci.yml
> ci: add CI for Bun

- bun_test/index.test.ts
- package.json
- src/middleware/basic-auth/index.ts
For supporting Basic Auth middleware for Bun, do not check types.
Close #380
> feat(bun): support `basic-auth` middleware

- src/middleware.ts
Hi, I forgot to add compress middleware to middleware.ts . This pull request solves my mistake. Thanks.
> Add compress middleware

- src/middleware/logger/index.test.ts
- src/middleware/logger/index.ts
Features to a better and eficient code
- add **enum** to acess message types
- it's not good to use mutations in code and i fix this
- will define the variables with precious names
- fix the time function that not calculate correctly
- achieving coverage 100% :)
Thank you, guys!
> refactor: the log middleware and its tests

- src/context.ts
This PR fixes #385.
This PR will replace executionCtx() with a getter method to check the type to runtime.
Since the FetchEvent object satisfies the ExecutionContext interface, how about returning a FetchEvent from executionCtx() even if we have a FetchEvent? I think users will be able to use executionCtx().waitUntil() without being aware of whether it is Service Worker syntax or new Module Worker format.
In this PR, I am checking the type in `this._executionCtx instanceof FetchEvent`.
I am not familiar with the performance differences, but is there anything that makes it less desirable than `'respondWith' in this._executionCtx`?
> refactor(context): executionCtx always returns ExecutionContext.

- .github/release.yml
Inspired by
https://github.com/r7kamura/github-label-presets
> chore: add conf file to categorize the PRs on release note

- README.md
- docs/CONTRIBUTING.md
> docs: make a contribution guide

- src/middleware/jwt/index.test.ts
- src/middleware/jwt/index.ts
Close https://github.com/honojs/hono/issues/437
> feat(jwt): enable token in cookie

- src/hono.test.ts
- src/request.ts
- src/utils/body.ts
> refactor: make `parsedBody` type as `Body`

- deno_dist/utils/html.ts
- src/utils/html.test.ts
- src/utils/html.ts
> refactor(`utils/html`): remove `escape` function

- deno_dist/middleware/etag/index.ts
- deno_dist/utils/crypto.ts
- src/middleware/etag/index.ts
- src/utils/crypto.ts
Made `utils/crypto` supports `ReadbleStream`.
Fix #458
> fix(ETag): fixed an error when the file size is too large.

- bun_test/index.test.tsx
- deno_dist/compose.ts
- deno_dist/utils/mime.ts
- deno_test/middleware.test.tsx
- src/utils/mime.test.ts
- src/utils/mime.ts
> refactor(mime): made `.ico` file's extension to `image/x-icon`

- deno_dist/compose.ts
- src/compose.test.ts
- src/compose.ts
#466 is awesome!
However, we should also support asynchronous functions that are not 'AsyncFunction'.
> fix(compose): Support a handler that non-async and returning a promise.

- deno_dist/context.ts
- deno_dist/hono.ts
- deno_dist/middleware/serve-static/serve-static.ts
- src/context.ts
- src/hono.ts
- src/middleware/serve-static/serve-static.ts
`c.get('bar')`  and `c.env.Foo` types were not correct. Fixed it.
> fix(type): fix type errors for Bindings and Variables

- deno_dist/context.ts
- deno_dist/hono.ts
- src/context.ts
- src/hono.ts
> fix(context): fix type error

- deno_dist/hono.ts
- src/hono.ts
Made it does not `compose` if it has only one handler. `await composed` is slow and could be speed up by avoiding `compose`.
Will be faster if it returns only "Hello World".
17%  Faster!!
```
hono - trie-router(default) x 421,632 ops/sec ±4.36% (79 runs sampled)
hono - regexp-router x 452,187 ops/sec ±5.90% (69 runs sampled)
hono - trie-router(default) - New x 506,280 ops/sec ±3.92% (85 runs sampled)
hono - regexp-router - New x 610,975 ops/sec ±4.52% (83 runs sampled)
```
Not much has changed.
```
v2.1.3
Requests/sec: 185881.3210
New
Requests/sec: 188679.7531
```
11% Faster!!
```
v2.1.3
Requests/sec: 133396.6236
New
Requests/sec: 149045.7514
```
> perf: do not `compose` if it has only one handler

- deno_dist/router/reg-exp-router/router.ts
- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
Fixes #497
The performance of this code is not that good, but it is a rare case and has little impact. Performance improvements will be considered later.
> Fix regexp ambigous route

- deno_dist/compose.ts
- deno_dist/context.ts
- deno_dist/hono.ts
- src/compose.ts
- src/context.ts
- src/hono.ts
> fix(types): correct types for `app.notFound` / `app.onError`

- deno_dist/middleware/basic-auth/index.ts
- deno_dist/middleware/bearer-auth/index.ts
- src/middleware/basic-auth/index.test.ts
- src/middleware/basic-auth/index.ts
- src/middleware/bearer-auth/index.test.ts
- src/middleware/bearer-auth/index.ts
> fix(middleware): support multiple middleware on bearer/basic auth middleware

- deno_dist/README.md
- deno_dist/middleware/validator/validator.ts
- src/middleware/validator/validator.test.ts
- src/middleware/validator/validator.ts
Add new rules `isBoolean` and `isNumber` for validator middleware. It's useful to validate JSON values.
> feat(validator): add `isBoolean` and `isNumber`

- deno_dist/middleware/cors/index.ts
- deno_dist/utils/url.ts
- src/middleware/cors/index.test.ts
- src/middleware/cors/index.ts
- src/utils/url.test.ts
- src/utils/url.ts
I think we should check by the Origin header, not the Referer header.
> Check in Origin header instead of Referer

- deno_dist/middleware/cors/index.ts
- src/middleware/cors/index.test.ts
- src/middleware/cors/index.ts
I would also like to be able to dynamically check Origin by a function.
> feat(cors): Enable to check origin header by a function.

- deno_dist/deno/serve-static.ts
- deno_test/deps.ts
- deno_test/middleware.test.tsx
- src/deno/serve-static.ts
> fix(deno): serve static middleware returns 404 correctly

- bun_test/index.test.tsx
- src/middleware/serve-static/bun.ts
> fix(bun): serve static middleware returns 404 correctly

- deno_dist/middleware/validator/middleware.ts
- src/middleware/validator/middleware.test.ts
- src/middleware/validator/middleware.ts
Fixed the bug pointed here: <https://github.com/honojs/hono/pull/535#issuecomment-1252210438>
> fix(validator): make "Types" work well

- deno_dist/middleware/validator/middleware.ts
- deno_dist/request.ts
- src/middleware/validator/middleware.test.ts
- src/middleware/validator/middleware.ts
- src/request.ts
Same as #546 
How about this additional feature?
> feat(validator): Enable verification results to be retrieved as structured data.

- deno_dist/hono.ts
- deno_dist/middleware/validator/middleware.ts
- deno_dist/utils/encode.ts
- src/hono.ts
- src/middleware/validator/middleware.ts
Now, you can do like this:
Close #551 #552
> fix(types): enable types for `c.env` when using validator

- src/hono.ts
Fixes: https://github.com/honojs/hono/issues/554
> use console.trace to improve error handler

- deno_dist/hono.ts
- src/hono.ts
> fix(handleEvent): use `dispatch` instead of `fetch`

- deno_dist/router/trie-router/node.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
> Fix Trie router multiple matching path parameters

- deno_dist/router/reg-exp-router/router.ts
- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
fixes #574
@yusukebe I think this PR will fix #574!
> fix(reg-exp-router): Register path for all the methods if method === METHOD_NAME_ALL.

- deno_dist/deno/serve-static.ts
- deno_test/middleware.test.tsx
- src/deno/serve-static.ts
> fix(deno): fixed the bug calling `next()` multiple times in Serve Static

- src/hono.ts
- src/middleware/basic-auth/index.test.ts
- src/middleware/bearer-auth/index.test.ts
This is a continuation of #608 .
> fix(basic/bearer): support "nested" middleware

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.test.ts
- src/middleware/jwt/index.ts
This is like #608 but just refactoring. It's not a security fix because it's already secured.
> refactor(jwt): refactor code and add more tests

- docs/CONTRIBUTING.md
> docs(contribution): update about 3rd-party middleware

- bun_test/index.test.tsx
> test(bun): JWT middleware works on Bun v0.2.2

- deno_dist/validator/validator.ts
- src/middleware/validator/middleware.test.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> feat(validator): support `v.queries`

- deno_dist/hono.ts
- deno_dist/request.ts
- src/hono.ts
- src/request.ts
> fix(type): make compatibility with `@cloudflare/workers-types`

- deno_dist/mod.ts
- src/index.ts
- src/mod.ts
I forgot about it.
This may close #648
> fix(types): export `ErrorHandler` and `NotFoundHandler`

- deno_dist/context.ts
- deno_dist/hono.ts
- deno_dist/types.ts
- deno_dist/utils/encode.ts
- src/context.ts
- src/hono.ts
- src/types.ts
> fix(type): change the type definition of `req` in Context

- deno_dist/validator/validator.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> fix(sanitizer)

- deno_dist/request.ts
- deno_dist/utils/encode.ts
- src/hono.test.ts
- src/request.ts
> fix(param): Decode context.param

- jest.config.js
- package.json
> fix(package.json): exports types correctly

- package.json
> fix(package.json): add `typesVersions` section

- deno_dist/router/reg-exp-router/router.ts
- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
I believe this change will fix #681.
> fix(reg-exp-router): Allows registering a star after a long prefix.

- src/compose.test.ts
- src/middleware/cache/index.test.ts
- src/middleware/html/index.ts
- src/middleware/jsx/index.ts
- src/middleware/jsx/jsx-dev-runtime.ts
- src/middleware/validator/middleware.ts
- src/mod.ts
- src/request.ts
- src/router/reg-exp-router/router.ts
- src/types.test.ts
- src/types.ts
This fixes all the lint warnings we get in PRs:
> chore: fix lint warnings

- deno_dist/context.ts
- deno_dist/middleware/html/index.ts
- deno_dist/middleware/jsx/index.ts
- deno_dist/middleware/jsx/jsx-dev-runtime.ts
- deno_dist/middleware/validator/middleware.ts
- deno_dist/mod.ts
- deno_dist/request.ts
- deno_dist/router/reg-exp-router/router.ts
- deno_dist/types.ts
- deno_dist/utils/encode.ts
- jest.config.js
- src/context.ts
> Fix detecting node runtime

- deno_dist/router/reg-exp-router/router.ts
- src/router/reg-exp-router/router.test.ts
- src/router/reg-exp-router/router.ts
@yusukebe I would like to fix #699 this way. Please review 🙇
> fix(reg-exp-router): bug of "star and all" routing

- deno_dist/validator/rule.ts
- src/validator/rule.test.ts
- src/validator/rule.ts
> fix(validator): enable checking `undefined` in rules

- deno_dist/types.ts
- src/middleware/validator/index.test.ts
- src/types.test.ts
- src/types.ts
> fix(types): fixed type structure

- LICENSE
- deno_dist/LICENSE
Hono is not made only by me. Need contributors. Thanks!!
> chore: update license, contributors as the copyright holders

- deno_dist/middleware/cors/index.ts
- deno_dist/utils/encode.ts
- src/middleware/cors/index.test.ts
- src/middleware/cors/index.ts
This PR fixes a bug that a pre-flight request would be 404.
> fix(cors): fix bugs handling pre-flight

- deno_dist/context.ts
- deno_dist/hono.ts
- deno_dist/request.ts
- deno_dist/utils/url.ts
- src/context.ts
- src/hono.ts
- src/request.ts
- src/utils/url.test.ts
- src/utils/url.ts
> perf: optimize parsing queries and headers / 19% faster than 2.7.2

- deno_dist/context.ts
- deno_dist/utils/encode.ts
- src/context.ts
- src/hono.test.ts
> fix(context): enable destruction such `json`

- deno_dist/types.ts
- src/types.ts
> fix: fixed type error for optional parameters

- package.json
- yarn.lock
This PR checks if Hono has proper package exports using publint. See #822 for details.
> build: validate package exports after build

- deno_dist/context.ts
- src/context.test.ts
- src/context.ts
- src/middleware/cors/index.test.ts
> fix(context): set the header values of already set

- src/adapter/cloudflare-pages/handler.ts
> fix(cloudflare-pages): fix type incompatibility

- deno_dist/hono.ts
- deno_dist/mod.ts
- deno_dist/types.ts
- deno_dist/utils/encode.ts
- src/hono.ts
- src/index.ts
- src/mod.ts
- src/types.test.ts
- src/types.ts
It's not needed. Use `Handler` or `MiddlewareHandler` instead.
> refactor: obsolute `CustomHandler`

- src/middleware/serve-static/bun.ts
- src/middleware/serve-static/serve-static.ts
The fix in the PR https://github.com/honojs/hono/pull/863 is only for Deno. So this PR will fix it for Cloudflare and Bun.
> fix(serve-static): decode url pathname

- deno_dist/compose.ts
- deno_dist/hono.ts
- src/compose.test.ts
- src/compose.ts
- src/hono.test.ts
- src/hono.ts
Derived from #866, version for errorHandler only
> feat: use added app's errorHandler

- deno_dist/hono.ts
- src/hono.ts
> feat: Remove the StaticRouter from default candidates.

- deno_dist/compose.ts
- deno_dist/hono.ts
- src/compose.test.ts
- src/compose.ts
- src/hono.test.ts
- src/hono.ts
A shorter version that solves the problem of https://github.com/honojs/hono/pull/871#issuecomment-1422647262
> feat: use added app's errorHandler with comose()

- deno_dist/request.ts
- docs/CONTRIBUTING.md
- src/hono.test.ts
- src/request.ts
See [Line 94](https://github.com/honojs/hono/pull/884/files#diff-b1a2ab03a3672e105afeaab6615ad625365cd8459d592a840d925f132af62b35R94).
> header may return undefined

- deno_dist/context.ts
- deno_dist/hono.ts
- deno_dist/types.ts
- src/context.ts
- src/hono.ts
- src/types.ts
Rename `TypeResponse` to `TypedResponse`.
> refactor: rename to `TypedResponse`

- src/request.ts
Refactored. Perhaps, it may improve performance.
> refactor(req): remove `async` keyword from `json()` etc.

- deno_dist/mod.ts
- src/mod.ts
> feat(deno): export `HonoRequest` type in Deno

- .github/FUNDING.yml
Add @usualoma to our funding list.
> chore: update sponsor link

- deno_dist/context.ts
- src/context.ts
This is suggested by @koistya. Thanks!
> feat(context): allow passing `unknown` to `executionCtx.waitUntil`

- deno_dist/hono.ts
- src/hono.test.ts
- src/hono.ts
> feat: Enable to add subApp with basePath.

- src/middleware/basic-auth/index.ts
- src/utils/encode.test.ts
- src/utils/encode.ts
- src/utils/jwt/jwt.ts
- Import base64 logic from https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/main/src/base64.ts
- Decoding speed will be faster almost 2x
- Accept to encode RFC 3548 examples
- This PR is created at YAPC::Japan::Kyoto 2023 🔥
> Refactoring base64 logic for JWT

- benchmarks/query-param/package-lock.json
- benchmarks/query-param/package.json
- benchmarks/query-param/src/bench.mts
- benchmarks/query-param/src/fast-querystring.mts
- benchmarks/query-param/src/hono.mts
- deno_dist/request.ts
- deno_dist/utils/url.ts
- src/request.ts
- src/utils/url.test.ts
- src/utils/url.ts
More accurate decoding in query string parsing. (e.g., encoded keys)
The following are the results of a comparison between hono's v3.1.3 and fast-querystring (which is used in elysia) with a slight modification to the benchmarks/query-param added in this PR.
In some places, hono's v3.1.3 is faster because decoding is skipped, and compared to that, this PR has a performance decrease. Nevertheless, the speed reduction is slight, and the amount of code has not increased.
This should be changed as it is unsuitable for a framework not to get parameters right.
```
$ npm run bench:bun
> bench:bun
> bun run ./src/bench.mts
cpu: Apple M2 Pro
runtime: bun 0.5.8 (arm64-darwin)
benchmark            time (avg)             (min … max)       p75       p99      p995 …
```
> refactor(utils/url): Decode parameters more accurately without performance degradation.

- src/adapter.ts
> feat(adapter): infer env typings from context

- deno_dist/mod.ts
- src/mod.ts
> fix(deno): export `HTTPException` from `mod.ts`

- deno_dist/middleware/jsx/jsx-dev-runtime.ts
- src/middleware/jsx/jsx-dev-runtime.ts
- tsconfig.json
> fix(jsx): fix a `jsx-runtime` bug

- deno_dist/utils/url.ts
- src/utils/url.test.ts
- src/utils/url.ts
> fix(getQueryParam): Fixed a bug in getQueryParam when a partial matching key was found.

- deno_dist/context.ts
- src/context.ts
Here it is UTF8 again!
https://github.com/honojs/hono/commit/0a19deaa5bb800a43909c0f25e53d68dbcf4e48a#diff-1c6b79733c620b41d7f8b63deb644f09e5fda79664918394b443c2a348731605L278-R279
> fix(context): Fix typo in charset, again.

- deno_dist/hono-base.ts
- deno_dist/hono.ts
- deno_dist/preset/quick.ts
- deno_dist/preset/tiny.ts
- deno_dist/types.ts
- src/hono-base.ts
- src/hono.ts
- src/preset/quick.ts
- src/preset/tiny.ts
- src/types.ts
> fix(types): set `/` for generics `basePath`

- .github/workflows/ci.yml
Use `setup-bun` for CI and specify the Bun version `v0.5.9`.
> ci: use `setup-bun`

- .github/workflows/ci.yml
- package.json
> ci: don't specify Bun version in CI

- deno_dist/context.ts
- deno_dist/utils/types.ts
- src/client/client.test.ts
- src/context.ts
- src/utils/types.ts
> feat: Allow `context.jsonT` to take interface as an argument

- benchmarks/routers/package.json
- benchmarks/routers/src/bench.mts
- benchmarks/routers/src/radix3.mts
- benchmarks/routers/yarn.lock
> chore(benchmark): add radix3

- src/adapter/aws-lambda/handler.ts
discussed in and close #1160 
At first I thought I should add new test but this PR makes no change for a behavior from outside so I decided not to do so.
> fix: replace to use better base64-encoder

- deno_dist/http-exception.ts
- src/hono.test.ts
- src/http-exception.ts
> fix(HttpException): error message should not be the HTTP reason phrase

- deno_dist/utils/cookie.ts
- src/utils/cookie.test.ts
- src/utils/cookie.ts
> fix(cookie): `maxAge` should be positive

- deno_dist/adapter/deno/serve-static.ts
- package.json
- src/adapter/aws-lambda/handler.ts
- src/adapter/deno/serve-static.ts
- tsconfig.json
- yarn.lock
> fix(tsconfig): remove `skipLibCheck`

- deno_dist/middleware/cookie/index.ts
- src/middleware/cookie/index.test.ts
- src/middleware/cookie/index.ts
fixes #1175
This implementation is based on `cookies.delete` in sveltekit (https://github.com/sveltejs/kit/blob/842e6abc7f32b228dc441c78d5636b1fbb1bae48/packages/kit/src/runtime/server/cookie.js#L117-L122)
> add deleteCookie

- deno_dist/hono-base.ts
- deno_dist/utils/url.ts
- src/hono-base.ts
- src/hono.test.ts
- src/utils/url.test.ts
- src/utils/url.ts
> fix(mount): include query params

- deno_dist/middleware/etag/index.ts
- src/middleware/etag/index.ts
If the upstream response doesn't include an `ETag` header, the ETag middleware needs to clone the response so it can read the body to compute an ETag. This commit simplifies the management of the original and cloned responses.
> refactor(etag): simplify cloning logic

- deno_dist/hono-base.ts
- src/hono-base.ts
- src/hono.test.ts
> fix(hono-base): enable `strict` with `getPath` option

- src/adapter/aws-lambda/handler.ts
fixes [#1265](https://github.com/honojs/hono/issues/1265)
> added generic parameters to aws-lambda handler to fix #1265

- src/adapter/cloudflare-pages/handler.ts
- src/adapter/cloudflare-pages/index.ts
> feat(cloudflare-pages): add `serveStatic()`

- README.md
- deno_dist/README.md
I've finished writing the 'GetStarted' section; may I add it?
> doc: Adding a Supported Runtime - Lambda@Edge

- src/hono.test.ts
> test(app): add more tests for hostname-routing

- deno_dist/context.ts
- src/context.ts
I've measured the benchmark roughly, but it may be a little bit faster.
> perf(context): add `init` flag

- src/adapter/aws-lambda/handler.test.ts
- src/adapter/aws-lambda/handler.ts
https://github.com/honojs/hono/issues/1294
> fix(adapter/aws-lambda): use content-encoding to determine isBase64Encoded

- deno_dist/utils/mime.ts
- src/utils/mime.ts
Wasm wont load in the browser without a corect Content-Type!
> Add missing wasm mime type

- deno_dist/mod.ts
- src/index.ts
- src/mod.ts
> Export Schema type to allow route exports in declaration files

- deno_dist/middleware/cookie/index.ts
- src/middleware/cookie/index.ts
> fix misspell

- src/types.test.ts
- src/types.ts
> fix(types): fix handler types

- src/request.ts
> feat(req): allow passing generics to `c.req.param()`

- .github/workflows/ci.yml
- package.json
- runtime_tests/lambda-edge/index.test.ts
- src/adapter/aws-lambda/custom-context.ts
- src/adapter/aws-lambda/index.ts
- src/adapter/lambda-edge/handler.ts
- src/adapter/lambda-edge/index.ts
- src/client/client.ts
- src/middleware/compress/index.test.ts
- src/middleware/etag/index.test.ts
- src/middleware/etag/index.ts
add new script `format`
Fix: #1318
> chore: add `format` script

- runtime_tests/lambda-edge/index.test.ts
> refactor: lint

- deno_dist/client/client.ts
- deno_dist/middleware/etag/index.ts
> refactor: denoify

- deno_dist/context.ts
- deno_dist/hono-base.ts
- runtime_tests/deno/hono.test.ts
- runtime_tests/node/index.test.ts
- src/compose.test.ts
- src/context.test.ts
- src/context.ts
- src/hono-base.ts
This does not cause performance degradation, but it makes the code cleaner.
> refactor(context): allow passing `HonoRequest` as 1st arg

- deno_dist/request.ts
- src/request.test.ts
- src/request.ts
> fix(req): fix inferring types in `req.valid()`

- deno_dist/types.ts
- deno_dist/validator/validator.ts
- src/types.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> feat(validator): deprecate `queries` (use `query` instead)

- deno_dist/types.ts
- deno_dist/validator/validator.ts
- src/types.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> feat(validator): supports `header` and `cookie`

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(type): add missing S to RemoveBlankRecord

- deno_dist/hono-base.ts
- src/hono-base.ts
- src/hono.test.ts
> feat(app): pass `env` to `getPath()`

- deno_dist/client/types.ts
- deno_dist/types.ts
- src/client/client.test.ts
- src/client/types.ts
- src/types.ts
> fix(client): ignore `header` and `cookie` types

- deno_dist/client/client.ts
- src/client/client.test.ts
- src/client/client.ts
> fix(client): `continue` if query value is `undefined`

- deno_dist/mod.ts
- src/index.ts
- src/mod.ts
> fix(types): export `ToSchema`

- deno_dist/types.ts
- src/types.ts
> fix(types): fix `AddDollar`

- .github/workflows/ci.yml
- src/mod.ts
The original PR: #1374
I've separated 'denoify' from the 'main'.
> ci: check if it is denoified

- .github/workflows/ci.yml
Updated!
https://github.com/actions/checkout/releases/tag/v4.0.0
> chore(ci): checkout@v4

- deno_dist/utils/buffer.ts
- src/utils/buffer.test.ts
- src/utils/buffer.ts
> fix(`utils/buffer`): don't decode space as `+`

- deno_dist/jsx/index.test.tsx
- deno_dist/jsx/index.ts
- src/jsx/index.test.tsx
- src/jsx/index.ts
> fix(jsx): enable `Fragment`

- .github/workflows/ci.yml
- package.json
> ci: add `--no-warnings` option for `main`

- deno_dist/types.ts
- src/client/client.test.ts
- src/types.test.ts
- src/types.ts
> fix(types): fix `MergeSchemaPath` correct

- deno_dist/client/client.ts
- deno_dist/client/types.ts
- package.json
- src/client/client.test.ts
- src/client/client.ts
- src/client/types.ts
> fix(client): remove async from `$url()`

- deno_dist/hono-base.ts
- src/hono-base.ts
> fix(hono-base): `deprecate` should be `deprecated`

- deno_dist/hono-base.ts
- deno_dist/types.ts
- src/hono-base.ts
- src/hono.test.ts
- src/types.ts
> fix(types): fix the type error in `MiddlewareHandlerInterface`

- deno_dist/helper/factory/index.ts
- deno_dist/types.ts
- deno_dist/utils/types.ts
- src/helper/factory/index.ts
- src/hono.test.ts
- src/types.ts
- src/utils/types.ts
> fix(types): middleware with different env types

- deno_dist/types.ts
- src/hono.test.ts
- src/types.ts
> fix(type): check 1st arg of middleware is `string`

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(types): return types of `jsonT()` should be union

- deno_dist/utils/cookie.ts
- src/helper/cookie/index.test.ts
- src/utils/cookie.test.ts
- src/utils/cookie.ts
This pull request does a few things, namely:
- Adds the code from #1198 (and supersedes #1198 due to there being radio silence in the aforementioned PR); I've added the code from that commit with the PR creator as the commit author (and myself as the committer) so as to credit that user
- Adds the requested applicable tests from said pull request - the helper doesn't seem to have anything applicable for test addition/update
- Fixes a spelling error in the helper test regardless
- Makes string templating consistent in `cookies.ts` as it inconsistently alternated between string templating and concatenation with the `+` operator
- Deno-ifies said changes
> feat: Add CHIP support - supersedes #1198

- benchmarks/routers/package.json
- benchmarks/routers/src/bench.mts
- benchmarks/routers/src/hono.mts
- benchmarks/routers/src/memoirist.mts
> chore(benchmark): add memoirist router

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Adding the .devcontainer configuration makes it easier for us to develop projects online.
> feat: add devcontainer to improve developer experience

- deno_dist/utils/jwt/jwt.ts
- src/utils/jwt/jwt.ts
> fix(jwt): avoid using `enum`

- deno_dist/helper.ts
- deno_dist/middleware.ts
- src/helper.ts
- src/middleware.ts
> fix(deno): export `testing` helper

- deno_dist/utils/buffer.ts
- deno_dist/validator/validator.ts
- src/utils/buffer.test.ts
- src/utils/buffer.ts
- src/validator/validator.ts
This PR may fix https://github.com/honojs/node-server/issues/85.
> fix(utils/buffer): fix `bufferToFormData()`

- runtime_tests/lambda/index.test.ts
- src/adapter/aws-lambda/handler.ts
- src/adapter/aws-lambda/index.ts
- src/adapter/aws-lambda/types.ts
Ref: https://github.com/orgs/honojs/discussions/1519
Lambda "Context"
https://docs.aws.amazon.com/lambda/latest/dg/typescript-context.html
```ts
app.get('/lambda-context', (c) => {
const fnctx = c.env.lambdaContext
console.log(fnctx..callbackWaitsForEmptyEventLoop)
return c.json(fnctx)
})
```
> feat(adaptor): Accessable Lambda "Context"

- deno_dist/hono-base.ts
- src/hono-base.ts
> refactor(hono-base): remove `any` casting

- src/adapter/vercel/handler.test.ts
- src/adapter/vercel/handler.ts
> fix(vercel): pass request context

- package.json
- src/context.test.ts
- src/middleware/cache/index.test.ts
- src/test-utils/setup-vitest.ts
- src/utils/crypto.test.ts
- vitest.config.ts
- yarn.lock
> test: use Node.js Native Web APIs instead of miniflare's

- package.json
- yarn.lock
> chore: bump up denoify

- package.json
> feat(`package.json`): export `streaming` helper

- deno_dist/helper/streaming/index.ts
- src/helper/streaming/index.test.ts
- src/helper/streaming/index.ts
> fix(streaming): fix SSE format

- deno_dist/helper/factory/index.ts
- src/helper/factory/index.ts
> fix(factory): fixed the comment

- deno_dist/helper.ts
- src/helper.ts
> feat(deno): export the `factory` helper for Deno

- deno_dist/hono-base.ts
- deno_dist/hono.ts
- deno_dist/preset/quick.ts
- deno_dist/preset/tiny.ts
- src/hono-base.ts
- src/hono.ts
- src/preset/quick.ts
- src/preset/tiny.ts
> refactor: refactored `hono-base`

- .github/workflows/ci.yml
- src/validator/validator.test.ts
> test(validator): fix the error message for node v18.18

- .github/workflows/ci.yml
- runtime_tests/bun/index.test.tsx
> chore(ci): bun v1

- package.json
> fix(package.json): export `hono-base`

- deno_dist/middleware/jsx-renderer/index.ts
- src/middleware/jsx-renderer/index.ts
> fix(jsx-renderer): fix `PropsForRenderer`

- deno_dist/client/types.ts
- src/client/client.test.ts
- src/client/types.ts
> fix(hc): allows optional schemas

- deno_dist/context.ts
- deno_dist/helper/adapter/index.ts
- src/context.ts
- src/helper/adapter/index.ts
> feat(helper/adapter): add `runtime` option to `env`

- deno_dist/helper/factory/index.ts
- src/helper/factory/index.ts
> feat(helper/factory): remove `@experimental` from `createMiddleware()`

- deno_dist/jsx/streaming.ts
- src/jsx/streaming.test.tsx
- src/jsx/streaming.ts
> feat(jsx/streaming): Support nested Suspense.

- deno_dist/jsx/streaming.ts
- src/jsx/streaming.test.tsx
- src/jsx/streaming.ts
Prior to this PR, if there were multiple nested Suspense, they were processed in stages, but in this PR, they will be processed first in the order of termination.
In the test I added this PR, it was `<p>last</p><p>first</p>` before this PR, but now it is `<p>first</p><p>last</p>` with this PR.
> perf(jsx/streaming): In multiple Suspense, go ahead in the order of resolved.

- deno_dist/helper/html/index.ts
- deno_dist/jsx/index.ts
- deno_dist/jsx/streaming.ts
- deno_dist/middleware/jsx-renderer/index.ts
- src/helper/html/index.ts
- src/jsx/index.ts
- src/jsx/streaming.ts
- src/middleware/jsx-renderer/index.test.tsx
- src/middleware/jsx-renderer/index.ts
@yusukebe 
How about this?
Implemented: #1659
> feat(jsx-renderer): Support "stream" option in jsxRenderer.

- README.md
- deno_dist/README.md
- deno_dist/helper/adapter/index.ts
- src/helper/adapter/index.ts
- src/utils/url.test.ts
> docs: rename Fastly `Compute@Edge` to `Compute`

- deno_dist/helper/html/index.ts
- deno_dist/jsx/index.ts
- deno_dist/jsx/streaming.ts
- deno_dist/utils/html.ts
- src/helper/html/index.ts
- src/jsx/index.ts
- src/jsx/streaming.test.tsx
- src/jsx/streaming.ts
- src/utils/html.ts
@yusukebe I'm adding a few more bug fixes now, so please wait a bit.
> fix(jsx/streaming): Fixed a problem when multiple children are added directly under Suspense.

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(types): infer env types with chaining handlers

- deno_dist/hono-base.ts
- src/hono-base.ts
> feat(hono): remove `experimental` flag from `app.mount()`

- deno_dist/context.ts
- src/context.ts
- src/types.test.ts
> fix(context): implement `ContextVariableMap` for `c.var`

- .github/workflows/ci.yml
> ci: rename fastly `compute@edge` to `compute`

- deno_dist/types.ts
- src/types.ts
> fix(types): fixed a typo

- deno_dist/compose.ts
- src/compose.test.ts
- src/compose.ts
> fix(compose): allow notFound handler to be async

- deno_dist/validator/validator.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
This error is captured and never shown which may by misleading. This PR suggest to throw this error directly to the reponse.
> Invalid HTTP header error is hidden

- deno_dist/context.ts
- src/context.ts
> feat(context): remove `experimental` from `c.render`/`c.setRenderer()`

- deno_dist/context.ts
- src/context.ts
- src/hono.test.ts
> fix(context): Set `content-type` with `c.text()` correctly

- deno_dist/client/types.ts
- src/client/client.test.ts
- src/client/types.ts
Fixes #1766 https://github.com/honojs/middleware/issues/285
> fix(client): Allow optional props in JSON response

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(client): `c.json()` supports `undefined`/`null` response

- deno_dist/context.ts
- src/context.ts
- src/middleware/cors/index.test.ts
> fix(context): set `status` correctly

- package.json
- yarn.lock
> chore: bump up `@hono/eslint-config`

- .gitignore
- package.json
- yarn.lock
> chore: bump `devDependencies`

- tsconfig.json
> chore(`tsconfig.json`): use `vitest/globals` for types

- deno_dist/client/types.ts
- deno_dist/types.ts
- src/client/types.ts
- src/helper/factory/index.test.ts
- src/types.ts
Reproduce: https://gist.github.com/sor4chi/a488b66c25017b228b6f45875157a073
> fix(factory): infer a merged path correctly

- package.json
> chore(package.json): remove `ts-jest`

- .github/workflows/ci.yml
> ci(bun): use `1.0.18`

- deno_dist/hono-base.ts
- src/hono-base.ts
> fix(hono-base): make `onError` and `notFound` as class field

- deno_dist/router/trie-router/node.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
> fix(trie-router): pass params to the next node

- deno_dist/client/types.ts
- src/client/types.ts
> fix(client): add missing properties to `ClientResponse`

- deno_dist/utils/url.ts
- src/utils/url.test.ts
- src/utils/url.ts
> fix(req): avoid error when `req.queries()` receives unexpected values

- deno_dist/hono-base.ts
- src/hono-base.ts
> fix(hono-base): fixed a typo

- deno_dist/jsx/jsx-dev-runtime.ts
- src/jsx/jsx-dev-runtime.ts
- src/jsx/jsx-runtime.test.tsx
> fix(jsx): fix jsx-runtime for falsy children

- deno_dist/helper/streaming/sse.ts
- src/helper/streaming/sse.test.ts
- src/helper/streaming/sse.ts
- src/helper/streaming/stream.test.ts
> fix: streamSSE's doesn't trigger `onAbort` correctly

- deno_dist/adapter/netlify/index.ts
- deno_dist/adapter/netlify/mod.ts
- src/adapter/netlify/index.ts
- src/adapter/netlify/mod.ts
> fix(netlify): add `adapter/netlify/index.ts`

- deno_dist/helper/css/index.ts
- deno_dist/jsx/dom/index.ts
- deno_dist/jsx/hooks/index.ts
- deno_dist/jsx/index.ts
- deno_dist/jsx/jsx-dev-runtime.ts
- deno_dist/utils/html.ts
- package.json
- src/helper/css/index.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/index.ts
- src/jsx/hooks/index.ts
- src/jsx/index.ts
- src/jsx/jsx-dev-runtime.ts
- src/utils/html.ts
> feat: Introduce jsx/dom

- .github/workflows/ci.yml
- deno_dist/hono-base.ts
- src/hono-base.ts
> ci: enables CI in the v4 branch

- deno_dist/jsx/dom/index.ts
- deno_dist/jsx/hooks/index.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/index.ts
- src/jsx/hooks/index.ts
There was a problem that cleanup was not called when changing "deps", so this has been fixed.
> fix(jsx/dom): fix cleanup for deps

- deno_dist/jsx/dom/index.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/index.ts
> refactor(jsx/dom): replace existing content by render()

- package.json
Hi, thank you for the great work on Hono! It seemed like this was missing from the package.json which may have caused some issues. Please let me know if changes should be made.
Thanks!
> fix(netlify): update package.json to export `./netlify`

- deno_dist/context.ts
- src/context.test.ts
- src/context.ts
> fix(context): set multiple cookies correctly in `set res`

- deno_dist/client/index.ts
- src/client/index.ts
Resolves #1950
This is a `feat` but a minor issue; I'll release it as a patch release.
> feat(client): export `ClientResponse` and `ClientRequest`

- deno_dist/request.ts
- src/request.ts
> refactor: remove unnecessary `import`

- deno_dist/context.ts
- deno_dist/hono-base.ts
- src/context.ts
- src/hono-base.ts
> refactor: remove and fix comments

- deno_dist/router/trie-router/node.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
> fix(trie-router): fixed the issue same param name is used

- deno_dist/helper/css/index.ts
- deno_dist/router/linear-router/router.ts
- deno_dist/utils/cookie.ts
- deno_dist/utils/encode.ts
- src/helper/css/index.ts
- src/router/linear-router/router.ts
- src/utils/cookie.ts
- src/utils/encode.test.ts
- src/utils/encode.ts
For loop use the length of the array cached first.
> refactor: faster for loop

- deno_dist/router/trie-router/node.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
> fix(trie-router): fixed same name path params matter

- deno_dist/middleware/basic-auth/index.ts
- deno_dist/middleware/cache/index.ts
- package.json
- src/middleware/basic-auth/index.ts
- src/middleware/cache/index.ts
> Refactor middleware, tests

- package.json
> feat: add script for watch, remove tsc from test

- deno_dist/middleware/cors/index.ts
- src/middleware/cors/index.ts
> refactor: cors

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.ts
> refactor: jwt

- package.json
> chore(package.json): specify the config in `test:deno`

- runtime_tests/deno/deno.lock
> chore(runtime-test): add `deno.lock`

- deno_dist/context.ts
- src/context.ts
- src/hono.test.ts
> fix(context): fixed middleware + `c.json({}, requestInit)` problem

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.test.tsx
- src/helper/ssg/index.ts
fixed https://github.com/honojs/hono/issues/2028
> fix(SSG): Correct extension of the file output

- deno_dist/helper/css/index.ts
- deno_dist/jsx/dom/render.ts
- deno_dist/jsx/hooks/index.ts
- deno_dist/jsx/index.ts
- src/helper/css/index.ts
- src/jsx/dom/css.test.tsx
- src/jsx/dom/render.ts
- src/jsx/hooks/dom.test.tsx
- src/jsx/hooks/index.ts
- src/jsx/index.ts
* Introduce `startViewTransition()`
* Partial support for `<Style />`
This is an API not found in the original React.
The usage of this API is the same as the existing `startTransition()`, with state updates wrapped and passed as callback
If you simply want to use `document.startViewTransition()`, you can do so by writing the following, although it is a bit long.
```ts
<button onClick={() => {
if (!document.startViewTransition) {
setCount((c) => c + 1)
}
else {
document.startViewTransition(() => {
setCount((c) => c + 1)
});
}
}}>
{count}
</button>
```
Replacing this with the `startViewTransition()` provided by hono here has the following two advantages.
* Can be written in short
* Transition can be applied to fallback by `Suspense` and subsequent delayed rendering.
```ts
<button …
```
> feat(jsx/dom): Introduce startViewTransition()

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.ts
fixes: https://github.com/honojs/hono/issues/2031
> fix(ssg): Remove ArrayBuffer from FileSystemModule's writeFile

- src/adapter/aws-lambda/handler.ts
> refactor: aws lambda createResult method

- deno_dist/middleware/secure-headers/index.ts
- src/middleware/secure-headers/index.ts
> refactor: secure headers middleware

- deno_dist/hono.ts
- deno_dist/preset/quick.ts
- deno_dist/preset/tiny.ts
- deno_dist/types.ts
- src/hono.ts
- src/preset/quick.ts
- src/preset/tiny.ts
- src/types.ts
> refactor(types): name them `BlankSchema` or `BlankInput`

- deno_dist/helper.ts
- deno_dist/helper/accept/accept.ts
- src/helper.ts
- src/helper/accept/accept.ts
> feat(deno): export accpet helper for deno

- .vscode/settings.json
- deno_dist/utils/body.ts
- src/utils/body.ts
> refactor: body parser

- deno_dist/utils/stream.ts
- src/utils/stream.ts
> refactor: stream pull

- deno_dist/utils/url.ts
- src/utils/url.ts
> refactor: url util splitRoutingPath

- deno_dist/middleware/jsx-renderer/index.ts
- src/middleware/jsx-renderer/index.test.tsx
- src/middleware/jsx-renderer/index.ts
> fix: use DOCTYPE by default 

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.test.tsx
- src/helper/ssg/index.ts
fixes https://github.com/honojs/hono/issues/2070
> fix:(ssg): make 'files' mandatory in ToSSGResult

- deno_dist/helper/factory/index.ts
- src/helper/factory/index.test.ts
- src/helper/factory/index.ts
> fix(factory): correct types inside of `createMiddleware()`

- vitest.config.ts
fixes https://github.com/honojs/hono/issues/2090
> chore: vitest test.pool to 'forks'

- deno_dist/request.ts
- src/request.ts
> refactor: request param

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/render.ts
> refactor: faster for loop in jsx/dom

- docs/CONTRIBUTING.md
> docs(contributing): add `Installing dependencies`

- src/adapter/bun/serve-static.ts
> fix: replace fs.existsSync() with Bun.file().exists()

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(types): infer complex path params

- deno_dist/jsx/index.ts
- src/jsx/index.test.tsx
- src/jsx/index.ts
In JSX `toString()`, `useContext()` did not work correctly for nested async component. This PR fixes that problem.
It is possible that this PR will fix #2118, but it may be another cause, which will need to be confirmed after merged.
> fix(jsx): fix context provider with async component

- deno_dist/router/trie-router/node.ts
- src/router/trie-router/node.test.ts
- src/router/trie-router/node.ts
> fix(trie-router): fix same parameter name issue

- deno_dist/jsx/index.ts
- src/jsx/index.ts
> refactor(jsx): Remove unused HONO_COMPONENT feature

- docs/MIGRATION.md
> docs: update the migration guide for releasing v4

- deno_dist/helper/streaming/sse.ts
- src/helper/streaming/sse.test.ts
- src/helper/streaming/sse.ts
fixes: https://github.com/honojs/hono/issues/2172
> feat(sse): Allow sending retry for SSE connection

- README.md
- deno_dist/README.md
> docs(readme): tweak

- deno_dist/middleware/jsx-renderer/index.ts
- src/middleware/jsx-renderer/index.test.tsx
- src/middleware/jsx-renderer/index.ts
> fix(jsx-renderer): support async component

- docs/CONTRIBUTING.md
Match the install command with Installing dependencies.
> docs(contribution): add install flag `--frozen-lockfile`

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/render.ts
fixes https://github.com/honojs/honox/issues/68
> fix(jsx/dom): fix finding element to insert before

- deno_dist/helper/html/index.ts
- src/helper/html/index.test.ts
- src/helper/html/index.ts
> feat(jsx): support HtmlEscapedString in html tag function

- package.json
> chore(package.json): remove `@edge` for `compute`

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.ts
> fix(jwt): import cookie helper correctly

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.test.tsx
- src/helper/ssg/index.ts
- before
- /index.html -> static/index.html.html 
- after
- /index.html -> static/index.html
> fix(ssg): path of already extention

- deno_dist/validator/validator.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> fix(validator): use the cached content

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.test.tsx
- src/helper/ssg/index.ts
fixes: https://github.com/honojs/hono/pull/2236
> fix: Dot-containing paths do not correctly receive extension completion.

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/render.ts
fixes https://github.com/honojs/hono/issues/2259
> fix: assign value to element's property for input, textarea, select

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/render.ts
When there is no update, assing to textContent is not performed to improve performance.
> perf(jsx/dom): update textContent only when content changes

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/render.ts
Fixes https://github.com/honojs/honox/issues/92
> fix(jsx/dom): import from correct file for avoiding circular dependency

- deno_dist/helper/ssg/index.ts
- src/helper/ssg/index.test.tsx
- src/helper/ssg/index.ts
> fix(ssg): preserve binary files as-is

- deno_dist/middleware/body-limit/index.ts
- src/middleware/body-limit/index.test.ts
- src/middleware/body-limit/index.ts
> feat(body-limit): Replace c.req.raw with body limit middleware proxy

- deno_dist/jsx/jsx-runtime.ts
- runtime_tests/deno-jsx/jsx.test.tsx
- src/jsx/jsx-runtime.ts
> fix(deno/jsx-precompile): use html() tag function if value is a promise

- deno_dist/utils/stream.ts
- src/utils/stream.ts
> fix(stream): remove async from onabort

- deno_dist/middleware.ts
- src/middleware.ts
> fix(body-limit): export `bodyLimit` for Deno

- deno_dist/utils/jwt/jwt.ts
- deno_dist/utils/jwt/key.ts
- deno_dist/utils/jwt/types.ts
- deno_dist/utils/jwt/utf8.ts
- src/utils/jwt/jwt.test.ts
- src/utils/jwt/jwt.ts
- src/utils/jwt/key.ts
- src/utils/jwt/types.test.ts
- src/utils/jwt/types.ts
- src/utils/jwt/utf8.ts
> feat(jwt): supported RS256, RS384, RS512 algorithm for JWT

- .github/workflows/ci.yml
> ci: fix bun version for `denoify`

- .github/workflows/ci.yml
- deno_dist/middleware/jsx-renderer/index.ts
- src/middleware/jsx-renderer/index.ts
> refactor(jsx-renderer): remove unnecessary comments for eslint

- deno_dist/utils/jwt/jwt.ts
- deno_dist/utils/jwt/types.ts
- src/utils/jwt/jwt.test.ts
- src/utils/jwt/jwt.ts
- src/utils/jwt/types.ts
> added remain algorithm for JWT

- deno_dist/middleware/jsx-renderer/index.ts
- src/middleware/jsx-renderer/index.test.tsx
- src/middleware/jsx-renderer/index.ts
Fixes the issue as same as https://github.com/honojs/middleware/issues/418
> fix(jsx-renderer): don't overwrite headers if stream is `true`

- deno_dist/context.ts
- src/context.test.ts
- src/context.ts
> fix(context): set headers correctly if it has `this.#headers`

- deno_dist/helper/streaming/sse.ts
- src/helper/streaming/sse.test.ts
- src/helper/streaming/sse.ts
Related to this issue: https://github.com/honojs/hono/issues/2319
> fix(streaming): Fix stream SSE, not necessary close stream.

- deno_dist/jsx/base.ts
- src/jsx/base.ts
- src/jsx/index.test.tsx
Fixes https://github.com/honojs/hono/issues/2383
> fix(jsx): use self closing tag only if element has no children

- deno_dist/helper/ssg/ssg.ts
- src/helper/ssg/ssg.test.tsx
- src/helper/ssg/ssg.ts
ref:  https://github.com/honojs/middleware/pull/412
> feat(ssg): Support asynchronous hooks 

- deno_dist/jsx/base.ts
- src/jsx/base.ts
- src/jsx/index.test.tsx
> fix(jsx): escape attribute value for "style"

- deno_dist/jsx/dom/index.ts
- deno_dist/jsx/hooks/index.ts
- deno_dist/jsx/index.ts
- src/jsx/dom/index.ts
- src/jsx/hooks/dom.test.tsx
- src/jsx/hooks/index.ts
- src/jsx/index.ts
https://github.com/honojs/hono/issues/2387#issuecomment-2009251402
> feat(jsx): add useId hook

- deno_dist/validator/validator.ts
- src/validator/validator.test.ts
- src/validator/validator.ts
> fix(validator): `await` cached contents

- benchmarks/utils/package.json
- benchmarks/utils/src/loop.js
> chore(benchmark): add "loop" script

- deno_dist/middleware/cache/index.ts
- src/middleware/cache/index.test.ts
- src/middleware/cache/index.ts
> fix(cache): not enabled if `caches` is not defined

- deno_dist/middleware/cache/index.ts
- src/middleware/cache/index.ts
> fix(cache): check `globalThis.caches`

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.ts
> feat(jwt): literal typed `alg` option value

- src/helper/ssg/ssg.test.tsx
> test(ssg): add test for content-type includes `;`

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.test.ts
- src/middleware/jwt/index.ts
> feat(jwt): add `JwtTokenInvalid` object as `cause` when JWT is invalid

- deno_dist/client/client.ts
- deno_dist/client/types.ts
- src/client/client.test.ts
- src/client/client.ts
- src/client/types.ts
> feat(client): accept a function that provides dynamic headers to hc

- deno_dist/client/types.ts
- src/client/client.test.ts
- src/client/types.ts
> fix(client): infer `null` correctly

- deno_dist/helper/testing/index.ts
- src/helper/testing/index.test.ts
- src/helper/testing/index.ts
> fix(testing): set `baseUrl` for `testClient`

- deno_dist/jsx/dom/render.ts
- src/jsx/dom/index.test.tsx
- src/jsx/dom/render.ts
> fix(jsx/dom): remove lookbehind assertion in event regexp

- deno_dist/helper/ssg/utils.ts
- src/helper/ssg/utils.ts
> refactor(ssg): update utils.ts

- deno_dist/context.ts
- src/context.test.ts
- src/context.ts
> fix(context): correct set-cookie header values if c.res is set

- src/adapter/cloudflare-workers/serve-static.ts
> feat(cloudflare-workers): deprecate `serveStatic`

- deno_dist/client/types.ts
- deno_dist/context.ts
- deno_dist/types.ts
- deno_dist/utils/types.ts
- src/client/client.test.ts
- src/client/types.ts
- src/context.ts
- src/helper/factory/index.test.ts
- src/types.test.ts
- src/types.ts
- src/utils/types.ts
- src/validator/validator.test.ts
Continuing from #2579
**UPDATE:** All commits follows conventional syntax, recommended to merge without squashing.
> feat(types): improve response types flow

- README.md
- deno_dist/README.md
There is no need to write the benchmarks on README now.
> docs(readme): remove Benchmarks section

- deno_dist/types.ts
- src/types.test.ts
- src/types.ts
> fix(types): correct inferring when Method has Endponts as Union

- deno_dist/request.ts
- src/hono.test.ts
- src/request.ts
> fix(types): relax the type of `c.req.param()`

- .eslintignore
- .eslintrc.cjs
- deno_dist/helper/css/index.ts
- deno_dist/jsx/dom/css.ts
- runtime_tests/tsconfig.json
- src/helper/css/index.ts
- src/helper/ssg/ssg.test.tsx
- src/jsx/dom/css.ts
> chore(eslint): enable `@typescript-eslint/unbound-method`

- deno_dist/utils/body.ts
- deno_dist/utils/color.ts
- src/utils/body.test.ts
- src/utils/body.ts
- src/utils/color.test.ts
- src/utils/color.ts
> refactor: improve parseBody function and docs

- deno_dist/jsx/dom/render.ts
- deno_dist/jsx/hooks/index.ts
- src/jsx/dom/render.ts
- src/jsx/hooks/dom.test.tsx
- src/jsx/hooks/index.ts
- src/jsx/hooks/string.test.tsx
> feat(jsx/dom): support getServerSnapshot in useSyncExternalStore

- deno_dist/context.ts
- src/context.ts
> refactor(context): remove some `any`

- deno_dist/helper/factory/index.ts
- src/helper/factory/index.ts
> fix(factory): export `CreateHandlersInterface`

- src/utils/body.ts
Some minor changes I suggested @fzn0x in this #2675. He might have forgotten to include these
> refactor(utils/body): minor cleanup

- deno_dist/middleware/jwt/index.ts
- src/middleware/jwt/index.ts
> fix(middleware/jwt): typo

- src/middleware/pretty-json/index.ts
> refactor(pretty-json): remove useless condition

- .github/workflows/ci.yml
docs, .vscode, ... don't need tests
> refactor: added paths-ignore for ignore files of dont need tests

- src/compose.ts
- src/context.ts
- src/hono-base.ts
- src/hono.ts
- src/http-exception.ts
- src/index.ts
- src/request.ts
- src/router.ts
> docs(src/*): Add TSDoc comments to improve code documentation

- .github/workflows/ci.yml
> refactor: removed v4 branch in actions.

- src/helper/testing/index.ts
> refactor(helper/testing): remove some any of helper/testing

- docs/CONTRIBUTING.md
hightlight for shell code
```shell
cd /hono
```
> docs: change to shell highlight

- .github/workflows/release.yml
I think this is more appropriate than before.
> ci: change name of workflow jobs

- README.md
- docs/MIGRATION.md
Ref: https://github.com/honojs/hono/issues/2201#issuecomment-2139166691
> docs: update readme and migrate guide for migrating `deno.land/x` to JSR

- README.md
Follow up to #2862 
N/A, doc change only
> chore: add coverage badge to README

- src/preset/quick.test.ts
- src/preset/tiny.test.ts
> test(presets): add tests for `hono/quick` and `hono/tiny`

- src/request.test.ts
Fixed what appears to be a typo in the test case.
> fix(typo): Fix typo in request.test.ts

- .gitpod.yml
Close https://github.com/honojs/hono/issues/2866
> chore: create .gitpod.yml

- src/hono.test.ts
> test(hono-base): add tests for covering 100%

- src/jsx/utils.ts
> fix(jsx): add an explicit type

- .github/workflows/ci.yml
- src/adapter/deno/deno.d.ts
- src/adapter/deno/websocket.test.ts
- src/adapter/deno/websocket.ts
- src/helper/websocket/index.ts
Closes https://github.com/honojs/hono/issues/2997
> fix: change to allow use of websocket options

- src/helper/ssg/ssg.test.tsx
https://github.com/honojs/hono/pull/3004#discussion_r1648679702
> refactor: remove unneeded import statements

- src/middleware/timing/index.test.ts
- src/middleware/timing/timing.ts
> fix(timing): prevent duplicate applications

- src/helper/streaming/sse.ts
- src/helper/streaming/stream.ts
> fix(helper/streaming): remove slow types

- src/utils/jwt/jwa.ts
- src/utils/jwt/jws.ts
- src/utils/jwt/jwt.ts
- src/utils/jwt/types.ts
- src/utils/jwt/utf8.ts
> chore(utils/jwt): add `@module` docs

- src/middleware/ip-restriction/index.ts
> fix(ip-restriction): return the named function

- src/client/client.ts
- src/types.ts
- src/validator/validator.test.ts
Close https://github.com/honojs/hono/issues/3119
> fix(validator-types): type Alignment with Web Standards

- src/compose.ts
- src/jsx/dom/hooks/index.ts
- src/jsx/dom/render.ts
- src/jsx/intrinsic-element/components.ts
> fix(types): remove slow types

- src/helper/factory/index.ts
See: https://github.com/honojs/hono/issues/3159#issuecomment-2238708179
> chore(factory): remove `@experimental` from `createApp`

- src/jsx/base.ts
- src/jsx/index.test.tsx
- src/jsx/intrinsic-element/components.ts
* 94d8471ba1ed1fab8ee852869348497d888726ad : fix #3179
* 2729019036b09aa6da600810fd72285771f0b766 : Replace camelCase with kebab-case, as in https://github.com/honojs/hono/commit/a036181677a1e6d3611f6d10323e9c4c57d2bb9b in dom
- <del>Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code</del>
> fix(jsx): fix handling of SVG elements in JSX.

- src/adapter/service-worker/handler.ts
> fix(service-worker): refer to `self.fetch` correctly

- src/validator/validator.test.ts
- src/validator/validator.ts
> fix(validator): Allow form data will mutliple values appended

- README.md
Twitter is now X, so README has to be changed, as website did at https://github.com/honojs/website/pull/231.
> docs(README): change Twitter to X

- README.md
- docs/CONTRIBUTING.md
> docs: `Twitter` to `X`

- src/middleware/bearer-auth/index.test.ts
- src/middleware/bearer-auth/index.ts
> fix(bearer-auth): typo

- src/jsx/streaming.ts
fixes #3422
I think it can reduce the confusion of the reader.
- <del>[ ] Add tests</del>
> refactor(jsx/streaming): Clarified the type of renderToReadableStream.

- .github/workflows/ci.yml
https://github.com/oven-sh/bun/issues/4015 has been implemented and Bun now generates LCOV coverage
> chore(test): include bun coverage

- runtime-tests/deno/middleware.test.tsx
> test(deno): remove duplicated app.get

- src/helper/factory/index.test.ts
- src/helper/factory/index.ts
Reverted the PR #3498 and added tests.
Fixes #3512
> fix(factory): revert PR #3498

- src/middleware/secure-headers/secure-headers.ts
Refine the code to make it more readable and better express its intention.
Suggestions are welcome.
> refactor(secure-headers): refine secureHeadersNonce init

- src/jsx/streaming.ts
- src/middleware/timing/timing.ts
- src/utils/body.ts
> refactor(timing/utils-body): a few minor edits

- .github/workflows/release.yml
> chore: fix jsr release workflow

- .github/workflows/release.yml
> chore: `deno install` before jsr publishing

- README.md
really under 12kb
https://bundlejs.com/?q=hono%404.6.10%2Ftiny&treeshake=%5B*%5D
> docs: changed as even smaller

- src/types.ts
> fix(types): missing response type on `OnHandlerInterface`

- src/adapter/bun/websocket.ts
> fix(bun): export `BunWebSocketHandler`

- perf-measures/type-check/client.ts
- runtime-tests/deno/hono.test.ts
> chore(lint): patch warnings

- .github/workflows/ci.yml
- codecov.yml
This reverts commit f5ae405d0f86ccfd6e34daa8b8b06c9875d47daa.
> chore: Revert "ci: Add Bundle Analysis (#4072)"

- src/hono-base.ts
- src/hono.test.ts
> feat(hono-base): Added `replaceRequest: false` option for `.mount`

- src/helper/cookie/index.ts
> fix(helper/cookie): correct `getSignedCookie` parameters type

- README.md
> docs(readme): Added Deepwiki link in README

- jsr.json
- package.json
- src/helper/route/index.test.ts
- src/helper/route/index.ts
- src/hono-base.ts
- src/request.test.ts
- src/request.ts
- src/request/constants.ts
- src/types.ts
> feat: introduce Route Helper

- src/utils/jwt/types.ts
> fix(jwt): fix the `JwtTokenIssuedAt` error message

- src/helper/ssg/middleware.ts
- src/helper/ssg/ssg.test.tsx
- src/helper/ssg/ssg.ts
- src/helper/ssg/utils.ts
> fix(ssg): invoke callback when it's only a dynamic route

- src/request.test.ts
- src/request.ts
> fix(request): `req.json()` keeps the content as is

- src/types.ts
> perf(types): remove unnecessary default types

- src/context.test.ts
- src/context.ts
- src/utils/url.test.ts
- src/utils/url.ts
> fix(context): encode the redirect location

- .github/workflows/release.yml
> chore: fix the deno version for publishing to jsr

- README.md
> docs: simplify the readme

- .editorconfig
- .vscode/extensions.json
This pull request introduces a new `.editorconfig` file to standardize code formatting across the project. The configuration ensures consistent indentation, character encoding, line endings, and handling of trailing whitespace for different file types.
I think this will be convenient for contributors.
> chore: add EditorConfig

- .github/workflows/autofix.yml
- src/index.ts
fixes #4320
Once merged, I can add a similar workflow to https://github.com/honojs/middleware
> chore: autofix ci

- src/adapter/bun/index.ts
> fix(bun): exports functions related to websocket

- src/middleware/etag/index.ts
To avoid this error: https://github.com/honojs/hono/actions/runs/17144367684/job/48637570824
> chore: add a type cast to run `deno publish`

- .github/actions/perf-measures/action.yml
- .github/workflows/autofix.yml
- .github/workflows/ci.yml
- .github/workflows/cr.yml
- .gitpod.yml
- benchmarks/http-server/benchmark.ts
- benchmarks/routers/README.md
- docs/CONTRIBUTING.md
cf. https://github.com/honojs/hono/pull/4397#issuecomment-3252509978
> chore: update `bun install` commands to use `--frozen-lockfile`

- src/hono-base.ts
> refactor(types): fix the type definitions in hono-base
